### ISSUE TITLE
Thread 'main' panicked at 'failed to update version: Custom { kind: Other, error: StringError("IO error: While fdatasync: /home/xxx/db/1358731.sst: Structure needs cleaning") }'

### ISSUE THREAD

**Issue by litoyao** [openethereum/openethereum#10037]
2018-12-10 01:42:16 UTC Starting Parity-Ethereum/v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0
2018-12-10 01:42:16 UTC Keys path /home/az-user/apps2/parity/node-data/keys/ethereum
2018-12-10 01:42:16 UTC DB path /home/az-user/apps2/parity/node-data/chains/ethereum/db/906a34e69aec8c0d
2018-12-10 01:42:16 UTC State DB configuration: archive
2018-12-10 01:42:16 UTC Operating mode: active
2018-12-10 01:42:16 UTC Warning: Warp Sync is disabled because of non-default pruning mode.
2018-12-10 01:42:17 UTC Configured for Foundation using Ethash engine

====================

stack backtrace:
   0:     0x55d2f4d2cfdc - <no info>
   1:     0x55d2f4d2cd92 - <no info>
   2:     0x55d2f4d2ce08 - <no info>
   3:     0x55d2f4d2bc0a - <no info>
   4:     0x55d2f4d2bab8 - <no info>
   5:     0x55d2f4d8c753 - <no info>
   6:     0x55d2f4d8c2f9 - <no info>
   7:     0x55d2f4d8c1f5 - <no info>
   8:     0x55d2f4dededb - <no info>
   9:     0x55d2f4630558 - <no info>
  10:     0x55d2f4622d51 - <no info>
  11:     0x55d2f43ec0c9 - <no info>
  12:     0x55d2f414cbe6 - <no info>
  13:     0x55d2f37426e5 - <no info>
  14:     0x55d2f3749a70 - <no info>
  15:     0x55d2f37daf7c - <no info>
  16:     0x55d2f3878748 - <no info>
  17:     0x55d2f387b265 - <no info>
  18:     0x55d2f374b3a2 - <no info>
  19:     0x55d2f4d8c192 - <no info>
  20:     0x55d2f4db69c9 - <no info>
  21:     0x55d2f4d8f5c5 - <no info>
  22:     0x55d2f387bbe3 - <no info>
  23:     0x14e948bff82f - <no info>
  24:     0x55d2f369f108 - <no info>
  25:                0x0 - <no info>

Thread 'main' panicked at 'failed to update version: Custom { kind: Other, error: StringError("IO error: While fdatasync: /home/az-user/apps2/parity/node-data/chains/ethereum/db/906a34e69aec8c0d/archive/db/1358731.sst: Structure needs cleaning") }', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by joshua-mir** [comment]
Hey @litoyao does this issue persist after restarting parity?

**Comment by litoyao** [comment]
odd, it works after restart today. But last time I restart it still not works, anyway, thanks your response.

**Comment by adria0** [comment]
Closing the issue due to its stale state
