### ISSUE TITLE
Feature-request: Be able to prune old blocks in disk

### ISSUE THREAD

**Issue by albpal** [openethereum/openethereum#10073]
As in pruning mode in Bitcoin client, it would be useful to have an option to prune old blocks so the disk usage will be much less and it will facilitate the possibility to have a full validated node (a much more close approach to "don't trust, verify"). Despite it won't provide old blocks to newcomers, will provide security by validating blocks against consensus rules and propagate only valid ones.

**Comment by AC0DEM0NK3Y** [comment]
Adding to this, perhaps adding an archive mode with a blocknumber option at which to prune at so it does same as full archive but only has historical state data up to that block.

For dapp devs this is something of great value as you don;t care about blocks before your contract deployment and can then possibly serve a full archive node on a dev machine and not have to store one in AWS etc. at cost.

**Comment by gituser** [comment]
This is a huge feature, a must have, especially when you're short on fast storage (SSD / NVMe) and don't want to keep old blocks available.

**Comment by XertroV** [comment]
related: #10760

**Comment by adria0** [comment]
Closing issue due to its stale state.
