### ISSUE TITLE
Openethereum on Gitcoin

### ISSUE THREAD

**Issue by mdben1247** [openethereum/openethereum#101]
There is a page on Gitcoin:

https://gitcoin.co/grants/1415/openethereum-ex-parity-client

listing `0x7A369245AD5E44018d677B60d5Bd4FF904da180E` ethereum address for contributions. Can the team confirm whether this is a valid entry and the address can receive donations that go towards `openethereum` development? If it is, perhaps also listing it in the README.md .

**Comment by claberus** [comment]
mdben,
That address is correct. 
https://gitcoin.co/grants/1415/openethereum-ex-parity-client is our Gitcoin page.
Thanks for the suggestion!
