### ISSUE TITLE
Possible to tune compaction profile beyond ssd/hdd?

### ISSUE THREAD

**Issue by charles-cooper** [openethereum/openethereum#10108]
Hello,

I have been experimenting with running `parity` on AWS and have found that a critical piece to getting good performance is having enough RAM that the state mostly (or all) fits in the page cache. I suspect that being able to reduce `block_size` below 16KB (https://github.com/paritytech/parity-common/blob/154990798896963fedf329b026011f3f8604e5e3/kvdb-rocksdb/src/lib.rs#L142-L159) to the OS page size would enhance performance, because it would reduce the amount of infrequently-used data a hot piece of data pulls into the cache with it, enabling the node to hold more hot words in the cache for the same amount of RAM. Would it be possible to expose the compaction profile options directly to the user? Thanks in advance!

**Comment by charles-cooper** [comment]
Preliminary update - I hardcoded the block size to 4096 and saw a reduction in real memory (used + cache) by about a factor of about 2. It looks like the average read size is 8KB which suggests to me that the compaction to 4KB is not really complete. My next step is to do a chain sync from scratch to see what happens.

**Comment by adria0** [comment]
Closing issue due to its stale state.

**Comment by charles-cooper** [comment]
This is still an issue
