### ISSUE TITLE
Aura: Block Reward contract not working

### ISSUE THREAD

**Issue by aaroncolaco** [openethereum/openethereum#10110]
- **Parity Ethereum version**: v2.1.10-stable-b47e064-20181213
- **Operating system**: Linux
- **Installation**: one-line installer 
- **Fully synchronized**: nodes in sync on private network
- **Network**: Private
- **Restarted**: yes

I am using [this block reward contract](https://github.com/parity-contracts/block-reward/blob/master/contracts/ExampleBlockReward.sol). 

**Expected Behaviour**
Authorities get rewarded for all blocks.

**Actual Behaviour**
The authorities do not get rewarded for empty blocks, and for blocks which contain 0 gas TXs. 
Auths get rewarded only when gas cost > 0

I have tried restarting. Nodes are in sync, and nothing weird in the logs. Anything I'm missing?

In spec file: 
```
       "params": {
        "gasLimitBoundDivisor": "0xFFF",
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x3FFFFFFF",
        "networkID" : "0x2323",
        "eip140Transition": "0x0",
        "eip211Transition": "0x0",
        "eip214Transition": "0x0",
        "eip658Transition": "0x0",
        "wasmActivationTransition": "0x0",

        "eip145Transition": "0x0",
        "eip1014Transition": "0x0",
        "eip1052Transition": "0x0",
        "eip1283Transition": "0x0",
        "kip4Transition": "0x0",
        "kip6Transition": "0x0",

        "transactionPermissionContract": "0x0000000000000000000000000000000000000009",
        "blockRewardContractAddress": "0x30401717e15f5d707e74a72434fba741d19653ca",
        "blockRewardContractTransition": "0xAA"
    }
```
In toml file:
```
[parity]
chain = "demo-spec.json"
base_path = "node1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
cors = ["all"]
interface = "all"
hosts = ["all"]
processing_threads = 8
server_threads = 8
[ui]
port = 8181
[websockets]
port = 8451
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "pubsub"]
hosts = ["all"]
origins = ["all"]
interface = "all"
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x3e86b3d46fe0494bdd94625cc12984ce1f7ac6ab"
author = "0x3e86b3d46fe0494bdd94625cc12984ce1f7ac6ab"
reseal_on_txs = "all"
min_gas_price = 0
relay_set = "lenient"
tx_queue_mem_limit = 0
tx_queue_size = 819200
[misc]
log_file = "./parity.log"
color = true
[footprint]
cache_size = 16384
```

**Comment by andresilva** [comment]
By default the authorities will only seal blocks if there are any transactions to include, please add `force_sealing = true` to the mining section to make sure authorities always produce blocks on their turn.

**Comment by aaroncolaco** [comment]
@andresilva, I'm not sure I follow. 
The problem is the authority is not being rewarded for the blocks which have TXs where `gasPrice` is 0. 
There are no missed steps - I have a 'seed script' which ensures there are always TXs to be included

**Comment by aaroncolaco** [comment]
@andresilva ?

**Comment by aaroncolaco** [comment]
@andresilva @5chdn @joshua-mir this is a bit of a blocker. Any idea what could be the problem

**Comment by andresilva** [comment]
I don't have time to look into this now. Would appreciate if someone else could try to replicate and take it over.

**Comment by adria0** [comment]
Closing issue due to its stale state.
