### ISSUE TITLE
Very slow stateDiff for blocks past 2,283,416 with EXTCODESIZE abuse

### ISSUE THREAD

**Issue by alecalve** [openethereum/openethereum#10131]
- **Parity Ethereum version**: 2.2.4
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

This block is one of the first of the post-DAO hard fork "spam attacks" (EXTCODESIZE abuse). So far I haven't been able to get a call to `trace_replayBlockTransactions` to finish for this block (some ran 20mins+).

The node is running on raid-0 SSD with ample RAM (128GB).

I'm interested in getting the stateDiff for each block (in order to maintain a historical mapping of account to balance). Is there a way that would bypass these extremely slow blocks?

**Comment by alecalve** [comment]
I finally got one RPC call to finish after 31 mins.

**Comment by tjayrush** [comment]
I wrote about this issue here: https://medium.com/@tjayrush/defeating-the-ethereum-ddos-attacks-d3d773a9a063 and here: https://medium.com/@tjayrush/the-trace-data-problem-d16b2e84fe40.  Maybe you'll find it interesting and/or useful.

**Comment by adria0** [comment]
Closing issue due to its stale state.
