### ISSUE TITLE
can't upgrade to parity 2.1.11: account not found for the current chain

### ISSUE THREAD

**Issue by elopio** [openethereum/openethereum#10160]
- **Parity Ethereum version**: 2.1.11
- **Operating system**:  Linux
- **Installation**: binary from github releases
- **Fully synchronized**: yes
- **Network**: ropsten
- **Restarted**: yes

I'm trying to update our ropsten parity node from 2.0.8, but when I try to start with the binary for 2.1.11 I get the following error:
```
Account [...] not found for the current chain. You can create an account via RPC, UI or `parity account new --chain ropsten --keys-path /data/parity/keys`.
```

I tried with 2.1.10 and it works correctly, so I'm leaving it on this version for now. This is the command we use to run it:

```
/usr/bin/parity -l info --chain ropsten -d "[...]" --port [...] --jsonrpc-hosts all --jsonrpc-cors "*" --jsonrpc-port [...] --jsonrpc-interface local --ipc-apis="web3,eth,net,parity,parity_accounts,traces,rpc,personal" --ipc-path="[...]" --pruning=fast --unlock="[...]" --password "[...]"
```

**Comment by joshua-mir** [comment]
Can you check whether you see the account keys present in your `keys` folder in the root of your data directory or if it is in the `keys` folder present in ropstens chaindata folder?

**Comment by elopio** [comment]
I have the keys in `<data>/keys/test/`.

`<data>/keys/ropsten` is empty.

**Comment by joshua-mir** [comment]
if you copy the keyfile into the ropsten dir, you should be able to unlock the account associated with the keyfile when using `--chain ropsten`

the root keys directory is what will be used for the chain defined in your config file.

**Comment by 5chdn** [comment]
oh darn, did we backport this to stable?

I'm sorry, @elopio can you symlink the `test/` to `ropsten/`?

**Comment by elopio** [comment]
Yes, the symlink works. I'm now on 2.1.11. Thanks @joshua-mir and @5chdn.

**Comment by DaWe35** [comment]
> 
> 
> oh darn, did we backport this to stable?
> 
> I'm sorry, @elopio can you symlink the `test/` to `ropsten/`?

I updated my parity from 1.2.10 to 2.1.11, and I also lost my Ropsten accounts. Sync restarted from block #1

**Comment by adria0** [comment]
Closing issue due to its stale state.
