### ISSUE TITLE
Disk space needed higher than expected

### ISSUE THREAD

**Issue by sebnyc** [openethereum/openethereum#102]
- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: Linux Ubuntu 20.04
- **Installation**: downloaded zip file
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Hi,

First of all, thumbs up to the team for your fantastic job.

I'm running a node that I guess you could call a "full" node, on Ubuntu 20.04. I have imported all blocks of the Ethereum blockchain (warp = false in my config.toml).
Before release 3.0.1, disk consumption was regular and predictable, it was pretty easy to manage.

Since I upgraded to 3.0.1 I started to experience important variations of disk consumption. Disk usage would increase very fast, up to 95% of my 600 GB volume, then I would pause block import, and a few days later, disk usage would be down at 60%, so I would restart blocks import, etc.)
It looks like I have no control over this kind of garbage collection behavior.

A few days ago disk consumption was once again at a high point around 560 GB, whereas I would expect the chain size to be around 350 GB (see https://etherscan.io/chartsync/chaindefault), so I paused sync again waiting for garbage collection but it didn't happen.

Yesterday I ran the migration tool and upgraded to version 3.1, hoping that the migration tool would trigger garbage collection and reduce chain size.
While the migration and upgrade was apparently successful, the migration tool took literally 1 second to execute (after several minutes of building) and didn't change anything regarding disk usage.

My question is : now that I am running release 3.1 is there anything I could do to trigger this garbage collection and reduce disk consumption ? Are there files or folder that I could safely delete (for instance the snapshot folder contains files created in 2018, it's only 6 GB but it could be a start) or options I should set when launching openethereum ?

Here are a few outputs I can share. If anything else is necessary to analyse I would be happy to share it with you.

Volume used:

    ~$ df
    Filesystem     1K-blocks      Used Available Use% Mounted on
    ...
    /dev/nvme1n1   618222752 567607728  23797504  96% /home/ubuntu/.local

Blockchain folder:

    /906a34e69aec8c0d$ du -s *
    560919008	overlayrecent
    6448264	snapshot

Content of blockchain folder (redacted) : 

```
/overlayrecent/db$ ll
total 558116316
drwx------ 4 ubuntu ubuntu   274432 Nov 16 04:01 ./
drwx------ 3 ubuntu ubuntu     4096 Dec 19  2018 ../
-rw-r----- 1 ubuntu ubuntu 69467344 Aug 19 05:23 8264891.sst
-rw-r----- 1 ubuntu ubuntu 69455377 Aug 19 05:23 8264892.sst
-rw-r----- 1 ubuntu ubuntu 69455094 Aug 19 05:24 8264893.sst
-rw-r----- 1 ubuntu ubuntu 69468010 Aug 19 05:24 8264894.sst
-rw-r----- 1 ubuntu ubuntu 69455321 Aug 19 05:24 8264895.sst
-rw-r----- 1 ubuntu ubuntu 69453941 Sep 25 12:21 8401648.sst
-rw-r----- 1 ubuntu ubuntu 68716983 Oct 26 19:52 8598355.sst
-rw-r----- 1 ubuntu ubuntu 69408507 Oct 26 19:52 8598356.sst
-rw-r----- 1 ubuntu ubuntu 69371257 Oct 26 19:53 8598357.sst
-rw-r----- 1 ubuntu ubuntu 69302412 Oct 26 19:53 8598358.sst
-rw-r----- 1 ubuntu ubuntu 68905613 Oct 26 20:00 8598601.sst
-rw-r----- 1 ubuntu ubuntu      988 Oct 26 20:55 8599514.sst
-rw-r----- 1 ubuntu ubuntu     1000 Oct 26 20:56 8599515.sst
-rw-r----- 1 ubuntu ubuntu      988 Oct 26 20:57 8599516.sst
-rw-r----- 1 ubuntu ubuntu     1326 Oct 26 20:57 8599517.sst
-rw-r----- 1 ubuntu ubuntu     1137 Oct 26 20:57 8599518.sst
-rw-r----- 1 ubuntu ubuntu      989 Oct 26 20:58 8599519.sst
-rw-r----- 1 ubuntu ubuntu     1145 Oct 26 20:58 8599520.sst
-rw-r----- 1 ubuntu ubuntu     1069 Oct 26 20:58 8599521.sst
-rw-r----- 1 ubuntu ubuntu     1201 Oct 26 20:58 8599524.sst
-rw-r----- 1 ubuntu ubuntu     1071 Oct 26 20:59 8599529.sst
-rw-r----- 1 ubuntu ubuntu      996 Oct 26 20:59 8599530.sst
-rw-r----- 1 ubuntu ubuntu     1231 Oct 26 21:00 8599531.sst
-rw-r----- 1 ubuntu ubuntu     1118 Oct 26 21:00 8599534.sst
-rw-r----- 1 ubuntu ubuntu      998 Oct 26 21:00 8599535.sst
-rw-r----- 1 ubuntu ubuntu     1177 Oct 26 21:02 8599536.sst
-rw-r----- 1 ubuntu ubuntu     1063 Oct 26 21:02 8599537.sst
-rw-r----- 1 ubuntu ubuntu     1184 Oct 26 21:02 8599538.sst
-rw-r----- 1 ubuntu ubuntu      989 Oct 26 21:02 8599539.sst
-rw-r----- 1 ubuntu ubuntu     1076 Oct 26 21:03 8599540.sst
-rw-r----- 1 ubuntu ubuntu     1126 Oct 26 21:03 8599541.sst
-rw-r----- 1 ubuntu ubuntu     1169 Oct 26 21:04 8599542.sst
-rw-r----- 1 ubuntu ubuntu      999 Oct 26 21:05 8599545.sst
-rw-r----- 1 ubuntu ubuntu     1140 Oct 26 21:05 8599546.sst
-rw-r----- 1 ubuntu ubuntu     1063 Oct 26 21:06 8599547.sst
...
...
...
-rw-r----- 1 ubuntu ubuntu 17512434 Nov 12 04:02 8705344.sst
-rw-r----- 1 ubuntu ubuntu 68277598 Nov 12 04:02 8705345.sst
-rw-r----- 1 ubuntu ubuntu 68305668 Nov 12 04:02 8705346.sst
-rw-r----- 1 ubuntu ubuntu 16325444 Nov 12 04:02 8705348.sst
-rw-r----- 1 ubuntu ubuntu 68631284 Nov 13 23:29 8705357.sst
-rw-r----- 1 ubuntu ubuntu  7953912 Nov 13 23:29 8705358.sst
-rw-r----- 1 ubuntu ubuntu 68669506 Nov 13 23:29 8705359.sst
-rw-r----- 1 ubuntu ubuntu 11545168 Nov 13 23:29 8705360.sst
-rw-r----- 1 ubuntu ubuntu 68639645 Nov 13 23:29 8705361.sst
-rw-r----- 1 ubuntu ubuntu 18957104 Nov 13 23:29 8705362.sst
-rw-r----- 1 ubuntu ubuntu 68702991 Nov 13 23:29 8705363.sst
-rw-r----- 1 ubuntu ubuntu 46298062 Nov 13 23:29 8705364.sst
-rw-r----- 1 ubuntu ubuntu 25118892 Nov 13 23:29 8705365.sst
-rw-r----- 1 ubuntu ubuntu     1000 Nov 16 03:47 8705392.sst
-rw-r----- 1 ubuntu ubuntu    16492 Nov 16 03:47 8705393.sst
-rw-r----- 1 ubuntu ubuntu 43088077 Nov 16 04:01 8705395.sst
-rw-r----- 1 ubuntu ubuntu     1000 Nov 16 04:01 8705397.sst
-rw-r----- 1 ubuntu ubuntu  1343460 Nov 16 12:46 8705398.log
-rw-r----- 1 ubuntu ubuntu 68587467 Nov 16 04:01 8705401.sst
-rw-r----- 1 ubuntu ubuntu 21931109 Nov 16 04:01 8705402.sst
-rw-r----- 1 ubuntu ubuntu       17 Nov 16 04:01 CURRENT
-rw-r--r-- 1 ubuntu ubuntu       37 Aug 28  2018 IDENTITY
-rw-r--r-- 1 ubuntu ubuntu        0 Aug 28  2018 LOCK
-rw-r----- 1 ubuntu ubuntu   105617 Nov 16 04:01 LOG
-rw-r----- 1 ubuntu ubuntu   735810 Nov 16 04:01 MANIFEST-8705396
-rw-r----- 1 ubuntu ubuntu    22405 Nov 16 03:47 OPTIONS-8705391
-rw-r----- 1 ubuntu ubuntu    22405 Nov 16 04:01 OPTIONS-8705400
drwxrwxr-x 2 ubuntu ubuntu     4096 Aug 28  2018 blooms/
drwxrwxr-x 2 ubuntu ubuntu     4096 Aug 28  2018 trace_blooms/


/db/blooms$ ll
total 2802960
drwxrwxr-x 2 ubuntu ubuntu       4096 Aug 28  2018 ./
drwx------ 4 ubuntu ubuntu     274432 Nov 16 04:01 ../
-rw-rw-r-- 1 ubuntu ubuntu 2854350080 Nov 12 04:01 bot.bdb
-rw-rw-r-- 1 ubuntu ubuntu  178396928 Nov 12 04:01 mid.bdb
-rw-rw-r-- 1 ubuntu ubuntu   11149824 Nov 12 04:01 top.bdb


db/trace_blooms$ ll
total 272
drwxrwxr-x 2 ubuntu ubuntu   4096 Aug 28  2018 ./
drwx------ 4 ubuntu ubuntu 274432 Nov 16 04:01 ../
-rw-rw-r-- 1 ubuntu ubuntu      0 Aug 28  2018 bot.bdb
-rw-rw-r-- 1 ubuntu ubuntu      0 Aug 28  2018 mid.bdb
-rw-rw-r-- 1 ubuntu ubuntu      0 Aug 28  2018 top.bdb
```

**Comment by sebnyc** [comment]
For the benefit of everyone who might experience the same issue, I could solve it :
I restored the database as it was before running the migration tool (version 15)
Then I ran Openethereum 3.0.1 without any peers (max_peers=0).
After about 24 hours disk usage started to go down, and about 12 hours later garbage collection was done ! 355 GB instead of 567 GB

```
~$ df
Filesystem     1K-blocks      Used Available Use% Mounted on
...
/dev/nvme1n1   618222752 355431560 235973672  61% /home/ubuntu/.local
``` 

Finally I could run the migration tool again and start using Openethereum 3.1

**Comment by rakita** [comment]
This is one of the reasons why we decided to make v3.1 from a v2.5.13 base.
