### ISSUE TITLE
Initialization of genesis block contracts is extremely difficult to debug

### ISSUE THREAD

**Issue by DemiMarie** [openethereum/openethereum#10210]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Fairly recent checkouts of the `stable` and/or `master` branches.  So far, this has only been checked with the [POA Network fork](/poanetwork/parity-ethereum), but I suspect it reproduces with the code in the official repository.
- **Operating system**: Linux, but it should not matter.
- **Installation**: Built from git
- **Fully synchronized**: N/A
- **Network**: Custom experimental test network
- **Restarted**: N/A

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

When developing new consensus protocols, one may have a genesis block that includes large custom smart contracts.  If these fail to initialize, debugging them is extremely difficult, as one gets a cryptic error message saying that the Rust code could not decode an empty block.  Worse, Parity doesn’t exit, but rather continues with the invalid genesis block, which can result in later problems that are extremely difficult to debug.

I expect that if an exception is thrown when creating the genesis block, Parity should consider this to be a fatal error and exit, just like it would if `spec.json` was syntactically incorrect or could not be found.  Furthermore, it should log an EVM trace, which existing tools can convert into a backtrace.

**Comment by adria0** [comment]
Closing issue due to its stale state.
