### ISSUE TITLE
Encountered error during snapshot restoration: Corruption: block checksum mismatch

### ISSUE THREAD

**Issue by xtien** [openethereum/openethereum#10219]
Latest stable version of parity 2.2.7-stable
Ubuntu 16.04
downloaded from parity web site
ethereum
restarted yes
killed db yes
manually removed db yes

2019-01-20 00:44:03  Encountered error during snapshot restoration: Corruption: block checksum mismatch: expected 1454440570, got 2150552784  in /mnt/a519ab96-add0-4531-a4f2-16eed9b8e64e/christine/local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/snapshot/restoration/db/000920.sst offset 5071627 size 12546

I downloaded the latest version of parity. I killed the db. I removed the cached, snapshot and chain directories. I started parity. It gave me corruption errors from the start.

**Comment by joshua-mir** [comment]
I haven't been able to replicate this reliably yet, but it has happened to me on a recent kovan sync.

**Comment by ralphholz-usyd** [comment]
I am experiencing this on a fresh parity install, with a modified parity_install sh:

`install() {
  TMPDIR=$(mktemp -d) && cd $TMPDIR
        curl -Ss -O $DOWNLOAD_FILE
  check_sha256

        if [ "$PKG" = "linux" ] ; then
          cp $TMPDIR/parity /home/obs/parity/bin && chmod +x /home/obs/parity/bin/parity
        fi
}`

Parity-Ethereum/v2.1.10-stable-b47e064-20181213/x86_64-linux-gnu/rustc1.31.0
Ubuntu 16.04.5, on a DigitalOcean box.

It does not happen on an Ubuntu 18.04 DigitalOcean box.

**Comment by ralphholz-usyd** [comment]
Does not happen on 2.2.9 for me, though.

**Comment by adria0** [comment]
Closing issue due to its stale state.
