### ISSUE TITLE
[Light] Flush db when the current block is older than the hardcoded block

### ISSUE THREAD

**Issue by Tbaut** [openethereum/openethereum#10236]
### Feature request

Consider a suit of event where:
- Parity Ethereum `light` version 1 is synced to block 6M and is then turned off and let offline for a while.
- Parity Ethereum is updated to version 1.1 which benefits from a hardcoded header at block 7M.
- Parity Ethereum (v1.1) is then launched and will sync from block 6M up until the top whereas if a `db kill` was performed, it would have synced from block 7M, being a lot quicker.

Therefore it would be great to do a `db kill` if the hardcoded header > current sync block.

Linked to https://github.com/paritytech/fether/issues/204

**Comment by adria0** [comment]
Closing issue due to its stale state.
