### ISSUE TITLE
Data mismatch for data returned in rpc calls (trace_block, eth_getBlockByHash)

### ISSUE THREAD

**Issue by adilimroz** [openethereum/openethereum#10245]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.1.7 Stable
- **Operating system**: Linux
- **Installation**: Built from source
- **Fully synchronized**: Yes
- **Network**: Kovan
- **Restarted**: Yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Issue**
---------------
There seem to be mismatch in data when data is retrieved for same block through different rpc calls.

**Steps to reproduce**
---------------------------
For block 8554568 in kovan, making following request
`curl --data '{"method":"trace_block","params":["0x828848"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`
returns this data - https://pastebin.com/FA5hqW8w

While making this call
`curl --data '{"method":"eth_getBlockByHash","params":["0x319334c41676b5e57387eed27e1a19b114a0dfffd457c930b45a3cd6a848f328",true],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`  
with the block hash returned from trace_block, following data is returned - 
https://pastebin.com/KmTQyi5c

**Observations**
-------------------------------------------

- Transaction from trace_block at transactionPosition 0 has transactionHash as " ", while seemingly same transaction in getBlockByHash has transaction Hash as 0x240f5517e5c3aa5c449dfb5923ca525e18a361e4646306bf27b1fc5d26b5211d

- Values for gas and gasUsed from both the calls do not match

**Expected Behaviour**
------------------------------------------
Data returned from both the call should have been consistent.

**Comment by adria0** [comment]
Closing issue due to its stale state.
