### ISSUE TITLE
Rework the logger setup

### ISSUE THREAD

**Issue by tomaka** [openethereum/openethereum#10252]
Right now, calling `parity_ethereum::start` set ups the logger of the `log` crate by calling `log::set_logger`.

This is problematic, because Parity is supposed to be usable as a library in a third-party application. We are essentially setting up a global variable from a library, which is not great. The third-party application can't use their custom logger if they wanted to.

Even internally in Parity this is a bit problematic, because in Android (and iOS and WASM in the future), we want to be able to intercept the logs. This isn't possible because of the aforementioned issue.

Instead, the logging should be entirely set up from within the `main.rs` file, as this is the one file that isn't part of the parity library.
A function should be added to the Parity C bindings so that C and Java bindings can also setup their own logging.

**Comment by adria0** [comment]
Closing issue due to its stale state.
