### ISSUE TITLE
P2Pv1 RelayTransactions Fails on Specific Signature Encoding

### ISSUE THREAD

**Issue by EBGToo** [openethereum/openethereum#10272]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.8
- **Operating system**: MacOS
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

When submitting a transaction using the P2Pv2 RelayTransaction message I saw a particular submission being rejected with:
```
2019-01-31 14:04:03  IO Worker #2 TRACE pip  Incoming packet 6 from peer 14 
2019-01-31 14:04:03  IO Worker #2 DEBUG pip  Disabling peer 14: RlpInvalidIndirection
2019-01-31 14:04:03  IO Worker #2 TRACE pip  Initiating disable of peer 14
```

After tracing down the 'RlpInvalidIndirection' cause, it appears that the RLP encoding of the signature as {v, r, s} where 'r' and 's' are (supposedly) 32 bytes, will be invalid if 'r' or 's' happen to start with the byte '0x00'.  Here was the transaction data:

```
2019-01-31 14:31:09  IO Worker #1 TRACE pip  Incoming rlp: [
    ["0x2f", 
     "0x012a05f200", 
     "0x5208",
     "0x19<...>",   // full address was correct
     "0x038d7ea4c68000", 
     "0x", 
     "0x25", 
     "0x98783059db354dcca7231d8c86de51df0fc676845892a42a3ef1ffd72186301e",
     "0x008e17b3f8f447e1b4a361a0b57edb34e72ad3ad447434c1432012448f881107"]
]
```
You can see the the final value in the encoding (the signature's 's') starts with '0x00...'.  This causes the server-side to reject and 'punish' the client.

Do you really, seriously expect 32 bytes of signature data to only have 31 (or 30 or 29 or ...) bytes encoded if it starts with 1 or more zeros?  At is a byte array; it is not a number like 0000024 or 0024 or 24 - which is 24; it is 32 bytes.

Note: when I changed something in the transaction (the gas Price), the signature happened not to start with a 0 byte... and the transaction sailed through.

Note: Geth behaves the same way - disconnecting and punishing as a 'useless peer'.  When Parity gets a 'r' or 's' value with 31 bytes, are you going to add the '0' byte at the start or the end?

**Comment by EBGToo** [comment]
The simple, backward compatible change would be not to punish clients that provide signature 'r' and 's' values that are 32 bytes.  The harder question would be when Parity encodes a transaction to send to a client should 'r' and 's' always be 32 bytes?  [Would some client reject, like Parity did, 'r' and 's' values that are 32 bytes *and* start with one or more leading zeros?]

Also sometimes documentation references an RLP data type as `P_32`.  If so, perhaps this should be changed to `P_32*` and documented as 'nominally 32 bytes but initial zero bytes must be stripped'

Presumably Parity will also reject a transaction target address encoded with an initial '0x00' byte?

**Comment by adria0** [comment]
Closing issue due to its stale state.
