### ISSUE TITLE
Specify rlp-encoded genesis block

### ISSUE THREAD

**Issue by viniul** [openethereum/openethereum#10304]
- **Parity Ethereum version**: 2.4.0
- **Operating system**: Linux

When starting parity with a json chain-specification, is there any way to specify the genesis block as rlp encoded data? So instead of this 

```
[...]
 "genesis": {
        "seal": {
            "ethereum": {
                "nonce": "0x0000000000000042",
                "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x10000",
        "author": "0x0000000000000000000000000000000000000000",
        "timestamp": "0x00",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "extraData": "0x3535353535353535353535353535353535353535353535353535353535353535",
        "gasLimit": "0x1000000"
    },
[...]
```

I want something like this:

```

[...]
 "genesis": {
        "rlp":<rlpencodedblock>
    },
[...]
```

Is there some way I can achieve this?

**Comment by joshua-mir** [comment]
Not yet unfortunately 😅 you can do something similar by specifying a genesis `state_root` and manually importing a valid db for it but that is probably not the same as what you want.

**Comment by viniul** [comment]
Thank you very much! Could you point me to a documentation on how to import a valid db consisting of rlp encoded blocks?

**Comment by joshua-mir** [comment]
ie; you would create a chain normally, (with --fat-db enabled), perform transactions and deploy contracts as required to get to the genesis state you require, and then run https://wiki.parity.io/CLI-Sub-commands#export-state (in addition to noting the stateRoot of the latest block, eg by using [eth_getBlockByHash](https://wiki.parity.io/JSONRPC-eth-module#eth_getblockbyhash)) 
you would put that state_root in your genesis, and all nodes using that genesis would need to run https://wiki.parity.io/CLI-Sub-commands#import before their clients would be able to start syncing with your network (or they could use warp-sync)

**Comment by adria0** [comment]
Closing issue due to its stale state.
