### ISSUE TITLE
Feature-request: Prune at blocknumber or split the chain to be able to run a local archive node.

### ISSUE THREAD

**Issue by AC0DEM0NK3Y** [openethereum/openethereum#10307]
Running a local archive node is getting closer to impossible for a dapp developer to run that needs it now as the ssd size requirement is >2TB. This means hosting on AWS or equivalent instead, and slowing down your testing and costing a monthly fee or relying on external services (that don't always work). The barrier to entry is quite high at a time we want to have devs building their dapps and not worrying about infrastructure issues.

So I'll propose two things that I think could really help here if possible:

1) Add a blocknumber option at which to prune at so it does same as full archive but only has historical state data up to the block specified. While this wouldn't save any time syncing (although I think a trusted source could be helpful to seed a node with export data) what it would do is be able to prune unneeded data immediately and only store when you hit the blocknumber specified, meaning if you for instance only needed history back to block 6 million where you deployed your contract you wouldn't have 6 million blocks worth of state history filling up your ssd footprint for no reason.

Just being to sync an archive node from a particular block number would be even better but I don't know if that is possible, I guess you need the state at that number - 1 to do that, and unless you are in available snapshot range you have no source for that.

2) Be able to archive to hdd while having active state on ssd. Here it might be good to have a two state db with a "bridge" state so that lets say for example you are running a node on ssd to fill in latest details for the chain head. After this is dealt with if the secondary storage option is set it archives older state to a separate hdd/ssd location in a separate thread. This could be analogous to a CPU using cache and heap for its data so the block ranges that are in current use are in the ssd "cache" so to speak and anything cold goes into hdd that can be queried for historical data but isn't necessarily needed for immediate operation of the node.

**Comment by AC0DEM0NK3Y** [comment]
Adding that perhaps some investigation could be made into a replacement for rocksdb to help with the above, maybe this for instance: https://en.wikipedia.org/wiki/Apache_Ignite

**Comment by XertroV** [comment]
#10760 provides a possible path forward for a pseudo-archive node from a certain block. 

You'd set `pruning_historical_eras: [[50000000, 7000000]]` to keep all state and blocks between 50m and 7m. You could specify [7000000, 50000000] too - I just do largest first because it made more sense when I started coding; the config parser will figure it out regardless of order.

Note: the PR isn't at a usable stage yet bc I think all ancient state that isn't pruned is stored in RAM, but I don't think it's too much to avoid that and keep on disk (falling back to on-disk db when an RPC call is made, or whatever)

**Comment by adria0** [comment]
Closing issue due to its stale state.
