### ISSUE TITLE
trace_filter in Parity Trace nodes sometimes fails to detect transactions in new blocks

### ISSUE THREAD

**Issue by AlexWilton** [openethereum/openethereum#10325]
_Before filing a new issue, please **provide the following information**._
- **Parity Ethereum version**: 2.2.7 / 2.3.0
- **Operating system**: Linux (Debian in Docker on CentOS 7)
- **Installation**: downloaded from releases, built into container (debian)
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

When making json-rpc calls to method "trace_filter" (https://wiki.parity.io/JSONRPC-trace-module#trace_filter), providing: 
- fromBlock
- toBlock (using most recent block height retrieved from tracing node), 
- toAddress
- fromAddress  

Sometimes (<10% time) an empty array of traces is returned, despite seeing transactions confirmed within block range on etherscan. However, if I were to make exact same call later (say 30 seconds), i would see the transaction appear in the returned trace.

Is there some sort of delay before being able to tracing brand new blocks?

**Comment by AlexWilton** [comment]
Similar issue to https://github.com/paritytech/parity-ethereum/issues/7228

**Comment by adria0** [comment]
Closing the issue due to its stale state
