### ISSUE TITLE
[Private transactions] High gas usage issue after a few tx on private contract

### ISSUE THREAD

**Issue by CremaFR** [openethereum/openethereum#10352]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.3.0-unstable-10657d96c-20190115
- **Operating system**: MacOS
- **Installation**:  built from source
- **Fully synchronized**: yes
- **Network**: private POA
- **Restarted**: yes

Settings: private [contract](https://gist.github.com/CremaFR/a00d226d011201422d3878bed751a7b1) deployed with 1 validator. There is 3 keyserver in our network.

We think there is an issue with gas usage using `private_sendTransaction` on our private contract.

We tried to add several accounts in our private contract but at the 4th account we hit the gas limit of 8M (0x7A1200). Our private node rejected the transaction with

` 2019-02-14 10:34:15  IO Worker #0 WARN privatetx  Failed to add transaction to queue, error: GasLimitExceeded { limit: 8000000, got: 8400400 }
2019-02-14 10:34:15  IO Worker #0 WARN privatetx  Unable to process the signature: Error of transactions processing Transaction error (Gas limit exceeded. Limit=8000000, Given=8400400)`

After resetting our blockchain data and increasing the gas limit to 80M in the chainspec. Adding account failed at 14 hitting gas limit

` 2019-02-14 10:44:25  IO Worker #0 WARN privatetx  Failed to add transaction to queue, error: GasLimitExceeded { limit: 23867002, got: 25404000 }
2019-02-14 10:44:25  IO Worker #0 WARN privatetx  Unable to process the signature: Error of transactions processing Transaction error (Gas limit exceeded. Limit=23867002, Given=25404000)`

When I query `eth_getTransactionReceipt` for the last transaction that goes through I get `{"blockHash":"0x894f5117d38fc6fbf4dabcca5fd2fb0374a870a7f44e19a274c80a237c973a31","blockNumber":"0x4d5","contractAddress":null,"cumulativeGasUsed":"0xc42f7","from":"0x1821c8a9c257a668b0a4285f9db1afd88f28718a","gasUsed":"0xc42f7","logs":[],"root":null,"status":"0x1","to":"0xdd269b93781e862d0df106c26fc7817051e47f53","transactionHash":"0xc1da29237869c6883e3d25b70a68ae8f30d6b66deac934588eca1fc19a05847e","transactionIndex":"0x0"},"id":1}`

so around 800k gas used which looks more "right" 

btw the transaction hash returned by `private_sendTransaction` is different than the one actually mined in the blockchain.

**Comment by adria0** [comment]
Closing the issue due to its stale state
