### ISSUE TITLE
Peering using `parity_addReservedPeer`  does not peer properly

### ISSUE THREAD

**Issue by araskachoi** [openethereum/openethereum#10404]
- **Parity Ethereum version**: v2.2.11-stable-683119f32-20190214
- **Operating system**: Linux
- **Installation**: built from source
- **Network**: custom

The peering mechanism seems to be a bit fidgety when trying to peer using the command `curl --data '{"method":"parity_addReservedPeer","params":["<enode address<@<ip>:30303"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <ip>:8545`
When calling it, the output of this call is:
`{"jsonrpc":"2.0","result":true,"id":1}`

And after, I check the peer list by calling:
`curl --data '{"method":"parity_netPeers","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <ip>:8545`
Which gives:
`{"jsonrpc":"2.0","result":{"active":0,"connected":0,"max":0,"peers":[]},"id":1}`

My colleague and I have tried to investigate and we found that this (command) needed to be called many times before the node was able to peer with a node. 

**actual** 
- peering stakes place with 20 JSONRPC calls

**expected behavior** 
- peering should take place with just one JSONRPC call

**steps to reproduce**
- set up 3 nodes (on a private network)
- create 3 new addresses that you will add to the keystore directory
- these addresses will be added into the custom genesis file and config file (and need to create a password file to unlock)
- using a custom genesis file `customeGenesis.json`:
`{ 
    "name": "testnet",
    "engine": {
        "Ethash": {
            "params": {
              "minimumDifficulty": "0x20000",
              "difficultyBoundDivisor": "0x800",
              "durationLimit": "0x800",
              "blockReward": "0x4563918244f40000"
            }
        }
    },
    "genesis": {
        "seal": {
            "ethereum": {
                "nonce": "0x0000000000000042",
                "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x186a0",
        "gasLimit": "0x3d0900"
    },
    "params": {
            "networkID" : "0x3c6c",
            "maximumExtraDataSize": "0x20",
            "minGasLimit": "0x1388",
            "gasLimitBoundDivisor": "0x400"
    },
    "accounts": {"0x....":{"balance":""},"0x...":{"balance":""},"0x....":{"balance":""}}`
- using this configuration file:
```
[parity]
mode = "last"
mode_timeout = 300
mode_alarm = 3600
auto_update = "critical"
release_track = "current"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false

chain = "/parity/customGenesis.json"
base_path = "/parity"
db_path = "/parity"
keys_path = "/parity/keys"
identity = ""
light = false

[account]
unlock = ["0x....","0x....","0x...."]
password = ["/parity/passwd"]
keys_iterations = 10240

[network]
port = 30303
min_peers = 0
max_peers = 50
nat = "any"
id = 123456
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false

reserved_only = false

[rpc]
disable = false
port = 8545
interface = "all"
cors = []
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub","parity_accounts","personal","parity_set"]
hosts = ["all"]

[websockets]
disable = false
port = 8546
interface = "0.0.0.0"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh","parity_accounts","personal","parity_set"]
hosts = ["all"]

[ipc]
disable = false
path = "$HOME/.local/share/io.parity.ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "traces", "rpc", "shh", "shh_pubsub","personal","parity_set"]

[dapps]
disable = false

[secretstore]
disable = false
nodes = []
http_interface = "local"
http_port = 8082
interface = "local"
port = 8083
path = "$HOME/.local/share/io.parity.ethereum/secretstore"

[ipfs]
enable = false
port = 5001
interface = "local"
cors = []
hosts = ["none"]

[mining]
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 4000
reseal_max_period = 60000
work_queue_size = 20
relay_set = "cheap"
usd_per_tx = "0.0025"
usd_per_eth = "auto"
price_update_period = "hourly"
gas_floor_target = "4700000"
gas_cap = "6283184"
tx_queue_size = 8192
tx_queue_strategy = "gas_price"
tx_gas_limit = "6283184"
tx_time_limit = 100
extra_data = "Parity"
remove_solved = false
notify_work = ["http://localhost:3001"]
refuse_service_transactions = false

[footprint]
tracing = "auto"
pruning = "auto"
pruning_history = 64
pruning_memory = 32
cache_size_db = 128
cache_size_blocks = 8
cache_size_queue = 40
cache_size_state = 25
cache_size = 128 # Overrides above caches with total size
fast_and_loose = false
db_compaction = "ssd"
fat_db = "auto"
scale_verifiers = true
num_verifiers = 6

[snapshots]
disable_periodic = false

[misc]
logging = "own_tx=trace"
log_file = "/var/log/parity.log"
color = trueroot
```

- get the enode addresses of those nodes using:
`curl -sS -X POST http://<ip>:8545 -H "Content-Type: application/json"  -d '{ "method": "parity_enode", "params": [], "id": 1, "jsonrpc": "2.0" }'`

- add those enode addresses to the `parity_addReservePeer` command:
`curl --data '{"method":"parity_addReservedPeer","params":["<enode address>:30303"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <ip>:8545`

- check the number of peers the node has:
`curl --data '{"method":"parity_netPeers","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST <ip>:8545`
-- this step is what needs to be repeated 20 times (in a for loop) in order for the node(s) to be peered with one another

**Comment by joshua-mir** [comment]
Are you certain it isn't just taking time to attempt to establish a connection to the new reserved peer? ie, have you tried simply making the single request and waiting a while? Will agree neither is ideal behavior.

**Comment by araskachoi** [comment]
I think the issue was that it took some time for it to peer. We just jam it into a for loop until it picks the peer up lol 😅

**Comment by adria0** [comment]
Closing issue due to its stale state.
