### ISSUE TITLE
Avoid using unnamed threads 

### ISSUE THREAD

**Issue by joshua-mir** [openethereum/openethereum#10402]
We currently use a mixture of thread::spawn and thread::Builder throughout the codebase - when a panic occurs in an unnamed thread (created via thread::spawn) it is harder to debug, and additionally if there is an error in spawning the thread - thread::Builder can handle it whereas with thread::spawn that is not possible (afair it leads to a panic, but this is less important because I don't believe we ever see this issue in our codebase).

we should perhaps consider "naming" *all* threads (and having handlers for failure in the spawning of a thread, although this is probably less important in our case)

**Comment by adria0** [comment]
Closing the issue due to its stale state
