### ISSUE TITLE
Transaction gets dropped before reaching queue limit

### ISSUE THREAD

**Issue by Pzixel** [openethereum/openethereum#10436]
- **Parity Ethereum version**: 2.2.11
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**:yes
- **Network**: private
- **Restarted**:  yes

Here I am again with my RPC problem. I see transactions get droppen even when queue size is 100k! I don't know for what reason it happens, but I clearly see it in logs. I tried to configure it via toml and pass via command line argument. Unfortunately, parity doesn't log what configuration it's exactly running so I don't know if this option is ignored somehow or there is a bug somewhere else.

Here is a small log for several minutes of working. You can see that it contains multiple "Dropped" statements. As per my app logic, transaction must not fail or the app breaks. I'm struggled now because I tried a lot of different configurations, but it doesn't work.

Running via docker-compose. Command:

```
    command:
      --config /parity/config/authority.toml
      --engine-signer 0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2
      --jsonrpc-interface 0.0.0.0
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --no-warp
      --tx-queue-per-sender 100000
      -lminer=trace,rpc=trace,txqueue=trace
```

authority.toml:

```
[parity]
chain = "/parity/config/chain.json"

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[network]
bootnodes = [
      "enode://147573f46fe9f5cc38fbe070089a31390baec5dd2827c8f2ef168833e4d0254fbee3969a02c5b9910ea5d5b23d86a6ed5eabcda17cc12007b7d9178b6c697aa5@10.127.9.138:30303",
      "enode://1412ee9b9e23700e4a67a8fe3d8d02e10376b6e1cb748eaaf8aa60d4652b27872a8e1ad65bb31046438a5d3c1b71b00ec3ce0b4b42ac71464b28026a3d0b53af@10.127.9.139:30303",
      "enode://9076c143a487aa163437a86f7d009f257f405c50bb2316800b9c9cc40e5a38fef5b414a47636ec38fdabc8a1872b563effa8574a7f8f85dc6bde465c368f1bf5@10.127.9.140:30303"
  ]

[account]
password = ["/parity/authority.pwd"]

[mining]
reseal_on_txs = "none"
tx_queue_size = 16384
tx_queue_mem_limit = 4096
tx_queue_per_sender = 100000
```

I send ~400 tx simultaneously and don't send another batch until this one gets processed, so there is no more than 400 txs in queue at any moment of time.

I also get tons of "Transaction culled", but I'm not sure what does it mean and if it's related somehow.

**Comment by joshua-mir** [comment]
@Pzixel transactions may be culled if they do not provide a high enough gas price to be included based on your settings (you should configure `min_gas_price` in your mining section, 0 is only safe if this is a private network) or if they share a nonce with another transaction that has a higher gas price. < manually setting your nonce, especially with batched requests, is the way to prevent this, if you aren't already doing that.

**Comment by Pzixel** [comment]
Okay, I see.

However, the main question still. Txs gets dropped when they shouldn't.

**Comment by joshua-mir** [comment]
> Here is a small log for several minutes of working.

Can you share this, along with an example transaction, or a snippet from the code generating the transactions?

**Comment by Pzixel** [comment]
Oh, sorry. I supposed to include it and I didn't

**Comment by Pzixel** [comment]
[parity-json.zip](https://github.com/paritytech/parity-ethereum/files/2914845/parity-json.zip)

**Comment by Pzixel** [comment]
I still getting this issue with brand new network, with new network name. I can provide full log but it's quite large (1GB of text)

**Comment by Pzixel** [comment]
https://drive.google.com/file/d/1IXfV6FzFTZZSonfszgJQsnwjZ9WBYd2Z/view?usp=sharing

Full 1GB log, starting from running clean parity instance (with new network name, etc, no nodes connected) until it started to drop stuff.

**Comment by joshua-mir** [comment]
Likely related: #10228

**Comment by adria0** [comment]
Closing issue due to its stale state.
