### ISSUE TITLE
Warp sync fails with memory allocation failed

### ISSUE THREAD

**Issue by zet-tech** [openethereum/openethereum#10447]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.11
- **Operating system**: Linux
- **Installation**: binary
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

We try to full resync one of our nodes. But it continuously fails the warp sync. It tries for at last 3 days. Disk space (ssd) is not the problem (we always have more than 80GB free). The VM have 32GB of RAM and 8 vCores and parity is the only significant running process (it is configured to use total 21GB of cache).

We attach logs and config. We use this config for more then one year so it is not a problem.
 
[eth.conf.txt](https://github.com/paritytech/parity-ethereum/files/2927005/eth.conf.txt)
[parity.log](https://github.com/paritytech/parity-ethereum/files/2926993/parity.log)

**Comment by joshua-mir** [comment]
Likely related to #10371 - OOM and memory allocation issues.

**Comment by adria0** [comment]
Closing issue due to its stale state.
