### ISSUE TITLE
[Feature-request]: Whitelisting service transaction destinations

### ISSUE THREAD

**Issue by alesanro** [openethereum/openethereum#10442]
Having configurable service transactions through Register and Certifier contracts is great and works perfect in most cases.

There is a suggestion/something to think about: it would be nice to have an ability to allow service transactions specified not only by their origin (sender) but also by a transaction destination (contract address or EOA). So it could be a contract with an interface like this
```json
[
	{ "constant": true, "inputs": [], "name": "activated", "outputs": [ { "name": "", "type": "bool" } ], "payable": false, "stateMutability": "view", "type": "function" },
	{ "constant": true, "inputs": [ { "name": "_target", "type": "address" } ], "name": "whitelisted", "outputs": [ { "name": "", "type": "bool" } ], "payable": false, "stateMutability": "view", "type": "function" }
]
```

`whitelisted(address _target)` would allow to check if `_target` address is from ACL and if so then treat it as service transaction. Removing such contract from registrar would revert current service transaction checker logic back.

**Comment by joshua-mir** [comment]
I'm quite certain that the reason this isn't feasible is because it introduces a DoS vector (if every transaction *to* a specific account or contract is free, people can just spam junk transactions to the contract and fill up your chain, regardless of which contract it is)

**Comment by alesanro** [comment]
Probably I was not clear enough about application of this feature: it must work only with original service transaction checker, so at first sender check should pass and only then destination check should come. It more like additional restriction to already existed service transaction requirements.

**Comment by adria0** [comment]
Closing issue due to its stale state.
