### ISSUE TITLE
RPC hangs after consistent requests over a period of time 

### ISSUE THREAD

**Issue by Pzixel** [openethereum/openethereum#10455]
- **Parity Ethereum version**: 2.2.11
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: private
- **Restarted**: yes

When sending lots of txs in the  blockchain at some point it rejects all RPC requests. Here are my logs (it's 7z archive, I renamed it to .zip to upload on github) - [log5.7z.zip](https://github.com/paritytech/parity-ethereum/files/2937218/log5.7z.zip).

My load is sending txs and then calling `eth_getTransactionReceipt` each second to see if tx was mined. The last line with this message was 
```
{"log":"2019-03-06 15:44:42 UTC jsonrpc-eventloop-1 TRACE rpc  Request: {\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0x0294eddf7d8d03ba1d651fa9d39170474e00e4c58842dc66161638f2f856e9f9\"]}.\n","stream":"stderr","time":"2019-03-06T15:44:42.052929678Z"}
```

And then logs are clean as there are no pending HTTP requests. But on the client side I see `RpcTimeoutError`.

I'm running with

```
      --jsonrpc-server-threads=8
      --jsonrpc-threads=0
```

**Comment by joshua-mir** [comment]
Possibly Related/duplicate of: #10344, #10321

**Comment by Pzixel** [comment]
Is not related to #10344 , may be related to #10321 but here we have more detailed logs.

**Comment by Pzixel** [comment]
I think the problem is
1. Bad parity RPC performance
2. Lack of 503 error when pending RPC requests are above some treshold.

**Comment by ayrat555** [comment]
@Pzixel did you find a solution for this?

**Comment by Pzixel** [comment]
Nope, I just don't work with parity anymore as well as I put on fire all my PCs where I have been writing my smart contracts. Hopefully I will never face blockchain techs anymore. Edge bleeds too much,

**Comment by ayrat555** [comment]
@adria0 is it fixed?

**Comment by adria0** [comment]
@ayrat555 This bug is reported in the `2.2.11` version. The currently supported versions now are the 2.7.2 and 3.0.1

**Comment by ayrat555** [comment]
Did you try reproducing it on the latest version?
