### ISSUE TITLE
Transactions get stuck forever in blockchain

### ISSUE THREAD

**Issue by Pzixel** [openethereum/openethereum#10453]
- **Parity Ethereum version**: 2.2.11
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: private
- **Restarted**: yes

I have an aura network which suddenly stopped to mine transactions. I have step duration 5 seconds and tx can't get mined in last 30 minutes. I don't know what's wrong. When I read logs I see that txs were added to the pool an then... Nothing happens. They are not rejected, they are not mines, they just stuck. Moreover, I have `--force-signing` which worked fine until this happened. Previosely it was generating a block once per each 5 seconds, now it doesn't generate anything at all.

I restarted but nothing happened. This is log after I restarted parity:

[log_fail.json.log](https://github.com/paritytech/parity-ethereum/files/2936264/log_fail.json.log)

**Comment by adria0** [comment]
Closing issue due to its stale state.
