### ISSUE TITLE
Test static validator set changes in Aura

### ISSUE THREAD

**Issue by HCastano** [openethereum/openethereum#10468]
As part of fixing #10306 through #10467 I figured it would be good to write a test to simulate a change in validators that were defined in a chain spec. This turned out to be a bit harder than expected so I plan to tackle it separately. The idea would be to create a new `aura_test_multi_validators.json` chain spec that has something like

```
"multi":
{
    "0": {
         "list": ["<address0>"]
    },
     "10": {
         "list": ["<address0>, <address1>"],
     }
}
```

and check the validator list at block 0. After making some fake blocks we should then jump to block `transition_block + 1` and check the validator list again. At this point we should expect the new validator to be part of this list.

**Comment by adria0** [comment]
Closing issue due to its stale state.
