### ISSUE TITLE
'ByzantiumToConstantinopleFixAt5' chain spec for json tests

### ISSUE THREAD

**Issue by cheme** [openethereum/openethereum#10461]
We currently do not have the chain spec for running 'ByzantiumToConstantinopleFixAt5'. Those are test of transition to constantinople (with constantinople specifics activated at block 5 iiuc).
This depends on the upcomming update of the submodule pointing to json test #10400

**Comment by adria0** [comment]
being implemented in https://github.com/openethereum/openethereum/pull/11597
