### ISSUE TITLE
Node doesn't sync

### ISSUE THREAD

**Issue by Pzixel** [openethereum/openethereum#10474]
- **Parity Ethereum version**: 2.2.11
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: private
- **Restarted**: yes

For some reason one of my nodes eventually stopped to sync. Suddenly, this is the same node that gets bombarded by RPC requests (other nodes are internally visible only). It worked fine until it just stopped to mine more blocks. It receives RPCs/responds them, when I send txs it resend them to other nodes so they mine more blocks. But this node doesn't mine anything.

Here is ethstats dashboard:

![image](https://user-images.githubusercontent.com/11201122/54320985-0e937580-4600-11e9-87cc-7028140b1d76.png)

And here are logs
[log_nosync.txt](https://github.com/paritytech/parity-ethereum/files/2964037/log_nosync.txt)

**Comment by adria0** [comment]
Closing issue due to its stale state.
