### ISSUE TITLE
`eth_getTransactionCount` and `eth_getTransactionReceipt` do not query the same state if two blocks with equal height present

### ISSUE THREAD

**Issue by reverendus** [openethereum/openethereum#10505]
- **Parity Ethereum version**: 2.2.11
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

I am running into behaviour I cannot really explain regarding `eth_getTransactionCount` and `eth_getTransactionReceipt`. I am tracking my own transactions confirming, I know there is only one transaction in the pool with some specific `nonce` (as I only sent one), but on rare occasion it happens to me that `eth_getTransactionCount(..., 'latest')` starts to report the account nonce already increased, but `eth_getTransactionReceipt` still doesn’t report the `blockNumber` in the receipt for the next few seconds.

I tried to correlate what my rpc client sees with Parity logs and that’s what I discovered:
```
2019-03-20 19:30:28 UTC Imported #7407625 0xabaa…b4ab (103 txs, 6.30 Mgas, 623 ms, 23.28 KiB)
2019-03-20 19:30:41 UTC Imported #7407626 0x5ded…1b8d (203 txs, 7.83 Mgas, 792 ms, 28.30 KiB)
2019-03-20 19:30:50 UTC Transaction mined (hash 0x…myhash...)
2019-03-20 19:30:50 UTC Imported #7407627 0x1a39…f65b (123 txs, 7.99 Mgas, 698 ms, 20.88 KiB)
2019-03-20 19:30:58 UTC Imported #7407628 0x0b3c…7f7b (184 txs, 7.76 Mgas, 529 ms, 27.94 KiB)
```

So `eth_getTransactionCount(..., 'latest')` goes up by one at `19:30:41 UTC`, the moment block `#7407626` gets imported. But the block number in the receipt (fetched via `eth_getTransactionReceipt`) doesn’t become available until `19:30:50 UTC` i.e. the moment when the next block (`#7407627`) gets imported. As I wrote before it’s not the first time it happened to me, but when it happens it’s always when a small (one block) reorg takes place. So my transaction `0x…myhash…` got actually included in block `#7407626`, but not the one with hash `0x5ded…1b8d` i.e. not the one Parity originally ingested at `19:30:41 UTC` (which then became an uncle https://etherscan.io/uncle/0x5ded68b54110b47737123eea94b2a6df89c0b36e5eac08a7000e31d23e871b8d), but the `#7407626 0x01a8f0d…` block which then `#7407627 0x1a39…f65b` linked to as its parent.

I perfectly understand that, small reorgs like that must be fairly common. What I don’t understand is that why do these two things (`eth_getTransactionCount(..., 'latest')` going up and the block number becoming available in the receipt) do not happen at the same time. If my transaction did get included in the pre-reorg `#7407626 0x5ded…1b8d` block, I would expect both the counter go up and the block number in the receipt to become available at `19:30:41 UTC`. If my transaction wasn’t included in the pre-reorg `#7407626 0x5ded…1b8d` block then why would `eth_getTransactionCount(..., 'latest')` already go up at `19:30:41 UTC`?

The only plausible explanation I can find is that during that period of time Parity had two blocks `#7407626` imported, and `eth_getTransactionCount(..., 'latest')` was looking at one of them but `eth_getTransactionReceipt` at the other one. I think the same problem got already reported here https://github.com/paritytech/parity-ethereum/issues/7689, but this issue got closed by providing another means of fetching that information and not by solving the actual problem.

**Comment by adria0** [comment]
Closing issue due to its stale state.
