### ISSUE TITLE
parity_composeTransaction rejects txs with `chainId` field

### ISSUE THREAD

**Issue by charles-cooper** [openethereum/openethereum#10512]
- **Parity Ethereum version**:   Parity-Ethereum/v2.3.8-stable-a39aaac-20190322/x86_64-linux-gnu/rustc1.33.0
- **Operating system**: Ubuntu bionic
- **Installation**: pulled from github release page
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

Calling `parity_composeTransaction` RPC endpoint with a transaction which contains a `chainId` results in the following error, instead of returning the transaction with other fields filled in.
```
{'code': -32602, 'message': 'Invalid params: unknown field `chainId`, expected one of `from`, `to`, `gasPrice`, `gas`, `value`, `data`, `nonce`, `condition`.'}
```
Possibly related to https://github.com/paritytech/parity-ethereum/issues/10411.

**Comment by joshua-mir** [comment]
Parity should be using the chainId/networkId of the chain it is currently running. If you want to composeTransaction *for a different network* than parity is on, you should probably be building your transactions on the client side. (and tbh, you should be doing that anyway as account management is deprecated as of parity 2.4.x)

**Comment by charles-cooper** [comment]
> If you want to composeTransaction for a different network than parity is on, you should probably be building your transactions on the client side. (and tbh, you should be doing that anyway as account management is deprecated as of parity 2.4.x)

I would expect parity_composeTransaction to check the supplied chainId is equal to the chain that it is on and reject the input if it is not

**Comment by joshua-mir** [comment]
Yes, and that's what #10411 is asking for.

**Comment by joshua-mir** [comment]
Will close as duplicate for now. lmk if you disagree.

**Comment by charles-cooper** [comment]
While related, I don't think this is a duplicate of #10411. That issue is that sendTransaction does not validate that chainId is the same as the chainId that the node is on. This issue that composeTransaction rejects transactions with the `chainId` field entirely.

**Comment by adria0** [comment]
Closing issue due to its stale state.
