### ISSUE TITLE
EIP 615: Subroutines and Static Jumps for the EVM

### ISSUE THREAD

**Issue by bmann** [openethereum/openethereum#10549]
We have a grant reviewer who would like to ensure that we have a good chance of having code accepted.

If we get funded to build a high quality [EIP615 Static Jumps & Subroutines](https://eips.ethereum.org/EIPS/eip-615) implementation, will you accept a PR to add it to your client?

@expede is a Rust developer and VM expert and will be the one leading the implementation.

**Comment by joshua-mir** [comment]
Of course, we always accept PRs given the requestor is willing to go through the review process.

**Comment by soc1c** [comment]
Please use this as tracking ticket. :rocket:

**Comment by bmann** [comment]
Will do, thank you.

**Comment by adria0** [comment]
Closing issue due to its stale state.
