### ISSUE TITLE
Bad block error message during Secret Store network setup

### ISSUE THREAD

**Issue by jordipainan** [openethereum/openethereum#10557]
- **Parity Ethereum version**: Parity-Ethereum/v2.4.0-unstable-c7d8ee1dd-20190227/x86_64-macos/rustc1.33.0-nightly
- **Operating system**: MacOS 10.14.3
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: private PoA
- **Restarted**: yes

**NOTE**: Same config used in some Ubuntu 18.04 pcs and works :')

**actual**

Trying to set up the network like in the Secret Store tutorial, using dev chain or using basic custom PoA chain, at first block creation the other nodes fail to import that block and the block issuer lose all its peers.

non-authority nodes logs:

`Stage 1 block verification failed for 0x21b2…e89f: Error(Block(ExtraDataOutOfBounds(OutOfBounds { min: None, max: Some(32), found: 39 })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
2019-04-01 19:52:20
Bad block detected: ExtraDataOutOfBounds(OutOfBounds { min: None, max: Some(32), found: 39 })
RLP: f9024ef90249a00c94cbe1a0474a3ecce0f97d74d70bf86c02197cb7bb164267607430801dc616a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794d21fbf6c7c1edc4e36baa6c1d6c6154ac42726dda04ea5ee2846d91264982e3a5d732eb66d6ab732344cdee440e135b71fb9107671a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000090ffffffffffffffffffffffffed79233b01835ba46280845ca24fd4a7e6830204008f5061726974792d457468657265756d8e312e33332e302d6e696768746c79826d61841286dcc4b84134f2de3430bfd6c31e718a527e2fc52d90c32617b1929c0e889a364c79a4ad2702c998652a4ed2ad6af36213409d591c703f548043cdcbfa9a4783e34cde339d00c0c0
Header: Header { parent_hash: 0x0c94cbe1a0474a3ecce0f97d74d70bf86c02197cb7bb164267607430801dc616, timestamp: 1554141140, number: 1, author: 0xd21fbf6c7c1edc4e36baa6c1d6c6154ac42726dd, transactions_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [230, 131, 2, 4, 0, 143, 80, 97, 114, 105, 116, 121, 45, 69, 116, 104, 101, 114, 101, 117, 109, 142, 49, 46, 51, 51, 46, 48, 45, 110, 105, 103, 104, 116, 108, 121, 130, 109, 97], state_root: 0x4ea5ee2846d91264982e3a5d732eb66d6ab732344cdee440e135b71fb9107671, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 0, gas_limit: 6005858, difficulty: 340282366920938463463374607431457383227, seal: [[132, 18, 134, 220, 196], [184, 65, 52, 242, 222, 52, 48, 191, 214, 195, 30, 113, 138, 82, 126, 47, 197, 45, 144, 195, 38, 23, 177, 146, 156, 14, 136, 154, 54, 76, 121, 164, 173, 39, 2, 201, 152, 101, 42, 78, 210, 173, 106, 243, 98, 19, 64, 157, 89, 28, 112, 63, 84, 128, 67, 205, 203, 250, 154, 71, 131, 227, 76, 222, 51, 157, 0]], hash: Some(0x21b23010fc975eafaeb04acf2d48d9893e9cf55890dc38ec48cc0b70ed53e89f) }
Uncles:
Transactions:`

authority node logs:

`2019-04-01 19:50:19  Starting Parity-Ethereum/v2.4.0-unstable-c7d8ee1dd-20190227/x86_64-macos/rustc1.33.0-nightly
2019-04-01 19:50:19  Keys path db.users/keys/PoA
2019-04-01 19:50:19  DB path db.users/chains/PoA/db/b7bb164267607430
2019-04-01 19:50:19  State DB configuration: fast
2019-04-01 19:50:19  Operating mode: active
2019-04-01 19:50:19  Configured for PoA using AuthorityRound engine
2019-04-01 19:50:20  Listening for new connections on 127.0.0.1:8546.
2019-04-01 19:50:25  Public node URL: enode://e3e8d984e8d1d2b3355f0b856d77a4b971d5de738e6d889e6907768b69e8f61f4a4439beb06153dcfba7ea640c41a40c45dc0f4023fc696844776f2baa1874f2@192.168.0.16:30300
2019-04-01 19:50:50     3/25 peers   8 KiB chain 1 KiB db 0 bytes queue 15 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-04-01 19:51:20     3/25 peers   8 KiB chain 1 KiB db 0 bytes queue 15 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-04-01 19:51:50     **3/25 peers**   8 KiB chain 1 KiB db 0 bytes queue 15 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-04-01 19:52:20  **Imported #1 0x21b2…e89f** (0 txs, 0.00 Mgas, 12 ms, 0.58 KiB)
2019-04-01 19:52:20     **0/25 peers**   8 KiB chain 2 KiB db 0 bytes queue 15 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
^C2019-04-01 19:52:25  Finishing work, please wait...`

**expected behavior**

The other nodes can import blocks.

**steps to reproduce**

https://wiki.parity.io/Secret-Store-Tutorial-1.html

**screenshots**

before block: https://imgur.com/a/eW4Mt4W
after block: https://imgur.com/a/qSQqxiW

**config files**

https://gofile.io/?c=k6AV0E

I also used InstantSeal engine

**Comment by joshua-mir** [comment]
I'm still personally uncertain about whether instantSeal is suitable for multinode networks and whether that's related to your issue - it's presence in the tutorial makes me reconsider though

**Comment by adria0** [comment]
Closing issue due to its stale state.
