### ISSUE TITLE
API "parity_liststoragekeys" documentation improvement

### ISSUE THREAD

**Issue by yxliang01** [openethereum/openethereum#10572]
The documentation for API `parity_listStorageKeys` is unclear about the `Hash` option that I am not sure whether the followings are true:
1. when invoked with `offset = "0x0"` and `quantity = 2`, is the storage keys returned **always** equal to the combination of two invocations: 1) `offset = "0x0"` and `quantity = 1` 2) `offset = "0x1"` and `quantity = 1`?
2. Should `Hash` be of type `string` and a `0x` prefixed number, and the length of the string should always be 18 (2 for `0x` + 16 hexadecimal characters)?

Also, I feel "`Offset`" is a better name for the option, rather than "`Hash`".
Essentially, this issue is both a question and potential improvement kind of issue.

Thanks

**Comment by joshua-mir** [comment]
1) I don't think `Offset` is an accurate replacement for `Hash` - `Hash` *is the storage key, not the offset to the key*
2) yes.

**Comment by yxliang01** [comment]
@joshua-mir 1. Right, indeed. I had misunderstanding back then since I saw the word "Offset" - was thinking it is a constant integer offset.

So, I would like to be sure that whether the order of storage keys is consistent across nodes? Or, it's only persistent in only one node all the time?

**Comment by joshua-mir** [comment]
I can't immediately comment on the order of the jsonrpc response, I do *believe* the order should be consistent, but that will need verification. I am certain you will get the same keys for the same Quantity/Hash/Address combination regardless of the node.

**Comment by adria0** [comment]
Closing issue due to its stale state.
