### ISSUE TITLE
Unclear definition of Loose tuple discriminator in pip1

### ISSUE THREAD

**Issue by FrankSzendzielarz** [openethereum/openethereum#10578]
According to the pip1 docs, the following:
`discriminant[U8, data].

If the discriminant is 0, data is an RLP-encoded value of the expected type. If the discriminant is 1, data is an output back-reference, as described above. All other discriminant values are undefined and are not valid under PIP.``

What is the U8 here? Is this the discriminant? Am in the process of transcribing the pip1 docs to the devp2p repo and trying to homogenise the doc format.

**Comment by joshua-mir** [comment]
https://github.com/paritytech/parity-ethereum/issues/9579#issuecomment-422426922 this is what I was referring to on gitter

(cc @rphmeier)

**Comment by rphmeier** [comment]
Yes, the `U8` is the discriminant.

**Comment by joshua-mir** [comment]
Thanks!

**Comment by rphmeier** [comment]
(docs need fixing)

**Comment by joshua-mir** [comment]
👍

**Comment by FrankSzendzielarz** [comment]
Separate issue but could you pls either pm me or add to original doc some info on the rationale for the cht spanning the 2048 blocks sequentially? As opposed to cumulatively? Me and zsolt were reviewing and scratching our heads a bit. Was it just to facilitate implementation?


On 8 Apr 2019 14:40, joshua-mir <notifications@github.com> wrote:

👍

**Comment by rphmeier** [comment]
1. Full nodes don't need to keep the full chain forever
2. Overhead of keeping a 32-byte CHT root for every 2048 headers is still a huge win.

**Comment by FrankSzendzielarz** [comment]
@rphmeier Ok I think I get where you are coming from..... I am trying to work on a unified direction for light protocols and achieve some consensus. It looks like it's going to be important to get your input, I will ping you with updates to the devp2p repo soon and hopefully we can try to hammer out the common direction there.

**Comment by rphmeier** [comment]
Yeah there are a bunch of weird things with the cumulative roots. The only way that they're useful is when hardcoded into a light node (which gets outdated quickly), and they probably take forever to generate. Light nodes can generate their own as they sync and then can fetch past blocks without worrying.

If the overhead of storing 32-bytes for every 2048 headers, you can just zip up every 2048 CHT roots (2^22 = ~4 million) into a bigger trie root.

**Comment by FrankSzendzielarz** [comment]
@rphmeier I don't know if you have access to the devp2p repo but I have added the pip/1 transcription there based on the wiki pip/1 proposal document.  Please could review the PR or comment? Also loop me in to any doc/protocol changes such as the above?

https://github.com/ethereum/devp2p/blob/578b4c9d59634e72744eb93c43d688e88a86e517/caps/pip.md

One thing I am confused about it is the message format 0x8 Executions, but maybe some other forum for that.

**Comment by adria0** [comment]
Closing issue due to its stale state.
