### ISSUE TITLE
Reverted report validator transactions get added in block

### ISSUE THREAD

**Issue by VladLupashevskyi** [openethereum/openethereum#10580]
While doing some tests with Validators contract I found out that if `reportBenign` transaction gets reverted due to smart contract logic, this tx gets added to the block.

It seems to me that there is no sense to put such transactions and they should be filtered via doing `estimateGas` first. Thus we save validator's ether as well as the volume in the block (imagine having 50 validators and contract where `reportBenign` is disabled via `revert`, but `reportMalicious` still takes place. In this case if 1 validator goes offline 49 would put reverted tx which costs 25k gas each, so in total ~1.2kk gas will be wasted).

I would propose to add `estimateGas` or `call` kind of checking to `transact` method of `ValidatorContract`. What do you think about it?

**Comment by VladLupashevskyi** [comment]
> This means that you need to exercise care when writing your smart contracts so you don't end up with a scenario like this unintentionally.

Very much agree!

I will try to open PR to fix that this week.

**Comment by adria0** [comment]
Closing issue due to its stale state.
