### ISSUE TITLE
Panic restoring from snapshot 

### ISSUE THREAD

**Issue by strusty** [openethereum/openethereum#10611]
3 TB Raid 5 SSD, brand new.  8GB memory, Asus z270f strix mb.

Ran this twice, keep getting same error.

- **Parity Ethereum version**:v2.5.0-beta-b52ac20-20190408
- **Operating system**:  Linux Ubuntu 18.04
- **Installation**:  one-line installer 
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

Thread 'IO Worker #0' panicked at 'Low-level database error. Some issue with your hard disk?: Custom { kind: Other, error: StringError("Corruption: block checksum mismatch: expected 4047782851, got 2069718997  in /home/sysadmin/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/snapshot/restoration/db/017601.sst offset 67122786 size 185232") }', src/libcore/result.rs:997

====================

stack backtrace:
   0:     0x5613d37a84cd - <no info>
   1:     0x5613d37a75f2 - <no info>
   2:     0x5613d37a6836 - <no info>
   3:     0x5613d22f1218 - <no info>
   4:     0x5613d3816839 - <no info>
   5:     0x5613d38162e1 - <no info>
   6:     0x5613d38161c5 - <no info>
   7:     0x5613d3836b1c - <no info>
   8:     0x5613d37c5f29 - <no info>
   9:     0x5613d37d2f23 - <no info>
  10:     0x5613d2fc8d9e - <no info>
  11:     0x5613d2d9c02a - <no info>
  12:     0x5613d2ef873b - <no info>
  13:     0x5613d2ef7d37 - <no info>
  14:     0x5613d2efbe01 - <no info>
  15:     0x5613d27e8c87 - <no info>
  16:     0x5613d27ed9ef - <no info>
  17:     0x5613d27fa7bc - <no info>
  18:     0x5613d27ff8dc - <no info>
  19:     0x5613d27eb68c - <no info>
  20:     0x5613d27e9de2 - <no info>
  21:     0x5613d27fef86 - <no info>
  22:     0x5613d27e9c17 - <no info>
  23:     0x5613d27e9391 - <no info>
  24:     0x5613d27e97fa - <no info>
  25:     0x5613d27ea084 - <no info>
  26:     0x5613d27fec55 - <no info>
  27:     0x5613d27f245c - <no info>
  28:     0x5613d27faf96 - <no info>
  29:     0x5613d27f7a46 - <no info>
  30:     0x5613d3822539 - <no info>
  31:     0x5613d27fe9a7 - <no info>
  32:     0x5613d38218ad - <no info>
  33:     0x7fbe851986da - <no info>
  34:     0x7fbe84ca988e - <no info>
  35:                0x0 - <no info>

**Comment by joshua-mir** [comment]
Can you try again after deleting the snapshot directory? 

I would trying a `--no-warp` sync if you still see this issue after that.

**Comment by adria0** [comment]
Closing issue due to its stale state.
