### ISSUE TITLE
v2.5.0 archival node gets stuck at block 0x2500f4

### ISSUE THREAD

**Issue by j4ys0n** [openethereum/openethereum#10621]
- **Parity Ethereum version**: 2.5.0
- **Operating system**: Linux
- **Installation**: docker, pull published image `FROM parity/parity:v2.5.0`
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

running with the flags:
``` 
/bin/parity \
  --chain=mainnet \
  --cache-size=4000 \
  --auto-update=critical \
  --port=30303 \
  --ws-port=8546 \
  --ws-interface=0.0.0.0 \
  --ws-origins=all \
  --ws-hosts=all \
  --jsonrpc-port=8545 \
  --jsonrpc-interface=0.0.0.0 \
  --jsonrpc-cors=all \
  --base-path=${DATA_DIR} \ <-- putting local dir here
  --jsonrpc-threads=12 \
  --jsonrpc-server-threads=100 \
  --pruning=archive
```

getting block height: `curl -X POST localhost:8545  -H 'Content-Type: application/json' -d '{ "jsonrpc": "2.0", "id": 5, "method": "eth_blockNumber", "params": [] }'`

result: `{"jsonrpc":"2.0","result":"0x2500f4","id":5}`

sync doesn't progress past block `0x2500f4` (2425076)

**Comment by joshua-mir** [comment]
I would recommend increasing cache-size if possible - 4gb for all of parity's cache will mean you are likely writing to/reading from disk several times *per block* in ordinary sync, and on top of that you are running an archive node.

**Comment by Tokens001** [comment]
Fuck you

**Comment by j4ys0n** [comment]
@joshua-mir is there somewhere i can read more about that so i can make an informed choice there?

Also to follow up on the original issue, i bumped the version down to 2.4.5 and it's synced past where 2.5.0 was getting stuck.

**Comment by Tokens001** [comment]
all ISSUE CRYPTO WETH9 ADDRESS
PLEASE STOP IT.
NOBODY CAN MAKE COPY PASTE MY ADDRESS CCRYPTO.ALL STOP.

**Comment by Tokens001** [comment]
@j4ys0n PLEASE CHANGE ADDRESS 
0xb03Fe4027f66c36Bd887A386A726436dDc98fbeA

WE NEED SAVE CRYPTO WETH9
REPORT BY : ADMIN WETH9

**Comment by joshua-mir** [comment]
@j4ys0n https://wiki.parity.io/FAQ.html#what-are-the-parity-ethereum-disk-space-needs-and-overall-hardware-requirements

There's a brief explanation there, and more context on the help page (`parity - h`) or https://wiki.parity.io/Configuring-Parity-Ethereum

**Comment by joshua-mir** [comment]
@Tokens001 can you please make a new issue for whatever you are experiencing, or DM me on gitter.im (@joshua-mir). Please refrain from using abusive language, spamming, and off topic conversation.

**Comment by j4ys0n** [comment]
So the FAQ link says that you can specify`--cache-size` but it doesn't say what's ideal or what would be recommended. It's probably worth explaining somewhere how that cache size relates to performance and what is ideal or recommended. There's a lot left to interpretation there.

I think we're also getting off topic - the issue is that 2.5.0 gets stuck when syncing the chain in archive mode.

**Comment by Tokens001** [comment]
NO control Anyone For WETHN TOKENS - IF U MAKE TO CHANGE AGAIN WE CHANGE DEPARTMENT

**Comment by abunsen** [comment]
Can confirm I've seen this as far back as `v2.3.4-beta` as well. 

Here is the start command: 

```sh
parity --keys-path "/storage/parity/secret_keys" --jsonrpc-hosts all --jsonrpc-apis traces,shh,web3,eth,net,parity,rpc --ws-origins=all --ws-hosts=all --chain mainnet --pruning archive --tracing on --cache-size 4096
```

on a machine with 16GB RAM, 50GB disk + a 4.3TB mounted volume, the only thing that fixes it is a parity stop, `sync; echo 1 > /proc/sys/vm/drop_caches` (which only clears page cache) and then start command above will get blocks syncing again.

Would love to understand what's going on. Any way I can help investigate this?

**Comment by joshua-mir** [comment]
it's my understanding that (unless you are seeing blocks getting ignored repeatedly in your `-l sync` logs,) this issue is usually related to the time spent idling in io, which causes your peers to drop you, and makes it harder to get up to date blocks (which is why I was recommending increasing cache_size - especially in an archive node you want the state trie to be entirely in memory and flushed to disk as few times as possible - if it is not entirely in memory, you need to read from and write to disk, potentially multiple times *every block*) 

 @abunsen I'm not sure how much memory you have available, but if parity's cache is spilling over into your pagefiles that might actually be counterproductive, for the same reason (although it may be necessary to avoid OOM crashes 😅)
