### ISSUE TITLE
Dependency installation instructions could be simplified

### ISSUE THREAD

**Issue by ltfschoen** [openethereum/openethereum#10656]
The installation instructions in this section https://github.com/paritytech/parity-ethereum#build-dependencies could be made simpler for users, so it's similar to the Substrate build instructions https://github.com/paritytech/substrate#6-building.

For example, instead of telling the user what specific dependencies they need, instead just give them a command they can copy paste or a shell script they can run to install the relevant dependencies on different operating systems.  For example, this is the one I use, but it includes some that aren't relevant https://github.com/ltfschoen/parity-ethereum-issue-9660/blob/master/parity-dependencies.sh

Possibly even using Docker as we have in Substrate https://github.com/paritytech/substrate/blob/master/Dockerfile

**Comment by adria0** [comment]
Closing issue due to its stale state.
