### ISSUE TITLE
Local transactions with same nonce but significantly higher gas price are rejected

### ISSUE THREAD

**Issue by marko429** [openethereum/openethereum#10671]
- **Parity Ethereum version**: 2.4.5
- **Operating system**: Linux
- **Installation**: Arch repo
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Actual: When sending local transaction with a gas price, say 5 Gwei, and then a moment later another transaction with the same nonce, but significantly higher gas price 7 Gwei, Parity returns error 32010 "There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee." 

Expected: local transaction with significantly higher fee and same nonce should have been accepted. This was actually the case in prior versions, as long as the gas price increase was high enough. Not sure when the regression happened, but 5 -> 7 Gwei increase would have been accepted in earlier versions.

**Comment by joshua-mir** [comment]
Are you certain your transaction is being ignored due to it's gasPrice and not due to your txqueue being full for the particular sender making the transaction?

**Comment by marko429** [comment]
Pretty sure. It's my own local transaction and the only one.

**Comment by marko429** [comment]
I did some further testing. Downgrading to 2.3.8 seems to fix the issue.

**Comment by or2008** [comment]
having the same issue on 2.5.3. downgrading to 2.3.8 did fix the problem.

**Comment by ordian** [comment]
cc @ascjones
