### ISSUE TITLE
Transactions dropping.

### ISSUE THREAD

**Issue by uurcm16** [openethereum/openethereum#10732]
- **Parity Ethereum version**:  2.4.5
- **Operating system**: Linux
- **Installation**: 
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: no, i can't, it is on production :(.

Hi there,

I'm running a ETH pool (currently on test with mainnet), everything was fine untill this morning.
When pool software tries to send transactions, i get "There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee. code -32010" this error.

I'm trying to send 2 transactions ONE after THE OTHER.

Here is the config: `./parity --chain mainnet --db-compaction ssd --mode active --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --cache-size 16000 --min-peers 150 --max-peers 256 --author XXX--ports-shift 250 ---no-ipc --base-path /media/XXX/XXX/chains/eth --no-download --no-periodic-snapshot --ws-port 1525 --ws-interface local`

**Comment by uurcm16** [comment]
And,

Transactions are being "culled" after a few seconds.

Trying to send 6 transactions, 4 of them gives the error above, and 2 of them returns txhash, but parity says they are culled.

`2019-06-10 16:10:40    150/150 peers   1 GiB chain 437 MiB db 0 bytes queue 245 KiB sync  RPC:  0 conn,  111 req/s, 1593 µs
2019-06-10 16:10:56  Transaction culled (hash 0x4966712a34d755ae1f838e07b012ad34d3e1c35c8fd9b01e8e2bb5da147e0e69)
2019-06-10 16:10:56  Imported #7931410 0xcd88…feb0 (172 txs, 7.98 Mgas, 306 ms, 32.77 KiB)
2019-06-10 16:10:57  Updated conversion rate to Ξ1 = US$243.78 (19533614 wei/gas)
2019-06-10 16:11:01  Imported #7931411 0xc28a…0e15 (122 txs, 7.99 Mgas, 327 ms, 29.48 KiB)
2019-06-10 16:11:02  Transaction culled (hash 0x5fd98c41988b9e705d16ec45a090b54272cb4c48664541857cd07d790ff96ff5)
2019-06-10 16:11:02  Transaction culled (hash 0x23c9b9498ab6334011eaa0ec2a044b378f86ccf4d84af9365ea304574ce2d9bc)
`

Any idea @joshua-mir ?

**Comment by danrmiller** [comment]
I have also been getting this "There are too many transactions in the queue.", still happens with 2.4.6.

**Comment by joshua-mir** [comment]
@uurcm16 sorry for the late response, if you are still seeing this, how are you setting the nonce for your transaction? Generally transactions are culled if they have a duplicate nonce to the one on the network - if you are sending your two transactions "simultaneously" 
@danrmiller are you doing something similar (sending very few transactions and having them culled)

**Comment by danrmiller** [comment]
Yes I am letting parity assign the nonces. It turns out my program is checking the balance from parity and the returned balance includes the funds in the unconfirmed pending transaction, so my program thinks it has available funds to send another transaction. Thanks for your help.
