### ISSUE TITLE
Error: Node error: code 32010. Insufficient funds. The account you tried to send transaction from does not have enough funds

### ISSUE THREAD

**Issue by RostyslavBortman** [openethereum/openethereum#10795]
Error: Node error: code 32010. Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 376051000000000 and got: 0.

But ledger has enough funds and this issue is really random. Any thoughts?

**Comment by debris** [comment]
are you synced with the network?

**Comment by RostyslavBortman** [comment]
@debris Sure, parity node is synced and running. I face this issue really random. For example, I can try to make a transaction from ledger 1 - get an error 32010. Insufficient funds, create another transaction from ledger 1 with the same parameters and transaction is success.

**Comment by RostyslavBortman** [comment]
@joshua-mir which details you need to understand the issue? **Insufficient funds** error when actually sender address balance is enough. Is it expected behavior?

**Comment by dvdplm** [comment]
@RostyslavBortman Not sure what you refer to but if you mean the `unconfirmed` label it means that nobody on the time has gotten round to debugging your issue which means we do not have a confirmation. Please feel free to provide any additional info that might help move this along, code examples, bash scripts, logs or anything similar will usually speed up response times. Thank you.

**Comment by adria0** [comment]
Closing issue due to its stale state.
