### ISSUE TITLE
Priority preparation of pending block 

### ISSUE THREAD

**Issue by tomusdrw** [openethereum/openethereum#10802]
In case a block is imported by client we should allow the PoW miners to start working on a new block as fast as possible.

Currently what happens is:
1. The client triggers `chain_new_block` (either [here - external import](https://github.com/paritytech/parity/blob/bf4fa658f37a97fcaad9f4b2f7f800fa71220326/ethcore/src/client/client.rs#L328) or [here - local (sealed) import](https://github.com/paritytech/parity-ethereum/blob/bf4fa658f37a97fcaad9f4b2f7f800fa71220326/ethcore/src/client/client.rs#L2428))
2. This in turns calls `update_sealing` [here](https://github.com/paritytech/parity-ethereum/blob/bf4fa658f37a97fcaad9f4b2f7f800fa71220326/ethcore/src/miner/miner.rs#L1300)
3. Which creates new pending block by pushing (executing) pending transactions: [here](https://github.com/paritytech/parity/blob/bf4fa658f37a97fcaad9f4b2f7f800fa71220326/ethcore/src/miner/miner.rs#L499)

Since executing the transactions can take a noticable amount of time especially on chains where block gas limits are saturated, new work package (the thing miners use to mine on) is significantly delayed.

There are some possible improvements to this workflow that we could implement. Note this applies ONLY to PoW mining, not PoA where we shouldn't really sign off multiple blocks built on top of the same parent.
Low hanging fruits:
1. Since we support multiple pending blocks (see `using_queue`) we could create an empty pending block first, so that it's possible to start mining and only push transactions afterwards and update the work package (that's what go-ethereum is doing, btw)
2. Profile the import -> pending block creation path and see if there is anything that could be improved. Introduce timings in the code for that path.

Some more involved optimisations:
1. Change the `client` notification to be async / channel-based and have miner control the threading of pending block creation. This way we could start working on multiple pending blocks at once, i.e.:
A. Start with empty block
B. Take existing pending block
C. clone and push one copy to using queue
D. Push some more transactions (deadline-based)
E. Go to (C)

2. Re-create the entire pending block from scratch every now and then.
Since new (higher fee) transactions can be imported into the pool we should attempt to produce a more profitable pending block and let miners work on sealing it too.

3. Parallelize transaction execution and verification when creating pending block (since we currently get the new pending transaction from iterator and call [`client.verify_signed()`](https://github.com/paritytech/parity/blob/bf4fa658f37a97fcaad9f4b2f7f800fa71220326/ethcore/src/miner/miner.rs#L507) before we actually push it to the block). We should be able to gain few millis with this.

4. Run transactions for `best_block_number + 2` and optimistically populate the caches - that could speed up pending block creation by avoiding doing db lookups on critical path. Since the state can obviously be different for some transactions it doesn't give us any guarantees so we should definitely benchmark it.

5. Transaction execution measurements obtained via (3) could also be used to slightly skew transaction packing strategy (so that you can optimize `fee/execution time` and not only `fee/gas used`)

**Comment by dvdplm** [comment]
cc @debris @ordian

**Comment by adria0** [comment]
Closing issue due to its stale state.
