### ISSUE TITLE
Invalid "highest block number" value for parity.

### ISSUE THREAD

**Issue by ysbae0928** [openethereum/openethereum#10873]
Synchronization is normally performed, but the synchronization does not start suddenly at some point.
The "Qed" value is strange, as you can see in the picture. What should I do?

![error](https://user-images.githubusercontent.com/42667564/61033079-a7df6680-a3fd-11e9-9ced-011ee52d8745.PNG)

- **Parity Ethereum version**: 
version Parity-Ethereum/v2.5.5-stable-3ebc769-20190708/x86_64-linux-gnu/rustc1.36.0

- **Operating system**: 
Linux (Ubuntu 18.04)

- **Fully synchronized**: 
yes

- **Network**: 
ethereum

- **Restarted**: 
yes

**Comment by joshua-mir** [comment]
https://wiki.parity.io/FAQ#what-does-paritys-command-line-output-mean
This output means you are at a certain block (8128666) but the highest blocknumber you see on the network is less than what you have locally (8121221) and therefore there are no blocks in the queue for being processed locally (0 Qed)

**Comment by ysbae0928** [comment]
The latest block on the other node is "8128853". And now it's connected normally to that node.
And the reason the peer is 1 was because the reserved_only option was enabled.

**Comment by joshua-mir** [comment]
Have the values in your local node's logs changed to reflect that?

**Comment by ysbae0928** [comment]
@joshua-mir
I didn't understand what you were saying. Can you explain it in detail?

**Comment by joshua-mir** [comment]
The link I shared explains what each part of the log output means. What do you find strange about the Qed value?

**Comment by ysbae0928** [comment]
@joshua-mir 
I'm sorry...
I mistook the field.
The value of "highest block number" is invalid.

**Comment by adria0** [comment]
Closing issue due to its stale state.
