### ISSUE TITLE
epoch_transistion_for does not fail on unequal hashes

### ISSUE THREAD

**Issue by ghost** [openethereum/openethereum#10878]
masks #10085

PR #10729 introduced a new problem/bug:

in case of an unequal hash, no error is raised, thus the client continues to operate, despite the chain being corrupted.

## Solution

At minimum, return `None` after the debug-log has been processed.

https://github.com/paritytech/parity-ethereum/pull/10729/files#diff-5bfc0a03ce9eda19d6d3927beaff4945R1006

**Comment by debris** [comment]
cc @ngotchac

**Comment by adria0** [comment]
Closing issue due to its stale state.
