### ISSUE TITLE
Feature request: method to get Merkle proof of transaction inclusion within a block

### ISSUE THREAD

**Issue by refi93** [openethereum/openethereum#10876]
I know there is the `eth_getProof` JSON RPC call ([EIP-1186](https://github.com/ethereum/EIPs/issues/1186)), but this only returns the proof of balance of an account. I think it would be nice to have the ability to also get the Merkle proof of inclusion of a transaction within a block, similar to BTC's [getTxOutProof](https://bitcoin.org/en/developer-reference#gettxoutproof).

This would be a convenient way to get a proof that a certain transaction took place, no matter if it was successful. In general, this may seem a "weak" information but if you have the guarantee that the receiving address is not a smart contract, it may be IMHO useful. Or you may simply want to know if a transaction actually belongs to a block.

Is there perhaps already some JSON RPC call that would provide this functionality, at least indirectly, but without fetching the whole block, or some work in progress in this direction?

**Comment by joshua-mir** [comment]
@refi93 the closest thing to this currently would probably be to use https://wiki.parity.io/JSONRPC-parity-module#parity_getblockheaderbynumber and use either the `transactionsRoot` or `receiptsRoot` - this would probably need an extra https://wiki.parity.io/JSONRPC-parity-module#parity_getblockreceipts call to get all the information needed to verify a specific transaction receipt in a block

**Comment by refi93** [comment]
would you appreciate a PR that would add this call?
