### ISSUE TITLE
parity_nextNonce race

### ISSUE THREAD

**Issue by charles-cooper** [openethereum/openethereum#10897]
- **Parity Ethereum version**: 2.5.5
- **Operating system**: Linux
- **Installation**: github release
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: no

`parity_nextNonce` gives the same nonce shortly after a call to eth_sendRawTransaction. I noticed this issue in a previous release but waiting 1s between RPCs seemed to be a good workaround. With the new stable release, the nonce can be the same even after the 1s delay.

**Comment by dtran320** [comment]
We're running into this running `2.5.5` as well

**Comment by charles-cooper** [comment]
I rolled back to 2.3.8 and still hit this issue
