### ISSUE TITLE
Enhancement: mainnet chain option as alternative to ethereum

### ISSUE THREAD

**Issue by yorickdowne** [openethereum/openethereum#109]
Currently `--chain` accepts `ethereum` to designate main net. I'd love to see an alternative `mainnet`, that does the exact same thing as `ethereum`.

Rationale: This makes my users' life a little easier. Nethermind and Besu use `mainnet`, and having OpenEthereum behave the same way means easier instructions for the docker-compose `.env` file, independent of client.

This is a small QoL change. It should have minimal impact on OpenEthereum as well as the tooling I am creating.

If you are okay with the addition, I am happy to offer a PR.

**Comment by rakita** [comment]
`"eth" | "ethereum" | "foundation" | "mainnet" => SpecType::Foundation,"` 
I think these are all synonyms
