### ISSUE TITLE
Schedule new_byzantium has create2 set to true

### ISSUE THREAD

**Issue by axic** [openethereum/openethereum#10914]
In https://github.com/paritytech/parity-ethereum/blob/master/ethcore/vm/src/schedule.rs#L274 the `Schedule::new_byzantium()` helper has `have_create2` set to true, however it was only introduced with Constantinople. See [EIP-609: Byzantium](http://eips.ethereum.org/EIPS/eip-609) and [EIP-1013: Constantinople](http://eips.ethereum.org/EIPS/eip-1013)).

The reason it is not manifesting as an error in the client is that in https://github.com/paritytech/parity-ethereum/blob/v2.6.0/ethcore/src/spec/spec.rs#L186 the setting is overridden determined by a block number.

This piece of code has changed after 2.6.0, but the problem remains in `vm/src/schedule.rs`.

Is there any reason to keep it this way?

It makes other uses of Parity EVM a bit more messy, [like here](https://github.com/axic/daytona/blob/master/src/lib.rs#L233).

**Comment by adria0** [comment]
Closing the issue due to its stale state

**Comment by axic** [comment]
Was this changed by any chance?
