### ISSUE TITLE
Stage 5 block verification failed for #10685005 on kovan network

### ISSUE THREAD

**Issue by zroper** [openethereum/openethereum#10910]
I'm having trouble syncing with the kovan network. I get a stage 5 verification failure/ bad block error at #10685005. I've upgraded parity and run a kill db for kovan and I can get the snapshots after about 2 days of downloading but the error persists after snapshots. Deleted nodes.json and it didn't help either.

- **Parity Ethereum version**: 2.5.5
- **Operating system**: MacOS
- **Installation**: homebrew
- **Fully synchronized**: no
- **Network**: kovan
- **Restarted**: yes

Stage 5 block verification failed for #10685005 (0x7330…7dbf)
Error: Error(Block(InvalidReceiptsRoot(Mismatch { expected: 0x7222fed91d1eec553bca5dce21137f1580ac8c12b53181a791bf60ab9124010f, found: 0xaf5695c3f1ac8a8dc69607f56d86a2d2313957c0435e529acbf337c8e465fb8e })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
2019-07-22 18:02:22  
Bad block detected: Error(Block(InvalidReceiptsRoot(Mismatch { expected: 0x7222fed91d1eec553bca5dce21137f1580ac8c12b53181a791bf60ab9124010f, found: 0xaf5695c3f1ac8a8dc69607f56d86a2d2313957c0435e529acbf337c8e465fb8e })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })

**Comment by joshua-mir** [comment]
Does this result in a crash? Or just this error and the node continues working? If it's the latter case, what happens if you allow the node to continue syncing after you see the bad block error? 

Also, in this scenario does block 10685005 represent the head of the chain and does this happen during sync, or is it a historical block? 

@zroper can you try on 2.6.0 as well? That version includes many potentially relevant bugfixes.

**Comment by zroper** [comment]
No, it doesn't result in a crash, but it will keep attempting to sync with block 10685004 without success (error only throws once).

10685005 is a historical block. Head of chain is >12376085.

After upgrading to 2.6.0, I'm getting the same error.

**Comment by zroper** [comment]
After updating to 2.6.0 and starting over with a fresh Kovan db, I still get the stage 5 error but now at block #12600016.

Stage 5 block verification failed for #12600016 (0x9b59…4582)
Error: Block(InvalidStateRoot(Mismatch { expected: 0xfd0efcb4af63316e362b22347e863463390ab0d1cd8aafc4528083c4e2b1aebb, found: 0x5feb5e89c84ba7159ac8b67f614a39924ac57c726045611a1b12bd696380f5da }))
