### ISSUE TITLE
Insufficient funds with pending txns

### ISSUE THREAD

**Issue by charles-cooper** [openethereum/openethereum#10917]
- **Parity Ethereum version**: 2.5.5
- **Operating system**: Linux
- **Installation**: github release
- **Fully synchronized**: no / yes
- **Network**: ethereum
- **Restarted**: no

I haven't reproduced this outside of observing it a couple times but I am fairly sure it has to do with pending txns with same nonce being applied as holds against account balance. E.g.,
1) acct balance 1.5 ETH
2) send 1 ETH, tx 0xabcd
3) replace tx 0xabcd with 0x1234 to send 1 ETH - same nonce but higher gas price
4) `{'code': -32010, 'message': 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required <redacted> and got: <redacted>.'}`

**Comment by joshua-mir** [comment]
@charles-cooper as per your gitter message, if the transactions have the same nonce this is indeed an error - the transaction should either be replaced or you should get an error that your gasPrice wasn't high enough to successfully replace the transaction.

**Comment by charles-cooper** [comment]
Rolled back to 2.3.8 and still get this issue
