### ISSUE TITLE
Thread 'tokio-runtime-worker-2' panicked at 'supplied instant is later than self', src/libcore/option.rs:1036

### ISSUE THREAD

**Issue by sandakersmann** [openethereum/openethereum#10930]
2019-07-31 17:35:08  Imported #8259239 0xc538…74ff (236 txs, 7.96 Mgas, 8525 ms, 35.06 KiB)
2019-07-31 17:35:39    11/25 peers   141 MiB chain 321 MiB db 0 bytes queue 18 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
2019-07-31 17:36:28    13/25 peers   141 MiB chain 321 MiB db 213 KiB queue 18 MiB sync  RPC:  0 conn,    0 req/s,    0 µs

====================

stack backtrace:
   0:     0x562ee64c20cd - <no info>
   1:     0x562ee64bf0fe - <no info>
   2:     0x562ee65cc157 - <no info>
   3:     0x562ee650a11a - <no info>
   4:     0x562ee6509e8e - <no info>
   5:     0x562ee6527505 - <no info>
   6:     0x562ee652d4ab - <no info>
   7:     0x562ee6533715 - <no info>
   8:     0x562ee6949258 - <no info>
   9:     0x562ee63c400d - <no info>
  10:     0x562ee63c1992 - <no info>
  11:     0x562ee63bfa52 - <no info>
  12:     0x562ee63a9435 - <no info>
  13:     0x562ee63a46b8 - <no info>
  14:     0x562ee63c467b - <no info>
  15:     0x562ee63c29af - <no info>
  16:     0x562ee652608e - <no info>
  17:     0x562ee652919f - <no info>
  18:     0x7f5f452f36da - <no info>
  19:     0x7f5f449f888e - <no info>
  20:                0x0 - <no info>

Thread 'tokio-runtime-worker-3' panicked at 'supplied instant is later than self', src/libcore/option.rs:1036

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

====================

stack backtrace:
   0:     0x562ee64c20cd - <no info>
   1:     0x562ee64bf0fe - <no info>
   2:     0x562ee65cc157 - <no info>
   3:     0x562ee650a11a - <no info>
   4:     0x562ee6509e8e - <no info>
   5:     0x562ee6527505 - <no info>
   6:     0x562ee652d4ab - <no info>
   7:     0x562ee6533715 - <no info>
   8:     0x562ee6949258 - <no info>
   9:     0x562ee63c400d - <no info>
  10:     0x562ee63c1992 - <no info>
  11:     0x562ee63bfa52 - <no info>
  12:     0x562ee63a9435 - <no info>
  13:     0x562ee63a46b8 - <no info>
  14:     0x562ee63c467b - <no info>
  15:     0x562ee63c29af - <no info>
  16:     0x562ee652608e - <no info>
  17:     0x562ee652919f - <no info>
  18:     0x7f5f452f36da - <no info>
  19:     0x7f5f449f888e - <no info>
  20:                0x0 - <no info>

Thread 'tokio-runtime-worker-1' panicked at 'supplied instant is later than self', src/libcore/option.rs:1036

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

====================

stack backtrace:
   0:     0x562ee64c20cd - <no info>
   1:     0x562ee64bf0fe - <no info>
   2:     0x562ee65cc157 - <no info>
   3:     0x562ee650a11a - <no info>
   4:     0x562ee6509e8e - <no info>
   5:     0x562ee6527505 - <no info>
   6:     0x562ee652d4ab - <no info>
   7:     0x562ee6533715 - <no info>
   8:     0x562ee6949258 - <no info>
   9:     0x562ee63c400d - <no info>
  10:     0x562ee63c1992 - <no info>
  11:     0x562ee63bfa52 - <no info>
  12:     0x562ee63a9435 - <no info>
  13:     0x562ee63a46b8 - <no info>
  14:     0x562ee63c467b - <no info>
  15:     0x562ee63c29af - <no info>
  16:     0x562ee652608e - <no info>
  17:     0x562ee652919f - <no info>
  18:     0x7f5f452f36da - <no info>
  19:     0x7f5f449f888e - <no info>
  20:                0x0 - <no info>

Thread 'tokio-runtime-worker-0' panicked at 'supplied instant is later than self', src/libcore/option.rs:1036

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

====================

stack backtrace:
   0:     0x562ee64c20cd - <no info>
   1:     0x562ee64bf0fe - <no info>
   2:     0x562ee65cc157 - <no info>
   3:     0x562ee650a11a - <no info>
   4:     0x562ee6509e8e - <no info>
   5:     0x562ee6527505 - <no info>
   6:     0x562ee652d4ab - <no info>
   7:     0x562ee6533715 - <no info>
   8:     0x562ee6949258 - <no info>
   9:     0x562ee63c400d - <no info>
  10:     0x562ee63c1992 - <no info>
  11:     0x562ee63bfa52 - <no info>
  12:     0x562ee63a9435 - <no info>
  13:     0x562ee63a46b8 - <no info>
  14:     0x562ee63c467b - <no info>
  15:     0x562ee63c29af - <no info>
  16:     0x562ee652608e - <no info>
  17:     0x562ee652919f - <no info>
  18:     0x7f5f452f36da - <no info>
  19:     0x7f5f449f888e - <no info>
  20:                0x0 - <no info>

Thread 'tokio-runtime-worker-2' panicked at 'supplied instant is later than self', src/libcore/option.rs:1036

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

2019-07-31 17:36:46  Finishing work, please wait...
2019-07-31 17:36:55  Imported #8259247 0xd55a…0c1b (114 txs, 7.99 Mgas, 7025 ms, 17.53 KiB)
satoshi@Satoshi:~$ 

- **Parity Ethereum version**: Parity-Ethereum 2.6.0-beta
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: almost
- **Network**: ethereum
- **Restarted**: no

**Comment by adria0** [comment]
Closing the issue due to its stale state
