### ISSUE TITLE
Implement EIP-1767 GraphQL API to Ethereum node data

### ISSUE THREAD

**Issue by adamschmideg** [openethereum/openethereum#10933]
This is a feature request.

The current JSON RPC API has shortcomings, so [EIP 1767, a GraphQL interface](https://eips.ethereum.org/EIPS/eip-1767) is proposed. It's implemented and released by [Geth 1.9.0](https://github.com/ethereum/go-ethereum/releases/tag/v1.9.0) and [Pantheon](https://github.com/PegaSysEng/pantheon/blob/master/CHANGELOG.md#111), and it's in progress for [Trinity](https://github.com/ethereum/trinity/issues/302). Also, feel free to join the [discussion on EIP 1767](https://ethereum-magicians.org/t/graphql-interface-to-ethereum-node-data/2710/42).

**Comment by adamschmideg** [comment]
I put together an almost-client-agnostic [test suite](https://gitlab.com/offcode/ethereum-graphql/tree/master/test-graphql). Replace `init-and-run.sh` with a parity-specific script and you're ready to run the tests against your implementation. Beware, some test cases have issues, they are listed in the README, but the others are fine.
You can also join the [graphql.eth Slack channel](https://join.slack.com/t/graphqleth/shared_invite/enQtNzMxNzEwNTE5NzQ1LTgxZjZlMzQyMThlYzgxMTA4YzY4NGQ0ODBjYzJkNjRkMzU2MTZmY2E4NDhjZDc5MzhiM2MxZDdjZWZiOWFkYWI) if you have any questions about using it.

**Comment by liamaharon** [comment]
Any update on this?

**Comment by seunlanlege** [comment]
blocked on graphql-rust/juniper#2

**Comment by adamschmideg** [comment]
@seunlanlege I understand you're waiting for the linked [GraphQL library](https://github.com/graphql-rust/juniper/) to have an async implementation. Isn't it an option to use the library as is now, then revisit this once they'll have async?

**Comment by seunlanlege** [comment]
unfortunately no, light client uses async code for fetching data from full nodes.
If i did that now, i'd have to refactor to async later.
I'd rather this work be done at once.

**Comment by adamschmideg** [comment]
yeah, it makes perfect sense

**Comment by liamaharon** [comment]
@adria0 why was this closed? OpenEthereum not planning on implementing a GraphQL interface?

**Comment by adria0** [comment]
Hi @liamaharon, I hope that somebody wants to implement this, unfortunately, all current developers now are just focused on fixing blocking bugs.

**Comment by liamaharon** [comment]
Thanks for the clarification @adria0
