### ISSUE TITLE
Lag in eth_getTransactionByHash

### ISSUE THREAD

**Issue by ds414** [openethereum/openethereum#10952]
- **Parity Ethereum version**: 2.3.9
- **Operating system**: x86_64-linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum(mainnet, 1)
- **Restarted**: no / yes
- **Mode**: archive

We regularly check the parity for new events. When a new event appears, we immediately try to get transaction properties - _eth_getTransactionByHash_.
Normally, _eth_getTransactionByHash_ returns "transaction receipt":
`{"jsonrpc":"2.0","result":{"blockHash":"0x937ecf4e0a98abeafde57529133b9b1bcdb6a42c5efa67d149c7b5692cb522f7","blockNumber":"0x7eb18d","chainId":"0x1","condition":null,"creates":null,"from":"0x6d5591ea38e3ea32cd4db138d26341c86827946a","gas":"0x5fe1b","gasPrice":"0x77359400","hash":"0xf5c0fe7f75f9b4aceee2dd87fb983cfe544607afcf1a9a462c218c0c0f744517","input":"0x1cff79cd000000000000000000000000526af336d614ade5cc252a407062b8861af998f500000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000044bc25a810000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3000000000000000000000000000000000000000000000000000000000000fd5a00000000000000000000000000000000000000000000000000000000","nonce":"0x5","publicKey":"0xbe0b515469f73fe287a0281408308da6a59e143d727d36e1b7b7993dea5efe9adcbdee76b6678ff281f29f105ced1d954968e1e5dd5e621edd788a30389dd201","r":"0x1cd79478210eeea6270c75c64bd85ebe6f25d234c2970f2ec0028ad2913aadc5","raw":"0xf9012f0584773594008305fe1b94c34ff80be0290bc4e90e19f9892773f3e1d2fc5b871ff973cafa8000b8c41cff79cd000000000000000000000000526af336d614ade5cc252a407062b8861af998f500000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000044bc25a810000000000000000000000000448a5065aebb8e423f0896e6c5d525c040f59af3000000000000000000000000000000000000000000000000000000000000fd5a0000000000000000000000000000000000000000000000000000000025a01cd79478210eeea6270c75c64bd85ebe6f25d234c2970f2ec0028ad2913aadc59f3a71ff8b2423c1dedc72ede14b2c7092dca45123fc5f9359a5896cd3209f84","s":"0x3a71ff8b2423c1dedc72ede14b2c7092dca45123fc5f9359a5896cd3209f84","standardV":"0x0","to":"0xc34ff80be0290bc4e90e19f9892773f3e1d2fc5b","transactionIndex":"0x48","v":"0x25","value":"0x1ff973cafa8000"},"id":1}`

, but sometimes it returns empty response:
`'{" jsonrpc ":" 2.0 "," result ": null," id ": 1}'`

We try again and again, usually within a minute "transaction receipt" comes.
Recently, empty response has been happening more and more often and the interval between the empty response and the "transaction receipt" in the response has been increasing (up to 5 min).
Is this normal behavior? 
Can we to get "transaction receipt" content from the first request _eth_getTransactionByHash_?

**Comment by joshua-mir** [comment]
@ds414 would it be possible for you to see if this is still the case on a more recent stable or beta release?

**Comment by ds414** [comment]
We can today upgrade parity and need some time (day or two) to check problem. I will return after that.

**Comment by ds414** [comment]
Parity updated - v2.5.5
but still sometime we get empty response:
`{"jsonrpc":"2.0","result":null,"id":1}`

**Comment by joshua-mir** [comment]
Would it be possible to run with the `-l rpc` flag and share the logs from your node when you have the null responses?

**Comment by ds414** [comment]
In attached file piece of rpc Request/Response log with empty responses on `eth_getTransactionReceipt`
[log.txt](https://github.com/paritytech/parity-ethereum/files/3490411/log.txt)

**Comment by dvdplm** [comment]
@ds414 are you seeing this issue both for `eth_getTransactionReceipt` and `eth_getTransactionByHash`? Are those the only two calls that exhibit this behaviour?
Have you been able to discern a pattern of any kind, e.g. more common when the server is under heavy load?
This might be a silly question, but in the log you attached I see `Pause=x` (where `x` is 4, 8, 16, 32, 64 and 128). I don't find anything in our code that has that output. Is there a different process that writes to the same logfile?

**Comment by dvdplm** [comment]
@ds414 Did you try to submit RPC calls using any other interface than http? If yes, do you see the same problem with, say, websockets? If no, can you try that?

**Comment by ds414** [comment]
Yes, I catched this problem in eth_getTransactionReceipt and eth_getTransactionByHash only.
Our single parity server serve average 20-70 request per second all time. I did not notice a clear dependence on the load.
We have only one synced parity node and it's in production and generate huge volume of log. This error rare and I can not select chain of logs with this error from all log. So I wrote small script, it wait new blocks (eth_blockNumber),  then send eth_getLogs and eth_getTransactionReceipt on all transactions. This script logs all requests and responses - I sent this log in previous message.

We use only http interface. I doubt that network problem, because we receive normal (albeit empty) response: {"jsonrpc":"2.0","result":null,"id":1}

**Comment by dvdplm** [comment]
@ds414 What are your tx pool settings currently? I.e. what are `--tx-queue-mem-limit`, `--tx-queue-size` and `--tx-queue-per-sender` set to? 
It would be interesting to see what `parity_pendingTransactionsStats` returns around the time when parity is responding with `null`.

**Comment by dvdplm** [comment]
> I doubt that network problem,

I don't think this is a network issue either. I asked because it is possible that we hit a bug in the http code path that is absent in the websocket code path. It seems like an unlikely possibility but doesn't hurt to rule it out.

**Comment by ds414** [comment]
We use default values of --tx-queue-mem-limit, --tx-queue-size and --tx-queue-per-sender.
I going to add parity_pendingTransactionsStats to script and run it again.

**Comment by iFA88** [comment]
I have the same issue with the latest stable release ( `Parity-Ethereum/v2.5.7-stable-6bd7db9-20190829/x86_64-linux-gnu/rustc1.36.0` ). Sometimes takes one `eth_getTransactionByHash` for 2 minute.. 334 query takes 795 seconds.
