### ISSUE TITLE
Save Rejected TRXs

### ISSUE THREAD

**Issue by Daniel600** [openethereum/openethereum#10963]
- **Parity Ethereum version**: 2.5.0
- **Operating system**:  Linux
- **Installation**: built from source
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**:  yes

HI - Trying to understand if it is possible to save trx information which are rejected by the Transaction Queue https://wiki.parity.io/Transactions-Queue , not dropped trxs but rather rejected - i.e a trx with the same nonce or other rejected reasons

**Comment by joshua-mir** [comment]
@Daniel600 you wouldn't be able to do this on the client itself using any existing features - you'd have to poll/subscribe to `parity_allTransactions`/`parity_allTransactionHashes` and then perhaps watch the `-l txqueue` logs to see which transactions get rejected.

**Comment by Daniel600** [comment]
Thanks! 
We are able to see the rejected trxs in the -l txqueue logs, but that only includes the Hash&reason not all info of the trx - I see parity_allTransactions only includes the Trx's in the queue. Any ideas of how we can get the information of the rejected trxs ?
