### ISSUE TITLE
eth_sendRawTransaction() returns an empty response

### ISSUE THREAD

**Issue by vladmelnyk** [openethereum/openethereum#10967]
- **Parity Ethereum version**: v2.6.0-beta / v2.5.5-stable / 2.4.9-stable / 2.4.8-stable
- **Operating system**:  Linux
- **Installation**: download from GitHub
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**: no

**Started parity with** :
`~/parity --warp --no-ancient-blocks --max-peers 250 --snapshot-peers 50 --min-peers 50 --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 4096 --base-path=/mnt/parity --infinite-pending-block --jsonrpc-apis all --no-persistent-txqueue --min-gas-price 1 --jsonrpc-server-threads 10 --jsonrpc-threads 10`

**Actual**:
When broadcasting transaction via `eth_sendRawTransaction()` receive empty response body:

`"POST / HTTP/1.1" 499 0 "-" "okhttp/3.12.0" 10.002 req_body:"{\x22jsonrpc\x22:\x222.0\x22,\x22method\x22:\x22eth_sendRawTransaction\x22,\x22params\x22:[\x220xf86b0b850165a0bc008307a120947074258e5963c90eba8868c89bac2cf56ce2be05865af3107a4000801ba0dc7d7a37c384a2fc75189748860a4be1c2ad3a37d0193fea35a65c91e406aab4a009dbfc2e614ebe9d0c1b3cf262d8076b7568d7aa6cdd95d4120dd744a484730d\x22],\x22id\x22:3}" resp_body:""`

**Expected**: 
When broadcasting transaction via `eth_sendRawTransaction()` receive txHash in response:

`"POST / HTTP/1.1" 200 287 "-" "okhttp/3.12.0" 0.002 req_body:"{\x22jsonrpc\x22:\x222.0\x22,\x22method\x22:\x22eth_sendRawTransaction\x22,\x22params\x22:[\x220xf86e8212a78502540be4008307a120940df366fc987ffdc3760f2ec5d01636c5e590b6308711c37937e08000801ba0b41b7a846ada02e245bcca93e2b26a670a92e0b1ce8bcb7e2418a4db093f02e3a06bc56692a057912a6d4b9afdf1988fe283740a7c32181135bd5387d76923fce7\x22],\x22id\x22:284697}" resp_body:"{\x22jsonrpc\x22:\x222.0\x22,\x22result\x22:\x220xf9e7af3fa5c24131f0babdcfaee24c1f5bace1383b6d4318ef0b25b55752f0e6\x22,\x22id\x22:284697}\x0A"`

**Comment by joshua-mir** [comment]
Possibly related to #10950

**Comment by joshua-mir** [comment]
Possibly related to #10952?

**Comment by vladmelnyk** [comment]
> Possibly related to #10952? Do you see this consistently or for other rpc calls?

I encountered it only for eth_sendRawTransaction().
Other methods seem to be fine.

**Comment by roma4u** [comment]
I have the same problem, temporarily switched to geth, but I need to use the parity logs and using geth is not an option.
