### ISSUE TITLE
Aura: removeValidator method implementation in openethereum. 

### ISSUE THREAD

**Issue by atif-konasl** [openethereum/openethereum#110]
- OpenEthereum/v3.0.1-stable-8ca8089-20200601/x86_64-unknown-linux-gnu/rustc1.43.1
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum
- **Restarted**: no / yes

 I had a network with 3 nodes(alice, node0, node1) and initially node0 was the validator. After that, i deployed validator set contract with initial validator, node1 and defined contract address at 175 block height in spec.json file. After 175 passed, node0 did not seal and only node1 started sealing. After sealing some blocks, i added node0 as validator from contract at 202 and node0, node1 started sealing from 203. When i removed node0 from contract at 244, node1 only continued sealing and node0 stopped. 

But i am confused about the state root at block no 245 and 246 because, state root of 245 was same as 244 and state root of 246 was changed. My question is at which block SYSTEM_ADDRESS calls finalizedChange method of validator set contract? And Why there was a transaction in block no 247 and 248? Actually i only send removeValidator method call txn at 244.

Could anyone please help me to explain what is happening underneath?

Here is configuration of node0. And node1 is the similar of node0.
```[parity]
chain = "../Validator-set-tutorial.json"
base_path = "node0"

[network]
port = 30300
bootnodes = ["enode://2a773e87946ac3ed0e3459be86d40d1d83737758fc7b4bc91ee68650618a6fba06c3a245247e3e1e4d22fdf0256990a89a1b468dc3271caeb16472bd8863df7a@127.0.0.1:30201"]

[rpc]
disable = true

[websockets]
disable = true

[account]
password = ["node0.pwd"]

[mining]
engine_signer = "0xdfa5b73a85f758b0a53992c968ac1a0e0f51ce83"
reseal_on_txs = "none"
force_sealing = true
```
Here is the spec.json
```
{
  "name": "AuthorityRound",
  "engine": {
    "authorityRound": {
      "params": {
        "stepDuration": "5",
        "validators" : {
          "multi": {
              "0": { "list": ["0xdfa5b73a85f758b0a53992c968ac1a0e0f51ce83"] },
              "175": {"contract" : "0x0057c5106de30fEC69574899C92c3dC4DfA43D0e" }
            }
        }
      }
    }
  },
  "params": {
    "gasLimitBoundDivisor": "0x400",
    "maximumExtraDataSize": "0x20",
    "minGasLimit": "0x1388",
    "networkID" : "0x2323"
  },
  "genesis": {
    "seal": {
      "authorityRound": {
        "step": "0x0",
        "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    "difficulty": "0x20000",
    "author": "0x0000000000000000000000000000000000000000",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x",
    "gasLimit": "0x222222"
  },
  "accounts": {
    "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
    "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
    "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
    "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } }
  }
}
```

**Comment by iFA88** [comment]
https://openethereum.github.io/Validator-Set
If you want to change the validators you need emit `InitiateChange` event.

**Comment by atif-konasl** [comment]
Could you please explain about these two transactions what node automatically generate after removeValidator method call txn?

**Comment by iFA88** [comment]
I dont know the `0x0057c5106de30fEC69574899C92c3dC4DfA43D0e` address contract source code. Where is? May you can put the bytecode into the "accounts".

**Comment by rakita** [comment]
I suppose this is resolved
