### ISSUE TITLE
eth_getlogs does not return expected logs entries when tried with address filters

### ISSUE THREAD

**Issue by vishalgupta96** [openethereum/openethereum#11005]
- **Parity Ethereum version**: 2.5.6-stable
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

**Actual Behaviour:**

Issue request over JSON RPC to eth_getLogs with params
"params": [{
	"fromBlock": "0x3CD7B3",
	"toBlock": "0x3CD7B3",
	"address": "0xb8c77482e45f1f44de1745f52c74426c631bdd52",
	"topics": ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]
}]

Response: I get back an empty list.
{"jsonrpc":"2.0","result":[],"id":1}

**Expected Behaviour:**

If i remove the params for address & topics and send the below request:
"params": [{
	"fromBlock": "0x3CD7B3",
	"toBlock": "0x3CD7B3",
}]

Response: I get a list of 103 Json in which below JSON with above address is present:
{  
   "address":"0xb8c77482e45f1f44de1745f52c74426c631bdd52",
   "blockHash":"0x332d5017474622cc9ee47abbf19c37c6e9ca00fd104bede7f116429685a28796",
   "blockNumber":"0x3cd7b3",
   "data":"0x00000000000000000000000000000000000000000000d3c21bcecceda1000000",
   "logIndex":"0x4e",
   "removed":false,
   "topics":[  
      "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
      "0x00000000000000000000000000c5e04176d95a286fcce0e68c683ca0bfec8454",
      "0x000000000000000000000000001866ae5b3de6caa5a51543fd9fb64f524f5478"
   ],  "transactionHash":"0xe6c51c4156154a78ccc341a2734f3ac233a9717ba3ce54db35558cc6877f4727",
   "transactionIndex":"0x5f",
   "transactionLogIndex":"0x0",
   "type":"mined"
}

This issue is not replicable for all addresses, i have below example for which it is working perfectly fine:
"params": [{
	"fromBlock": "0x5e85c9",
	"toBlock": "0x5e85c9",
	"address": "0xb8c77482e45f1f44de1745f52c74426c631bdd52",
	"topics": ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]
}]

Response:
{  
   "jsonrpc":"2.0",
   "result":[  
      {  
         "address":"0xb8c77482e45f1f44de1745f52c74426c631bdd52",       
      "blockHash":"0x6cb1782673f5a624ee76b0f71d4217874332b706ec69c3017c00a5fd7f7a0b3f",
         "blockNumber":"0x5e85c9",
         "data":"0x000000000000000000000000000000000000000000000002313ead2567c52000",
         "logIndex":"0x9",
         "removed":false,
         "topics":[  
            "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
            "0x000000000000000000000000764343498cdca9cc95ade006cbe07b78bae0f50c",
            "0x0000000000000000000000003f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be"
         ],   
"transactionHash":"0xe021deb66c4196e96e9f0964e4232cf59295d4e88caa221aac0f1fd31f1ca3c2",
         "transactionIndex":"0x1d",
         "transactionLogIndex":"0x0",
         "type":"mined"
      }
   ],
   "id":1
}

**Comment by vishalgupta96** [comment]
This looks similar to below bug which seems to be closed in 2017: 
https://github.com/ethereum/go-ethereum/issues/15404

**Comment by vishalgupta96** [comment]
Hi, Did anyone look into it? Its an Open issue and we are waiting on this to be fixed in our current project. We even tried upgrading it to latest version 2.5.7-stable but it seems it is still present. In case you are not able to replicate, is there a way that i can reach out to parity team and show them on a meeting?

**Comment by vishalgupta96** [comment]
Hi Parity team, could you please provide an update when this issue is expected to resolve? I see that it has been added to 2.7 milestone, when it is expected to go live?

@joshua-mir : Could you please reply as we are stuck in our development for this.

**Comment by joshua-mir** [comment]
@vishalgupta96 you shouldn't take milestones as any kind of ETA - we just use them to keep track of which branch issues get backported into *when* they are resolved. Sorry if that is confusing.

In the meanwhile, to somewhat address the issue you are facing, if there were issues in the past that caused missing logs on your node, a future fix will not cause those missing logs to be repopulated somehow. 

That unfortunately means updating your version of parity will not be sufficient to fix the problem unless you also sync from scratch on the newer version, which I understand may be frustrating if you aren't certain whether the issue is resolved or which version introduced the bug that caused missing logs.

**Comment by vishalgupta96** [comment]
@joshua-mir : Thanks for the reply but i think i was not able to explain the issue properly. We are not missing any log entries. As when we are querying using below filters, we are able to see the correct records:
**Able to fetch the records using below params:**
"params": [{
"fromBlock": "0x3CD7B3",
"toBlock": "0x3CD7B3",
}]

But when we are applying additional filter of "address" and "topics", data is not getting fetched while it should be fetched as we have the matching data from the output of above mentioned query.

**Unable to fetch using "Address" and "Topics" filter:**
"params": [{
"fromBlock": "0x3CD7B3",
"toBlock": "0x3CD7B3",
"address": "0xb8c77482e45f1f44de1745f52c74426c631bdd52",
"topics": ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]
}]

And this is an intermittent issue which is not replicable for all the blocks. 
Other people using Parity for eth_getlogs API might be facing the same issue.

Could you check the above discrepancy and respond.

**Comment by vishalgupta96** [comment]
@joshua-mir : Hello... Did you get a chance to review my last comment... i have tried to clarify the issue again as it not an issue with missing log entries. All expected log entries are there but we are unable to filter them using "Address" and "Topics" filters for some cases. For some cases, it works but for many other cases, it does not give the expected entries filtered by address.

Please advise. I have re-tested it again for the example above mentioned but it is still not resolved.

**Comment by joshua-mir** [comment]
I haven't had the opportunity to attempt to replicate this myself - I understand what you are saying and agree that it is not how we expect it to work.

**Comment by vishalgupta96** [comment]
@joshua-mir : Hello... could you please try having a look or create a bug so that it would be taken care in upcoming parity builds.

**Comment by vishalgupta96** [comment]
Hi @joshua-mir ... its been around 3 months now... Could you please have someone look into it... I dont think Parity would want to have any kind of bug in the system for a longer run.. It would be great if you can try replicating this and if replicated, let us know if it is possible to fix this or not.

**Comment by ryanschneider** [comment]
I just ran into the same issue w/ a node running `Parity-Ethereum/v2.5.10-stable-9f94473-20191112/x86_64-linux-gnu/rustc1.39.0` (downloaded from parity website).  Node is running in archive +trace mode:

```
sudo nc -U /path/to/parity/jsonrpc.ipc
{"jsonrpc":"2.0", "id": 1123123, "method": "eth_getLogs", "params": [{"fromBlock": "0x602160","toBlock":"0x602165","topics":[["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]]}]}
{"jsonrpc":"2.0","result":[],"id":1123123}
```

If I had to guess, there's an issue with the bloom filter, but I'm not familiar with parity's internals.
