### ISSUE TITLE
error report: There are too many transactions in the queue. Your transaction was dropped due to limit. 

### ISSUE THREAD

**Issue by past2017** [openethereum/openethereum#11003]
- **Parity Ethereum version**: 2.5.6
- **Operating system**: Ubuntu +16G mem+8core CPU cloud machine
- **Installation**:  download binary from release page
- **Fully synchronized**: yes
- **Network**: ethereum  
- **Restarted**: yes   

**step1:**
       start parity with
      

>  ./parity daemon .pid --min-peers 50 --max-peers 60  --port 30333 --jsonrpc-port 4444 --jsonrpc-hosts all --log-file ./parity.log --pruning fast --jsonrpc-interface all --remove-solved --cache-size 2048 --cache-size-db 4096 --db-compaction ssd --tracing off --mode active --relay-set strict --force-sealing --tx-queue-size 4000 --db-path /data/.data --jsonrpc-apis web3,eth,net,personal,parity,parity_set,traces,rpc,parity_accounts --reseal-on-txs all --gas-price-percentile 60 --price-update-period=5 minutes --tx-queue-per-sender 1024 --min-gas-price 1 --tx-queue-mem-limit 0   

**step2:** 
         send transaction about 5 transactions / per minutes 
          
**step3:** 
       often error report:   
{"code":-32010,"message":"There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee."}

**step4:** 
      I check my tranasctions the gas price is about 15 G and in that time average gas price is only 4G

**Before in version 2.3.9 never report this error and after I upgrade to v2.5.6 serveral days ago, the error report over 20 times one day.** 
please help me to check what happen, thank you

**Comment by AnonOY** [comment]
Having same issue, any help?
