### ISSUE TITLE
Unable to export state of the chain at the latest block

### ISSUE THREAD

**Issue by Vid201** [openethereum/openethereum#11021]
- **Parity Ethereum version**: v2.6.2-beta
- **Operating system**: Linux (Ubuntu 18.04.3 LTS (Bionic Beaver))
- **Installation**: binary downloaded from releases
- **Fully synchronized**: yes
- **Network**: private development chain
- **Restarted**: yes

There is a bug when exporting state of the chain at the latest block.

**Command:** `$ parity export state ./state.json --chain demo-spec.json --fat-db on --at "latest"`
**Output:** 
```
2019-09-04 12:19:32  Running AuRa with a single validator implies instant finality. Use a database?
2019-09-04 12:19:32  Not preparing block; cannot sign.
2019-09-04 12:19:32  Configured for DemoPoA using AuthorityRound engine


====================

stack backtrace:
   0:     0x5602ea30796d - <no info>
   1:     0x5602ea3049ae - <no info>
   2:     0x5602ea30476e - <no info>
   3:     0x5602ea34f60a - <no info>
   4:     0x5602ea34f37e - <no info>
   5:     0x5602ea36c7a5 - <no info>
   6:     0x5602ea37284b - <no info>
   7:     0x5602ea378ab5 - <no info>
   8:     0x5602e9bf64af - <no info>
   9:     0x5602e9b4bdc1 - <no info>
  10:     0x5602e9dea38f - <no info>
  11:     0x5602e958c5aa - <no info>
  12:     0x5602ea5e26d9 - <no info>
  13:     0x5602ea5dba32 - <no info>
  14:     0x5602ea61da62 - <no info>
  15:     0x5602ea5da41f - <no info>
  16:     0x7fad29b37b96 - <no info>
  17:     0x5602e93f55d8 - <no info>
  18:                0x0 - <no info>

Thread 'main' panicked at 'Missing fatdb hash', src/libcore/option.rs:1036

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new


Aborted (core dumped)
```

**Comment by dvdplm** [comment]
@Vid201 can you show us the content of `state.json` and `demo-spec.json` please?

**Comment by Vid201** [comment]
@dvdplm 

**state.json:** `{ "state": {`
**demo-spec.json:**
```
 {
    "name": "DemoPoA",
    "engine": {
        "authorityRound": {
            "params": {
                "stepDuration": "1",
                "validators" : {
                     "list": ["0x12890d2cce102216644c59dae5baed380d84830c"]
                 }
            }
        }
    },
    "params": {
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "networkID" : "0x2323",
        "gasLimitBoundDivisor": "0x400",
	"eip140Transition": 0,
        "eip211Transition": 0,
        "eip214Transition": 0,
        "eip658Transition": 0,
	"eip145Transition": 0,
	"eip1014Transition":0,
	"eip1052Transition":0
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x5B8D80"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
        "0x12890d2cce102216644c59dae5baed380d84830c": { "balance": "10000000000000000000000" }
    }
}
```

**Comment by joshua-mir** [comment]
Is that the entire content of state.json? It looks like something went wrong in it's creation.

**Comment by Vid201** [comment]
Yes, that's all. It's same after every try.

**Comment by dvdplm** [comment]
@Vid201 how are you generating the `state.json`? Maybe the bug is in that process. As-is it is not valid json.

**Comment by Vid201** [comment]
@dvdplm Not sure if I understand your question. In one terminal tab I am running the node and in the second tab I am executing the above **command** which generates the `state.json`.

**Comment by dvdplm** [comment]
> Not sure if I understand your question.

Yeah, apologies, my question did not make sense. Please ignore.

**Comment by dvdplm** [comment]
Is the DB empty?

**Comment by Vid201** [comment]
> Is the DB empty?

It's not empty.

**Path:** `~/Documents/TestChains/parity-poa-linux/parity0/chains/DemoPoA/db/955c4dfcb19b0ee6/overlayrecent/db`
**db contents:** `000006.log  blooms  CURRENT  IDENTITY  LOCK  LOG  MANIFEST-000005  OPTIONS-000022  OPTIONS-000024  trace_blooms`
**blooms contents:** `bot.bdb  mid.bdb  top.bdb`, these files are empty
**trace_blooms contents:** `bot.bdb  mid.bdb  top.bdb`

**Comment by dvdplm** [comment]
So the error comes from [here](https://github.com/paritytech/trie/blob/502740b973fcc9d66b8fe769189609c67f1dd88d/trie-db/src/fatdb.rs#L122) but that's not super helpful. Is it possible you ran your node(s) without `--fat-db=on` for some time? As with tracing, fatdb has to be turned on from the beginning.

**Comment by dvdplm** [comment]
Here's what I get on my end (`macos`):

```
$ cat ./state.json
{ "state": {
"0x0000000000000000000000000000000000000001": {"balance": "1", "nonce": "0"},
"0x0000000000000000000000000000000000000003": {"balance": "1", "nonce": "0"},
"0x12890d2cce102216644c59dae5baed380d84830c": {"balance": "21e19e0c9bab2400000", "nonce": "0"},
"0x0000000000000000000000000000000000000004": {"balance": "1", "nonce": "0"},
"0x0000000000000000000000000000000000000002": {"balance": "1", "nonce": "0"}
}}
```

On my system the node has to be shut down when exporting or I get `Failed to open database Custom { kind: Other, error: "IO error: While lock file: /Users/dvd/Library/Application Support/io.parity.ethereum/chains/DemoPoA/db/955c4dfcb19b0ee6/overlayrecent/db/LOCK: Resource temporarily unavailable" }` – is it possible that linux lets you open the DB and that is why it fails?
@joshua-mir is `export` supposed to work with a running node?

**Comment by joshua-mir** [comment]
>  is export supposed to work with a running node?

Nope, that's why they are cli commands and not rpc endpoints 👍

**Comment by Vid201** [comment]
> Here's what I get on my end (`macos`):
> 
> ```
> $ cat ./state.json
> { "state": {
> "0x0000000000000000000000000000000000000001": {"balance": "1", "nonce": "0"},
> "0x0000000000000000000000000000000000000003": {"balance": "1", "nonce": "0"},
> "0x12890d2cce102216644c59dae5baed380d84830c": {"balance": "21e19e0c9bab2400000", "nonce": "0"},
> "0x0000000000000000000000000000000000000004": {"balance": "1", "nonce": "0"},
> "0x0000000000000000000000000000000000000002": {"balance": "1", "nonce": "0"}
> }}
> ```
> 
> On my system the node has to be shut down when exporting or I get `Failed to open database Custom { kind: Other, error: "IO error: While lock file: /Users/dvd/Library/Application Support/io.parity.ethereum/chains/DemoPoA/db/955c4dfcb19b0ee6/overlayrecent/db/LOCK: Resource temporarily unavailable" }` – is it possible that linux lets you open the DB and that is why it fails?
> @joshua-mir is `export` supposed to work with a running node?

Oh ok. I'll try tomorrow with the node shut down. If that's the case, it could be mentioned in the docs (https://wiki.parity.io/CLI-Sub-commands.html).

**Comment by dvdplm** [comment]
> it could be mentioned in the docs

I agree wholeheartedly.

**Comment by Vid201** [comment]
I tried with the node shut down. It works now and I get the same `state.json` as you. But now I can't manage to get the state after the last commited block (I am getting the state after genesis). What's wrong with the following **command**: `$ parity export state ./state.json --chain demo-spec.json --fat-db on --at "latest"`

**Comment by dvdplm** [comment]
Hmm, I don't have a database synced with `--fat-db on` and I'm unsure what should happen tbh (I only get the same `state.json` as above ofc as I don't have anything in the db). Can you guide me through adding a few blocks so I can debug this further?

**Comment by Vid201** [comment]
I made some transactions with MetaMask and balances on some addresses changed, but `state.json` stayed the same. More precisely, sent some ETH from 0x12890d2cce102216644c59dae5baed380d84830c to some address.

**Comment by adria0** [comment]
Closing the issue due to its stale state
