### ISSUE TITLE
[rpc tests]: sometime fails

### ISSUE THREAD

**Issue by niklasad1** [openethereum/openethereum#11070]
The following tests sometimes in CI:
- [v1::tests::mocked::signing::should_check_status_of_request_when_its_resolved](https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/v1/tests/mocked/signing.rs#L205)
```bash 
v1::tests::mocked::signing::should_check_status_of_request_when_its_resolved stdout ----
thread 'v1::tests::mocked::signing::should_check_status_of_request_when_its_resolved' panicked at 'assertion failed: `(left == right)` (left: `Some("{\"jsonrpc\":\"2.0\",\"result\":null,\"id\":1}")`, right: `Some("{\"jsonrpc\":\"2.0\",\"result\":\"0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001\",\"id\":1}")`, diff: ` [91mSome("{\"jsonrpc\":\"2.0\",\"result\":null,\"id\":1}")[0m [92mSome("{\"jsonrpc\":\"2.0\",\"result\":\"0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001\",\"id\":1}")[0m `)', rpc/src/v1/tests/mocked/signing.rs:235:2
```
- [tests::rpc::tests::should_extract_rpc_origin](https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/tests/rpc.rs#L70)
```bash
---- tests::rpc::tests::should_extract_rpc_origin stdout ----
thread 'tests::rpc::tests::should_extract_rpc_origin' panicked at 'Expected a response', src/libcore/option.rs:1036:5
```
- [tests::rpc::tests::should_respond_valid_to_any_requested_header](https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/tests/rpc.rs#L121)
```bash
---- tests::rpc::tests::should_respond_valid_to_any_requested_header stdout ----
thread 'tests::rpc::tests::should_respond_valid_to_any_requested_header' panicked at 'Expected a response', src/libcore/option.rs:1036:5
```
- [ws::testing::should_allow_if_authorization_is_correct](https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/tests/ws.rs#L107)
```bash
---- tests::ws::testing::should_allow_if_authorization_is_correct stdout ----
thread 'tests::ws::testing::should_allow_if_authorization_is_correct' panicked at 'Expected a response', src/libcore/option.rs:1036:5
```
- [ws::testing::should_not_redirect_to_parity_host ](https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/tests/ws.rs#L62)
```bash
---- tests::ws::testing::should_not_redirect_to_parity_host stdout ----
thread 'tests::ws::testing::should_not_redirect_to_parity_host' panicked at 'Expected a response', src/libcore/option.rs:1036:5
```
- [ws::testing::should_block_if_authorization_is_incorrect](https://github.com/paritytech/parity-ethereum/blob/master/rpc/src/tests/ws.rs#L82)
```bash
---- tests::ws::testing::should_block_if_authorization_is_incorrect stdout ----
thread 'tests::ws::testing::should_block_if_authorization_is_incorrect' panicked at 'Expected a response', src/libcore/option.rs:1036:5
```

**Comment by afck** [comment]
Since in `should_check_status_of_request_when_its_resolved` the `result` is unexpectedly `null`: Is it just the `thread::sleep` duration that needs to be increased?

**Comment by dvdplm** [comment]
Possibly yes, or rather: while that would probably work it's a bit worrying that it happens so often (and only in CI) so ideally we should dig into why this happens rather than "sweep it under the rug" with a longer delay. That said, I'd probably accept a PR with a longer delay to kick the can down the road a bit.

**Comment by afck** [comment]
I guess the proper solution would be to somehow be notified when the work in the other thread is complete. (But that might involve adding lots of test-only code into production code?)

Or a cruder solution: Keep calling `tester.io.handle_request_sync(&request)` every few milliseconds while the `result` is `null`, until it's either as expected or some much longer timeout is exceeded? (That's better than just always waiting for a longer timeout unnecessarily.)
