### ISSUE TITLE
Odd behavior starting up Parity on Win10

### ISSUE THREAD

**Issue by A2be** [openethereum/openethereum#11081]
- **Parity Ethereum version**: 2.5.5
- **Operating system**: Windows 
- **Installation**: from Parity site for Intel 64 bit build
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: yes, the behavior is repeatable

Parity is now auto-updating the version of my Parity (I don't know when this began), and places it in `Parity\EthereumUpdates\parity-2.5.8-c52a6c8fb7188ee01fcf90d8094eac339470767f` in the `AppData\Roaming` part of my Win10 machine. 

ACTUAL: **Running the "`parity`" cmd on the downloads folder (where I had left the `parity.exe` file) from the command line, Parity reports that it is running `Starting Parity-Ethereum/v2.5.5-stable-3ebc76975-20190708/x86_64-windows-msvc/rustc1.36.0` , rather than the latest.** 

EXPECTED BEHAVIOR I am expecting it to **Run the current Parity (2.5.8)** since @matrixbot mentioned on the Parity gitter that this would all happen automatically, now that Parity has this automatic version updating (19 Sep 2019). 

**steps to reproduce: Win10 machine, just run parity 2.5.5 from the folder as I described above**

**Comment by joshua-mir** [comment]
(I just want clarify that if a message on gitter is from matrixbot, that just means that it comes from the other side of our gitter-matrix bridge, and the first part of the message is the name of the sender 😅)

**Comment by A2be** [comment]
> (I just want clarify that if a message on gitter is from matrixbot, that just means that it comes from the other side of our gitter-matrix bridge, and the first part of the message is the name of the sender 😅)

So can I assume that "JAM" is joshua-mir?  :)

**Comment by adria0** [comment]
Auto-update feature has been removed in OpenEthereum. Closing.
