### ISSUE TITLE
parity node stops syncing on high load from json rpc

### ISSUE THREAD

**Issue by ayrat555** [openethereum/openethereum#11097]
- **Parity Ethereum version**: Parity-Ethereum//v2.5.5-stable-3ebc769-20190708/x86_64-linux-gnu/rustc1.36.0 (the same behaviour is for 2.5.8)
- **Operating system**: Linux
- **Fully synchronized**: yes
- **Network**: ethereum main
- **Restarted**: yes

Parity node stops synchronisation under high load from json rpc. I'm using json rpc to run blockscout instance and it uses some heavy tracing requests like `trace_replayBlockTransactions`. Disk utilisation reaches 100 % and parity doesn't sync anymore. What are possible approaches to mitigate that?

I tried setting different values for
```
processing_threads
server_threads
```
It doesn't help.

**Comment by joshua-mir** [comment]
@ayrat555 this may be unavoidable if disk IO is the bottleneck as you are describing, as server_threads only determines CPU threads being used. If it's feasible, you may want to run two separate nodes for staying in sync and running heavy rpc queries.

**Comment by ayrat555** [comment]
> If it's feasible, you may want to run two separate nodes for staying in sync and running heavy rpc queries.
@joshua-mir but I won't be able to run rpc queries on newer blocks?

**Comment by joshua-mir** [comment]
Do you also see this issue for recent blocks on a non-archive node with tracing enabled? IIUC that may be grabbing from cache and io shouldn't be the bottleneck.

**Comment by ayrat555** [comment]
@joshua-mir I think we only recently started having this issue. Can you suggest a more stable version?

**Comment by dvdplm** [comment]
@ayrat555 disk IO is disk IO and if it is completely saturated then it's hard to fix. There has been some recent improvements to threads handling for JSON rpcs which might help (but as said: if the disk(s) are completely stalled it will not help). To try out these latest patches you would have to compile parity from source, let us know if this is an option to you and we can help you (caveat: 2.6+ updates the database format so once upgraded there's no going back, so make sure you have backups).
We can definitely debug this further but we need more information about your work-load and preferably a script that repeats the issue.
