### ISSUE TITLE
Aura: TX premission broken in 3.1.0

### ISSUE THREAD

**Issue by iFA88** [openethereum/openethereum#111]
Client:
`OpenEthereum/v3.1.0-stable/x86_64-linux-musl/rustc1.47.0`

Error:
`Unknown version of tx permissions contract is used`

After error syncing hangs, with 3.0.1 works fine.

**Comment by rakita** [comment]
There are a lot of commits that need to be merged regarding AuRa, we are working on it here: https://github.com/openethereum/openethereum/issues/118
