### ISSUE TITLE
Expose hidden configuration options individually. 

### ISSUE THREAD

**Issue by joshua-mir** [openethereum/openethereum#11113]
We currently have three config options hidden behind the `--geth` commandline flag:

https://github.com/paritytech/parity-ethereum/blob/d193ddde19dbf3574aca8638c1a4041cc06472d7/parity/rpc_apis.rs#L303-L305

Which would be very useful to be able to configure independently as part of the `[mining]` section. 

For reference: https://github.com/paritytech/parity-ethereum/blob/3420c2bac08353f4269b9589decf8a9351275e64/parity/cli/mod.rs#L942 is where the existing flag is configured, which sets this variable here, among other small conditionals in configuration.rs: https://github.com/paritytech/parity-ethereum/blob/0051c26acfedd26591224155973ea175ca10f39a/parity/configuration.rs#L141
It may even be worthwhile additionally removing the `--geth` flag for good after this

**Comment by estk** [comment]
@joshua-mir can i pick this one up?

**Comment by joshua-mir** [comment]
Feel free to do so @estk! although I'm no longer so certain about removing the `--geth` flag, due to the number of people who use it regularly. Exposing the other options should be uncontroversial.

**Comment by niklasad1** [comment]
@joshua-mir 

We can still have the `geth flag` with a deprecation notice which that indicates `use mining options` instead `--geth` then the users have at least one release to transition or complain and we can revert it. 

IMHO, from a user perspective, the `--geth flag` is quite convenient even though it is not explicit.

However, if `--geth` and `miner options` have different configurations which one to use?

**Comment by joshua-mir** [comment]
presumably `miner` options would take precedence when present?

**Comment by niklasad1** [comment]
> presumably miner options would take precedence when present?

Yeah, I agree but perhaps print a warning about it, if it occurs.
