### ISSUE TITLE
eth_syncing shows wrong data

### ISSUE THREAD

**Issue by AlexRychkov** [openethereum/openethereum#11137]
I have two VPS that runs parity.

**First** shows eth_syncing result on 07.10.2019 11:33 (MSK)
{"jsonrpc":"2.0","result":{"currentBlock":"0x84a89d","highestBlock":"0x884bd3","startingBlock":"0x8380a9","warpChunksAmount":null,"warpChunksProcessed":null},"id":1} 
Which means the highest block is 8932307.
But the higest block on etherscan was 8693927.

**Second** shows eth_syncing result on 07.10.2019 11:26 (MSK)
{"jsonrpc":"2.0","result":{"currentBlock":"0x84a876","highestBlock":"0x885aa1","startingBlock":"0x8476d3","warpChunksAmount":null,"warpChunksProcessed":null},"id":1}
Which means the highest block is 8936097.
But the higest block on etherscan was 8693885.

But after I restart the **second** node it starts to show correct results (11:38 MSK)
{"jsonrpc":"2.0","result":{"currentBlock":"0x84a8b2","highestBlock":"0x84a8bd","startingBlock":"0x84a87c","warpChunksAmount":null,"warpChunksProcessed":null},"id":1}

**First**
- one core & 2 gb ram
- **Parity Ethereum version**: 2.5.7
- **Operating system**:  Linux
- **Installation**:  one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: no 
- **Config**:

[rpc]
port = 8545
disable = false
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]

[network]
allow_ips = "all"
port = 30303

[misc]
log_file = "xxx/log.log"

[parity]
base_path = "xxx/.local/share/io.parity.ethereum/"
mode = "active"
no_persistent_txqueue = true

[websockets]
disable = true

[ipc]
disable = true

[dapps]
disable = true

[ipfs]
enable = false

[secretstore]
disable = true

**Second**
- two cores & 4 gb ram
- **Parity Ethereum version**: 2.5.9
- **Operating system**:  Linux
- **Installation**:  one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: no 
- **Config**:

[rpc]
port = 8545
disable = false
interface = "0.0.0.0"

[network]
min_peers = 15
max_peers = 50
max_pending_peers = 5 
allow_ips = "all"
port = 30303
warp = true

[misc]
log_file = "xxx/log.log"

[parity]
base_path = "xxx/.local/share/io.parity.ethereum/"
mode = "active"

[websockets]
disable = true

[ipc]
disable = true

[dapps]
disable = true

[ipfs]
enable = false

[secretstore]
disable = true

Edit: I have monitoring logs for CPU, ram, etc if need

**Comment by joshua-mir** [comment]
@AlexRychkov eth_syncing only reports what your peers are reporting to you, which isn't guaranteed to be accurate - as you've noticed, restarting (and wiping your peers) should resolve this.

There are probably a few places (ie light, warp,) that we should be more aggressive in cycling peers

**Comment by AlexRychkov** [comment]
I can't find anything about accuracy in docs. It would be good if it will be specified
https://wiki.parity.io/JSONRPC-eth-module#eth_syncing

**Comment by joshua-mir** [comment]
It is stated that it is an estimate. Do you think it would be helpful to make that more explicit?

**Comment by AlexRychkov** [comment]
Oh, sorry, you're right, it's ok
