### ISSUE TITLE
ethstore KeyFile not being public and usage of KeyFile values

### ISSUE THREAD

**Issue by elpiel** [openethereum/openethereum#11152]
Given that KeyFile is public, but not exported publicly from `ethstore` and the `OpaqueKeyFile` is public and exported, but lacks the possibility of converting back to `KeyFile`, we have a use case where we want to check if the `address` checksum is correct with `eth_checksum::checksum`, so we access it by `keystore["address"]`, but this leads to interesting outcome: We are bound to use `serde_json::Value` for that case and later on, when we do want to use create a `SafeAccount,` we need to go through all this trouble of:

```
    SafeAccount::from_file(
            // keystore_json is the serde_json::Value
            // and we do need to convert it to KeyFile
            serde_json::from_value(self.keystore_json.clone())?,
            ....
    );
```

This is because the [`SafeAccount::from_file`, accepts only `KeyFile`](https://github.com/paritytech/parity-ethereum/blob/9584faee5590c145ef0d5772102446e486165857/accounts/ethstore/src/account/safe_account.rs#L83) .

I am not suggesting any specific changes, but rather wanted to bring this up and see if this API can be improved in a way.

**Comment by seunlanlege** [comment]
Do you have a proposal on how the API can be improved?

**Comment by elpiel** [comment]
What about `impl Into<KeyFile> for OpaqueKeyFile` and in `SafeAccount::from_file` take an `T: Into<KeyFile>` for example?
And also implement `Deserialize` for `OpaqueKeyFile`, this way we can read from a file and deserialize it in publicly accessible struct, which can be use in other structs (as in our case).

Tbh I don't know the reason that `KeyFile` is not exported, nor why the `OpaqueKeyFile` exists and only allows Serialization, so take this proposal lightly.
