### ISSUE TITLE
Wallet returns invalid address balance when ran with `--pruning=fast` and `--warp-barrier`

### ISSUE THREAD

**Issue by mknycha** [openethereum/openethereum#11162]
First of all, thanks for Parity, great to see it open-source.

- **Parity Ethereum version**: 2.5.7
- **Operating system**: MacOS
- **Installation**: homebrew
- **Fully synchronized**: no
- **Network**: ropsten
- **Restarted**: yes

1. I get some ETH from a ropsten faucet, it is [visible in explorer](https://ropsten.etherscan.io/tx/0xe0d0b50e2cc6365583a91d60329b4d635c80d8590eeeea9259dd5fa62ff34898) and a wallet running in light mode.
2. I want to save some disk usage, so I run my wallet with the following options:
```
parity --chain=ropsten --pruning=fast --warp-barrier=6504698
```
(Note that the transaction I am looking for was mined in the block 6544698, as per the explorer)

**What happens next:**
When I try to check the balance for the destination address or send any ETH, my wallet tells me there were no transactions:
```
> curl --data '{"method":"eth_getBalance","params":["0xb64c0d60fa9fcbafcfadecedc42f3646d41f6f49"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST 127.0.0.1:8545
{"jsonrpc":"2.0","result":"0x0","id":1}
```
**What is supposed to happen:**
Calling `getBalance` should return a valid balance:
```
> curl --data '{"method":"eth_getBalance","params":["0xb64c0d60fa9fcbafcfadecedc42f3646d41f6f49"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST 127.0.01:8545
{"jsonrpc":"2.0","result":"0xde0b6b3a7640000","id":1}
```

I am new to crypto - if I am doing something wrong, I will be grateful for a precise explanation ;)

**Comment by seunlanlege** [comment]
Your node isn't fully synced.
