### ISSUE TITLE
There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.

### ISSUE THREAD

**Issue by heimi-block** [openethereum/openethereum#11182]
- **Parity Ethereum version**: v2.5.9-stable
- **Operating system**:  Linux
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

```
"code":-32010,"message":"There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.
```
## bug
All my transactions are from the same sender, gas price >= 34gwei!, bug some of tx failed!
![WechatIMG12](https://user-images.githubusercontent.com/22029390/67136580-bf2ebb00-f25a-11e9-865e-cf06dbddb907.png)

## my config.toml:

```
[parity]
# Basic parameters regarding Parity operation.
chain = "mainnet"
mode = "active"
base_path = "./data"
light = false
no_persistent_txqueue = false
public_node = false
no_download = false
no_consensus = false

[network]
# Network and peer-related settings. Network is not available if Parity is in offline mode.
warp = true
port = 30304
min_peers = 6
max_peers = 12
max_pending_peers = 320

[websockets]
# UI won't work and WebSockets server will be not available.
disable = false
interface = "0.0.0.0"
cors = ["*"]
hosts = ["all"]
apis = ["all"]
server_threads = 12
poll_lifetime = 120
allow_missing_blocks = false
```

how to resolve it????? who can help me?

**Comment by icxcat** [comment]
before i use parity, i am used infrua.io， its ok

**Comment by icxcat** [comment]
shoud i add this to config?

```
[mining]
# Parity will keep/relay at most 32768 transactions in queue.
tx_queue_size = 32768
# Maximum number of transactions per sender in the queue. By default it's 1% of the entire queue, but not less than 16.
tx_queue_per_sender = 8192
```

**Comment by past2017** [comment]
> shoud i add this to config?
> 
> ```
> [mining]
> # Parity will keep/relay at most 32768 transactions in queue.
> tx_queue_size = 32768
> # Maximum number of transactions per sender in the queue. By default it's 1% of the entire queue, but not less than 16.
> tx_queue_per_sender = 8192
> ```



> shoud i add this to config?
> 
> ```
> [mining]
> # Parity will keep/relay at most 32768 transactions in queue.
> tx_queue_size = 32768
> # Maximum number of transactions per sender in the queue. By default it's 1% of the entire queue, but not less than 16.
> tx_queue_per_sender = 8192
> ```
@icxcat 
Hi have you resoved this issue after modify config
I filed it also in https://github.com/paritytech/parity-ethereum/issues/11003

**Comment by AnonOY** [comment]
I have the same error response from a parity node, instead with Infura works fine, so I'm having the same issue as you. Let me know if someone find the solution, thanks!

**Comment by icxcat** [comment]
@AnonOY @past2017  i am fix my send-coin code.  Using more address as the sender,  not one as before.  ps: you can ready more address to handle user tx request in your project queue, use them like `Dispatch center`

**Comment by icxcat** [comment]
Because one address remote nonce will be not refresh quickly and diff, even if you pay more gas fee and wait 60s to handle next tx. sometimes node remote nonce for this sender is not diff, it still use last nonce

**Comment by icxcat** [comment]
@past2017 @AnonOY If you have WeChat or telegram, we can discuss and share it together.

**Comment by frmiqueias** [comment]
> > shoud i add this to config?
> > ```
> > [mining]
> > # Parity will keep/relay at most 32768 transactions in queue.
> > tx_queue_size = 32768
> > # Maximum number of transactions per sender in the queue. By default it's 1% of the entire queue, but not less than 16.
> > tx_queue_per_sender = 8192
> > ```
> 
> > shoud i add this to config?
> > ```
> > [mining]
> > # Parity will keep/relay at most 32768 transactions in queue.
> > tx_queue_size = 32768
> > # Maximum number of transactions per sender in the queue. By default it's 1% of the entire queue, but not less than 16.
> > tx_queue_per_sender = 8192
> > ```
> 
> @icxcat
> Hi have you resoved this issue after modify config
> I filed it also in #11003

Solved for me.
