### ISSUE TITLE
Fatal: Failed to start the JavaScript console: api modules: invalid character 'W' looking for beginning of value

### ISSUE THREAD

**Issue by shaohongwu** [openethereum/openethereum#11213]
Fatal: Failed to start the JavaScript console: api modules: invalid character 'W' looking for beginning of value

**Comment by shaohongwu** [comment]
docker run -d -h eth --name eth-kovan -p 8548:8546 \
           -it parity/parity:stable --chain=kovan \
           --ws-interface=all --ws-origins="all" \
           --jsonrpc-hosts="all" \
           --base-path /home/parity/.local/share/io.parity.ethereum/

**Comment by joshua-mir** [comment]
@shaohongwu can you clarify what you are trying to achieve here, and what directions you are following to do that?

I'm not sure why you would see an error regarding a javascript console when running the command you shared.
