### ISSUE TITLE
which wallet?

### ISSUE THREAD

**Issue by drandreaskrueger** [openethereum/openethereum#11223]
Isn't this information inconsistent? At least it is confusing me, so before I now loose tons of time, I better ask. Apologies that this is a question not a code issue. But I guess you want to modify the 2nd, no? -->

* homepage https://www.parity.io/technologies/ says ... --> [Fether](https://github.com/paritytech/fether)
* wiki https://wiki.parity.io/Parity-Wallet says --> [MyCrypto Desktop app](https://download.mycrypto.com/)

Which one to use? Is there another wallet than those 2 ? 

The second page talks about parity v2 not being compatible anymore with [parity UI](https://github.com/parity-js/shell). But v1 is EOLife, right?

I have key files with filenames like `UTC--2017-06-10T12-12-12Z--aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee` and I simply want to **move my ETH and my ERC20 tokens**. As syncing is probably not possible within a reasonable time, with a "light client". Thanks.

Secondly, is there any reason NOT to use the "Parity Ethereum v2.5.9-stable" version? Which version do you recommend?

Thanks a lot
Andreas

**Comment by seunlanlege** [comment]
To answer your first question. I would recommend the Fether wallet. I don't think the wiki is currently being maintained.

**Comment by joshua-mir** [comment]
@drandreaskrueger for previous users of the UI we recommend MyCrypto because of the feature set - for new users we recommend Fether. Your keyfiles should be able to be imported into either, but if you use fether it will automatically load keyfiles in parity's default base directory.

**Comment by drandreaskrueger** [comment]
> I don't think the wiki is currently being maintained.  

what about a red header line "wiki not maintained since xx/yy/2019, information might be outdated" on all wiki pages?

Thank you very much, @joshua-mir and @seunlanlege - good that I asked. 

So ... Fether it is. I assume it can do token transfers too?

**Comment by drandreaskrueger** [comment]
Ah, idea:

>  because of the feature set 

what about a quick comparison table of the two?

I do understand "feature set" but still cannot decide until I know the feature comparison.

**Comment by drandreaskrueger** [comment]
oh, and any hints for how exactly to run the light client?  Some cool CLI switches that you recommend? Thanks.

```
parity --light

2019-11-04 19:51:43  Starting Parity-Ethereum/v2.5.9-stable-06c7096-20190926/x86_64-linux-gnu/rustc1.36.0
2019-11-04 19:51:43  Keys path ~/.local/share/io.parity.ethereum/keys/ethereum
2019-11-04 19:51:43  DB path ~/.local/share/io.parity.ethereum/chains_light/ethereum/db/906a34e69aec8c0d
2019-11-04 19:51:43  Running in experimental Light Client mode.
2019-11-04 19:51:43  Inserting hardcoded block #7460865 in chain
2019-11-04 19:51:44  Debug API is not available in light client mode.
2019-11-04 19:51:44  Debug API is not available in light client mode.
2019-11-04 19:51:44  Listening for new connections on 127.0.0.1:8546.
2019-11-04 19:51:44  Public node URL: enode://...@...:30303
```

**Comment by drandreaskrueger** [comment]
syncing:
```
2019-11-04 19:55:59  Syncing #7464532 ...
2019-11-04 20:26:21  Imported #8873175 ...
```
so, until head of chain, 8873175, **approx 30 minutes** ...

**Comment by drandreaskrueger** [comment]
unfortunately ...

https://github.com/paritytech/fether/issues/573

**Comment by drandreaskrueger** [comment]
> for new users we recommend Fether. 

Sadly, newer than 0.3.1 versions of fether don't work: https://github.com/paritytech/fether/issues/573#issuecomment-589323133

And the 0.3.1 does not work with parity 2.7.2 anymore.

checkmate?
