### ISSUE TITLE
Why does warp sync get disabled with tracing=on?

### ISSUE THREAD

**Issue by JonasPf** [openethereum/openethereum#11256]
The relevant code is here:

https://github.com/paritytech/parity-ethereum/blob/ffeaee778c0eaa60a7e0f6381cf069135c3ef5c3/parity/run.rs#L460

I'm curious about the rationale behind this. Tracing seems to work perfectly fine with warp sync. I've tested it by disabling tracing, running a warp sync and then re-enabling tracing.

The only thing I cannot trace are historic transactions from before the warp sync snapshot. This only affects the `trace_replay*` methods, all the other tracing APIs seem to work.

Related docs: https://wiki.parity.io/JSONRPC-trace-module

**Comment by stone212** [comment]
@JonasPf 

I am not a Parity dev but I have a little experience and basically I think the answer is that the tracing function logs details of each block that are contrarywise to the warp function because warp only downloads the most important information.

Tracing does not work with warp sync and it fails exactly how you said.  When you turn tracing on *after* you warp sync it can work but you will not have tracing data for the blocks that were synced with warp, only the new blocks since turning on tracing.

**Comment by JonasPf** [comment]
My understanding is that out of the 5 tracing calls only two (`trace_replayBlockTransactions` and `trace_replayTransaction`) require the block data. With warp sync the historic block data is missing but everything after the initial sync is fully available.

So most of the tracing api actually would work with warp enabled. Only two calls may not work, depending on which block is traced. In a situation like this I would expect a warning (`warp sync is enabled, do not expect historic tracing to work`) instead of blocking the functionality completely. Especially considering that a full (non-warp) sync may take days or weeks.

Unless I'm missing something.

**Comment by dvdplm** [comment]
I think you're right and we could probably allow tracing and warp sync (and make sure any RPCs affected get proper checks and error messages).

Would you be interested in submitting a PR for this?

**Comment by JonasPf** [comment]
I'd love to but, since I would first need to learn rust, it might take a while until I get to it if I find the time at all.

So if anybody else wants to tackle this, please go ahead.

**Comment by alsofter** [comment]
@JonasPf 
How could you managed to turn Parity on after warp sync with --tracing=on flag?
I tried such a thing, but got an error saying I need to resync my db first. The process of parity was killed after that.
Could you tell me the exact steps to turn on Parity with tracing after warp sync?

**Comment by richardpringle** [comment]
@dvdplm, I would love to do this but could definitely use some guidance as I am not that familiar with the code-base (and it's a big one).

**Comment by richardpringle** [comment]
@adria0, this issue has not been resolved. We're still running an older version in production as newer versions have issues syncing.
