### ISSUE TITLE
How to sign a transaction using password before dispatching it to the network?

### ISSUE THREAD

**Issue by mknycha** [openethereum/openethereum#11296]
- **Parity Ethereum version**: 2.5.10-stable
- **Operating system**: MacOS
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum (ropsten for testing)
- **Restarted**: yes

I have a cold wallet and I would like to sign a transaction with a private key (or password for encrypted key) before dispatching it to the ethereum network. Is it possible to do so in Parity? Could you provide an example please?

I went through the documentation and I thought that I could use `eth_signTransaction` followed by `eth_sendRawTransaction`, but it is not really clear to me how the transaction gets signed (when do I provide the password in this process?) and I see that `eth_signTransaction` is marked as deprecated.

Thanks in advance

**Comment by joshua-mir** [comment]
the process is to use eth_sendtransaction (or eth_sendrawtransaction) and then pass the password to your node using https://wiki.parity.io/JSONRPC-signer-module#signer_confirmrequest

alternatively you can simply use https://wiki.parity.io/JSONRPC-personal-module#personal_sendtransaction
