### ISSUE TITLE
Openethereum crashing at block 11281279

### ISSUE THREAD

**Issue by alt229** [openethereum/openethereum#113]
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 0.0.0
  version OpenEthereum/v3.1.0-stable-2072341-20201102/x86_64-linux-gnu/rustc1.47.0
- **Operating system**: Windows / MacOS / Linux
Linux debianhost 5.4.41-1-pve #1 SMP PVE 5.4.41-1 (Fri, 15 May 2020 15:06:08 +0200) x86_64 GNU/Linux
- **Installation**: homebrew / one-line installer / built from source
unzip openethereum-linux-v3.1.0.zip
- **Fully synchronized**: no / yes
No
- **Network**: ethereum / ropsten / kovan / ...
mainnet
- **Restarted**: no / yes
yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Client crashes now on startup with the following error attached in the text file. Please advise

[openethereum_error.txt](https://github.com/openethereum/openethereum/files/5569080/openethereum_error.txt)

**Comment by roninkaizen** [comment]
try to restart without permanent-tranaction que, if you like :)

**Comment by alt229** [comment]
Sure thing. Is this the argument I’m looking for? --no-persistent-txqueue?

Erin
@alt229

— "Follow your heart but take your brain with you.” - Alfred Adler

On Nov 20, 2020, at 11:09 AM, roninkaizen <notifications@github.com<mailto:notifications@github.com>> wrote:

permanent

**Comment by roninkaizen** [comment]
--no-persistent-txqueue is correct- would give it a try

**Comment by alt229** [comment]
Thanks, tried it and no change. Resyncing the whole blockchain so we’ll see how it goes.

Erin
@alt229

"Some lack the fickleness to live as they wish and just live as they have begun." -Seneca

On Nov 22, 2020, at 1:42 PM, roninkaizen <notifications@github.com<mailto:notifications@github.com>> wrote:



--no-persistent-txqueue is correct- would give it a try

**Comment by rakita** [comment]
This is new error, but it probably related to #69. FIx is made here: https://github.com/openethereum/openethereum/pull/149

**Comment by rakita** [comment]
There is fix for it for in v3.1.1
