### ISSUE TITLE
CentOS 7.x (7.7.1908) - Parity v2.7.0 Installation: failed to run custom build command for `librocksdb-sys v6.2.4

### ISSUE THREAD

**Issue by ymonye** [openethereum/openethereum#11326]
#### Versions 
* OS: CentOS 7.7.1908
* Hardware: Dell PowerEdge R720 (Red Hat / CentOS 7.x is the latest supported OS)
* Parity v2.7.0

This is a follow up to another (now resolved) issue: originally was I was unable to get Parity (v2.5.6 beta) installed on CentOS 7.x: https://github.com/paritytech/parity-ethereum/issues/11291

The above solution works for v2.6.5 beta, however it appears the following changes from commit https://github.com/paritytech/parity-ethereum/commit/f6c3d4c6951ecf2070bdf7e6a5c6a24edb1a43d6 introduced a new error for me: https://github.com/paritytech/parity-ethereum/pull/11248

### Build Process
These are the steps I'm performing to download & build Parity on my local machine:

```
curl https://sh.rustup.rs -sSf | sh
echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> /root/.bashrc
source /root/.bashrc
cd /
git clone https://github.com/paritytech/parity-ethereum
cd parity-ethereum
cargo build --release --features final
```
After sending the above "cargo build" command, the build process sends the following error:

> error: failed to run custom build command for `librocksdb-sys v6.2.4`
> 
> Caused by:
>   process didn't exit successfully: `/parity-ethereum/target/release/build/librocksdb-sys-0eb3d76ea19b6313/build-script-build` (exit code: 101)
> --- stdout
> cargo:rerun-if-changed=build.rs
> cargo:rerun-if-changed=rocksdb/
> cargo:rerun-if-changed=snappy/
> cargo:rerun-if-changed=lz4/
> cargo:rerun-if-changed=zstd/
> cargo:rerun-if-changed=zlib/
> cargo:rerun-if-changed=bzip2/
> cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
> cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
> 
> --- stderr
> thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7: cannot open shared object file: No such file or directory"', src/libcore/result.rs:1165:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
> error: build failed

I ran a search on my machine and in appears those 'libclang' files actual do exist:

> ls -la /usr/lib64/clang-private/ | egrep 'libclang.so|libclangAST.so'
> lrwxrwxrwx.   1 root root      16 Dec  9 18:37 libclangAST.so -> libclangAST.so.7
> -rwxr-xr-x.   1 root root 3650216 Aug  8 21:14 libclangAST.so.7
> lrwxrwxrwx.   1 root root      13 Dec  9 18:37 libclang.so -> libclang.so.7
> -rwxr-xr-x.   1 root root  558232 Aug  8 21:14 libclang.so.7

I searched Google for similar results and couldn't find any solutions. Would you all be able to help, and possibly introduce CentOS 7.x into future bug-testing pipelines?

Thanks

**Comment by dvdplm** [comment]
Building from source is something we welcome users to do, but unfortunately we cannot support everyone's build combinations. I am not a CentOS user myself and don't really know much about how it deals with packages and dependencies in general. 
When we switched to a more recent version of rocksdb we had to do some work to get our current CI pipeline updated to a more recent version of `libclang` – maybe what you're seeing is the CentOS version of the same? (ping @General-Beck ?).

When you do figure out how to build it for your OS, it'd be very useful if you commented here to help others in your situation!

**Comment by niklasad1** [comment]
https://github.com/rust-rocksdb/rust-rocksdb/issues/312 

can you try to remove the `llvm-private` package?

**Comment by ethcoreorg** [comment]
I'd the same error with latest master branch,

On ubuntu, try

    $ sudo apt-get install -y clang-6.0 lldb-6.0 lld-6.0 libc++-dev llvm

**Comment by Michael-fore** [comment]
I was having the same issue and 
`sudo apt-get install -y clang-6.0 lldb-6.0 lld-6.0 libc++-dev llvm` on 
Ubuntu 18.04.3 LTS

**Comment by derp42** [comment]
Fixed by removing the llvm-private packages through rpm (not the best, but I finally got a different error) and then installing the "Development Tools" group. Try installing the development tools first, I found I was missing the gcc++ compiler after killing the llvm-private packages.

To find the installed packages names: 
`rpm -qa | grep "llvm-private"`

To remove the offending packages:
`rpm -e --nodeps <package name>`

Installing the development tools group:
`sudo yum groupinstall "Development tools`

**Comment by ymonye** [comment]
> Fixed on Cent OS 7 minimal with KDE Plasma by removing the llvm-private packages through rpm (not the best, but I finally got a different error) and then installing the "Development Tools" group. Try installing the development tools first, I found I was missing the gcc++ compiler after killing the llvm-private packages.
> 
> To find the installed packages names:
> `rpm -qa | grep "llvm-private"`
> 
> To remove the offending packages:
> `rpm -e --nodeps <package name>`
> 
> Installing the development tools group:
> `sudo yum groupinstall "Development tools"`

This doesn't work for me:

```
error: failed to run custom build command for `librocksdb-sys v6.6.4`

Caused by:
  process didn't exit successfully: `/openethereum/target/release/build/librocksdb-sys-d44f7d75e99cdccd/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.2/src/lib.rs:1956:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```
Installing "Development Tools" has no leads:

`# sudo yum groupinstall "Development Tools"
Loaded plugins: fastestmirror, langpacks
There is no installed groups file.
Maybe run: yum groups mark convert (see man yum)
Loading mirror speeds from cached hostfile
 * base: mirror.team-cymru.com
 * epel: mirror.atl.genesisadaptive.com
 * extras: mirror.twinlakes.net
 * remi-safe: mirror.team-cymru.com
 * updates: repo1.dal.innoscale.net
Warning: Group development does not have any packages to install.
Maybe run: yum groups mark install (see man yum)
No packages in any requested group available to install or update`

**Comment by ymonye** [comment]
I ran install -y clang-6.0 lldb-6.0 lld-6.0 libc++-dev llvm and only the below installed:

```
llvm-3.4.2-9.el7.x86_64
llvm-libs-3.4.2-9.el7.x86_64
```
Looks like it still needs clang. Is there any other way of installing it?

```
# yum install -y clang-6.0 lldb-6.0 lld-6.0 libc++-dev llvm
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.team-cymru.com
 * epel: mirror.atl.genesisadaptive.com
 * extras: mirror.twinlakes.net
 * remi-safe: mirror.team-cymru.com
 * updates: repo1.dal.innoscale.net
No package clang-6.0 available.
No package lldb-6.0 available.
No package lld-6.0 available.
No package libc++-dev available.
Resolving Dependencies
--> Running transaction check
---> Package llvm.x86_64 0:3.4.2-9.el7 will be installed
--> Processing Dependency: llvm-libs(x86-64) = 3.4.2-9.el7 for package: llvm-3.4.2-9.el7.x86_64
--> Processing Dependency: libLLVM-3.4.so()(64bit) for package: llvm-3.4.2-9.el7.x86_64
--> Running transaction check
---> Package llvm-libs.x86_64 0:3.4.2-9.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
```

Build error:

```
# cargo build --release --features final
   Compiling semver v0.9.0
   Compiling impl-serde v0.3.0
   Compiling parity-scale-codec v1.2.0
   Compiling serde_json v1.0.48
   Compiling toml v0.5.6
   Compiling bincode v1.2.1
   Compiling docopt v1.1.0
   Compiling librocksdb-sys v6.6.4
   Compiling ethbloom v0.9.0
error: failed to run custom build command for `librocksdb-sys v6.6.4`

Caused by:
  process didn't exit successfully: `/openethereum/target/release/build/librocksdb-sys-d44f7d75e99cdccd/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.53.2/src/lib.rs:1956:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by ymonye** [comment]
> @ymonye
> 
> This is perhaps the same as: [rust-rocksdb/rust-rocksdb#312](https://github.com/rust-rocksdb/rust-rocksdb/issues/312)
> 
> can you try to remove the `llvm-private` package?

Thanks @niklasad1 that worked, along with the below:

> Fixed on Cent OS 7 minimal with KDE Plasma by removing the llvm-private packages through rpm (not the best, but I finally got a different error) and then installing the "Development Tools" group. Try installing the development tools first, I found I was missing the gcc++ compiler after killing the llvm-private packages.
> 
> To find the installed packages names:
> `rpm -qa | grep "llvm-private"`
> 
> To remove the offending packages:
> `rpm -e --nodeps <package name>`
> 
> Installing the development tools group:
> `sudo yum groupinstall "Development tools"`

Awesome! To get this build working on CentOS 7.x, I had to first remove llvm-private, then install clang & llvm:

```
rpm -qa | grep "llvm-private"
rpm -e --nodeps llvm-private-7.0.1-1.el7.x86_64
yum install -y clang llvm
```

Thanks!
