### ISSUE TITLE
AuRa multiple InitChange before FinalizeChange may cause client<->contract mismatch and potential consensus issues

### ISSUE THREAD

**Issue by LukaszRozmej** [openethereum/openethereum#11344]
- **Parity Ethereum version**: v2.5.* (but previous too)
- **Operating system**: system agnostic
- **Installation**: installation agnostic
- **Fully synchronized**: not applicable
- **Network**: sokol test network (but network agnostic)
- **Restarted**: not applicable

**actual behavior and steps to reproduce**

During full sync of sokol network, logs show:

At block 205821:
Signal for transition within contract. New list: [0xe8ddc5c7a2d2f0d7a9798459c0104fdf5e987aca, 0x82e4e61e7f5139ff0a4157a5bc687ef42294c248, 0x23468db7f4b8ff4924b0709ab7ae0971b3bc8d28, 0xa0b0d4ccf483b000f0af59c47a1944668477b941, 0xe2ac1c6843a33f81ae4935e5ef1277a392990381]

At block 212436:
2019-12-19 14:23:39  Signal for transition within contract. New list: [0xe8ddc5c7a2d2f0d7a9798459c0104fdf5e987aca, 0x82e4e61e7f5139ff0a4157a5bc687ef42294c248, 0x23468db7f4b8ff4924b0709ab7ae0971b3bc8d28, 0xa0b0d4ccf483b000f0af59c47a1944668477b941, 0xe2ac1c6843a33f81ae4935e5ef1277a392990381, 0xde88a1a783b29a0b476be28beef38b4a85c0e024]

After block 214414:
2019-12-19 14:23:40  Applying validator set change signaled at block 205821

The 2nd InitiateChange at block 212436 is ignored, never finalized and not used by parity client.

This might lead to an issue dependent on contract implementation. In sokol network at this block validator contract is not secured against this issue. This cause the FinalizeChange call at block 214414 to finalize 212436 validator list in contract. Next GetValidators call will return 6 validator addresses while parity client will use 5 validator addresses to produce and validate the chain.

I haven't tested but if parity client does warp-sync in that state it might get consensus issues. I think full sync works fine as client saves validator list in local db and fetch it from it on restart instead of calling contract GetValidators.

**expected behavior**

Minimum: This limitation should be well documented for contract developers to not emit InitateChange if previous one was not finalized.

Full: Parity client should queue InitiateChange events and finalize them consecutively. This still would require contract support to be consistent as contract would have to queue InitiateChange pending validators and match them with consecutive FinalizeChanges calls. So would need to be properly documented.

**Comment by LukaszRozmej** [comment]
I don't think it was resolved, was it? if not is this accepted as a compromise design in AuRa and won't be addressed?

**Comment by adria0** [comment]
@LukaszRozmej it seems that nobody has been working on it, or maybe fixed it but did not updated this issue.
