### ISSUE TITLE
Empty response from RPC API when `id` field is missing

### ISSUE THREAD

**Issue by kryvel** [openethereum/openethereum#11353]
- **Parity Ethereum version**: Parity-Ethereum/v2.5.12-stable-29ebddc64-20191216/x86_64-linux-gnu/rustc1.39.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**:  ropsten
- **Restarted**: yes

RPC API return an empty responses for all methods.

```
# curl -v --data '{"jsonrpc":"2.0","method":"personal_newAccount","params":["asdasd"]}' -H 'Content-Type:application/json' -m 3 http://127.0.0.1:44441
* Expire in 0 ms for 6 (transfer 0x560d1d943c40)
* Expire in 3000 ms for 8 (transfer 0x560d1d943c40)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x560d1d943c40)
* Connected to 127.0.0.1 (127.0.0.1) port 44441 (#0)
> POST / HTTP/1.1
> Host: 127.0.0.1:44441
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 68
>
* upload completely sent off: 68 out of 68 bytes
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< content-length: 0
< date: Fri, 27 Dec 2019 10:59:15 GMT
<
* Connection #0 to host 127.0.0.1 left intact
```

There are no any errors/warnings in log. Node is fully synced. 
Light = off, Warp = true, Pruning = fast.

Parity was build from sources

**Comment by seunlanlege** [comment]
can you rerun with ` --logging "rpc=trace"`

**Comment by kryvel** [comment]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore", "personal", "parity_set"]
logging = "own_tx=trace,rpc=trace"

```
2019-12-28 11:50:17 UTC http.worker30 TRACE rpc  Request: {"jsonrpc":"2.0","method":"parity_allAccountsInfo","params":[]}.
2019-12-28 11:50:17 UTC http.worker30 DEBUG rpc  Response: None.

2019-12-28 11:50:24 UTC http.worker00 TRACE rpc  Request: {"jsonrpc":"2.0","method":"net_version","params":[]}.
2019-12-28 11:50:24 UTC http.worker00 DEBUG rpc  Response: None.

2019-12-28 11:50:31 UTC http.worker40 TRACE rpc  Request: {"jsonrpc":"2.0","method":"personal_newAccount","params":["asdlkj"]}.
2019-12-28 11:50:31 UTC http.worker40 DEBUG rpc  Response: None.
```

**Comment by niklasad1** [comment]
@kryvel 

Your request is missing `id`, should work if you do:

```bash
curl -v --data '{"method":"personal_newAccount","params":["hunter2"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:44441 -m 3
```

**Comment by seunlanlege** [comment]
completely missed the `id` and the spent the last few days scratching my head as to what the problem could be, needs a better error message.

**Comment by kryvel** [comment]
@niklasad1 
 Hi, I'm already moved to geth. But it has the same issue with "id" param.

I think this is issue. What is the reason to call methods such as personal_newAccount as notification call ? 
API should warn about missing id param, as it's required for every call, and it should be visible mentioned somewhere in documentation.

**Comment by niklasad1** [comment]
> I think this is issue. What is the reason to call methods such as personal_newAccount as notification call ? 

We are not doing it (see answer below)

> API should warn about missing id param, as it's required for every call, and it should be visible mentioned somewhere in documentation.

The problem is that this managed by the `jsonrpc library` which then interprets the request as a notification and then `personal_newAccount` never gets called. Thus, it is not possible for the parity client to warn about this because it will not be notified. Sure, the documentation could be more explicit about this.
