### ISSUE TITLE
Publish ethstore and ethkey:0.4 on crates.io

### ISSUE THREAD

**Issue by elpiel** [openethereum/openethereum#11374]
We are using the two crates in our project and it will be convenient to see the `ethstore` published on crates.io and the `0.4` of `ethkey`.

Using the repository as a registry is very very very slow (definitely takes more than 10 minutes).
But this is quite a big bottleneck for us...

**Comment by dvdplm** [comment]
Yeah, we need to clean things up a little but don't see why we can't publish them.

If you don't mind me asking, what is your project? (personal curiosity).

**Comment by elpiel** [comment]
The @adexnetwork Rust validator stack:
https://github.com/AdExNetwork/adex-validator-stack-rust

**Comment by dvdplm** [comment]
> the `0.4` of `ethkey`

Are referring to https://crates.io/crates/ethkey perhaps? Seems like the Golem project published a crate with the same name (but different code). We can publish our `ethkey` (under a different name, and GPL) but just wanted to make sure it is actually what you need.

As for `ethstore` it's a bit more complicated as it has a few big unpublished dependencies that I don't think we can publish without a lot of hassle atm. :/

**Comment by elpiel** [comment]
I am not talking about https://crates.io/crates/ethkey , I just thought it's the same crate, my bad.
Yeah, publishing it will make it better.

Regarding `ethstore` - that's too bad since loading from this repository takes quite a long time fetching.

Sorry for the late response

**Comment by rakita** [comment]
Closing the issue due to its stale state
