### ISSUE TITLE
Parity ethereum  block restoration fails again and again with error "memory allocation of 9797894160 bytes failed""

### ISSUE THREAD

**Issue by AqeelKazmi** [openethereum/openethereum#11420]
Running ethereum parity with server xlarge 16gb ram 4 cores, its been 2 times when it fails with this status code "memory allocation of 9797894160 bytes failed" at same block  #4570000
Can anybody guide whether it is hardware specs issue or sync issue from other peers?
![image](https://user-images.githubusercontent.com/30657768/73358909-78247d00-42c1-11ea-9523-7d26f5c71c9e.png)

**Comment by niklasad1** [comment]
@AqeelKazmi 

I can't understand the log did you restart your or something why did the peers for example change?

Can you share your `config.toml`?  (`config.toml` should only be read at startup AFAIK)
