### ISSUE TITLE
Homomorphic encryption in smart contracts

### ISSUE THREAD

**Issue by jon-chuang** [openethereum/openethereum#11452]
What are plans to support homomorphic encryption in smart contracts? This could enable outsourced computing on secret data, including data that has been stored on the blockchain. The public keys can also be stored on the blockchain. 

Having worked with Microsoft's SEAL, I have some knowledge of how to implement certain variants of HE, so this could be an interesting project. In particular, arithmetic operations over the integers and fixed point arithmetic have efficient instantiations that could be practical for certain purposes (secure accounting, data processing, simple machine learning models) etc.

For some idea of efficiency, neural networks operating on MNIST have been evaluated with a throughput of 2959 img/s, albeit on 112 cores (see: ngraph-HE2). That's still ~25-30 img/s per core.

**Comment by ordian** [comment]
@jon-chuang I'm not sure this is the right repository for this discussion, the one you probably want is https://github.com/ethereum/EIPs.

**Comment by rakita** [comment]
Seems resolved
