### ISSUE TITLE
2.6.8 → 2.7.2: Stange disk usage pattern, allocating and freeing ~20GB in 48 hours

### ISSUE THREAD

**Issue by c0deright** [openethereum/openethereum#11516]
- **Parity Ethereum version**: 2.7.2-stable
- **Operating system**: Linux
- **Installation**: binary from github
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

After upgrading parity from `v2.6.8-beta` to `v2.7.2-stable` on my test VM I see increased monitoring events informing me of low free disk space. From the graphs it looks like v2.7.2 is allocating around 20GB in less than 48 hours only to then reduce used disk space again. This goes on in a saw tooth like fashion:

![disk-usage](https://user-images.githubusercontent.com/20477825/75243019-74551f00-57c9-11ea-95d5-6eb3b319ee1c.png)

**Just wanted to know whether this is expected behaviour or not.**

## Config

```
[parity]
no_download = true

[snapshots]
disable_periodic = true

[ui]
disable = true

[websockets]
disable = true

[ipc]
disable = true

[rpc]
disable = false
hosts = ["http://eth-test:8545"]
interface = "0.0.0.0"
apis = ["rpc", "web3", "eth", "net", "personal", "parity", "parity_set", "parity_accounts"]

[network]
min_peers = 12
max_peers = 12

[mining]
tx_queue_per_sender = 1024

[footprint]
tracing = "off"
db_compaction = "ssd"
pruning = "fast"
cache_size = 2000

[misc]
log_file = "/home/foo/.local/share/io.parity.ethereum/log.txt"
logging  = "own_tx,shutdown=trace,signer=trace"
```

**Comment by c0deright** [comment]
Restarting parity does trigger disk usage shrinking, too.

**Comment by ordian** [comment]
As in https://github.com/OpenEthereum/open-ethereum/issues/11503, this could be a rocksdb background compaction process triggered because of the settings change (take a look at rocksdb logs). The issue should go away after it's finished.

**Comment by c0deright** [comment]
1 hour after parity restart there are 27 occurences of `compaction_finished` in rocksdb LOG, disk usage did shrink upon restart (parity took an unusual long time to start) and keeps low at the moment.

Will report back in 24 hours if disk usage stays appr. constant again.

**Comment by c0deright** [comment]
Could someone please have a look at my [LOG](https://github.com/OpenEthereum/open-ethereum/files/4256305/LOG.txt) (10 MB) to check if it's "normal"? Disk usage is still growing more than usual and compaction is still happening regularly. How long is this process of compaction supposed to take appr.?

**Comment by Serpent6877** [comment]
I am looking to do the same upgrade. Should we expect some reduction in space usage? My ETC uses 47GB and my ETH uses 172GB.

**Comment by dvdplm** [comment]
Rocksdb compaction runs regularly whenever the different DB levels fill up; when settings change, such as for the 2.7 upgrade we've seen reports of increased IO and/or seemingly erratic disk usage patterns. How long it take really varies on many factors: hardware, network traffic, local RPC traffic or other system activity, database size etc. There is really no clear answer other than heuristics: most reporters have seen their systems return to normal within 24h, some longer, (some much longer actually, most much shorter).

**Comment by c0deright** [comment]
> Should we expect some reduction in space usage?

From the graph: nope

![disk-usage](https://user-images.githubusercontent.com/20477825/75428277-3af6ed80-5948-11ea-947b-2a45f4c3ff49.png)

But from analyzing the LOG file it seems to actually free *some* disk space:

```bash
grep -P 'compaction_finished|compaction_started' /home/*/.local/share/io.parity.ethereum/chains/ethereum/db/*/*/db/LOG \
	| perl -p -e 's#^.*total_output_size.: ([0-9]+),.*$#out $1#, s#^.*input_data_size.: ([0-9]+)\}.*$#in $1#' \
	| awk 'BEGIN {SUM_OUTPUT=SUM_INPUT=INPUTS=OUTPUTS=0}
          $N ~ /^out/ {SUM_OUTPUT+=$2; OUTPUTS+=1;}
          $N ~ /^in/ {SUM_INPUT+=$2; INPUTS+=1;}
          END {print "compaction entries in LOG: "INPUTS" (input), "OUTPUTS" (output)"
               print "disk usage before compression: "SUM_INPUT/1024/1024" MBytes"
               print "disk usage after compression: "SUM_OUTPUT/1024/1024" MBytes\n----"
               print "disk usage reduction: "(SUM_INPUT-SUM_OUTPUT)/1024/1024" MBytes / "(SUM_INPUT-SUM_OUTPUT)/SUM_INPUT*100" %"}'
```
```
compaction entries in LOG: 273 (input), 273 (output)
disk usage before compression: 57023.5 MBytes
disk usage after compression: 51418.4 MBytes
----
disk usage reduction: 5605.04 MBytes / 9.82935 %
```
