### ISSUE TITLE
[light client]: `getTransactionReceipt` returning wrong data

### ISSUE THREAD

**Issue by emilbayes** [openethereum/openethereum#11536]
- **Parity Ethereum version**: 2.7.2
- **Operating system**: MacOS
- **Installation**: Downloaded from github releases
- **Fully synchronized**: no
- **Network**: ropsten
- **Restarted**: no

When running in light mode I get incorrect data for transaction receipts on contract creation.

I run `parity --light --chain ropsten` and do `eth_getTransactionReceipt` on the following tx hash on Ropsten: https://ropsten.etherscan.io/tx/0xe95f1615d85378ecd95298461130125833260577421a9313d6ce975643c5f2f9

Here's what Parity reports:

```
{
  blockHash: '0xbc492c4cf8a4abf5052361d118999df9fafad99057c747801538b0d1f549fd07',
  blockNumber: '0x719df7',
  contractAddress: null,
  cumulativeGasUsed: '0x52b8ae',
  from: null,
  gasUsed: null,
  logs: [],
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  status: '0x1',
  to: null,
  transactionHash: '0xe95f1615d85378ecd95298461130125833260577421a9313d6ce975643c5f2f9',
  transactionIndex: '0x19'
}
```

As you can see `contractAddress` and `status` are wrong compared to etherscan. The block has 18 confirms at the time of writing

**Comment by emilbayes** [comment]
I just tried the same on `mainnet`/`foundation` for a contract creation and am seeing the same results

**Comment by emilbayes** [comment]
A workaround for now is to wait for the transaction receipt and then looking up the transaction with `getTransactionByHash` and seeing if `creates` is set despite the `status` of the receipt

**Comment by niklasad1** [comment]
@emilbayes 

1.  `contractAddress`, the internal receipt structure doesn't have it so it will always be `None` or `null` when serializing it. Could be fixed by using fetching `RichReceipt` instead of `Receipt`
2. `status == 1`, seems correct to me because `etherscan` shows Success (which is 1). Am I missing something?

Thus, I agree with 1)

**Comment by emilbayes** [comment]
You are right about status, got the states mixed up. I don’t understand the difference between receipt and rich receipt yet, but will look at it. It seems a lot of other confusion about getTransactionReceipt also stems from this difference

**Comment by niklasad1** [comment]
Right, I totally get that I didn't explain them very well but I edited my previous post with some hopefully useful links.

Well, this the annoying part of this is that [interface between light and full node](https://github.com/OpenEthereum/open-ethereum/blob/master/ethcore/light/src/provider.rs#L124) needs to either to be extended or replaced to support `RichReceipts` which requires quite big changes. In other words, the [request](https://github.com/OpenEthereum/open-ethereum/blob/master/ethcore/light/src/on_demand/request.rs#L949-#L965) and [response](https://github.com/OpenEthereum/open-ethereum/blob/master/ethcore/light/src/on_demand/request.rs#L680) types need to be added for `RichReceipt`.

In addition `RichReceipt` also needs to implement `rlp encoding/decoding` to be exchanged over the network.

So, if anyone wants to tackle this task I can mentor.

**Comment by rakita** [comment]
Closing issue due to light client deprecation

**Comment by emilbayes** [comment]
😢
