### ISSUE TITLE
Parity wasm version 

### ISSUE THREAD

**Issue by nagarajmanjunath** [openethereum/openethereum#11545]
- **Parity Ethereum version**: v2.7.2
- **Operating system**:  MacOS
- **Installation**: built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum...
- **Restarted**: yes

Hi, this question is related to general, As I see the parity-wasm using in this project is 0.31 version. But the actual version of the parity-wasm is 0.41 version. May I know is there any specific reason not using the latest parity-wasm version in the project. Is there any plan of deprecating wasm from project

**Comment by dvdplm** [comment]
No, no particular reason as far as I know; it would definitely be good to update open-ethereum to use 0.41 and if you'd like to work on that we might be able to mentor! :)

**Comment by nagarajmanjunath** [comment]
I would like to contribute to it.
