### ISSUE TITLE
Change database path to `openethereum` 

### ISSUE THREAD

**Issue by niklasad1** [openethereum/openethereum#11559]
The current database path on different supported platforms are the following: 
- Linux: `/home/XXX/.local/share/io.parity.ethereum`
- OSX: `/home/XXX/.local/share/io.parity.ethereum`
- Windows: `C:\Users\XXX\AppData\Roaming\Parity\Ethereum\keys`

The occurrences of `parity` shall be replaced with `openethereum`. 

The easiest would just be to change the path(s) in the [dir crate](https://github.com/OpenEthereum/open-ethereum/blob/master/util/dir/src/lib.rs) or rewrite completely

**Comment by eduadiez** [comment]
As we talked in the call the previous week, if we only make a remplace of the occurrences will force every node in the network to manually move the data to the new directory or to synchronized it again.
That is why I think this could have some impact on the network.

**Comment by dvdplm** [comment]
> As we talked in the call the previous week, if we only make a remplace of the occurrences will force every node in the network to manually move the data to the new directory or to synchronized it again.
> That is why I think this could have some impact on the network.

Let's keep existing databases where they are but create new databases under the new path. There's the possibility of users having databases in both locations; in that case the new path should be used.
/cc @vorot93 @denisgranha works for you?

**Comment by denisgranha** [comment]
yeah, I agree with you @dvdplm 

Keep for old data
New path for fresh installs

For more complex scennarios, I think the variable with path is the source of trust

**Comment by rakita** [comment]
I think this is finished.
