### ISSUE TITLE
Failed to auto-update latest ETH price

### ISSUE THREAD

**Issue by KimBev** [openethereum/openethereum#11567]
- **Open Ethereum version**: v2.5.13
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**: yes

Hi, I am getting the following error appear in my logs

```
2020-03-13 02:25:49 UTC tokio-runtime-worker-0 WARN price_info  Failed to auto-update latest ETH price: Fetch(Timeout)
```

My node is a wallet node and is not directly connected to the public internet, instead it is on a private network and connects to a single node (that has public access) to sync the chain.

I am assuming I am getting this error because the node does not have access to the public internet, question is can it get this data from the single node it is syncing with.

Also what is they data actually used for, is it important for fee calculations or such things or is it not really used by anything important?

thanks
Kim

**Comment by de1acr0ix** [comment]
By default it is getting ETH/USD price from https://api.etherscan.io/api?module=stats&action=ethprice. As I know it is primarily used for setting a minimal gas price of tx pool for mining. If you are using the node only for wallet purpose, I guess this does not matter.

**Comment by rakita** [comment]
Closing issue due to its stale state.
