### ISSUE TITLE
Cannot run PARITY from CLI but can from Finder

### ISSUE THREAD

**Issue by mustapha-mond** [openethereum/openethereum#11575]
I installed parity using homebrew / built from source. If I go to the directory where the executable resides "open-ethereum/target/release" and type "parity" I get:

-bash: parity: command not found

If I go to Finder and double click on the file it fires right up. 

I ran chmod 754 on the executable and tried copying to a file with different name so it's not some PATH issue but still no luck.

I need the CLI interface because I want to synch to goerli.

**Comment by niklasad1** [comment]
run `./parity` and it should work if you built it from source.
