### ISSUE TITLE
Replace command line parsing with structopt

### ISSUE THREAD

**Issue by dvdplm** [openethereum/openethereum#11574]
The client has it's own command line parsing facilities that has served us well for a long time but I think the time is ripe to consider replacing it with a well-regarded, well-maintained library such as `structopt`.
As an example of a problematic quirk with the current code we'd like to get rid of, consider https://github.com/openethereum/openethereum/pull/11558/files#r393715863 and the need to update default values in two places.

**Comment by adria0** [comment]
Closing the issue due to its stale state
