### ISSUE TITLE
Parity - where do address keys go when I create a new account

### ISSUE THREAD

**Issue by mustapha-mond** [openethereum/openethereum#11579]
I was unable to find address keys anywhere on my system so I created a new path for keys using:

./parity --keys-path <path>

This created an empty file in the target directory called address_book.json

I then created a new account using:

./parity account new --chain=ropsten

This created a new account but the .json file is still empty.

**Comment by niklasad1** [comment]
Hey, 

The address book is something else not related to your created account.
You can find your generated accounts by either:
1. [JSON RPC allAccountsInfo](https://wiki.parity.io/JSONRPC-parity_accounts-module#parity_allaccountsinfo), it requires parity-accounts RPC API to be enabled
2. You can find your generates accounts in a separate file which starts with `UTC--<date when generated`
