### ISSUE TITLE
Crash on Ubuntu 16.04 Ethereum Classic

### ISSUE THREAD

**Issue by platofff** [openethereum/openethereum#11582]
- **Parity version**: 2.7.2-stable
- **Operating system**: Ubuntu 16.04 amd64 kernel 4.15
- **Installation**: from Snapcraft
- **Fully synchronized**: yes
- **Network**: classic
- **Restarted**: no
I am using Parity for mining Ethereum Classic. Here's my node parameters:
`/snap/bin/parity --base-path=/mnt/ssd/io.parity.ethereum --chain classic --stratum --stratum-interface=0.0.0.0 --stratum-port=8888 --port=30304 --mode active --no-ipc --jsonrpc-interface "0.0.0.0"  --jsonrpc-port 8545 --no-discovery --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --author whatever --cache-size 512 --logging info`
I got a crash after few days of work. Here's a log from systemd: https://dropmefiles.com/ydpth

**Comment by dvdplm** [comment]
Looks like your clocks were off, can you make sure your system is correctly configured to update the clocks frequently enough?
The panic comes from [here](https://github.com/rust-lang/rust/blob/master/src/libstd/time.rs#L263).

**Comment by platofff** [comment]
@dvdplm I didn't install ntpd before. At now there's ntpd service running. I will re-open this issue if Parity will crash again.
