### ISSUE TITLE
Error: This request is not supported because your node is running with state pruning. Run with --pruning=archive.

### ISSUE THREAD

**Issue by GWELL52** [openethereum/openethereum#11594]
call: eth.getBalance("0x61c380e6b913e80ebb8b8bab2406b2ed3c274ead",10086648)

Error: This request is not supported because your node is running with state pruning. Run with --pruning=archive.
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

**Comment by GWELL52** [comment]
version 2.7.2

**Comment by rakita** [comment]
I think this is self-explanatory
