### ISSUE TITLE
[light-client][classic]: Parity doesn't fetch block anymore after sync in the beginning

### ISSUE THREAD

**Issue by aghamir** [openethereum/openethereum#11591]
- **OpenEthereum version**: Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
- **Operating system**: Linux
- **Installation**: binary
- **Fully synchronized**: no
- **Network**: classic
- **Restarted**: yes

After parity sync in the beginning, it doesn't fetch blocks anymore. Therefore, we need to restart it again.

## How to reproduce this issue
Run parity as below:
```./parity --port=30304 --chain="classic" --light  --no-ws  --jsonrpc-apis='all' --jsonrpc-port=8545```

Wait until it sync. After that no block fetches anymore.

## Expected behavior
Fetch upcoming block after sync

## Actual behavior
Doesn't fetch anymore.

**Comment by rakita** [comment]
Light client and ETC are deprecated
