### ISSUE TITLE
cargo not installed during setup

### ISSUE THREAD

**Issue by noahsalvadordenjo** [openethereum/openethereum#11618]
after cloning the git repository
```
git clone https://github.com/paritytech/parity
```
and running
```
cargo build
```
I get the following error
```
error: 'cargo' is not installed for the toolchain 'stable-x86_64-pc-windows-msvc'
To install, run `rustup component add cargo`
```

**Comment by noahsalvadordenjo** [comment]
after running
```
rustup component add cargo
```
i get
```
info: component 'cargo' for target 'x86_64-pc-windows-msvc' is up to date
```

**Comment by ordian** [comment]
This sounds like a general rust question rather than openethereum specific one, does
`rustup default stable-x86_64-pc-windows-msvc`
if not please ask a question in the rust community https://discordapp.com/invite/rust-lang
