### ISSUE TITLE
Compile error running 'cargo build --release --features final' on Debian 10

### ISSUE THREAD

**Issue by teotikalki** [openethereum/openethereum#11615]
- **OpenEthereum version**: v3.0.0-alpha.1
- **Operating system**: Linux / Debian 10 (Proxmox VM)
- **Installation**: built from source

Error building from source.
- Installed clang-0 from apt.llvm.org/buster
- Installed rust with rustup
- Installed other listed dependencies with apt
- git clone https://github.com/openethereum/openethereum

Running 'cargo build --release --features final' got to
`Building 535/538: parity-rpc, openethereum`
and then exited with this very long error:

https://gist.github.com/teotikalki/150d1841a79348ea987e4879381b63fe

**Comment by ordian** [comment]
You probably ran out of memory while building the client, for `--release` build we're using LTO, which is memory hungry, so 16GB or RAM could be required.

**Comment by dvdplm** [comment]
If you want to turn off LTO you can override the setting by setting the `RUSTFLAGS` env var to `-C lto=off`.

**Comment by teotikalki** [comment]
Thank you both; I should have come back here yesterday before I fell asleep to report that it was indeed a memory error. In the end I got it to work with 4GB allocated to the VM.

**Comment by teotikalki** [comment]
One it was all done, I got an 'Illegal Instruction' error which I believe is https://github.com/openethereum/openethereum/issues/11390 since I'm using an old xeon (X3430). @dvdplm mentioned in that issue that rustc could be run with the proper flags to build without aesni. Could you/someone else please provide instructions for doing so? Your mention of `RUSTFLAGS` made me think of it, since (not being a rust person) that seems like where I might want something like `-C aesni=off`.
