### ISSUE TITLE
parity accounts

### ISSUE THREAD

**Issue by puffanddmx** [openethereum/openethereum#11622]
The address created by the ./parity account new command will be queried when searching for the next parity_allAccountsInfo rpc on privatechain. However, if you send money to an individual address created using the Ethereum library rather than the address created through the above individually, it will not be searched when viewed with parity_allAccountsInfo. It is not retrieved by parity_allAccountsInfo, but getbalance is visible. How to solve it to see all addresses using rpc parity_allAccountsInfo?

**Comment by adria0** [comment]
The `parity_allAccountsInfo` functionality is to retrieve _all personal accounts_  in parity, so which ones it has the private key of them. At this moment there's no direct way to retrieve all existing accounts via JSON-RPC, think that there are 93M and growing up unique accounts at this moment.

**Comment by puffanddmx** [comment]
thanks
