### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by CryptoGravity** [openethereum/openethereum#11638]
Thread 'fetch' panicked at 'cannot access native cert store: Custom { kind: InvalidData, error: BadDER }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-rustls-0.18.0\src\connector.rs:29

**Comment by adria0** [comment]
@CryptoGravity, please **provide the following information**._

- **OpenEthereum version**: 0.0.0
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / goerli / ...
- **Restarted**: no / yes
- **Steps to reproduce (if applicable)**

**Comment by niklasad1** [comment]
Closing as duplicated of #11515
