### ISSUE TITLE
error when trying to install ethcore-network

### ISSUE THREAD

**Issue by decanus** [openethereum/openethereum#11631]
I am trying to depend on `ethcore-network` in a project of mine. I've done this exactly how it is done in the [openethereum/whisper](https://github.com/openethereum/whisper) cargo file. As seen:

```toml
[dependencies]
ethcore-network = { git = "https://github.com/openethereum/openethereum.git" }
```

However, when I cargo install it fails with the following error:

```console
  Updating git repository `https://github.com/openethereum/openethereum.git`
error: failed to load source for a dependency on `ethcore-network`

Caused by:
  Unable to update https://github.com/openethereum/openethereum.git

Caused by:
  failed to update submodule `ethcore/res/ethereum/tests`

Caused by:
  object not found - no match for id (06acfb48aee71ecb57a9ca991cf0f57b630e3469); class=Odb (9); code=NotFound (-3)

```

This is weird because it fails even though that git commit exists on the repository see: https://github.com/ethereum/tests/tree/06acfb48aee71ecb57a9ca991cf0f57b630e3469

When going into the cargo itself, and adding the git submodule it still fails.

**Comment by ordian** [comment]
It seems that cargo does a shallow clone for git dependencies and doesn't checkout the submodules recusively. Maybe there is a setting in cargo to do that?

**Comment by decanus** [comment]
¯\_(ツ)_/¯

**Comment by tomaka** [comment]
When doing this:

```
cd ~/.cargo/git/checkouts/openethereum-73b1d27a6fe08245/4b5e9dd/
git submodule update
```

I get:

```
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Fetched in submodule path 'ethcore/res/ethereum/tests', but it did not contain 06acfb48aee71ecb57a9ca991cf0f57b630e3469. Direct fetching of that commit failed.
```

> It seems that cargo does a shallow clone for git dependencies and doesn't checkout the submodules recusively. Maybe there is a setting in cargo to do that?

It seems that the cloned repo is not shallow.
When doing `git fetch --unshallow` in `~/.cargo/git/checkouts/openethereum-73b1d27a6fe08245/4b5e9dd/` I get:

```
fatal: --unshallow on a complete repository does not make sense
```

**Comment by tomaka** [comment]
Ah, doing `git submodule sync` in the cloned repo fixes it.

**Comment by ordian** [comment]
Can confirm that
```
cd .cargo/git/checkouts/openethereum-73b1d27a6fe08245/4b5e9dd
git submodule update --init --recursive
```
fixes the error for me, but it's obviously shouldn't be done manually.

**Comment by ordian** [comment]
Closing the issue as it's not something that is specific to openethereum client, but rather should be reported here https://github.com/rust-lang/cargo/issues.

**Comment by Rizato** [comment]
It looks like the commit openethereum uses, `06acfb48aee71ecb57a9ca991cf0f57b630e3469` is not part of the ethereum/tests git anymore. 

It is still searchable in github, but you can't clone it since there is no branch with it anymore.
