### ISSUE TITLE
[question] about parity-ether

### ISSUE THREAD

**Issue by puffanddmx** [openethereum/openethereum#11655]
There are three questions.
The first is using the main chain as a parity-ether poa. Can you bring specific data to the parity-ether main chain later by interworking with the substrate?

The second is to operate the node on the parity-ether poa, but there is no gas fee for system call coin transfer. I would appreciate it if you could tell me the location of the code to know how to avoid the gas fee even when using the contract.

The third is that when using the parity-ether poa, the first validator is fixed. However, it is possible to add a validator without recreating genesis during node operation. Is this possible? Also, I know that block rewards are set in the early stages, but I would also like to ask if I can change the rewards during node operation using a half-life.

**Comment by adria0** [comment]
> The first is using the main chain as a parity-ether poa. Can you bring specific data to the parity-ether main chain later by interworking with the substrate?

I think that is better if you ask this question to the parity substrate forums
 
> The second is to operate the node on the parity-ether poa, but there is no gas fee for system call coin transfer. I would appreciate it if you could tell me the location of the code to know how to avoid the gas fee even when using the contract.

Modifying the source code is a complex task, what about setting the gas price to zero?

```
    --min-gas-price=[STRING]
        Minimum amount of Wei per GAS to be paid for a
        transaction to be accepted for mining. Overrides --usd
        -per-tx.
``` 
> The third is that when using the parity-ether poa, the first validator is fixed. However, it is possible to add a validator without recreating genesis during node operation. Is this possible? Also, I know that block rewards are set in the early stages, but I would also like to ask if I can change the rewards during node operation using a half-life.

Parity-ethereum supports different PoA engines, which are you referring to?

**Comment by puffanddmx** [comment]
[2]Modifying the source code is a complex task, what about setting the gas price to zero?
-> Does this setting make gas fee 0 when deploying / transfering smart contracts?

[3] Parity-ethereum supports different PoA engines, which are you referring to?
-> https://github.com/openethereum/wiki/blob/master/Demo-PoA-tutorial.md [Proof of Authority]
->I referenced the link above. If you create genesis by setting the validators part in the link above, it works. However, if you want to add validators in the middle, it is difficult to regenerate genesis. Is there any way to solve this? In other words, is there a way to add validators without generating genesis in the middle? To do that, you would have to change the chain specs of all miners, is this possible?

**Comment by adria0** [comment]
[2] afaik, yes. It allows the sender to set a gas price to zero.
[3] I think that the only way to have a dynamic set of validators is doing it with https://github.com/openethereum/wiki/blob/master/Aura.md. There is also clique but I do not know if there’s a way to propose validators with this engine.

@dvdplm, please, is this ok?

**Comment by dvdplm** [comment]
Right, Aura has this feature but I have to admit I'm hazy on the details on how to add/remove validators. Maybe @varasev can help?

**Comment by varasev** [comment]
3.1) If you don't use a ValidatorSet contract, the validator set is defined in the `list` spec option. For example, in Kovan: https://github.com/poanetwork/poa-chain-spec/blob/906484af924ad31e518415c021f0a24e88fd1793/spec.json#L11-L23

To add/remove validators in this case, you need to specify a block number for transition to the new set of validators. E.g., most of validators were removed on block `10960440` in Kovan: https://github.com/poanetwork/poa-chain-spec/blob/906484af924ad31e518415c021f0a24e88fd1793/spec.json#L24-L30

The spec file, of course, needs to be updated on all validator nodes.

3.2) If you use ValidatorSet contract (like in [POA Core](https://github.com/poanetwork/poa-chain-spec/blob/c75764159b91fd3743de28274b0d3122146bf79e/spec.json#L18-L20)), in order to change validator set the contract needs to emit the `InitiateChange` event with the new set of validators:  https://github.com/openethereum/wiki/blob/master/Validator-Set.md

See also the tutorial https://github.com/openethereum/wiki/blob/master/Validator-Set-Tutorial-Overview.md

**Comment by puffanddmx** [comment]
3.1)
Then, even after a long time after genesis is created, do you mean that if you set validators for a block in the spec.json file and run it again, new validators are set without deleting the existing blocks?
Or is it necessary to get the block again from the beginning?

**Comment by varasev** [comment]
Yes, you don't need to reset the chain.

**Comment by puffanddmx** [comment]
Just one more question, in the link you sent, there are a lot of params eips. Well, we just need to get what we want, but more than that, are there any documents that contain details about what these eips must add at runtime? Because it is not a situation where every person can know all the eips, it would be more helpful for the person who uses the parity to provide additional eips.

**Comment by puffanddmx** [comment]
thanks!
