### ISSUE TITLE
i want get pairty ,Why not download

### ISSUE THREAD

**Issue by anyluckwell** [openethereum/openethereum#11652]
want get pairty ,Why not download

**Comment by kepikoi** [comment]
I think what he is trying to say is this:
```bash
atlas@vmss-parity-1:~$ ./update-parity.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: get.parity.io
atlas@vmss-parity-1:~$ ping get.parity.io
ping: get.parity.io: No address associated with hostname
```

Seems like get.parity.io is down. Cannot install or update parity

**Comment by dvdplm** [comment]
Yes, the `get.parity.io` service has been shut off and is no longer available. 
You can download release binaries from https://github.com/openethereum/openethereum/releases

**Comment by kepikoi** [comment]
Got it. Came here from https://wiki.parity.io/Setup thus the get.parity.io reference

**Comment by dvdplm** [comment]
Yeah, not ideal, apologies for the hassle. :/

**Comment by anyluckwell** [comment]
Yes, I downloaded the old version
