### ISSUE TITLE
Can't run OpenEthereum on macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by varasev** [openethereum/openethereum#11666]
- **OpenEthereum version**: 3.0.0-alpha.1
- **Operating system**: macOS High Sierra 10.13.6
- **Installation**: copied from [releases page](https://github.com/openethereum/openethereum/releases/tag/v3.0.0-alpha.1)

I tried to download and run the binary from https://github.com/openethereum/openethereum/releases/download/v3.0.0-alpha.1/openethereum-v3.0.0-alpha.1-macos.zip on my Mac, but encounter the following error:

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/vadim/Downloads/openethereum-v3.0.0-alpha.1-macos/./openethereum (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/vadim/Downloads/openethereum-v3.0.0-alpha.1-macos/./openethereum (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

Seems this binary is incompatible with macOS prior to 10.15. Is it possible to include a binary supporting macOS >=10.13 to the Release page?

**Comment by ordian** [comment]
The binaries are produced using github actions
https://github.com/openethereum/openethereum/blob/748a8e384d06b7c963b34456b0bd04e5d02bba29/.github/workflows/build.yml#L17
only 10.15 version of macOS seem to be supported https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners

**Comment by varasev** [comment]
Got it. I will try to build it myself, thanks for the info.

**Comment by dvdplm** [comment]
Hmm, @ordian I think `macOS-10.14` should work too ([this](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) is the list of images I think, and [this](https://github.com/microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md) lists the packages included.

@denisgranha do you think we can try with `macOS-10.14` too?

**Comment by dvdplm** [comment]
> but I'm not sure that github actions provide the same options

You are correct: https://github.com/actions/virtual-environments/issues/78 :/

**Comment by dvdplm** [comment]
K, so digging around it seems like this miiight be fixable by building/linking with XCode v10.3 (instead of v11) but tbh I'm not sure it's worth the hassle. Definitely something worth mentioning in the release notes though.

**Comment by denisgranha** [comment]
Hi! Mac made a big break change with the catalina release. With github actions the only build is for 10.15 and they don’t support previous versions.

Travis does have support for older macos versions but I’m not sure if it’s worth maintaining those versions?

It’s good to know it’s not working for <10.15 though for proper release notes

**Comment by denisgranha** [comment]
@varasev do you have some concern about using the last Mac OS version?

**Comment by varasev** [comment]
Np, I managed to build the binary manually with the latest Rust on macOS 10.13. I'll probably upgrade to Catalina.

**Comment by denisgranha** [comment]
Awesome, thanks for letting us know @varasev
