### ISSUE TITLE
Where to download to Wallet?

### ISSUE THREAD

**Issue by t2dk49580** [openethereum/openethereum#11665]
Where can I download the full version of your wallet? There is no download address on the official website. I don't want the light version. I want the full version

**Comment by adria0** [comment]
With `wallet` are you referring to a graphical user interface to interact with accounts?

**Comment by t2dk49580** [comment]
@adria0 yes

**Comment by adria0** [comment]
The GUI Wallet was removed in 2.x, see https://www.parity.io/parity-ethereum-2-0 
There are no plans for adding this functionality again.
