### ISSUE TITLE
The old Parity documentation is not available

### ISSUE THREAD

**Issue by mr-older** [openethereum/openethereum#11670]
There is a link to a well-documented Parity methods, [https://wiki.parity.io/](https://wiki.parity.io/), but it isn`t available nowdays.

Where this documentation could be found?

**Comment by yozx** [comment]
yeah, currenly using lastest snapshot from weybackmachine
https://web.archive.org/web/*/https://wiki.parity.io/

**Comment by yozx** [comment]
> There is a link to a well-documented Parity methods, https://wiki.parity.io/, but it isn`t available nowdays.
> 
> Where this documentation could be found?

Site is up

**Comment by dvdplm** [comment]
New URL for the documentation wiki is: https://openethereum.github.io/wiki/ (wiki.parity.io redirects here).
