### ISSUE TITLE
Aggressive eth_getBlockByNumber stuck on reorg

### ISSUE THREAD

**Issue by emilbayes** [openethereum/openethereum#11674]
- **OpenEthereum version**: 2.7.2
- **Operating system**: MacOS / Linux
- **Installation**: Download from GitHub releases
- **Fully synchronized**: no (light client)
- **Network**: ethereum / ropsten
- **Restarted**: N/A

When aggressively fetching block number and then fetching the associated block after, parity often gets stuck when a reorg happens of the block fetched. It is somewhat reliably reproducible and from parity's output we can see that it keeps sync'ing the new blocks with the highetst cumulative pow, but `eth_blockNumber()` keeps returning the same. I tried looking for similar issues but didn't find any

**Comment by vorot93** [comment]
OpenEthereum v3.0.0 has been released, and it deprecates the light client. Can you reproduce this issue with 3.0.0 full node?

**Comment by emilbayes** [comment]
I'm pretty confident this is #11758. Closing in favour of that issue
