### ISSUE TITLE
Parity often sync failed. It recover when I restart parity.

### ISSUE THREAD

**Issue by garysdevil** [openethereum/openethereum#11683]
- **OpenEthereum version**: Parity-Ethereum/v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0
- **Operating system**: Linux
- **Installation**: one-line installer 
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes
My config: 
![图片](https://user-images.githubusercontent.com/41293784/81133266-a92ce180-8f83-11ea-83c8-029f6cd3b373.png)

Problem: Sync failed.
Phenomenon：
![图片](https://user-images.githubusercontent.com/41293784/81132961-c1503100-8f82-11ea-9eff-1a4fef677e0b.png)

Recovery method: I need to restart parity every time it stop sync.
I need to restart parity for recovery every time I found it sync failed, which disturb me..
How to solve this question? And why happend this?

**Comment by vorot93** [comment]
Can you back up the database and try to sync with 2.7.2? And with master?

**Comment by garysdevil** [comment]
>  2.7.2

I feel puzzled at this reply "try to sync with 2.7.2? And with master?".
I don't know how to operate it, can you say it detailly?

**Comment by garysdevil** [comment]
> 
> 
> Can you back up the database and try to sync with 2.7.2? And with master?

I feel puzzled at this reply "try to sync with 2.7.2? And with master?".
I don't know how to operate it, can you say it detailly?

**Comment by vorot93** [comment]
Download Parity-Ethereum 2.7.2 and try again with this version.

If the error persists, build the source code from the master branch, and try running it instead.

**Comment by garysdevil** [comment]
> 
> 
> Download Parity-Ethereum 2.7.2 and try again with this version.
> 
> If the error persists, build the source code from the master branch, and try running it instead.

Thank you. I update parity version to 2.7.2 directly and still use old db. Is it work?

**Comment by garysdevil** [comment]
> 
> 
> Download Parity-Ethereum 2.7.2 and try again with this version.
> 
> If the error persists, build the source code from the master branch, and try running it instead.

Thank you. I update parity version to 2.7.2 directly and still use old db. Is it work?
It is output log below:
![图片](https://user-images.githubusercontent.com/41293784/81557968-7178cc00-93bf-11ea-9abc-779811b3bd0c.png)

**Comment by vorot93** [comment]
OpenEthereum v3.0.0 has been released, try with it as well.

**Comment by garysdevil** [comment]
> 
> 
> OpenEthereum v3.0.0 has been released, try with it as well.

I will try it lately.

**Comment by garysdevil** [comment]
> 
> 
> OpenEthereum v3.0.0 has been released, try with it as well.

I will try it lately.
I deployed parity 2.7.2 completely yesterday, which sync normally .
Howere "Not preparing block; cannot sign." occure again torday! 

![图片](https://user-images.githubusercontent.com/41293784/81798105-36eb6c80-9542-11ea-91ab-75b10a8d1878.png)
![图片](https://user-images.githubusercontent.com/41293784/81798122-3d79e400-9542-11ea-87eb-0377b82fbfdd.png)

**Comment by dvdplm** [comment]
> "Not preparing block; cannot sign."

This just means that you are not a validator and you are not producing blocks. It's not an error.

**Comment by adria0** [comment]
@dvdplm, the `Not preparing block; cannot sign.` is a `warn!`, is sane to we downgrade this to `debug!` or `trace!`?"

**Comment by dvdplm** [comment]
> is sane to we downgrade this to `debug!` or `trace!`?"

Yeah, let's do that. :)

**Comment by garysdevil** [comment]
> 
> 
> > "Not preparing block; cannot sign."
> 
> This just means that you are not a validator and you are not producing blocks. It's not an error.

Thank you.
Howere, it is still sync slow than "https://kovan.etherscan.io/blocks" 
The last sync log:
2020-05-14 07:39:26  Imported #18512828 0x473a…8b32 (4 txs, 0.16 Mgas, 546 ms, 1.16 KiB) + another 4 block(s) containing 59 tx(s)
It stop sync again:
![图片](https://user-images.githubusercontent.com/41293784/81878385-735aaf00-95ba-11ea-9054-63c1fe8156fb.png)

https://kovan.etherscan.io/blocks: 18513164

**Comment by garysdevil** [comment]
> 
> 
> @dvdplm, the `Not preparing block; cannot sign.` is a `warn!`, is sane to we downgrade this to `debug!` or `trace!`?"

Why not judge that this warning is only displayed when it is vaidator?

**Comment by garysdevil** [comment]
> 
> 
> @dvdplm, the `Not preparing block; cannot sign.` is a `warn!`, is sane to we downgrade this to `debug!` or `trace!`?"

Why not this warning is only displayed when it is vaidator?

**Comment by kael-shipman** [comment]
Cross-referencing potentially related issues:

* #11793 
* #11758 
* #11737

**Comment by vorot93** [comment]
Looks like #11758.
