### ISSUE TITLE
Parity v2.7.2 - Illegal instruction: 4

### ISSUE THREAD

**Issue by ronix73** [openethereum/openethereum#11685]
- Parity Ethereum version: 2.7.2
- Operating system: MacOS High Sierra
- Installation: homebrew
- Fully synchronized: no
- Network: ethereum
- Restarted: yes

After update I got error Illegal instruction: 4
I removed everything (parity db kill, brew uninstall parity ... ) and trying to fresh start but same issue. 
Any help appreciated!

```
2020-05-06 17:53:14  Starting Parity-Ethereum/v2.7.2-stable-d961010f63-20200205/x86_64-apple-darwin/rustc1.41.0
2020-05-06 17:53:14  Keys path <keys path>
2020-05-06 17:53:14  DB path <db path>
2020-05-06 17:53:14  State DB configuration: fast
2020-05-06 17:53:14  Operating mode: active
2020-05-06 17:53:14  Configured for Ethereum using Ethash engine
2020-05-06 17:53:15  Removed existing file '/Users/name/Library/Application Support/io.parity.ethereum/jsonrpc.ipc'.
2020-05-06 17:53:15  Updated conversion rate to Ξ1 = US$207.89 (22905886 wei/gas)
Illegal instruction: 4
```

**Comment by dvdplm** [comment]
What is the output of `sysctl -n machdep.cpu.brand_string`?

**Comment by dvdplm** [comment]
I suspect this is caused by the binary being compiled for MacOS Mojave, 10.14 and it is likely incompatible with High Sierra. 
To prove this hypothesis you could compile it yourself from source (I do not have access to a High Sierra machine or I'd try it myself).

**Comment by ronix73** [comment]
> What is the output of `sysctl -n machdep.cpu.brand_string`?
```
sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz
```

**Comment by ronix73** [comment]
> I suspect this is caused by the binary being compiled for MacOS Mojave, 10.14 and it is likely incompatible with High Sierra.
> To prove this hypothesis you could compile it yourself from source (I do not have access to a High Sierra machine or I'd try it myself).

I think so, since I have another machine with MacOS Mojave and run 2.7.2 without issues. How to compile it myself from source? Is there something to read about it?

**Comment by ronix73** [comment]
I tried with:
```
git clone https://github.com/paritytech/parity
cd parity
cargo build --release
```
but I got error

```
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
warning: unused manifest key: dependencies.ethtrie.package
...
warning: unused manifest key: package.edition
warning: unused manifest key: dependencies.call-contract.package
warning: unused manifest key: dependencies.types.package
warning: unused manifest key: package.edition
warning: unused manifest key: package.edition
error: failed to parse lock file at: /Users/user/parity/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

**Comment by dvdplm** [comment]
So the repo is at https://github.com/openethereum/openethereum.git (this repo); it looks like your rust version is outdated, check out https://www.rust-lang.org/ for installation instructions.

**Comment by ronix73** [comment]
I updated rust but seems I got same problem ...
```
$ git clone https://github.com/openethereum/openethereum
$ cd openethereum
$ cargo build --release --features final
```
```
   Compiling libc v0.2.68
   Compiling cfg-if v0.1.10
   Compiling autocfg v1.0.0
   Compiling spin v0.5.2
   Compiling proc-macro2 v1.0.9
   ...
   Compiling cli-signer v1.4.0 (/Users/user/openethereum/cli-signer)
   Compiling openethereum v3.0.0 (/Users/user/openethereum)
    Finished release [optimized] target(s) in 51m 28s
```
and when I want to start OpenEthereum manually...
```
$ ./target/release/openethereum
Illegal instruction: 4
```

**Comment by ronix73** [comment]
Even if I trying to open it manually I got: 

> You can’t open the application “openethereum.service.app” because it is not supported on this type of Mac.
![Screen Shot 2020-05-07 at 17 30 57](https://user-images.githubusercontent.com/34712087/81307197-12e2e380-9089-11ea-92de-c72a0c0c9f21.png)

**Comment by dvdplm** [comment]
I don't know what `openethereum.service.app` is or how you obtained it, but it is not part of the openethereum distribution.

**Comment by ronix73** [comment]
> I don't know what `openethereum.service.app` is or how you obtained it, but it is not part of the openethereum distribution.

After compile from source app can be found in `openethereum/script/` folder. Anyway seems like is not suported on MacOS High Sierra.

**Comment by adria0** [comment]
Closing the issue due to its stale state
