### ISSUE TITLE
Unable to sync Kovan network using warp/snapshot

### ISSUE THREAD

**Issue by jesinspirment** [openethereum/openethereum#11691]
- **OpenEthereum version**: Parity-Ethereum/v2.7.2-stable-d961010f63-20200205/x86_64-apple-darwin/rustc1.41.0
- **Operating system**: MacOS
- **Installation**: homebrew
- **Fully synchronized**: no
- **Network**: kovan
- **Restarted**: yes

Over the past week, I have been trying to sync Kovan network on my Macbook Pro with SSD. I am consistently getting a stage 5 block verification failed error. The block numbers which failed aren't fixed, but I just cannot get it to sync properly. Have tried to delete nodes.json, doesn't work. Restart parity, doesn't work.

Anyway to resolve this? I'm now trying to sync without warp. But I'm sure there is a proper solution for warp.

2020-05-08 09:28:38  Stage 5 block verification failed for #18405004 (0xb646…be1e)
Error: Block(InvalidStateRoot(Mismatch { expected: 0x70f051af6f84d82ad6545d410d1929728978a49993a05219aa130c5ff85baa05, found: 0x309af692175dad46add449e51c004eb6b129a8f6069f5062cbc30edf921a54d7 }))
2020-05-08 09:28:38
Bad block detected: Block(InvalidStateRoot(Mismatch { expected: 0x70f051af6f84d82ad6545d410d1929728978a49993a05219aa130c5ff85baa05, found: 0x309af692175dad46add449e51c004eb6b129a8f6069f5062cbc30edf921a54d7 }))
RLP: f9041ef90248a0a40937ea755e2858400ac4da67ef40453c011fd8ae0e59ca0e026663902ef54ca01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794a4df255ecf08bbf2c28055c65225c9a9847abd94a070f051af6f84d82ad6545d410d1929728978a49993a05219aa130c5ff85baa05a00bf38b99872a02ff27edd27678f4f740b6b0655f1d3f7cbc589a5402da477434a0113bc93e162daaf462dc903038a7e992541cc764f7ef9fa8b54e00ee8cd3ff53b901000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000090fffffffffffffffffffffffffffffffd840118d68c8398968083012a9a845eb434ac9fde830207028f5061726974792d457468657265756d86312e34312e30826c698417ad0d2bb841b1553c902829613361954db6806e9ab8b17a17d4fafb97c1a234118632d595a5700ddd0f761817e7dbc241e76704b8d83c2b85cfb19be0bcaf9d0d329767678c01f901cff901cc826157843b9aca008301996e94741a4dcad4f72b83be9103a383911d78362611cf80b90164a8f0802e000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000060b2abfdfad9c0873242f59f2a8c32a3cc682f80000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000040b274f2e0000000000000000000000000000000000000000000000000000000078a04a30e4eb123cc0beeb6cee9b20a56680c161d2bd964644f7f285f70865d98429a04116a51c90c376517a17336d22094719ee97f7dd5c79f49656eb62f80e5e5610c0
Header: Header { parent_hash: 0xa40937ea755e2858400ac4da67ef40453c011fd8ae0e59ca0e026663902ef54c, timestamp: 1588868268, number: 18405004, author: 0xa4df255ecf08bbf2c28055c65225c9a9847abd94, transactions_root: 0x0bf38b99872a02ff27edd27678f4f740b6b0655f1d3f7cbc589a5402da477434, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [222, 131, 2, 7, 2, 143, 80, 97, 114, 105, 116, 121, 45, 69, 116, 104, 101, 114, 101, 117, 109, 134, 49, 46, 52, 49, 46, 48, 130, 108, 105], state_root: 0x70f051af6f84d82ad6545d410d1929728978a49993a05219aa130c5ff85baa05, receipts_root: 0x113bc93e162daaf462dc903038a7e992541cc764f7ef9fa8b54e00ee8cd3ff53, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 76442, gas_limit: 10000000, difficulty: 340282366920938463463374607431768211453, seal: [[132, 23, 173, 13, 43], [184, 65, 177, 85, 60, 144, 40, 41, 97, 51, 97, 149, 77, 182, 128, 110, 154, 184, 177, 122, 23, 212, 250, 251, 151, 193, 162, 52, 17, 134, 50, 213, 149, 165, 112, 13, 221, 15, 118, 24, 23, 231, 219, 194, 65, 231, 103, 4, 184, 216, 60, 43, 133, 207, 177, 155, 224, 188, 175, 157, 13, 50, 151, 103, 103, 140, 1]], hash: Some(0xb646a1144bfa7177ffd6a0f13f6c19a8e71dccdfc96a580a2aa2cf0ba371be1e) }
Uncles:
Transactions:[Tx 0] UnverifiedTransaction { unsigned: Transaction { nonce: 24919, gas_price: 1000000000, gas: 104814, action: Call(0x741a4dcad4f72b83be9103a383911d78362611cf), value: 0, data: [168, 240, 128, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 224, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 178, 171, 253, 250, 217, 192, 135, 50, 66, 245, 159, 42, 140, 50, 163, 204, 104, 47, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 11, 39, 79, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, v: 120, r: 33557539389946223765310164757639227483232822932554078503869648239373804209193, s: 29440345351608545300329504247974690827588507259517488286741061001857034245648, hash: 0x09d4a0fb03be5356523f3ab6731bc689d8f47d9c7acb8c701cf212af4dfe51ff }

**Comment by vorot93** [comment]
Could you please try building and running the latest `master`?

**Comment by dvdplm** [comment]
FWIW I synced Kovan from genesis yesterday with a recent master.

**Comment by jesinspirment** [comment]
> FWIW I synced Kovan from genesis yesterday with a recent master.

Did you sync with or without warp? I'm currently syncing without warp on 2.7.2, so far seems good, now I'm close to full sync.

**Comment by rakita** [comment]
Seems resolved
