### ISSUE TITLE
Thread 'IO Worker #3' panicked at 'DB flush failed.

### ISSUE THREAD

**Issue by Conviley** [openethereum/openethereum#11692]
- **OpenEthereum version**: v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
- **Operating system**: Windows
- **Installation**: Docker
- **Fully synchronized**: No
- **Network**: Ropsten
- **Restarted**: Yes

I set up a docker container with parity using the following commands
```
docker pull parity/parity:stable
docker run --name eth -p 8546:8546 \
           -v ~/.parity-ropsten:/home/parity/.local/share/io.parity.ethereum/ \
           -it parity/parity:stable --chain=ropsten \
           --ws-interface=all --ws-origins="all" \
           --base-path /home/parity/.local/share/io.parity.ethereum/
```
and i am attempting to sync to the ropsten network. During my syncing process i have had it say `Encountered error during snapshot resotration: std Io error: No space left on device (os error 28)`
Even though i have plenty of space left on my computer and and the docker container has more than 20GB of space left as showed by the resource tab. This error showed up at around 1300-1700/4257 snapshots synced. At those times i have just restarted the container and now it seems to do a regular sync whereupon i received the following error

```
Thread 'IO Worker #3' panicked at 'DB flush failed.: Custom { kind: Other, error: Error { message: "IO error: No space left on deviceWhile appending to file: C:/Program   
Files/Git/home/parity/.local/share/io.parity.ethereum//chains/ropsten/db/ae90623718e47d66/overlayrecent/db/041159.log: No space left on device" } }', src/libcore/result.rs:1188
This is a bug. Please report it at:
    https://github.com/paritytech/parity-ethereum/issues/new
```
So as it requested i'm reporting this bug.  Again i have plenty of space left and when i restart the container it picks up where it left off.
**Note:** The URL it asks you to report the issue on needs updating
**Another Note:**
I've also received this error a couple of times
```
Panic occurred, see stderr for details
   0:     0x561cc4ba3a0d - <no info>
   1:     0x561cc5361147 - <no info>
   2:     0x561cc4ab6498 - <no info>
   3:     0x561cc5e5a1db - <no info>
   4:     0x561cc5e59f76 - <no info>
   5:     0x561cc4c54845 - <no info>
   6:     0x561cc4c5b145 - <no info>
   7:     0x561cc4dcfa13 - <no info>
   8:     0x561cc5022671 - <no info>
   9:     0x561cc5049bd4 - <no info>
  10:     0x561cc504bb6a - <no info>
  11:     0x561cc5047ad9 - <no info>
  12:     0x561cc50266c5 - <no info>
  13:     0x561cc5e73d2e - <no info>
  14:     0x561cc5e76abf - <no info>
  15:     0x7fd30074e6b9 - <no info>
  16:     0x7fd2ffe6241c - <no info>
Error grabbing logs: unexpected EOF
```
Currently on block `#7766041` and i think this error started showing up around 7.7mil blocks synced.

**Comment by dvdplm** [comment]
> No space left on device

The error is pretty unequivocal; I'm not sure there's anything to do other than increasing the available space. Note that the database sometimes need to compact the level files which means it can temporarily use more disk space; looking at the available space after the crash is not a good way to check that.
So please free up some space and try again.

> Another Note: The URL it asks you to report the issue on needs updating

Good catch!

**Comment by Conviley** [comment]
@dvdplm Thanks! Oh okay if i get that error again i can try bumping up the resources for my container.
I updated my post adding in an error that **is** the error that i started getting after like 7.7Mil blocks and that i have received a couple of times. The Error that it asked me to report i have only received once
