### ISSUE TITLE
How to config something in openethereum  v3.0.0  like parity config.toml ?

### ISSUE THREAD

**Issue by heimi-block** [openethereum/openethereum#11704]
![image](https://user-images.githubusercontent.com/22029390/81715996-71ee9100-94ab-11ea-9f6d-7a3f1c5d2b5a.png)
I'm running openethereum with command ./target/release/openethereum

**Comment by heimi-block** [comment]
![image](https://user-images.githubusercontent.com/22029390/81715996-71ee9100-94ab-11ea-9f6d-7a3f1c5d2b5a.png)
I'm running openethereum with command ./target/release/openethereum

**Comment by dvdplm** [comment]
Or put differently: nothing changed as far as configuring your node. :)

**Comment by heimi-block** [comment]
> Or put differently: nothing changed as far as configuring your node. :)

thanks:
