### ISSUE TITLE
Lost Ethereum

### ISSUE THREAD

**Issue by noahsalvadordenjo** [openethereum/openethereum#11703]
All I Know is that I recieved ether and i could see the balance of 0.05 ether on my node.
I created a new account and.... It's gone (or it was already gone). is this because of the update?
```
0x2097804265948018272362CF4dAf6B5432d52F56
```
version
```
openethereum-v3.0.0-alpha.1-ubuntu-16.04
```

**Comment by adria0** [comment]
Hi @noahsalvadordenjo, 

Creating a new account does not generate any signed transaction, so this is not technically possible.

**Comment by noahsalvadordenjo** [comment]
Im currently at blocknumber: 10022916
https://etherscan.io/address/0x2097804265948018272362CF4dAf6B5432d52F56
and it were there

**Comment by jesinspirment** [comment]
According to etherscan, all your ethers were sent out to another address. It is not possible for an address to lose all ethers just because a new address is generated. Is the original address that has ETH managed by you, or a 3rd party?

**Comment by noahsalvadordenjo** [comment]
this address is hosted by me
0x2097804265948018272362CF4dAf6B5432d52F56
