### ISSUE TITLE
Turn the sealing_state message from warn! to debug!

### ISSUE THREAD

**Issue by adria0** [openethereum/openethereum#11708]
This message is created as a warning but is only useful for troubleshooting. Should be changed from `warn!` to `debug!`

https://github.com/openethereum/openethereum/blob/3ccfe735aa579f89a1f8de192a7625084a6f530f/ethcore/engines/authority-round/src/lib.rs#L1334

**Comment by tomokos2** [comment]
Hello, may I work on this?
