### ISSUE TITLE
There is a Pending txn with a lower account nonce

### ISSUE THREAD

**Issue by mtb-pro** [openethereum/openethereum#11712]
My parity is executed with the following command
parity --tx-queue-size 500000 --tx-queue-mem-limit=0 --tx-queue-per-sender 2000

My trancations are pending for a long time
https://etherscan.io/txsPending?a=0x9ce7456ec06b1457c91bd4619a08dbe8adc926fd&m=hf

error : There is a Pending txn with a lower account nonce. This txn can only be executed after confirmation of the earlie
how to set setting for  send transactions with the same priority?
And I want to use the queue

- **OpenEthereum version**: Parity-Ethereum//v2.5.13-stable-253ff3f-20191231/x86_64-linux-gnu/rustc1.40.0
- **Operating system**: Linux
- **Installation**: linux-gnu
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: no

**Comment by vorot93** [comment]
Please try with OpenEthereum v3.0.0.

**Comment by mtb-pro** [comment]
how to disable  nonce ordering?

**Comment by mtb-pro** [comment]
how to disable nonce ordering?
Transaction with low gasPrice makes all the other transactions hang on the pending state

**Comment by adria0** [comment]
> how to disable nonce ordering?
> Transaction with low gasPrice makes all the other transactions hang on the pending state

@mtb-pro, nonce ordering is part of the core ethereum protocol and cannot be disabled.
