### ISSUE TITLE
Windows CertificateStore

### ISSUE THREAD

**Issue by CryptoGravity** [openethereum/openethereum#11733]
OpenEthereum version : 3.0.0
Operating system : Windows 10
Installation : openethereum-windows-v3.0.0.zip
Fully synchronized : no
Network : ethereum
Restarted : yes

  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart

Thread 'fetch' panicked at 'cannot access native cert store: Custom { kind: InvalidData, error: BadDER }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-rustls-0.18.0\src\connector.rs:29

**Comment by adria0** [comment]
Duplicated of #11515

**Comment by Gdocal** [comment]
@CryptoGravity did yo solve issue?

**Comment by CryptoGravity** [comment]
No, I'm afraid not, I see no clou at all...
Kind regards, CryptoGravity

Op ma 13 jul. 2020 om 14:58 schreef Gdocal <notifications@github.com>:
