### ISSUE TITLE
"infinite loop" test can cause potential denial of service

### ISSUE THREAD

**Issue by BattleBird** [openethereum/openethereum#11739]
when we use a bytecode which contains an "infinite loop" to test the aleth, the aleth will keep running and consume the memory and CPU resources until the out of memory and crash. If we use the crafted bytecode to attack the aleth-vm, is this a kind of denial of service? for example, we use this simple contract as follows,
![Screenshot from 2020-05-31 22-36-52](https://user-images.githubusercontent.com/13298978/83355020-4e728400-a38f-11ea-8857-71f98400b42b.png)

- **OpenEthereum version**: 2.7.2
- **Operating system**: Linux
- **Installation**: built from source

**Comment by adria0** [comment]
@BattleBird, this is the GitHub for OpenEthreum. Please, go to https://github.com/ethereum/aleth/ to report aleth issues.

**Comment by BattleBird** [comment]
sorry，my bad
