### ISSUE TITLE
v3.0.1 release notes has wrong tag and 404 download links

### ISSUE THREAD

**Issue by meowsbits** [openethereum/openethereum#11748]
The download links for [the latest release](https://github.com/openethereum/openethereum/releases/tag/v3.0.1) points to https://github.com/openethereum/openethereum/releases/download/v3.0.0/openethereum-linux-v3.0.1.zip, and the download link is broken (404).

```
> wget https://github.com/openethereum/openethereum/releases/download/v3.0.0/openethereum-linux-v3.0.1.zip
--2020-06-01 13:02:10--  https://github.com/openethereum/openethereum/releases/download/v3.0.0/openethereum-linux-v3.0.1.zip
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-01 13:02:10 ERROR 404: Not Found.
```
This is the case for all OS distributions.

__Note__ that this is only the case for the markdown-rendered links. (__The actual _Assets_ links are functional.__)

![image](https://user-images.githubusercontent.com/45600330/83439177-486cb980-a408-11ea-9ed7-5aa0cd7370d2.png)

**Comment by denisgranha** [comment]
Thank you for reporting it!

In fact binaries where correctly attached but the link in the table was malformed. Human error :see_no_evil: hopefully next release has this step automated

**Comment by meowsbits** [comment]
> Note that this is only the case for the markdown-rendered links. (The actual Assets links are functional.)
👍
