### ISSUE TITLE
eth_sendTransaction for help!

### ISSUE THREAD

**Issue by lz931585538** [openethereum/openethereum#11751]
How can I use the rpc function called "eth_sendTransaction"  or the other rpc function?

**Comment by adria0** [comment]
@lz931585538 You can find information about ethereum JSON-RPCs in https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction

**Comment by lz931585538** [comment]
> @lz931585538 You can find information about ethereum JSON-RPCs in https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction

Yeah! I had already seen this.
But how can I run this command?
I got errors when compiling.


error: failed to run custom build command for `librocksdb-sys v6.6.4`

Caused by:
  process didn't exit successfully: `D:\code\Rust\openethereum-master\target\debug\build\librocksdb-sys-2cf4461ebc7f7d64\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
cargo:warning=couldn't execute `llvm-config --prefix` (error: 系统找不到指定的文件。 (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'clang.dll\', \'libclang.dll\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.53.2\src/lib.rs:1956:13
stack backtrace:

**Comment by lz931585538** [comment]
> n

And now I got this when I installed clang,gcc and cmake.
Microsoft Visual C++ Runtime Library

Assertion failed!

Program:C:\Prigram Files\LLVM\bin\libclang.dll
File:D:\src\llvm_release_build_3.7.0\llvm\tools\cla.../Type.h
Line:5591

Expression:isa<T>(CanonicalType)

For information on how your program can cause an assertion failure,see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enable)

**Comment by wesrer** [comment]
@lz931585538 this seems to be an error with your clang build system, unrelated to openethereum

**Comment by lz931585538** [comment]
> @lz931585538 this seems to be an error with your clang build system, unrelated to openethereum

Yeah , But I do not know how to fix it.
