### ISSUE TITLE
Error: Returned error: Transaction cost exceeds current gas limit. Limit: 5000, got: 1600000. Try decreasing supplied gas

### ISSUE THREAD

**Issue by noahsalvadordenjo** [openethereum/openethereum#11756]
```
        web3.eth.sendTransaction({
            value: 14117982602080,
            from: '0x711E94d7bea1a35D319183AD244B534100Bef8f5',
            to: '0x12AdF37d82D978fD72bfcC95Ca09C0D91Bb4F4d3',
        }).then(console.log)
```
gives me the following error:
```
Error: Returned error: Transaction cost exceeds current gas limit. Limit: 5000, got: 1600000. Try decreasing supplied gas
```
version
```
openethereum-linux-v3.0.1
```
web3 version
```
"web3": "^1.2.8"
```
system ubuntu

**Comment by palkeo** [comment]
I'm not 100% sure, but I think this means that the block gas limit is 5000, so your transaction is too big to fit in any single block.
Are you on mainnet?

**Comment by noahsalvadordenjo** [comment]
yes

**Comment by palkeo** [comment]
Is your node fully synced? What block is it at?

**Comment by noahsalvadordenjo** [comment]
10185104

**Comment by noahsalvadordenjo** [comment]
Its working now

**Comment by noahsalvadordenjo** [comment]
It gives me the error but does send the transaction

**Comment by noahsalvadordenjo** [comment]
It propably gave me the error because i got hacked

**Comment by noahsalvadordenjo** [comment]
Can someone tell me if it is working before i send another 50 worth of ether, the minimum gas for a transaction is 21000

**Comment by palkeo** [comment]
I think if you want assistance you will need to follow the issue template, include all the information that's required and describe your problem in more details.

**Comment by noahsalvadordenjo** [comment]
Where can i find this template and geth is unable to unlock any accounts
