### ISSUE TITLE
Traces to include revert reasons [Feature request]

### ISSUE THREAD

**Issue by k06a** [openethereum/openethereum#11776]
I wonder if revert reason could be included in `Trace`. This would be really handy to see what exactly went wrong inside complex transactions. Seeing events in their proper places also would be helpful.

**Comment by adria0** [comment]
duplicated of https://github.com/openethereum/openethereum/issues/11513

**Comment by k06a** [comment]
@adria0 are you sure? I am talking about transaction traces will tree of external calls.

**Comment by adria0** [comment]
Sorry, let's me explain, I see this feature is a part of the "revert reason awareness" inside OE. I add this feature to the main issue also.
