### ISSUE TITLE
Where to find alternative for account management ?

### ISSUE THREAD

**Issue by winf3** [openethereum/openethereum#11780]
_

- **OpenEthereum version**: 3.0.1
- **Operating system**: Windows 
- **Installation**:  one-line installer 
- **Fully synchronized**: no 
- **Network**: open ethereum 
- **Restarted**: no 

I downloaded the binary for Windows 10 and executed openethereum.exe.
Command Window opened and openethereum started syncing.

When I started the Energy WEB UI, I gave the message "Your node is still syncing ... "
So far so good !

But openethereum now gave the following message:

2020-06-14 15:11:07  eth_accounts is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.

My Questions:
1. Where do I find the alternatives ?
2. Where do I find #9997

**Comment by adria0** [comment]
@winf3, just click in the `#9997` link in your message

**Comment by rakita** [comment]
Seems resolved
