### ISSUE TITLE
Registrar contract contents

### ISSUE THREAD

**Issue by BronacusAmmon** [openethereum/openethereum#11797]
- **Parity version**: 2.7.2
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**:  yes
- **Network**: custom
- **Restarted**:  yes

Im trying to understand a chain.json I found online, the registrar address is used as an account parameter with a constructor, how can I turn the constructor data into an account that I can understand the data?

**Comment by rakita** [comment]
Hi, maybe this link can help you: https://eth.wiki/en/fundamentals/specs/chain-spec-format
This seems to be a question on the custom network and I find it okay to just close it because it is not connected to OE.
