### ISSUE TITLE
Too many transactions in queue

### ISSUE THREAD

**Issue by jesinspirment** [openethereum/openethereum#11798]
- **OpenEthereum version**: 3.0.1
- **Operating system**: Linux
- **Installation**: Downloaded zip file from repository
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

I started OpenEthereum with these parameters:
--tx-queue-size=200000
--tx-queue-per-sender=2000
--cache-size=3072

I was expecting the queue size of 200k to be more than enough, as currently, the number of pending transactions in the network is around 101k. However, despite setting these parameters, I am still occasionally getting this error:

**There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.**

Is there a way to fully eliminate this problem?

**Comment by noahsalvadordenjo** [comment]
I Had the same problem, but when i restarted my node, the error was gone

**Comment by jesinspirment** [comment]
Just for a while. It will eventually come back. This is quite annoying in a production environment, so was hoping there's a way to prevent this.

**Comment by rakita** [comment]
Hello jesinspirment, here is the text that explains why some transactions got dropped, I think it could be helpful: https://openethereum.github.io/wiki/Transactions-Queue

**Comment by or2008** [comment]
have the same issue
```There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.```

happens when I send a new transaction with same nonce, to speed up existing pending transactions.

**Comment by rakita** [comment]
Hello @or2008, maybe this link https://openethereum.github.io/wiki/Transactions-Queue will explain what is happening and why you get that log. This is expected behaviour and not a bug.

**Comment by jesinspirment** [comment]
Understood that it is not exactly a bug. But any way we can prevent this from happening at all?

--tx-queue-size=200000
--tx-queue-per-sender=2000

Other than these 2 flags, anything else I can do? Due to the nature of my projects, it is extremely annoying when this happens.

**Comment by rakita** [comment]
Unfortunately no, this is something that can happen.

**Comment by rakita** [comment]
Seems answered
