### ISSUE TITLE
DB size with tracing on is 414GB, is it normal? 

### ISSUE THREAD

**Issue by or2008** [openethereum/openethereum#11792]
- **OpenEthereum version**: 3.0.1
- **Operating system**: MacOS
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

hello, I am running a fully synced node with tracing on, and I just noticed the chain size is about 414 GB, and If I remember correctly, 2 weeks ago it was 380 GB only, is it normal? is the growth rate normal? I only have 20 GB free left on my machine, should I get worried?

**Comment by thomsh** [comment]
With
```
[footprint]
tracing = "on"
pruning = "archive"
db_compaction = "ssd"
scale_verifiers = true
num_verifiers = 64
cache_size = 1000
```
It took, 4.3 TiB
Probably not the answer you expect, just a quick info.

**Comment by rakita** [comment]
Closing the issue do to inactivity.
