### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by enertom** [openethereum/openethereum#11805]
The memory usage is very high. (about 16Gb)

Start with:
`--cache-size=512 --jsonrpc-port=60000 --ws-port=60001 --jsonrpc-interface all --jsonrpc-server-threads=8 --ws-interface all --db-compaction=ssd --pruning fast --mode active -l sync=info --no-warp --pruning-history=1000000`

htop command:
https://pix.toile-libre.org/upload/original/1593625288.png

- **OpenEthereum version**: Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.0
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: no

**Comment by jiangxjcn** [comment]
set
--pruning-history=1000000
need large memory.
(i set pruning-history=24000, and it will use around 70GB memory)

**Comment by adria0** [comment]
Duplicated of https://github.com/openethereum/openethereum/issues/11760
