### ISSUE TITLE
parity ether architecture Inquiry

### ISSUE THREAD

**Issue by puffanddmx** [openethereum/openethereum#11806]
Is there any material with pictures of the entire architecture of parity-ether? including consensus logic poa. If not, please share a link or paper for reference.

**Comment by adria0** [comment]
We are starting to document how parity works internally in videos, please check https://www.youtube.com/watch?v=0BqHZVuqli4&feature=youtu.be, also you have an overall architecture diagram in https://github.com/openethereum/openethereum/blob/master/docs/architecture-draft.png
