### ISSUE TITLE
getTransaction() returning 'not found'

### ISSUE THREAD

**Issue by purplebiatch** [openethereum/openethereum#11804]
- **OpenEthereum version**: 3.0.0
- **Operating system**:  Linux
- **Installation**: downloaded binary
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Hey, I have an issue with my openethereum node not fetching pending transactions properly
I get a list of transaction hashes from web3.py and get the actual transaction with:
```
filter = W3.eth.filter('pending')
filter.get_new_entries()
...
w3.eth.getTransaction(hash)
```
But around half of the transaction lookups return `transaction not found`
How can the node not have the transaction but have the transaction hash?
I have tried catching this error and waiting ~1s and doing `w3.eth.getTransaction(hash)` on hashes that errored, but it usually returns the same error
I know this includes web3.py code which is not part of this repo but it's impossible for me to manually test this non-programatically

**Comment by rakita** [comment]
Hi purplebiath, maybe because both APIs are fetching pending transactions, maybe transaction in block got mined and the transaction is no longer in pending state.
