### ISSUE TITLE
getPastLogs cannot retrieve the entire history in a fast prunning node

### ISSUE THREAD

**Issue by hellwolf** [openethereum/openethereum#11808]
- **OpenEthereum version**: 3.0.1
- **Operating system**: Linux
- **Installation**: downloaded from github
- **Fully synchronized**: yes (--pruning fast)
- **Network**: kovan
- **Restarted**: yes

Synced kovan node with the following options:

```
	--chain kovan \
	--pruning fast \
```

I am aware of that by not using archive pruning, it is not possible to query past state beyond certain "buffer blocks", and from various internet search, I have been expecting web3.getPastLogs would still be able to query the pastLogs from even the blocknumber 0.

Do I have the wrong assumption, if so, how to achieve that without going to full archive node?

**Comment by rakita** [comment]
I think you have a good assumption, the node cant return past block cause it does not have them.

**Comment by hellwolf** [comment]
> I think you have a good assumption, the node cant return past block cause it does not have them.

Hi, but my assumption was that "web3.getPastLogs would still be able to query the pastLogs from the blocknumber 0". It seems openethereum doesn't do that, while geth could do that.

**Comment by rakita** [comment]
Sorry, I didn't say it clearly. The assumption on "buffer blocks" is correct and we cant return pastLogs from blocknumber 0 because we don't have those blocks on the client. Pruning fast option is exactly that.
