### ISSUE TITLE
Create/Unlock Accounts from Mnemonic

### ISSUE THREAD

**Issue by fredfortier** [openethereum/openethereum#11813]
- **OpenEthereum version**: latest
- **Operating system**: Linux
- **Installation**: Docker: parity/parity:latest
- **Fully synchronized**:  yes
- **Network**: kovan
- **Restarted**: yes

In the context of deploying a dApp testnet using Docker, I'm trying to run an openethereum container that unlocks specific accounts. I could not find much documentation about this, but I basically following this process: https://ico.readthedocs.io/en/latest/chain.html#parity-with-kovan-testnet. This means that I created accounts a priori using the openethereum cli, then I backed up their keys into a volume that mounts into: `io.parity.ethereum/keys/kovan`. Then, I use the unlock argument to give the account addresses and paths to password files. This works but it strikes me as too complicated to be right. Is there a way to just give openethereum a menmonic and account derivation paths to unlock accounts that weren't created in advance?

**Comment by vorot93** [comment]
[Account management is deprecated for all use cases except block authoring in PoA networks.](https://github.com/openethereum/openethereum/issues/9997)

Please use a proper wallet like MetaMask or MyEtherWallet for restoring account from your mnemonic.
