### ISSUE TITLE
CertStore

### ISSUE THREAD

**Issue by CryptoGravity** [openethereum/openethereum#11810]
Windows 10, one-line installer
Ethereum network, not fully synchronized

2020-07-05 13:28:15  Starting OpenEthereum/v3.0.1-stable-8ca8089-20200601/x86_64-pc-windows-msvc/rustc1.43.1
2020-07-05 13:28:15  Keys path d:\eth\keys\ethereum
2020-07-05 13:28:15  DB path d:\eth\ethereum\db\906a34e69aec8c0d
2020-07-05 13:28:15  State DB configuration: fast
2020-07-05 13:28:15  Operating mode: active

====================

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart

Thread 'fetch' panicked at 'cannot access native cert store: Custom { kind: InvalidData, error: BadDER }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-rustls-0.18.0\src\connector.rs:29

**Comment by adria0** [comment]
Duplicated of https://github.com/openethereum/openethereum/issues/11515

**Comment by Gdocal** [comment]
@adria0 did you solve issue?

**Comment by CryptoGravity** [comment]
No, I'm afraid not, I see no solution at all...
Kind regards, CryptoGravity

Op ma 13 jul. 2020 om 14:59 schreef Gdocal <notifications@github.com>:

**Comment by adria0** [comment]
@Gdocal, @CryptoGravity , I'm asking for more information in #11515
