### ISSUE TITLE
After block import fails, app struggles to sync. Restart does not help.

### ISSUE THREAD

**Issue by rakita** [openethereum/openethereum#11828]
- **OpenEthereum version**: 3.0.1_test_67b417976
- **Operating system**: Linux
- **Installation**:  built from source
- **Fully synchronized**: yes
- **Network**: mainnet
- **Restarted**: yes

After this log, app will strugle to include new blocks:
```
2020-07-26 16:24:23 UTC Verified blocks that we want to insert is: n0:10536160 size:35136
2020-07-26 16:24:23 UTC Block import failed for #10536160 (0xa99e…9c3c)
Error: Trie(InvalidStateRoot(0xcb9ef760f961e17685989f95f39449ef3c546c25df9895995694df0934563317))
2020-07-26 16:24:23 UTC Check for block failed
2020-07-26 16:24:23 UTC 
Bad block detected: Trie error: Invalid state root: 0xcb9ef760f961e17685989f95f39449ef3c546c25df9895995694df0934563317
...
[Tx 1] UnverifiedTransaction { unsigned: Transaction { nonce: 2360, gas_price: 132000001852,...
[Tx 139] UnverifiedTransaction { unsigned: Transaction { nonce: 746, gas_price: 85000000000,...
...
````

Restart does not help.

This is the full log after the problem happened (ignore test logs):
https://drive.google.com/file/d/1Ee9vguU8jMbhCYA3leqQqrk1dbnJTlWi/view?usp=sharing

**Comment by askucher** [comment]
So where is a bug?

**Comment by adria0** [comment]
@askucher, we decided to move to 2.5.13 (#11858), could you check with this version, please?

**Comment by rakita** [comment]
We decided to backport to 2.5.13
