### ISSUE TITLE
Question about ETC deprecation / migration

### ISSUE THREAD

**Issue by hitchcott** [openethereum/openethereum#11829]
Given that the ETC network is relying heavily on this OpenEthereum, I was wondering what is likely to happen when the next release of OpenEtheruem is published. 

For those clients that use auto-update, will this an immediate issue? If an update gets shipped, will we suddenly see 70% of ETC nodes go offline?

Is there anything that can be done to help migrate users; perhaps a simple message notifying them that ETC is deprecated and to use a different client?

**Comment by sorpaas** [comment]
Hi @hitchcott, as the ETC community has been extremely toxic recently towards a lot of different reputable teams including OpenEthereum, I hope you can understand that it's a legitimate and necessary response that we do not provide support for ETC or answer questions related to ETC. I wish ETC good luck for its future.

**Comment by rakita** [comment]
Hello @hitchcott, thanks for posting, I think most of ETC community know about OE dropping ETC support, we made our decision public via twitter and the community already started moving to alternatives. Leaving console messages after someone is already upgraded will not help much, and anybody that gets upgraded should be capable with quick search to find what is the problem.
