### ISSUE TITLE
Invalid request errors with skipCache in JSON-RPC request

### ISSUE THREAD

**Issue by KaiRo-at** [openethereum/openethereum#11824]
- **OpenEthereum version**: 3.0.1
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: yes
- **Network**: ropsten
- **Restarted**: yes

This was first reported and worked around in https://github.com/MetaMask/web3-provider-engine/issues/311 but it may actually be an OpenEthereum issue.

Quoting from the `web3-provide-engine` issue:

> Web3 is polling the blockNumber with the request:
> 
> ```json
> {"id":1,"jsonrpc":"2.0","params":[],"method":"eth_blockNumber","skipCache":true}
> ```
> 
> The parity (v2.4.5) node is responding with
> 
> ```json
> {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":1}
> ```

I'm seeing the same issue with OpenEthereum 3.0.1 from docker when trying to deploy contracts via truffle, see some of my output in https://github.com/trufflesuite/truffle/issues/3182#issuecomment-660989269

It may be that `skipCache` is a non-standard option that correctly isn't supported in OpenEthereum, or it may be a bug, I'm not sure, but I wanted to let the OE team know. ;-)

**Comment by adria0** [comment]
@KaiRo-at, I do not see any `skipCache` entry in the OpenEthereum source code, so it seems that this is something specific of other implementations
