### ISSUE TITLE
Project Scope: Remove non-ETH related Networks

### ISSUE THREAD

**Issue by gitr0n1n** [openethereum/openethereum#11837]
- **OpenEthereum version**: 3.0.2
- **Network**: ETH Mainnet and Testnets ONLY

Modify development teams' desired scope of only supporting ETH Mainnet and Testnet by release 3.0.2 of the OpenEthereum project:
https://github.com/openethereum/openethereum/pull/11821#issuecomment-659540776

"We will focus our resources on one network to ensure the best quality in development, and we appreciate any fixes for issues on Ethereum Mainnet and related testnets."
https://twitter.com/OpenEthereumOrg/status/1285556828391301120?s=20

**Comment by vorot93** [comment]
We are not going to outright remove all non-Ethereum chains, Ethereum Classic was a notable exception.
