### ISSUE TITLE
Centos 8.2 stuck on compiling openethereum

### ISSUE THREAD

**Issue by BronacusAmmon** [openethereum/openethereum#11845]
- **OpenEthereum version**: 3.0.0
- **Operating system**: Centos 8.2
- **Installation**: built from source
- **Fully synchronized**: no 
- **Network**: ethereum 
- **Restarted**: no

Attempting to compile a fresh install of openethereum on my centos 8.2 server, followed instructions got cargo, rustup, perl, yasm, and clang installed at the following versions
rustup 1.22.1
cargo 1.45.1
perl5 v 26
yasm 1.3.0
clang version 9.0.1

on building release cargo build --release --features final it gets to 
   Compiling openethereum v3.0.0 (/root/openethereum)
  Building [=================================================> ] 542/543
and it has been sitting there for over three hours with no change but no error, is the openethereum compile this slow normally or am I possibly missing an essential install?

**Comment by adria0** [comment]
@BronacusAmmon, in which hardware are you compiling?
