### ISSUE TITLE
[BUG 3.0.1]Thread 'IO Worker #0' panicked at 'State root of the best block header always vaild

### ISSUE THREAD

**Issue by heimi-block** [openethereum/openethereum#11844]
![image](https://user-images.githubusercontent.com/22029390/89123946-ce3edb00-d505-11ea-83d8-760c8470f9b9.png)

**Comment by rakita** [comment]
Not enough information on the issue.

**Comment by rakita** [comment]
We are currently moving to v2.5.13 code base
