### ISSUE TITLE
What should I do about fixing the parity network traffic overhead

### ISSUE THREAD

**Issue by yangxiao1220** [openethereum/openethereum#11857]
Gentlemen, I want to raise a question, I use Parity-Ethereum/ V2.7.2 synchronization Ropsten at AWS, and last month I checked the rates generated by Internet traffic are up to a staggering $1,000, And I'm trying to optimize the rates generated by Internet traffic, Please ask what I should do, I tried Trickle seems to be useless.

**Comment by rakita** [comment]
Hello, try to reduce the number of max peers maybe it helps. 
Ethereum client, in general, is network intensive, high network traffic is expected, I will close this issue.
