### ISSUE TITLE
news about bug in parity

### ISSUE THREAD

**Issue by askucher** [openethereum/openethereum#11865]
Found the information about bug of parity https://www.coindesk.com/buggy-code-release-13-ethereum-nodes-offline

Please help me to understand why is downgrading to 2.5 helps and what major changes were in 2.6 / 2.7 ? 

please mark this issue as duplicate if you have another issue with exact explanation of the problem

**Comment by claveros** [comment]
https://github.com/openethereum/openethereum/issues/11858
