### ISSUE TITLE
Split header into two structures

### ISSUE THREAD

**Issue by debris** [openethereum/openethereum#1267]
- first one - modifiable, used to build block header
- second one -  readonly, with cached hash and bare hash. No public fields should be exposed.

goal:
- get rid of `note_dirty` function and possible inconsistency between header fields and hash

**Comment by edwardw** [comment]
All fields of the `Header` structure except `hash` and `bare_hash` are modified. So is it that the intention here is actually to make all fields private and add `setter/getter` methods?

**Comment by debris** [comment]
> All fields of the `Header` structure are modified in one place or the other. So is it that the intention here is actually to make all fields private and add `setter/getter` methods? 

this could be the first step.

After that it would be good, to split header into two data structures. One immutable - `SealedHeader` and the other one with public fields `Header`.

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still _involved_ and realistic to implement. If so, please add an assignee and a milestone, or close otherwise.

**Comment by dvdplm** [comment]
@debris is the second part of this issue still relevant? If yes, do I understand it correctly:
- split `Header` into `Header` and `SealedHeader`
- leave all fields on `Header` except `hash`
- implement `bare_hash()` on `SealedHeader` and change code to get&use a `SealedHeader` anywhere `bare_hash()` is called
- how are `Header` and `SealedHeader` linked? In cases both are needed, how to we link the two together?

**Comment by debris** [comment]
yes, it's still relevant.

> how are Header and SealedHeader linked? In cases both are needed, how to we link the two together?

`SealedHeader` has all fields that `Header` has + `hash` field. Or it can contain `header` and `hash. We did something like this in [parity-bitcoin](https://github.com/paritytech/parity-bitcoin/blob/160e8c636f9b92a30519d2e8050485e5f0f8b43d/chain/src/indexed_header.rs#L7-L11).

**Comment by adria0** [comment]
Closing the issue due to its stale state
