### ISSUE TITLE
Bugs when running openethereum after building on MacOS

### ISSUE THREAD

**Issue by SirFrankieCrisp** [openethereum/openethereum#128]
- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: MacOS
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
 **Restarted**: no

Just started openethereum with .target/release/openethereum and a panix occured. Below are the error messages when it started going wrong.

> Thread 'Verifier #2' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H160, std::option::Option<state::account::Account>>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658
> 2020-11-25 16:16:21  Finishing work, please wait...
> 2020-11-25 16:16:21  Block import failed for #3 (0x3d61…f741): Parent not found (0xb495…98c9)
> 2020-11-25 16:16:21
> Bad block detected: Error(Msg("Parent not found"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
> RLP: f90434f90218a0b495a1d7e6663152ae92708da4843337b958146015a2802f4193a410044698c9a06b17b938c6e4ef18b26ad81b9ca3515f27fd9c4e82aac56a1fd8eab288785e41945088d623ba0fcf0131e0897a91734a4d83596aa0a076ab0b899e8387436ff2658e2988f83cbf1af1590b9fe9feca3714f8d1824940a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008503fe802ffe03821388808455ba4260a0476574682f76312e302e302d66633739643332642f6c696e75782f676f312e34a065e12eec23fe6555e6bcdb47aa25269ae106e5f16b54e1e92dcee25e1c8ad037882e9344e0cbde83cec0f90215f90212a0d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794c8ebccc5f5689fa8659d83713341e5ad19349448a01e6e030581fd1873b4784280859cd3b3c04aa85520f08c304cf5ee63d3935adda056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008503ff80000001821388808455ba42429a59617465732052616e64616c6c202d2045746865724e696e6a61a0f8c94dfe61cf26dcdf8cffeda337cf6a903d65c449d7691a022837f6e2d994598868b769c5451a7aea
> Header: Header { parent_hash: 0xb495a1d7e6663152ae92708da4843337b958146015a2802f4193a410044698c9, timestamp: 1438270048, number: 3, author: 0x5088d623ba0fcf0131e0897a91734a4d83596aa0, transactions_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, uncles_hash: 0x6b17b938c6e4ef18b26ad81b9ca3515f27fd9c4e82aac56a1fd8eab288785e41, extra_data: [71, 101, 116, 104, 47, 118, 49, 46, 48, 46, 48, 45, 102, 99, 55, 57, 100, 51, 50, 100, 47, 108, 105, 110, 117, 120, 47, 103, 111, 49, 46, 52], state_root: 0x76ab0b899e8387436ff2658e2988f83cbf1af1590b9fe9feca3714f8d1824940, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 0, gas_limit: 5000, difficulty: 17154715646, seal: [[160, 101, 225, 46, 236, 35, 254, 101, 85, 230, 188, 219, 71, 170, 37, 38, 154, 225, 6, 229, 241, 107, 84, 225, 233, 45, 206, 226, 94, 28, 138, 208, 55], [136, 46, 147, 68, 224, 203, 222, 131, 206]], hash: Some(0x3d6122660cc824376f11ee842f83addc3525e2dd6756b9bcf0affa6aa88cf741) }
> Uncles: [Uncle 0] Header { parent_hash: 0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3, timestamp: 1438270018, number: 1, author: 0xc8ebccc5f5689fa8659d83713341e5ad19349448, transactions_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [89, 97, 116, 101, 115, 32, 82, 97, 110, 100, 97, 108, 108, 32, 45, 32, 69, 116, 104, 101, 114, 78, 105, 110, 106, 97], state_root: 0x1e6e030581fd1873b4784280859cd3b3c04aa85520f08c304cf5ee63d3935add, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 0, gas_limit: 5000, difficulty: 17171480576, seal: [[160, 248, 201, 77, 254, 97, 207, 38, 220, 223, 140, 255, 237, 163, 55, 207, 106, 144, 61, 101, 196, 73, 215, 105, 26, 2, 40, 55, 246, 226, 217, 148, 89], [136, 104, 183, 105, 197, 69, 26, 122, 234]], hash: Some(0x5cd50096dbb856a6d1befa6de8f9c20decb299f375154427d90761dc0b101109) }
> Transactions:
> 
> 2020-11-25 16:16:21  Panic occured, see stderr for details
> 
> 
> ====================
> 
> stack backtrace:
>    0: backtrace::backtrace::trace
>    1: backtrace::capture::Backtrace::new
>    2: panic_hook::set_with::{{closure}}
>    3: std::panicking::rust_panic_with_hook
>    4: std::panicking::begin_panic_handler::{{closure}}
>    5: std::sys_common::backtrace::__rust_end_short_backtrace
>    6: rust_begin_unwind
>    7: core::panicking::panic_fmt
>    8: core::panicking::panic
>    9: linked_hash_map::LinkedHashMap<K,V,S>::insert
>   10: lru_cache::LruCache<K,V,S>::insert
>   11: memory_cache::MemoryLruCache<K,V>::insert
>   12: ethcore::client::bad_blocks::BadBlocks::report
>   13: ethcore::client::client::Importer::import_verified_blocks
>   14: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
>   15: ethcore_io::service_mio::IoChannel<Message>::send_sync
>   16: std::sys_common::backtrace::__rust_begin_short_backtrace
>   17: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   18: std::sys::unix::thread::Thread::new::thread_start
>   19: _pthread_start
> 
> 
> Thread 'Verifier #6' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H256, (verification::queue::kind::blocks::Unverified, std::string::String)>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658
> 
> This is a bug. Please report it at:
> 
>     https://github.com/openethereum/openethereum/issues/new
> 
> 
> 2020-11-25 16:16:21  Block import failed for #15 (0x2d33…0f1c): Parent not found (0x4601…10a4)
> 2020-11-25 16:16:21
> Bad block detected: Error(Msg("Parent not found"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
> RLP: f90216f90211a046015afbe00cf61ff284c26cc09a776a7303e422c7b359fe4317b4e6aaa410a4a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940193d941b50d91be6567c7ee1c0fe7af498b4137a063b69382fcecd8767a1938345589b82412694e25c052af80d968e4ec4791038fa056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008504007f8ff20f821388808455ba42d899476574682f76312e302e302f6c696e75782f676f312e342e32a01885b2df55b0e2e138194d0532402092645aa0c66b5c7e9e54fe9a31ef15a9688891ed702e05c83014c0c0
> Header: Header { parent_hash: 0x46015afbe00cf61ff284c26cc09a776a7303e422c7b359fe4317b4e6aaa410a4, timestamp: 1438270168, number: 15, author: 0x0193d941b50d91be6567c7ee1c0fe7af498b4137, transactions_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [71, 101, 116, 104, 47, 118, 49, 46, 48, 46, 48, 47, 108, 105, 110, 117, 120, 47, 103, 111, 49, 46, 52, 46, 50], state_root: 0x63b69382fcecd8767a1938345589b82412694e25c052af80d968e4ec4791038f, receipts_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, log_bloom: 0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, gas_used: 0, gas_limit: 5000, difficulty: 17188229106, seal: [[160, 24, 133, 178, 223, 85, 176, 226, 225, 56, 25, 77, 5, 50, 64, 32, 146, 100, 90, 160, 198, 107, 92, 126, 158, 84, 254, 154, 49, 239, 21, 169, 104], [136, 145, 237, 112, 46, 5, 200, 48, 20]], hash: Some(0x2d33dc73755afbbbeb6ec4885f2923398901bf1ad94beb325a4c4ecad5bf0f1c) }
> Uncles:
> Transactions:
> 
> 2020-11-25 16:16:21  Panic occured, see stderr for details
> 
> 
> ====================
> 
> stack backtrace:
>    0: backtrace::backtrace::trace
>    1: backtrace::capture::Backtrace::new
>    2: panic_hook::set_with::{{closure}}
>    3: std::panicking::rust_panic_with_hook
>    4: std::panicking::begin_panic_handler::{{closure}}
>    5: std::sys_common::backtrace::__rust_end_short_backtrace
>    6: rust_begin_unwind
>    7: core::panicking::panic_fmt
>    8: core::panicking::panic
>    9: linked_hash_map::LinkedHashMap<K,V,S>::insert
>   10: lru_cache::LruCache<K,V,S>::insert
>   11: memory_cache::MemoryLruCache<K,V>::insert
>   12: ethcore::client::bad_blocks::BadBlocks::report
>   13: ethcore::client::client::Importer::import_verified_blocks
>   14: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
>   15: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
>   16: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
>   17: std::sys_common::backtrace::__rust_begin_short_backtrace
>   18: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   19: std::sys::unix::thread::Thread::new::thread_start
>   20: _pthread_start
> 
> 
> Thread 'IO Worker #1' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H256, (verification::queue::kind::blocks::Unverified, std::string::String)>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658
> 
> This is a bug. Please report it at:
> 
>     https://github.com/openethereum/openethereum/issues/new
> 
> 
> 2020-11-25 16:16:21  Panic occured, see stderr for details
> 
> 
> ====================
> 
> stack backtrace:
>    0: backtrace::backtrace::trace
>    1: backtrace::capture::Backtrace::new
>    2: panic_hook::set_with::{{closure}}
>    3: std::panicking::rust_panic_with_hook
>    4: std::panicking::begin_panic_handler::{{closure}}
>    5: std::sys_common::backtrace::__rust_end_short_backtrace
>    6: rust_begin_unwind
>    7: core::panicking::panic_fmt
>    8: core::option::expect_none_failed
>    9: <ethcore::verification::queue::VerificationQueue<K> as core::ops::drop::Drop>::drop
>   10: core::ptr::drop_in_place
>   11: core::ptr::drop_in_place
>   12: alloc::sync::Arc<T>::drop_slow
>   13: alloc::sync::Arc<T>::drop_slow
>   14: alloc::sync::Arc<T>::drop_slow
>   15: core::ptr::drop_in_place
>   16: alloc::sync::Arc<T>::drop_slow
>   17: alloc::sync::Arc<T>::drop_slow
>   18: alloc::sync::Arc<T>::drop_slow
>   19: <hashbrown::raw::RawTable<T> as core::ops::drop::Drop>::drop
>   20: alloc::sync::Arc<T>::drop_slow
>   21: core::ptr::drop_in_place
>   22: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
>   23: tokio_threadpool::worker::Worker::run_task
>   24: tokio_threadpool::worker::Worker::run
>   25: tokio_reactor::with_default
>   26: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
>   27: std::sys_common::backtrace::__rust_begin_short_backtrace
>   28: core::ops::function::FnOnce::call_once{{vtable.shim}}
>   29: std::sys::unix::thread::Thread::new::thread_start
>   30: _pthread_start
> 
> 
> Thread 'event.loop0' panicked at 'Propagating verifier thread panic on shutdown: Any', /Users/frankie/openethereum/ethcore/src/verification/queue/mod.rs:853
>

**Comment by adria0** [comment]
Duplicated of #120
