### ISSUE TITLE
could someone tell me the <YOUR_ETH1_NODE_ENDPOINT>of openethereum?

### ISSUE THREAD

**Issue by navy665180** [openethereum/openethereum#132]
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: Windows 
- **Installation**: homebrew 
- **Fully synchronized**: no
- **Network**: ethereum 
- **Restarted**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
could someone tell me the <YOUR_ETH1_NODE_ENDPOINT>of openethereum?

I choose to use the prysm .and in the step2 of guild of install prysm,is:
prysm.bat beacon-chain --http-web3provider=<YOUR_ETH1_NODE_ENDPOINT>
where can i find  <YOUR_ETH1_NODE_ENDPOINT>?
thanks a lot!!!

**Comment by roninkaizen** [comment]
you need a OpenEthereum node running
with cli/config containing at least "----jsonrpc-apis=safe"
by default usage of prysm and openeth is possible
then the setting would be
--http-web3provider=127.0.0.1(or localhost)

**Comment by navy665180** [comment]
thanks，what's the mean of  [cli/config containing at least "----jsonrpc-apis=safe"]  ?
i just thought i need to syncing all of the node. is it wrong??

**Comment by navy665180** [comment]
http-web3provider=127.0.0.1

**Comment by navy665180** [comment]
> 
> 
> you need a OpenEthereum node running
> with cli/config containing at least "----jsonrpc-apis=safe"
> by default usage of prysm and openeth is possible
> then the setting would be
> --http-web3provider=127.0.0.1(or localhost)
thanks，what's the mean of [cli/config containing at least "----jsonrpc-apis=safe"] ?
i just thought i need to syncing all of the node. is it wrong??
i download the OpenEthereum and double click on it ,then it start syncing .now the hight is 4226683.need several days more.
did i have any mistakes?

**Comment by roninkaizen** [comment]
you need to start the programm by hand from your dos-window
please read in yourself how to use the command-line-window

this is no "double-click-area" :)

**Comment by navy665180** [comment]
it seams i waste severy days ? TT.can i do anything useful?

**Comment by Legogris** [comment]
> can i do anything useful?

Read through documentation so you understand yourself the answer to questions like:

>  what's the mean of [cli/config containing at least "----jsonrpc-apis=safe"] ?

Perform the entire setup on a testnet first (*a lot* less time to completion/wasted) before trying mainnet again.
