### ISSUE TITLE
Volume permission issue in docker openethereum

### ISSUE THREAD

**Issue by jurosh** [openethereum/openethereum#133]
- **OpenEthereum version** 3.1.0 (Docker)
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: no
- **Network**: ethereum

Starting fresh instance, By following [documentation](https://openethereum.github.io/Docker) and running command:
```
docker run -ti \
 -v ~/.openethereum/:/home/openethereum/.local/share/openethereum/ \
 openethereum/openethereum:v3.1.0 --base-path /home/openethereum/.local/share/openethereum/
```

(There is no `~/.openethereum` folder yet - I expect container to create it.)

It will always crash on:
```
Error upgrading OpenEthereum data: CannotCreateConfigPath(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

Expected:
- I would expect that openethereum would create folder with root permission (eg. that is how `geth` works), so that only admin can read and write data in `.openthereum` folder

**Comment by roninkaizen** [comment]
did i get it right, 
that you wanted docker to use an self-defined location for the chain outsides of the docker-container itself?

**Comment by jurosh** [comment]
> did i get it right,
> that you wanted docker to use an self-defined location for the chain outsides of the docker-container itself?

Yes, it's defined by this parameter ` -v ~/.openethereum/:/home/openethereum/.local/share/openethereum/ \`
So `~/.openethereum` is host path for chain data which allows me to remove and recreate docker image without worrying about data.

**Comment by rakita** [comment]
It seems this is docker folder permission related
