### ISSUE TITLE
Thread 'IO Worker #3' panicked at 'nonce will return 

### ISSUE THREAD

**Issue by ctar** [openethereum/openethereum#134]
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.1.0-stable-94a784bfe-20201106/x86_64-linux-gnu/rustc1.47.0
- **Operating system**: Manjaro
- **Installation**: Arch/Manjaro package manager
- **Fully synchronized**: no 
- **Network**: ethereum 
- **Restarted**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I had a hard disk issue - after reboot, openethereum panics after a few seconds of starting - more complete logs attached

:

2020-11-29 21:46:04  Syncing #11355272 0xae5d…74ec     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11355652   15/25 peers   189 KiB chain 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2020-11-29 21:46:07  Panic occured, see stderr for details

====================

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: start_thread
  19: __GI___clone

Thread 'IO Worker #3' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new

2020-11-29 21:46:07  Finishing work, please wait...
Error: 1

[openethcrash.txt](https://github.com/openethereum/openethereum/files/5614039/openethcrash.txt)

**Comment by roninkaizen** [comment]
try  https://gist.github.com/adria0/1a4505e1823373b03db37a0de5e92b75
and report, if it worked for you if you like

**Comment by ryanobjc** [comment]
I also ran into this issue. I am using 56131b6d9 on "Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64".  I was just running the client, and overnight it crashed with this.  Restarting without doing anything triggers the bug again.  I'll try the instructions in that gist and see what happens.

**Comment by ryanobjc** [comment]
Those instructions did not work for me.  I did 'db reset 10' and 'db experimental-drop-future-blocks' using that branch, then I went back to the commit I was using and tried to restart and I got the same crash again.

**Comment by rakita** [comment]
duplicate for #69, will close this issue.
