### ISSUE TITLE
Ethereum Classic node is stuck at block 11699999

### ISSUE THREAD

**Issue by 1scrooge** [openethereum/openethereum#136]
- **OpenEthereum version **: 3.0.1
- **Operating system**: Linux
- **Installation**: Docker
- **Fully synchronized**: no 
- **Network**: ethereum classic
- **Restarted**: yes

My Ethereum Classic node is stuck at block 11699999, I can't update the client to 3.1.0 because Openethereum no longer supports ethereum classic. As I understand it, I need to change the client??

**Comment by gsalzer** [comment]
If I remember correctly, `openethereum` dropped support for Ethereum Classic (which means that they will not integrate changes to the protocol), and Ethereum Classic performed a hard fork with block 11,700,000. If I'm right, then you have to switch to another client.

**Comment by rakita** [comment]
`OpenEthereum` is not supporting `ETC`.
