### ISSUE TITLE
Multi-threaded server is not available on Windows. Falling back to single thread.

### ISSUE THREAD

**Issue by navy665180** [openethereum/openethereum#140]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**:3.1.0
- **Operating system**: Windows 
- **Installation**: homebrew  download the resouse.doulbe-click the openethereum.exe.
- **Fully synchronized**: no 
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

when i Syncing the node,at the hight of #4711999.i powered off the windows.then restart.
at the head of terminal window,it says:Multi-threaded server is not available on Windows. Falling back to single thread.
what can i do?and what is the mistake i have done?
![eth1 0](https://user-images.githubusercontent.com/75147624/100743467-461b0480-3417-11eb-956a-5afb2e0274be.png)

**Comment by rakita** [comment]
It will always write that

**Comment by navy665180** [comment]
thanks a lot!
