### ISSUE TITLE
Possible DoS when 8545 is reachable and `eth_sendTransaction` is attempted

### ISSUE THREAD

**Issue by yorickdowne** [openethereum/openethereum#141]
- **OpenEthereum version (>=3.1.0)**: OpenEthereum/v3.1.0-rc1-stable/x86_64-linux-musl/rustc1.47.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: no

Found while testing: If OE is on a VPS with 8545 open to world (1), then it's possible to DoS OE. Started with `--no-secretstore`.

The error was "BlockGasLimitReached", which would be expected since there's no account and no Eth in OE. After that error, OE's sync "hung", it was not able to keep up with head. These two might be unrelated.

This may resolve when `eth_sendTransaction` and `eth_accounts` gets removed, and that might be the easy answer: Keep 8545 closed, wait for account management to be removed.

(1) While 8545 open to world, particularly without TLS, is a terrible idea, I'd still hope that a DoS of OE would be non-trivial. This feels like a bug. That said, yes: 8545 should never be open to world.

[eth1err.log](https://github.com/openethereum/openethereum/files/5624369/eth1err.log)

**Comment by adria0** [comment]
@yorickdowne, yes, RPC endpoints should be protected in some way, if are public exposed you need to:

1) Authenticate the endpoint
2) Add TLS
3) Add some throttling or limit the kind of requests that can be done (e.g. subscriptions could be really heavy)

Some time ago I did this small proxy https://github.com/adria0/web3proxy for web3, I do not know if still works

Probably there are some ppl that are exposing their RPCs with `--no-secretstore`, so let's check this.

**Comment by adria0** [comment]
@yorickdowne, I am not able to reproduce the sync "hung", could you provide to me more information, please. Better if in Discord private channel.

**Comment by yorickdowne** [comment]
No longer relevant
