### ISSUE TITLE
about snapshot .how to use?how to sovle ?thanks!

### ISSUE THREAD

**Issue by navy665180** [openethereum/openethereum#142]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: Windows 
- **Installation**: homebrew
- **Fully synchronized**: no 
- **Network**: ethereum 
- **Restarted**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I powered off the windows .and 8 hours later restarted it.
the syncing window  shows:syncing snapshot 169/5112 #4712648. 23/25 peers    210 KiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs

![snapshot](https://user-images.githubusercontent.com/75147624/100820839-16f1ab00-348a-11eb-8f61-091930a19c5d.png)

what's the mean of snapshot?did i make any mistakes?how to use it if one day i need to copy the datebase?
now every 5 seconds,it only get 1by1,up .i don't know the reason.when i did not restarted,it get up by 50by 50  or even more.
![syncing one by one](https://user-images.githubusercontent.com/75147624/100823163-adc06680-348e-11eb-9dda-e8f06640fa8a.png)

thanks!

**Comment by roninkaizen** [comment]
looking at it,
i can confirm, that the warp sometimes happens twice, "short" after each other, which is not good to interrupt at all-
if you started all over again, cleared the db before, you could(should) get different ops-behaviour.
feel also free to visit the discord-channel.
https://discord.gg/mzr6xEtM
