### ISSUE TITLE
Open Ethereum Rust profiling

### ISSUE THREAD

**Issue by cyrilnavessamuel** [openethereum/openethereum#143]
Hello, 

My question is general : Please can you let me know the possibility of  rust profiling the open-ethereum binary , I would like to nderstand the performance of the binary. Please can you let me know the possibility and steps to do it. Thanks!

**Comment by adria0** [comment]
@cyrilnavessamuel for questions please use https://discord.io/openethereum, issues are for bugs and feature requests.
