### ISSUE TITLE
Thread 'IO Worker #3' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some;

### ISSUE THREAD

**Issue by winlin** [openethereum/openethereum#144]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 0.0.0
- **Operating system**: Linux Ubuntu 20.04
- **Installation**:  one-line installer 
- **Fully synchronized**: no 
- **Network**: ethereum.
- **Restarted**: yes

[Tx 197] UnverifiedTransaction { unsigned: Transaction { nonce: 22998, gas_price: 24255001684, gas: 313359, action: Call(0x2a549b4af9ec39b03142da6dc32221fc390b5533), value: 0, data: [166, 138, 118, 204] }, v: 28, r: 57215410476555576401340367311312765606019736860293815134931783258087773404669, s: 13363662997838742338835035592929530406687779565080358978944122946951907099032, hash: 0xd0f5b6c795d627aeb8be7e15bf046c893e7af5bbec0753037739cb3472449512 }
[Tx 198] UnverifiedTransaction { unsigned: Transaction { nonce: 7, gas_price: 24000000000, gas: 21000, action: Call(0x0aeee23d16084d763e7a65577020c1f3d18804f2), value: 109000000000000000, data: [] }, v: 37, r: 111490444233025345037331855589425357801727916256553905551614366817084893729499, s: 55926225791819151299504355886879705836458833523874062825227613388103585423392, hash: 0x4d0be66f2421f4235c93311116a9d96740ebf4f00d482f9adeb1c380f1252c55 }
[Tx 199] UnverifiedTransaction { unsigned: Transaction { nonce: 3, gas_price: 24000000000, gas: 21000, action: Call(0x95737da4810dd2dc535e0e98f9f47d67d4673d27), value: 214761197929783120, data: [] }, v: 38, r: 63531889051828440983939578576080599478757970432546000310061411569390391920475, s: 15984354401595416244866239140761906310055868333295009711220340993607611519443, hash: 0x8cacf04a03f05e71e80812af2237cbb57e58e0e92332c7e3f0a59a3624c043bd }
[Tx 200] UnverifiedTransaction { unsigned: Transaction { nonce: 76, gas_price: 23210001235, gas: 60000, action: Call(0xdac17f958d2ee523a2206206994597c13d831ec7), value: 0, data: [169, 5, 156, 187, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 137, 136, 173, 155, 104, 133, 118, 114, 51, 4, 166, 9, 251, 252, 64, 15, 181, 250, 224, 154, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 215, 112, 64] }, v: 37, r: 16384440857470017231477779355141013559459343952419917903189467408705774274279, s: 14451631173982269675123323544829167577146572498703280414508500449146680052419, hash: 0x38ad333475bd69e9bbcf2da2a8fe5963ae1e6286b8e3a0316672e528ceeac547 }
[Tx 201] UnverifiedTransaction { unsigned: Transaction { nonce: 967, gas_price: 23100001604, gas: 21000, action: Call(0xcb86e96e7e2b25ff374e1700c03aef593e2b6609), value: 1386000096240000, data: [] }, v: 37, r: 19740893510355633282651691421789405792045897857473205066475733544028082490413, s: 4934194393362176271154069184857407125998066734216316481141191512832870859800, hash: 0x1b0321675ca89eeba7ba21cac2889571aaf5e5e95de29f175d8b213c067fda40 }
[Tx 202] UnverifiedTransaction { unsigned: Transaction { nonce: 212, gas_price: 23100001604, gas: 21000, action: Call(0x34998ac6c06b5c297b43a08ab409a4655fc46279), value: 851420000000000000, data: [] }, v: 37, r: 80704756616313797848558885072693740063434502079416288707410586546347590235091, s: 41697494409765494968872910105983989148811653894886536258955865360607619308846, hash: 0x91db11ed8a54e1757e2ff82b961257a2d81be294b38c484f9584766c19795474 }
[Tx 203] UnverifiedTransaction { unsigned: Transaction { nonce: 14, gas_price: 23100001604, gas: 21000, action: Call(0x2050642b4cab599019aa873177e1c56d4900ff19), value: 7500000000000000000, data: [] }, v: 38, r: 113423341107503845724021887951693748301822750606515973450943090690309688792770, s: 54972286613157846735892793645625292987287154492606746398034889964477745970285, hash: 0x360c989d9a650919d45df62e0a7929b5f2ffe352047e0335e44ace8a71f823b9 }

2020-12-03 00:22:35  Panic occured, see stderr for details

====================

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: start_thread
  19: __clone

Thread 'IO Worker #3' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new

2020-12-03 00:22:35  Finishing work, please wait...
2020-12-03 00:22:37  Panic occured, see stderr for details

====================

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: start_thread
  19: __clone

Thread 'IO Worker #1' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new

**Comment by rakita** [comment]
Duplicated from: #69. Potential fix is currently in testing.
