### ISSUE TITLE
openethereum crash on ARM64 / Ubuntu bionic

### ISSUE THREAD

**Issue by tkanerva** [openethereum/openethereum#146]
- **OpenEthereum version (>=3.1.0)**: 0.0.0
- **Operating system**: Linux, ubuntu bionic on aarch64
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum 
- **Restarted**: no 

openethereum was syncing with the ethereum chain and got stuck at snapshot 1093/5706.

[backtrace.20201202.txt](https://github.com/openethereum/openethereum/files/5634226/backtrace.20201202.txt)

**Comment by tkanerva** [comment]
was too hasty to submit, forgot to specify the versions of OpenEthereum and Rust.

OpenEthereum v3.1.0-rc.1

rustc 1.48.0 (7eac88abb 2020-11-16)

**Comment by rakita** [comment]
Fix is in dev branch #120
