### ISSUE TITLE
Thread 'IO Worker #3' panicked at 'State root of best block header always valid.: InvalidStateRoot(0xe9b5ef1092243f036e4a16e5cacee  f71e8dbf19b17883704cc341b1c09860074)', ethcore/src/client/client.rs:1179

### ISSUE THREAD

**Issue by lakoma** [openethereum/openethereum#152]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: v3.1.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum 
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
Mainnet sync (Eth1) failed:

Started with:
openethereum --fast-unlock --remove-solved --no-seal-check --can-restart --max-peers=100

Output:
[Tx 171] UnverifiedTransaction { unsigned: Transaction { nonce: 9, gas_price: 40000001347, gas: 50000, action: Call(0xf82c0514f95e
7a036e60c07509c745c5ae236305), value: 0, data: [60, 207, 214, 11] }, v: 38, r: 113099126192024109796116921175127757299841922789921
472973100531444956037098979, s: 32428916433983984238998372683497868060987943372928588272554605850608607977525, hash: 0x3019b955fdf
a54357cb9f331502ac4ba26cd50a9aeaa4eb61d9b170f680a6424 }
[Tx 172] UnverifiedTransaction { unsigned: Transaction { nonce: 0, gas_price: 40000000000, gas: 21000, action: Call(0x9d96b0561be0
440ebe93e79fe06a23bbe8270f90), value: 104047748700000016, data: [] }, v: 38, r: 29429995475142653482326526899245207240217842898940
322434540872033984978592139, s: 53081479139001588730588059955759190132430769403489429320441786785873075140372, hash: 0xf5e021b1a79

3697931c1505388f855508ec4c2fea255d07252b158c58e245f1a }

2020-12-05 07:51:51 UTC Syncing #11388785 0xd719…0f22     0.00 blk/s    0.0 tx/s    0.0 Mgas/s   1045+    0 Qed  #11391383   23/25
 peers   896 KiB chain 127 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2020-12-05 07:51:55 UTC Syncing #11388785 0xd719…0f22     0.00 blk/s    0.0 tx/s    0.0 Mgas/s   1250+    0 Qed  #11391383   24/25
 peers   1 MiB chain 146 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2020-12-05 07:52:00 UTC Syncing #11388785 0xd719…0f22     0.00 blk/s    0.0 tx/s    0.0 Mgas/s    609+    0 Qed  #11391383   25/25
 peers   1 MiB chain 74 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2020-12-05 07:52:05 UTC Syncing #11388785 0xd719…0f22     0.00 blk/s    0.0 tx/s    0.0 Mgas/s     12+    0 Qed  #11391383   27/10
0 peers   1 MiB chain 2 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2020-12-05 07:52:05 UTC Panic occured, see stderr for details

====================

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>

   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: start_thread
  21: __clone

Thread 'IO Worker #3' panicked at 'State root of best block header always valid.: InvalidStateRoot(0xe9b5ef1092243f036e4a16e5cacee
f71e8dbf19b17883704cc341b1c09860074)', ethcore/src/client/client.rs:1179

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new

2020-12-05 07:52:05 UTC Finishing work, please wait...
Error: 1

**Comment by rakita** [comment]
duplicate #69. fix for bug is here: https://github.com/openethereum/openethereum/pull/149
You can try to salvage with this: https://gist.github.com/adria0/1a4505e1823373b03db37a0de5e92b75
The most probable outcome is that you need to remove DB and sync again.
