### ISSUE TITLE
v3.1.0: Optimizing Archive Node Sync Times

### ISSUE THREAD

**Issue by ymonye** [openethereum/openethereum#158]
- **OpenEthereum version**: 3.1.0
- **Operating system**: Linux CentOS 7
- **Hardware**: 24 CPU cores, 128GB RAM
- **Installation**: Built from source
- **Fully synchronized**: Currently Syncing
- **Network**: Ethereum Mainnet
- **Restarted**: Yes

Hi. Is there a way of optimizing OpenEthereum's archive node sync time to less than a month? This method takes a relatively short amount of time under Go-Ethereum (Geth), roughly 7 days on a previous test run by myself.

I currently have three fully synced archive nodes all within the same local network (one on OpenEthereum v3.0.0, two on the latest Geth clients), and all of their enodes were added to my OpenEthereum v3.1 argument list under `--reserved-peers=enodes.txt`.

Network connectivity and Firewall rules were confirmed to these other servers and nodes via `nc -zv`, yet for whatever reason my v3.1 client still updates at less than 1 blk/s. The only reason I'm running a new sync vs. copying data from my OpenEthereum v3.0.0 node is to avoid any potential database issues, as I'd previously faced issues when upgrading from 2.x to 3.0.

Are there any other ways to optimize the overall archive node sync process, given my current system? Thanks

**Comment by ytrezq** [comment]
@ymone Ethereum archive node databse size recently doubled. How much your test under geth was recent?

**Comment by ymonye** [comment]
> @ymone Ethereum archive node databse size recently doubled. How much your test under geth was recent?

Hi @ytrezq, my latest Geth archive node sync from block 0 to the latest was around 1 month ago, and took roughly a week. Many archive nodes were synced then, since I've had to deploy onto multiple systems (all Dell PowerEdge servers). My initial attempt also took 7 days in 2019, documented in the Tweet below.

Since 2019, it's taken me well over a month for OpenEthereum (Parity) archive nodes to complete an archive node sync, with significantly less time on Go-Ethereum. This is not intended to be a bash at the design, since I still greatly depend on the OpenEthereum client for pulling Transaction Traces, but more of a heads up and awareness. I'd be more than willing to help where I can, if possible, identifying any choke points within the code.

April 2019 Go-Ethereum Archive Node Sync (7 days and 19 hrs)
https://twitter.com/LedgerQL/status/1114478908219514880

**Comment by ymonye** [comment]
Was resolved from v3.2.x
