### ISSUE TITLE
Can no longer apply filters to parity_pendingtransactions

### ISSUE THREAD

**Issue by ytrezq** [openethereum/openethereum#159]
This is a regression of https://github.com/openethereum/parity-ethereum/issues/11189. Using the request of the doc, OpenEthereum complains that only one parameter is accepted not 2.

**Comment by ytrezq** [comment]
The reason is simple! https://github.com/openethereum/parity-ethereum/pull/10506 is no longer part of commit history.
@lamafab would it be possible to reimplment your pull request?

**Comment by mohoff** [comment]
Facing the same issue with

```
openethereum --version
OpenEthereum Client.
  version OpenEthereum/v3.1.0-stable-94a784b-20201106/x86_64-macos/rustc1.47.0
Copyright 2015-2020 Parity Technologies (UK) Ltd.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf/Greeff
   Habermeier/Czaban/Gotchac/Redman/Nikolsky
   Schoedon/Tang/Adolfsson/Silva/Palm/Hirsz et al.
```

**Comment by lamafab** [comment]
@ytrezq yeah I guess I could re-implement it again, it's not too hard. In the previous PR I wrote a custom `Deserialize` implementation, which was way overkill. `serde` offers attributes which handle most of the part, anyway. If the team thinks this should be included I can write a new PR. This time I'd appreciate it if people could tell me where the tests should go, and how to generate good test data (assuming there's a mechanism for that).

**Comment by rakita** [comment]
@lamafab that would be great if you can help us. Just make pull request on `dev` branch.

**Comment by pedrobranco** [comment]
Any news on this breaking change?

**Comment by lamafab** [comment]
@pedrobranco I did not start with it yet, sorry.

**Comment by rakita** [comment]
@jomuel please dont forget to update our wiki: https://openethereum.github.io/JSONRPC-parity-module
repo is here: https://github.com/openethereum/openethereum.github.io
and close this issue when you finish.
