### ISSUE TITLE
openethereum stoped  and dont start

### ISSUE THREAD

**Issue by mtb-pro** [openethereum/openethereum#161]
how to fix this problem?

- **OpenEthereum version (>=3.0.1)**: 0.0.0
- **Operating system**: Linux
- **Fully synchronized**:  yes
- **Network**: ethereum
- **Restarted**: yes

Started openethereum Ethereum Daemon.
 openethereum[6867]: Loading config file from /root/.local/share/io.parity.ethereum/config.toml
 openethereum[6867]: Option '--no-dapps' has been removed and is no longer supported.
 openethereum[6867]: 2020-12-10 22:42:41  Starting OpenEthereum/v3.0.1-stable-8ca8089-20200601/x86_64-unknown-linux-gnu/rustc1.43.1
 openethereum[6867]: 2020-12-10 22:42:41  Keys path /root/.local/share/io.parity.ethereum/keys/ethereum
 openethereum[6867]: 2020-12-10 22:42:41  DB path /root/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
 openethereum[6867]: 2020-12-10 22:42:41  State DB configuration: fast
 openethereum[6867]: 2020-12-10 22:42:41  Operating mode: active

**Comment by roninkaizen** [comment]
edit the  /root/.local/share/io.parity.ethereum/config.toml
and uncomment the --no-dapps
or simply erase it from the config-
then the error notice disappears

**Comment by rakita** [comment]
It seems same problem as #69, I concluded this from this comment https://github.com/openethereum/openethereum/issues/163#issuecomment-743732897
