### ISSUE TITLE
openethereum synced with errors

### ISSUE THREAD

**Issue by Bombommi** [openethereum/openethereum#163]
Hello, i have this error

>Dec 10 20:28:04 instance-2 openethereum[82002]: 2020-12-10 20:28:04 UTC Syncing #11427046 0xc16bвЂ¦1080     1.00 blk/s  148.2 tx/s   12.5 Mgas/s      0+    5 Qed  #11427327   36/50 peers      >
Dec 10 20:28:08 instance-2 openethereum[82002]: 2020-12-10 20:28:08 UTC Panic occured, see stderr for details
Dec 10 20:28:08 instance-2 openethereum[82002]: ====================
Dec 10 20:28:08 instance-2 openethereum[82002]: stack backtrace:
Dec 10 20:28:08 instance-2 openethereum[82002]:    0: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    1: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    2: <unknown>
Dec 10 20:27:03 instance-2 openethereum[82002]: 2020-12-10 20:27:03 UTC Syncing #11427046 0xc16bвЂ¦1080      NaN blk/s    NaN tx/s    NaN Mgas/s      0+   53 Qed  #11427327   35/50 peers      
>c 10 20:27:04 instance-2 openethereum[82002]: 2020-12-10 20:27:04 UTC Syncing #11427046 0xc16bвЂ¦1080     0.74 blk/s  116.9 tx/s    9.2 Mgas/s      0+   53 Qed  #11427327   35/50 peers      
>c 10 20:27:09 instance-2 openethereum[82002]: 2020-12-10 20:27:09 UTC Syncing #11427046 0xc16bвЂ¦1080     0.80 blk/s  102.8 tx/s   10.0 Mgas/s      0+   53 Qed  #11427327   34/50 peers      
>c 10 20:27:14 instance-2 openethereum[82002]: 2020-12-10 20:27:14 UTC Syncing #11427046 0xc16bвЂ¦1080     1.00 blk/s  121.4 tx/s   12.5 Mgas/s      0+   53 Qed  #11427327   35/50 peers      
>c 10 20:27:19 instance-2 openethereum[82002]: 2020-12-10 20:27:19 UTC Syncing #11427046 0xc16bвЂ¦1080     0.60 blk/s   70.4 tx/s    7.5 Mgas/s      0+   41 Qed  #11427327   35/50 peers      
>c 10 20:27:24 instance-2 openethereum[82002]: 2020-12-10 20:27:24 UTC Syncing #11427046 0xc16bвЂ¦1080     1.00 blk/s  159.6 tx/s   12.5 Mgas/s      0+   41 Qed  #11427327   35/50 peers      
>c 10 20:27:29 instance-2 openethereum[82002]: 2020-12-10 20:27:29 UTC Syncing #11427046 0xc16bвЂ¦1080     1.00 blk/s  169.2 tx/s   12.5 Mgas/s      0+   41 Qed  #11427327   35/50 peers      
>c 10 20:27:34 instance-2 openethereum[82002]: 2020-12-10 20:27:34 UTC Syncing #11427046 0xc16bвЂ¦1080     0.80 blk/s  145.6 tx/s   10.0 Mgas/s      0+   29 Qed  #11427327   35/50 peers      
>c 10 20:27:39 instance-2 openethereum[82002]: 2020-12-10 20:27:39 UTC Syncing #11427046 0xc16bвЂ¦1080     1.00 blk/s  140.2 tx/s   12.5 Mgas/s      0+   29 Qed  #11427327   35/50 peers      
>c 10 20:27:44 instance-2 openethereum[82002]: 2020-12-10 20:27:44 UTC Syncing #11427046 0xc16bвЂ¦1080     1.00 blk/s   96.6 tx/s    9.9 Mgas/s      0+   17 Qed  #11427327   35/50 peers      
>c 10 20:27:49 instance-2 openethereum[82002]: 2020-12-10 20:27:49 UTC Syncing #11427046 0xc16bвЂ¦1080     1.00 blk/s  176.8 tx/s   12.4 Mgas/s      0+   17 Qed  #11427327   35/50 peers      
>c 10 20:27:54 instance-2 openethereum[82002]: 2020-12-10 20:27:54 UTC Syncing #11427046 0xc16bвЂ¦1080     1.00 blk/s  120.6 tx/s   12.5 Mgas/s      0+   17 Qed  #11427327   36/50 peers      
>c 10 20:27:59 instance-2 openethereum[82002]: 2020-12-10 20:27:59 UTC Syncing #11427046 0xc16bвЂ¦1080     0.80 blk/s   98.0 tx/s    9.9 Mgas/s      0+    5 Qed  #11427327   36/50 peers      
>c 10 20:28:04 instance-2 openethereum[82002]: 2020-12-10 20:28:04 UTC Syncing #11427046 0xc16bвЂ¦1080     1.00 blk/s  148.2 tx/s   12.5 Mgas/s      0+    5 Qed  #11427327   36/50 peers      
>c 10 20:28:08 instance-2 openethereum[82002]: 2020-12-10 20:28:08 UTC Panic occured, see stderr for details
Dec 10 20:28:08 instance-2 openethereum[82002]: ====================
Dec 10 20:28:08 instance-2 openethereum[82002]: stack backtrace:
Dec 10 20:28:08 instance-2 openethereum[82002]:    0: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    1: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    2: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    3: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    4: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    5: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    6: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    7: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    8: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    9: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   10: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   11: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   12: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   13: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   14: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   15: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   16: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   17: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   18: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   19: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   20: start_thread
Dec 10 20:28:08 instance-2 openethereum[82002]:   21: __clone
Dec 10 20:28:08 instance-2 openethereum[82002]: Thread 'IO Worker #0' panicked at 'State root of best block header always valid.: InvalidStateRoot(0xdeab52cf9818c3f5052a6f178fedef7a366c75217>
Dec 10 20:28:08 instance-2 openethereum[82002]: This is a bug. Please report it at:
Dec 10 20:28:08 instance-2 openethereum[82002]:     https://github.com/openethereum/openethereum/issues/new
Dec 10 20:28:08 instance-2 openethereum[82002]: 2020-12-10 20:28:08 UTC Finishing work, please wait...
Dec 10 20:28:08 instance-2 openethereum[82002]: 2020-12-10 20:28:08 UTC Panic occured, see stderr for details
Dec 10 20:28:08 instance-2 openethereum[82002]: ====================
Dec 10 20:28:08 instance-2 openethereum[82002]: stack backtrace:
Dec 10 20:28:08 instance-2 openethereum[82002]:    0: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    1: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    2: ### <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    3: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    4: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    5: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    6: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    7: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    8: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:    9: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   10: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   11: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   12: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   13: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   14: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   15: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   16: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   17: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   18: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   19: <unknown>
Dec 10 20:28:08 instance-2 openethereum[82002]:   20: start_thread
Dec 10 20:28:08 instance-2 openethereum[82002]:   21: __clone
Dec 10 20:28:08 instance-2 openethereum[82002]: Thread 'IO Worker #3' panicked at 'State root of best block header always valid.: InvalidStateRoot(0xdeab52cf9818c3f5052a6f178fedef7a366c75217>
Dec 10 20:28:08 instance-2 openethereum[82002]: This is a bug. Please report it at:
Dec 10 20:28:08 instance-2 openethereum[82002]:     https://github.com/openethereum/openethereum/issues/new
Dec 10 20:28:15 instance-2 openethereum[82002]: Error: 1
Dec 10 20:28:15 instance-2 systemd[1]: eth1.service: Main process exited, code=exited, status=1/FAILURE
Dec 10 20:28:15 instance-2 systemd[1]: eth1.service: Failed with result 'exit-code'.
Dec 10 20:28:15 instance-2 systemd[1]: eth1.service: Scheduled restart job, restart counter is at 1.
Dec 10 20:28:15 instance-2 systemd[1]: Stopped openethereum eth1 service.

But after two restarts openethereum node synced. BUT i cannot start beacon-chain lighthouse because it start with error if i use my localhost node 
>Dec 10 21:44:33 instance-2 lighthouse[85132]: Dec 10 21:44:33.369 INFO UPnP not available error: IO error: Resource temporarily unavailable (os error 11), service: UPnP
Dec 10 21:44:35 instance-2 lighthouse[85132]: Dec 10 21:44:35.773 ERRO Failed to update eth1 cache error: Failed to update eth1 cache: "FailedToInsertDeposit(NonConsecutive { log_index: 31373, expected: 0 })", retry_millis: 7000, service: eth1_rpc

If i use infura.io third party nodes, lighthouse start with out problems.

**Comment by mtb-pro** [comment]
I have the same problem
OpenEthereum version 3.1.0

Syncing #11433978

**Comment by rakita** [comment]
Related to #69
