### ISSUE TITLE
Panic when synching

### ISSUE THREAD

**Issue by osoWP95** [openethereum/openethereum#164]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: Ubuntu 20.04
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum 
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I started ethereum with the following command: ./target/release/openethereum

When trying to sync I got the following panic: 

stack backtrace:
   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at library/std/src/panicking.rs:483
   5: core::panicking::panic_fmt
             at library/core/src/panicking.rs:85
   6: core::panicking::panic
             at library/core/src/panicking.rs:50
   7: linked_hash_map::LinkedHashMap<K,V,S>::insert
   8: lru_cache::LruCache<K,V,S>::insert
   9: ethcore_network_devp2p::discovery::Discovery::on_packet
  10: <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::stream_readable
  11: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  12: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at library/std/src/sys/unix/thread.rs:87
  16: start_thread
  17: __clone

Thread 'IO Worker #1' panicked at 'attempted to leave type `linked_hash_map::Node<ethereum_types::H512, (node_table::NodeEndpoint, std::time::Instant)>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658

**Comment by jmb-42** [comment]
I experienced this issue as well. They fixed it in the `dev` branch. You can switch from the `dev` branch by using the following command in the root of the openethereum directory on your filesystem.

`git checkout dev`

You will have to build from source again.

`cargo build --release --features final`

**Comment by osoWP95** [comment]
Thanks. I'll try it and provide feedback.

**Comment by rakita** [comment]
Related to rust `1.48`, as said fix is in `dev` branch

**Comment by osoWP95** [comment]
I was able to get past the issue. Thank you for the help.
