### ISSUE TITLE
Error with openethereum I'm frozen at the same block

### ISSUE THREAD

**Issue by m1mishamax** [openethereum/openethereum#166]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 0.0.0
- **Operating system**: Windows
- **Installation**: downloaded exe file from zip
- **Fully synchronized**: yes or almost fully(With warp)
- **Network**: ethereum 
- **Restarted**:   yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

So I forgot to pay for my internet bill and... And it went off. When it happen windows was notifying that I had dns not reachable. Anyways I got the error. When I'm trying to restart this happens. How to reproduce? Hm... Don't know, but try to give bad DNS address maybe that will do the trick(Since it can probably replicate the no internet situation)

[openethereum.docx](https://github.com/openethereum/openethereum/files/5681529/openethereum.docx)

**Comment by mtb-pro** [comment]
I have the same problem
OpenEthereum version 3.1.0

  Syncing  loop at #11433978

**Comment by rakita** [comment]
duplicate for: #69
