### ISSUE TITLE
Node worker blockId nonce issue

### ISSUE THREAD

**Issue by nlandeker** [openethereum/openethereum#171]
- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: Linux
- **Installation**: build from github
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

**actual**
Node is running and sometimes drops this error:
Dec 14 11:16:19 ethereum-mainent openethereum[115895]: 2020-12-14 11:16:19 UTC Panic occured, see stderr for details
Dec 14 11:16:19 ethereum-mainent openethereum[115895]: ====================
Dec 14 11:16:19 ethereum-mainent openethereum[115895]: stack backtrace:
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    0: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    1: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    2: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    3: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    4: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    5: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    6: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    7: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    8: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:    9: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   10: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   11: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   12: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   13: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   14: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   15: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   16: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   17: <unknown>
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   18: start_thread
Dec 14 11:16:19 ethereum-mainent openethereum[115895]:   19: __clone
Dec 14 11:16:19 ethereum-mainent openethereum[115895]: Thread 'IO Worker #0' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore/src/client/traits.rs:93

**Comment by nlandeker** [comment]
Please note that node is stuck on block #11435953 and unable to move forward.

**Comment by darzyx** [comment]
I just had this same exact issue pop up for me today.

**Comment by rakita** [comment]
This is fixed in 3.1.1 release.
