### ISSUE TITLE
Node detected invalid state root, stuck since

### ISSUE THREAD

**Issue by lgrapenthin** [openethereum/openethereum#177]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**:  Linux
- **Installation**: cmdline
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
Yesterday the node apparently took offense with a block:

> 
> 2020-12-15 21:37:12  Imported #11459875 0xd2b6…cf34 (144 txs, 12.43 Mgas, 2055 ms, 35.58 KiB)
> 2020-12-15 21:37:46    #11459394   26/50 peers    366 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs
> 2020-12-15 21:38:05  Block import failed for #11459877 (0xc9a7…240a)
> 
> 

It then goes on to print info about that

> Error: Error(Trie(InvalidStateRoot(0xc4cf167250f63d3045796af1d550c9dcbcf52b5edd8997c28b9453146d588db8)), State { next_error: None, backtrace: InternalBacktrace { backtr\
> ace: None } })
> 2020-12-15 21:38:06
> Bad block detected: Error(Trie(InvalidStateRoot(0xc4cf167250f63d3045796af1d550c9dcbcf52b5edd8997c28b9453146d588db8)), State { next_error: None, backtrace: InternalBackt\
> race { backtrace: None } })
> 

Since then, output looks like the following excerpt (> 12h now).
> 
> 2020-12-15 22:52:11    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:52:41    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:53:11    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:53:41    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:54:11    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:54:41    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:54:46  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459875   33/50 peers    455 MiB chain  0 bytes queue  R\
> PC:  1 conn,    0 req/s,  147 µs                                                                                                                                         
> 2020-12-15 22:55:16    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:55:46    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:56:16    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:56:46    #11459846   32/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:57:16    #11459846   33/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:57:46    #11459846   33/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:58:16    #11459846   33/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:58:46    #11459846   33/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:59:16    #11459846   33/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 22:59:46    #11459846   31/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 23:00:16    #11459846   31/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 23:00:47    #11459846   31/50 peers    455 MiB chain  0 bytes queue  RPC:  1 conn,    0 req/s,  147 µs                                                        
> 2020-12-15 23:01:01  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459868   32/50 peers    455 MiB chain  0 bytes queue  R\
> PC:  1 conn,    0 req/s,  147 µs                                                                                                                                         
> 2020-12-15 23:01:06  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459868   32/50 peers    455 MiB chain  0 bytes queue  R\
> PC:  1 conn,    0 req/s,  147 µs                    

After a restart it looks like this, where in the meantime the stuck block has changed from #11459846 to #11459845. It appears the block number after Qed is going down and back up again around the number of the stuck block.

> 2020-12-16 12:37:29  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459859   23/25 peers      1 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:37:59    #11459877   25/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:38:04  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459857   26/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:38:34    #11459877   25/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:38:44  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459856   27/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:14    #11459877   25/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:19  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459850   28/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:24  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459850   28/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:29  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459850   28/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:59    #11459877   24/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:40:39    #11459877   23/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:40:39    #11459877   23/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:41:09  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459868   15/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:41:14  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459844   18/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:41:19  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459748   16/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:41:24  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459875   16/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:42:05    #11459877   14/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 
> 
> 2020-12-16 12:37:29  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459859   23/25 peers      1 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:37:59    #11459877   25/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:38:04  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459857   26/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:38:34    #11459877   25/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:38:44  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459856   27/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:14    #11459877   25/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:19  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459850   28/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:24  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459850   28/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:29  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459850   28/50 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:39:59    #11459877   24/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:40:39    #11459877   23/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:40:39    #11459877   23/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:41:09  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459868   15/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:41:14  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459844   18/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:41:19  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459748   16/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:41:24  Syncing #11459875 0xd2b6…cf34     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11459875   16/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 2020-12-16 12:42:05    #11459877   14/25 peers      6 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
> 
> 

In between restarts I have deleted the nodes.json file, as per rec. elsewhere.
>

**Comment by dylanwinn** [comment]
I am getting a similar error for a different block number:

```
2020-12-16 18:26:10 UTC Block import failed for #11441029 (0x8179…06b3)
Error: Error(Trie(InvalidStateRoot(0x26888ecb21149a2511f9d6199ad806e71e7d990b793d2e7328f87c53d312a3e3)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

**Comment by rakita** [comment]
There is issue #69 that is fixed in dev/main branches, but you will need to clean db and resync again.

**Comment by lgrapenthin** [comment]
Please cut a new release.

**Comment by rakita** [comment]
There is draft for 3.1.1-rc.1 containing this fix: https://github.com/openethereum/openethereum/releases/tag/v3.1.1-rc.1
