### ISSUE TITLE
Can't get Open Ethereum binary release to run as service w/ systemd

### ISSUE THREAD

**Issue by aacostarua** [openethereum/openethereum#179]
- **OpenEthereum version (>=3.1.0)**: latest release
- **Operating system**: Linux
- **Installation**: binary release
- **Fully synchronized**: yes
- **Network**: goerli
- **Restarted**: yes

Works on normal command line with ./openethereum...

Service file doesn't work it fails immediately with no error log (just code exited).  Prysm is working fine as a service.  I was wondering if I should reference the cmd to run the binary in a .sh file and link that to the service file like Prysm does (I believe).

I know this isn't just Open Ethereum but this is critical for most getting a stable auto restarting node for ETH 2.  Thank you I'd appreciate it if you give me your input.

**Comment by roninkaizen** [comment]
hello  aacostarua,
reading your issue may i kindly ask
if you altered/configured the location of the binary within the service-file?
i have created my own openethereum.service file
and uploaded it, works fine with an appropriate config.toml file within the directory $HOME/.local/share/openethereum/

`[Unit]
Description=OpenEthereum Daemon
After=network.target

[Service]
# run as root, set base_path in config.toml
ExecStart=/home/ubuntu/openethereum-dev/target/release 
# To run as user, comment out above and uncomment below, fill in user and group
# picks up users default config.toml in $HOME/.local/share/openethereum/
# User=username
# Group=groupname
# ExecStart=/usr/bin/openethereum	
Restart=on-failure

# Specifies which signal to use when killing a service. Defaults to SIGTERM.
# SIGHUP gives openethereum time to exit cleanly before SIGKILL (default 90s)
KillSignal=SIGHUP

[Install]
WantedBy=default.target`

**Comment by aacostarua** [comment]
Thanks a lot for all the help! @roninkaizen
