### ISSUE TITLE
the trait bound `primitive_types07::U256: rlp04::Encodable` is not satisfied

### ISSUE THREAD

**Issue by alianse777** [openethereum/openethereum#180]
- **OpenEthereum version 3.1.0
- **Operating system**:  Linux
- **Installation**: built from source
- **Rustc**: 1.48.0 stable

I'm trying to compile openethereum from source release 3.1.0 and I'm getting the following error:

        error[E0277]: the trait bound `primitive_types07::U256: rlp04::Encodable` is not satisfied
            --> ethcore/sync/src/chain/mod.rs:1282:23
             |
        1282 |         packet.append(&primitive_types07::U256(chain.total_difficulty.0));
             |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rlp04::Encodable` is not implemented for `primitive_types07::U256`
        
        error[E0277]: the trait bound `primitive_types07::H256: rlp04::Encodable` is not satisfied
            --> ethcore/sync/src/chain/mod.rs:1283:23
             |
        1283 |         packet.append(&primitive_types07::H256(chain.best_block_hash.0));
             |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rlp04::Encodable` is not implemented for `primitive_types07::H256`
        
        error[E0277]: the trait bound `primitive_types07::H256: rlp04::Encodable` is not satisfied
            --> ethcore/sync/src/chain/mod.rs:1284:23
             |
        1284 |         packet.append(&primitive_types07::H256(chain.genesis_hash.0));
             |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rlp04::Encodable` is not implemented for `primitive_types07::H256`
        
        warning: use of deprecated associated function `ethereum_types::H256::new`: use `fixed_hash`::zero constructor instead
            --> ethcore/sync/src/chain/mod.rs:1291:49
             |
        1291 |             let manifest_hash = manifest.map_or(H256::new(), |m| keccak(m.into_rlp()));
             |                                                 ^^^^^^^^^
        
        error[E0277]: the trait bound `primitive_types07::H256: rlp04::Encodable` is not satisfied
            --> ethcore/sync/src/chain/mod.rs:1292:27
             |
        1292 |             packet.append(&primitive_types07::H256(manifest_hash.0));
             |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rlp04::Encodable` is not implemented for `primitive_types07::H256`

**Comment by rakita** [comment]
I would try to delete everything and build again.
