### ISSUE TITLE
The eth_sendTransaction endpoint does nothing over ipc.

### ISSUE THREAD

**Issue by ytrezq** [openethereum/openethereum#197]
Just tried to sent this transaction using my full OpenEthereum 3.1.1-rc.1 full archival node.

    {"method":"eth_sendTransaction","params":[{"from":"0x395be1c1eb316f82781462c4c028893e51d8b2a5","to":"0x3582F0e90a11D1e021B48E70421770A063CC9e57","gas":"0x249be","data":"0xf14fcbc8c210a7fdb16411e7121e009005461b4eb8fa58d02adff7e9f10230442ec71ad8"}],"id":1,"jsonrpc":"2.0"}
using

    socat - UNIX-CONNECT:/home/liveuser/.local/share/openethereum/jsonrpc.ipc

After having imported the required private key previously. And then nothing is written on the socket even if left open during several hours.

There’s a line in the log stating that `event.loop0` signed and sent the transaction but nothing happens on the network too.

I know that I should sign the transactions myself, but this requires serializing and deserializing several times in json and raw transaction both in my client and the OpenEthereum node which node good for transaction Fontrunning and where latency is at prenium.
Not to mention there’s no C/C++ library for assisting with such Ethereum internals.

Is it the expected behavior? I didn t tried on Websocket or the http endpoint.

**Comment by rakita** [comment]
What is the older version that you were using and did it work there for you, and can you check if you have same behavior on 3.1.0?

**Comment by ytrezq** [comment]
@rakita it did not worked too under 3.1.0. For testing 3.0, I would need a tool for downgrading the database.

I m thinking the issue is well reproductible, just create an account and replace the `From:` field in my transaction.

**Comment by rakita** [comment]
It works for me. Some steps
* created account with ./openethereum account new
* enabled all API modules with `--jsonrpc-apis="all"`
* checked pw with `curl --data '{"method":"parity_testPassword","params":["0x056967db3159f60ssssssscaaaaaaaa","hunter2"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`
* unlocked account: `curl --data '{"method":"personal_unlockAccount","params":["0x056967db3159f608cb897ddddddefc9daaaaaaaaaa","hunter2",null],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`
* send transaction for signing: `curl --data '{"method":"eth_sendTransaction","params":[{"from":"0x056967db3159f608cb8975a5d3cefc9d5f8ed0a3","to":"0xd46e8dd67c5d32be8058bb8eb970870f07244567","gas":"0x76c0","gasPrice":"0x9184e72a000","value":"0x9184e72a","data":"0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545` . I don't have sufficient funds, but signing passes and I got response. If account is not open it will not return any response, this is responding to your case.

**Comment by ytrezq** [comment]
@rakita you didn t do it over ipc. Shouldn t it print an error message for passwordless unlocked accounts?

**Comment by ytrezq** [comment]
I’m having the same problem for `personal_unlockAccount `which returns nothing over ipc.

**Comment by ytrezq** [comment]
{"method":"personal_unlockAccount","params":["0x395be1c1eb316f82781462c4c028893e51d8b2a5","",31536000],"id":1,"jsonrpc":"2.0"}

**Comment by roninkaizen** [comment]
i agree with rakita but offer to join the discord chat,
to describe your config-values or cli-subset-
i just opened ipc and did it successful like rakita wrote-
so it must be something with the config from my perspective- feel invited to solve your question more interactive :)
Merry Christmas @ytrezq

**Comment by ytrezq** [comment]
@roninkaizen did you even tried `{"method":"personal_unlockAccount","params":["your_own_account","",31536000],"id":1,"jsonrpc":"2.0"}`  using "" as password?

**Comment by rakita** [comment]
Generally speaking, accounts are deprecated in OE. If you want to continue, create a new account with my steps to see if it is working for you

**Comment by ytrezq** [comment]
@rakita it seems the underlying issue is using empty passwords.
