### ISSUE TITLE
Openethereum panics when syncing block

### ISSUE THREAD

**Issue by xenoliss** [openethereum/openethereum#199]
- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: Windows 
- **Installation**: built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum 
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**actual**: Trying to sync the blockchain causes the client to randomly panic with the given ouptut:

```
2020-12-26 11:42:30  Syncing #11528757 0xd76f…3854     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #11528756    8/25 peers    253 KiB chain  0 bytes queue  RPC:
  0 conn,    0 req/s,    0 µs
2020-12-26 11:42:31  Block import failed for #11528844 (0x1524…4ef9)
Error: Error(Trie(InvalidStateRoot(0x0010df8abe765d50fd526f93da9866ac1e01be134252ef2a917b387ddebc4c83)), State { next_error: None, backtrace: InternalBacktrace { backtrace
: None } })
2020-12-26 11:42:31  Panic occured, see stderr for details


====================

stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: BaseThreadInitThunk
  21: RtlUserThreadStart


Thread 'IO Worker #2' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', ethcore\src
\client\traits.rs:93
```
The next hundred/thousands lines are then dumps of this error : `2020-12-26 11:42:31
Bad block detected: Error(Trie(InvalidStateRoot(0x0010df8abe765d50fd526f93da9866ac1e01be134252ef2a917b387ddebc4c83)), State { next_error: None, backtrace: InternalBacktrac
e { backtrace: None } })` with a big chunk of hexa.

After this point, the syncing process can not recover from this step and you need to resync the entire blockchain (unless you have a valid backup to start from).

**expected behavior**: the client should not panic during the syncing process.

**steps to reproduce** : nothing special : `openethereum.exe --db-path=./ --cache-size=8192` and wait until it panics (often after it caught up the head or really close to). I have been facing this issue twice now.

**Comment by rakita** [comment]
It is issue #69 that happens on initial sync. It is fixed in 3.1.1-rc.1, but you will need to resync again.
