### ISSUE TITLE
Links to issues in source code point nowhere

### ISSUE THREAD

**Issue by nazar-pc** [openethereum/openethereum#200]
#31 renamed links automatically and broke some of them at least.

For instance this leads to nowhere:
https://github.com/openethereum/openethereum/blob/27cd034ba61e47bf64c83475ac3051eac20c218e/.cargo/config#L1-L3

BTW, similarly some links from https://openethereum.github.io also point to nowhere.

Would be nice to have them fixed.

**Comment by rakita** [comment]
it is pointing to parity-ethereum repo: https://github.com/openethereum/parity-ethereum/issues/6643

**Comment by nazar-pc** [comment]
It does, but would be nice to have link working in the first place

**Comment by rakita** [comment]
https://github.com/openethereum/openethereum/pull/202
