### ISSUE TITLE
Can't filter transactions with RPC API

### ISSUE THREAD

**Issue by sebm81** [openethereum/openethereum#201]
- **OpenEthereum version (>=3.1.0)**:  3.1.0 and 3.1.1-rc1
- **Operating system**:  Ubuntu 20.04
- **Installation**:  from precompiled zip file
- **Fully synchronized**: yes
- **Network**: ethereum mainnet
- **Restarted**:  yes

actual:

I want to filter the pending transactions with the "parity_pendingTransactions" method, but the filtering doesn't work.
Please see my request and response below. 

Request:
`curl -X POST --data '{"jsonrpc":"2.0","method":"parity_pendingTransactions","params":[null,{"from": { "eq": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984" }}],"id":73}'  -H "Content-Type: application/json" -X POST 192.168.1.57:8545 | jq
`

Response:
```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32602,
    "message": "Invalid parameters: Expected from 0 to 1 parameters.",
    "data": "\"Got: 2\""
  },
  "id": 73
}
```

I found the following previous report, which was similar but this is already closed: https://github.com/openethereum/parity-ethereum/issues/11189 
I used the same request as used in the issue 11189 and got the following results, which are the same results as  in the issue 11189:

Request:
`curl --data '{"method":"parity_pendingTransactions","params":[{"from":{"eq":"0x5f3dffcf347944d3739b0805c934d86c8621997f"},"to": {"eq":"0xe8b2d01ffa0a15736b2370b6e5064f9702c891b6"}}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST 192.168.1.57:8545 | jq`

Response:

```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32602,
    "message": "Invalid params: invalid type: map, expected usize."
  },
  "id": 1
}
```

expected:
I'm expecting a filtered response with the pending transactions.

**Comment by rakita** [comment]
Duplicate: #159

**Comment by rakita** [comment]
closing duplicate
