### ISSUE TITLE
Not connecting to peers

### ISSUE THREAD

**Issue by Code0x2** [openethereum/openethereum#209]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: Windows
- **Installation**: executable file
- **Fully synchronized**: no 
- **Network**: mainnet
- **Restarted**: yes

I have --min-peers set to 7000 and --max-peers set to 12500. Expected behavior is that it will attempt to connect to 7000 peers and maintain the connection. However after running for a while it is only connected to 50 peers.

**Comment by roninkaizen** [comment]
try 1000 and 2000 instead,
and visit afterward the above mentioned channel :)

**Comment by rakita** [comment]
It is not relevant to have as many peers as that.
