### ISSUE TITLE
Update uint package to v0.8

### ISSUE THREAD

**Issue by varasev** [openethereum/openethereum#212]
In the year 2019 we had an issue with slow `MULMOD` operations on our AuRa chains (POA Core, Sokol, xDai). This issue was solved by upgrading `uint` package to at least **v0.7.1** as @ordian wrote in https://github.com/poanetwork/parity-ethereum/pull/137#issuecomment-512506924 - we were making benchmark tests for math operations after the upgrade and got the significantly better performance.

The upgrade commit was https://github.com/openethereum/parity-ethereum/commit/dae5d75dd65d6a51873ecd9c1c4f159f49f2a9f3#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e

Before backporting to v3.1, OpenEthereum used `uint v0.8.2` in `OpenEthereum v3.0.1`: https://github.com/openethereum/parity-ethereum/blob/v3.0.1/Cargo.lock#L5326-L5328

But after backporting, there is an old `uint v0.4.1`: https://github.com/openethereum/openethereum/blob/v3.1.1-rc.1/Cargo.lock#L1389

The `ethereum-types v0.9` package [uses `uint v0.8.5`](https://github.com/openethereum/openethereum/blob/v3.1.1-rc.1/Cargo.lock#L1403) but it seems that `ethereum-types v0.9` is only used by the [`ethereum-forkid` package]( https://github.com/openethereum/openethereum/blob/v3.1.1-rc.1/Cargo.lock#L1371) and by [`parity-util-mem`](https://github.com/openethereum/openethereum/blob/v3.1.1-rc.1/Cargo.lock#L3213). Other packages use `ethereum-types 0.4.2` which uses the slow `uint 0.4.1`: https://github.com/openethereum/openethereum/blob/v3.1.1-rc.1/Cargo.lock#L1389

Please, update `uint` package to `v0.8` to increase math operations performance

**Comment by rakita** [comment]
We plan to upgrade libraries after berlin fork.

**Comment by ordian** [comment]
This might be quick an effort: https://github.com/openethereum/parity-ethereum/pull/10670

**Comment by rakita** [comment]
ethereum-types updated to 0.9.2
