### ISSUE TITLE
Recurring Issue Building Openethereum from Github Souce (Ubuntu 20.04)

### ISSUE THREAD

**Issue by osoWP95** [openethereum/openethereum#214]
- **OpenEthereum version (>=3.1.0)**: 3.1.1
- **Operating system**: Ubuntu 20.04
- **Installation**: built from source
- **Fully synchronized**: no 
- **Network**: didn't get that far...
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I have been attempting to build openethereum on Ubuntu 20.04 and I remain stuck. I installed a fresh version of Ubuntu 20.04 and all packages listed in the readme including Rustup, clang 10.0, clang++, pkg-config, file, make, cmake, Yasm, and Perl.  I updated Ubuntu using apt-get update and apt-get upgrade to ensure all libraries and dependencies were up to date. I have reinstalled the OS twice and gone through the installation of all packages and programs twice as well.

The command I used to build openethereum is below: 

**~/openethereum$ cargo build --release --features final**

It works every time until operations 603 / 610. I have truncated the first ~600 successful operations of output:

   Compiling parity-rpc v1.12.0 (/home/patrick/openethereum/rpc)
   Compiling ethcore-service v0.1.0 (/home/patrick/openethereum/ethcore/service)
   Compiling parity-rpc-client v1.4.0 (/home/patrick/openethereum/cli-signer/rpc-client)
   Compiling cli-signer v1.4.0 (/home/patrick/openethereum/cli-signer)

error: failed to run custom build command for `parity-rocksdb-sys v0.5.6`

Caused by:
  process didn't exit successfully: `/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-cbca316fcc02154d/build-script-build` (exit code: 101)
  --- stdout
  running: "cmake" "/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DWITH_SNAPPY=ON" "-DFAIL_ON_WARNINGS=OFF" "-DSNAPPY_INCLUDE_DIR=/home/patrick/openethereum/target/release/build/parity-snappy-sys-44f6753a64367ffb/out/build" "-DSNAPPY_LIBRARIES=/dev/null" "-DPORTABLE=ON" "-DCMAKE_INSTALL_PREFIX=/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is Clang 10.0.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- The ASM compiler identification is GNU
  -- Found assembler: /usr/bin/cc
  -- Found snappy: /dev/null  
  -- Found Git: /usr/bin/git (found version "2.25.1") 
  -- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER
  -- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER - Success
  -- Enabling RTTI in Debug builds only (default)
  -- Looking for malloc_usable_size
  -- Looking for malloc_usable_size - found
  -- Looking for sched_getcpu
  -- Looking for sched_getcpu - found
  -- Looking for pthread.h
  -- Looking for pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - found
  -- Found Threads: TRUE  
  -- JNI library is disabled
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build
  running: "cmake" "--build" "." "--target" "rocksdb" "--config" "Release" "--"
  /usr/bin/cmake -S/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb -B/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build --check-build-system CMakeFiles/Makefile.cmake 0
  /usr/bin/make -f CMakeFiles/Makefile2 rocksdb
  make[1]: Entering directory '/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build'
  /usr/bin/cmake -S/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb -B/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build --check-build-system CMakeFiles/Makefile.cmake 0
  /usr/bin/cmake -E cmake_progress_start /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles 29
  /usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/rocksdb.dir/all
  make[2]: Entering directory '/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build'
  /usr/bin/make -f CMakeFiles/build_version.dir/build.make CMakeFiles/build_version.dir/depend
  make[3]: Entering directory '/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build'
  cd /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/build_version.dir/DependInfo.cmake --color=
  Dependee "/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/build_version.dir/DependInfo.cmake" is newer than depender "/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/build_version.dir/depend.internal".
  Dependee "/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/build_version.dir/depend.internal".
  Scanning dependencies of target build_version
  make[3]: Leaving directory '/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build'
  /usr/bin/make -f CMakeFiles/build_version.dir/build.make CMakeFiles/build_version.dir/build
  make[3]: Entering directory '/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build'
  [  0%] Building CXX object CMakeFiles/build_version.dir/build_version.cc.o
  /usr/bin/c++  -DOS_LINUX -DROCKSDB_LIB_IO_POSIX -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_PLATFORM_POSIX -DROCKSDB_SCHED_GETCPU_PRESENT -DSNAPPY -I/home/patrick/openethereum/target/release/build/parity-snappy-sys-44f6753a64367ffb/out/build -I/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/util -I/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb -I/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/include -isystem /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/third-party/gtest-1.7.0/fused-src  -ffunction-sections -fdata-sections -fPIC -m64 -W -Wextra -Wall -Wsign-compare -Wshadow -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-strict-aliasing -std=c++11 -O2 -fno-omit-frame-pointer -momit-leaf-frame-pointer -O3 -DNDEBUG -fno-rtti   -o CMakeFiles/build_version.dir/build_version.cc.o -c /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/build_version.cc
  make[3]: Leaving directory '/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build'
  [  0%] Built target build_version
  /usr/bin/make -f CMakeFiles/rocksdb.dir/build.make CMakeFiles/rocksdb.dir/depend
  make[3]: Entering directory '/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build'
  cd /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build /home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/rocksdb.dir/DependInfo.cmake --color=
  Dependee "/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/rocksdb.dir/DependInfo.cmake" is newer than depender "/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/rocksdb.dir/depend.internal".
  Dependee "/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build/CMakeFiles/rocksdb.dir/depend.internal".
  Scanning dependencies of target rocksdb
  make[3]: Leaving directory '/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build'
  /usr/bin/make -f CMakeFiles/rocksdb.dir/build.make CMakeFiles/rocksdb.dir/build
  make[3]: Entering directory '/home/patrick/openethereum/target/release/build/parity-rocksdb-sys-17dc738f3a734569/out/build'
  [  0%] Building CXX object CMakeFiles/rocksdb.dir/cache/clock_cache.cc.o
  /usr/bin/c++  -DOS_LINUX -DROCKSDB_LIB_IO_POSIX -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_PLATFORM_POSIX -DROCKSDB_SCHED_GETCPU_PRESENT -DSNAPPY -I/home/patrick/openethereum/target/release/build/parity-snappy-sys-44f6753a64367ffb/out/build -I/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb -I/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/include -isystem /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/third-party/gtest-1.7.0/fused-src  -ffunction-sections -fdata-sections -fPIC -m64 -W -Wextra -Wall -Wsign-compare -Wshadow -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-strict-aliasing -std=c++11 -O2 -fno-omit-frame-pointer -momit-leaf-frame-pointer -O3 -DNDEBUG -fno-rtti   -o CMakeFiles/rocksdb.dir/cache/clock_cache.cc.o -c /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/cache/clock_cache.cc
  [  0%] Building CXX object CMakeFiles/rocksdb.dir/cache/lru_cache.cc.o
  /usr/bin/c++  -DOS_LINUX -DROCKSDB_LIB_IO_POSIX -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_PLATFORM_POSIX -DROCKSDB_SCHED_GETCPU_PRESENT -DSNAPPY -I/home/patrick/openethereum/target/release/build/parity-snappy-sys-44f6753a64367ffb/out/build -I/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb -I/home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/include -isystem /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/third-party/gtest-1.7.0/fused-src  -ffunction-sections -fdata-sections -fPIC -m64 -W -Wextra -Wall -Wsign-compare -Wshadow -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-strict-aliasing -std=c++11 -O2 -fno-omit-frame-pointer -momit-leaf-frame-pointer -O3 -DNDEBUG -fno-rtti   -o CMakeFiles/rocksdb.dir/cache/lru_cache.cc.o -c /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/cache/lru_cache.cc
 

**I have removed a bunch of gnereally repetitive stuff from here**

    ^
  In file included from /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/utilities/blob_db/blob_compaction_filter.cc:8:
  In file included from /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/utilities/blob_db/blob_compaction_filter.h:13:
  In file included from /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/utilities/blob_db/blob_db_impl.h:22:
  In file included from /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/db/db_iter.h:13:
  In file included from /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/db/db_impl.h:23:
  In file included from /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/db/compaction_job.h:24:
  /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/db/internal_stats.h:113:5: warning: declaration shadows a variable in namespace 'rocksdb' [-Wshadow]
      WRITE_WITH_WAL,
      ^
  /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-rocksdb-sys-0.5.6/rocksdb/include/rocksdb/statistics.h:198:3: note: previous declaration is here
    WRITE_WITH_WAL,       // Number of Write calls that request WAL
    ^
  8 warnings generated.
  make[2]: *** [CMakeFiles/Makefile2:2205: CMakeFiles/rocksdb.dir/all] Error 2
  make[1]: *** [CMakeFiles/Makefile2:2212: CMakeFiles/rocksdb.dir/rule] Error 2
  make: *** [Makefile:893: rocksdb] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2

  build script failed, must exit now', /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.42/src/lib.rs:861:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I have reinstalled my OS, deinstalled / reinstalled Rust and Rustup several times, as well as deinstalled and reinstalled Perl, Yasm, clang, pkg-config, file, make, and cmake at least two times each with the same results. I have also used the alternate command for building openethereum in the readme, **~/.cargo/bin/cargo build --release**. In between each attempt I have run **cargo clean** and / or deleted the entire ~/openethereun directory.

**Comment by roninkaizen** [comment]
sudo apt-get install openssl libudev-dev file curl jq
sudo apt install build-essential libssl-dev openssl git libclang-dev and
report back if helpful :)
otherwise, there is the discord channel

**Comment by osoWP95** [comment]
I'm happy to report this worked perfectly. Thank you!

**Comment by roninkaizen** [comment]
you are welcome!
