### ISSUE TITLE
Running openethereum without parameters causes a crash

### ISSUE THREAD

**Issue by chuacw** [openethereum/openethereum#218]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: v3.0.1-stable-8ca8089-20200601/x86_64-pc-windows-msvc/rustc1.43.1
- **Operating system**: Windows
- **Installation**: binary from https://github.com/openethereum/openethereum/releases/download/v3.1.0/openethereum-windows-v3.1.0.zip
- **Fully synchronized**: not applicable
- **Network**: not applicable.
- **Restarted**: no / yes

Running openethereum.exe without any parameters causes a crash.
See below:

```
2021-01-08 19:13:23  Starting OpenEthereum/v3.0.1-stable-8ca8089-20200601/x86_64-pc-windows-msvc/rustc1.43.1
2021-01-08 19:13:23  Keys path C:\Users\Administrator\AppData\Roaming\OpenEthereum\keys\ethereum
2021-01-08 19:13:23  DB path C:\Users\Administrator\AppData\Local\OpenEthereum\chains\ethereum\db\906a34e69aec8c0d
2021-01-08 19:13:23  State DB configuration: fast
2021-01-08 19:13:23  Operating mode: active


====================

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart


Thread 'fetch' panicked at 'cannot access native cert store: Custom { kind: InvalidData, error: BadDER }', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9
ec823\hyper-rustls-0.18.0\src\connector.rs:29

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new

```

**Comment by thorsteneb** [comment]
You're not starting the version that's inside that ZIP. Just tried it and it reports `Starting OpenEthereum/v3.1.0-stable-2072341-20201102/x86_64-windows-msvc/rustc1.47.0` 

Maybe verify where your executables are and that they are from that release.

**Comment by roninkaizen** [comment]
i agree in the observed version mismatch,
download and extract again, and report back if any better,
otherwise visit us at https://discord.gg/aRXRv4b5

**Comment by rakita** [comment]
Try with new version
