### ISSUE TITLE
 why openethereum syncing  stop "Qed Ancient" on 5155  [ Qed Ancient:#5155  ]

### ISSUE THREAD

**Issue by mtb-pro** [openethereum/openethereum#219]
- **OpenEthereum version (>=3.1.0)**: 0.0.0
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

this is my config

```
[parity]
mode = "active"
mode_timeout = 500
mode_alarm = 3600
no_persistent_txqueue = false

[network]
warp = true
warp_barrier = 11337727
min_peers = 20
max_peers = 60
max_pending_peers = 32

[rpc]
interface = "0.0.0.0"
cors = ["*"]
apis = ["web3", "eth", "net", "parity", "personal", "parity_accounts"]
keep_alive = true


[websockets]
disable = false
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces","personal"]

[ipc]
apis = ["web3", "eth","net", "parity", "personal"

[snapshots]


[footprint]
#disable_periodic = true
scale_verifiers = true
num_verifiers = 6
db_compaction = "ssd"
```

this is my sync process

: 2021-01-10 16:36:43  Syncing #11619988 0x2574…a960     0.40 blk/s   66.8 tx/s    5.0 Mgas/s      0+  523 Qed Ancient:#5155 LI:#11620512   34/60 peers      3 MiB chain   88 MiB queue  RPC:  0 conn,   17 req/s, 2573 µs

: 2021-01-10 16:36:48  Syncing #11619989 0xe3a7…0815     0.20 blk/s   27.2 tx/s    2.5 Mgas/s      0+  522 Qed Ancient:#5155 LI:#11620512   34/60 peers      3 MiB chain   88 MiB queue  RPC:  0 conn,   18 req/s, 2472 µs

: 2021-01-10 16:36:53  Syncing #11619991 0x2134…4f0f     0.40 blk/s   88.0 tx/s    5.0 Mgas/s      0+  520 Qed Ancient:#5155 LI:#11620512   35/60 peers      3 MiB chain   88 MiB queue  RPC:  0 conn,   16 req/s, 2449 µs

: 2021-01-10 16:36:58  Syncing #11619993 0xbb65…cabc     0.40 blk/s   69.0 tx/s    5.0 Mgas/s      0+  518 Qed Ancient:#5155 LI:#11620512   35/60 peers      3 MiB chain   88 MiB queue  RPC:  0 conn,   18 req/s, 2471 µs

: 2021-01-10 16:37:02  personal_sendTransaction is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.

: 2021-01-10 16:37:03  Syncing #11619996 0x2db9…99b5     0.60 blk/s  117.6 tx/s    7.4 Mgas/s      0+  515 Qed Ancient:#5155 LI:#11620512   35/60 peers      3 MiB chain   87 MiB queue  RPC:  0 conn,   18 req/s, 1172 µs

: 2021-01-10 16:37:08  Syncing #11619999 0x244a…1a49     0.60 blk/s   86.6 tx/s    4.9 Mgas/s      0+  512 Qed Ancient:#5155 LI:#11620512   35/60 peers      3 MiB chain   87 MiB queue  RPC:  0 conn,   19 req/s, 1163 µs

: 2021-01-10 16:37:13  Syncing #11620001 0x3f54…12fc     0.40 blk/s   68.6 tx/s    5.0 Mgas/s      0+  510 Qed Ancient:#5155 LI:#11620512   36/60 peers      3 MiB chain   86 MiB queue  RPC:  0 conn,   17 req/s, 1817 µs

: 2021-01-10 16:37:18  Syncing #11620003 0xa8b2…1429     0.40 blk/s   83.2 tx/s    5.0 Mgas/s      0+  508 Qed Ancient:#5155 LI:#11620512   36/60 peers      3 MiB chain   86 MiB queue  RPC:  0 conn,   18 req/s, 2435 µs

how to fix this?
please help me

**Comment by rakita** [comment]
Hi, syncing newest blocks has priority...

**Comment by mtb-pro** [comment]
my  Syncing completed but  Ancient process very slow .
how can i  increase speed "Ancient block process" ?

**Comment by mtb-pro** [comment]
: 2021-01-11 11:28:04  personal_unlockAccount is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.
: 2021-01-11 11:28:13  Imported #11633046 0x7144…d572 (176 txs, 12.48 Mgas, 1994 ms, 42.35 KiB)
: 2021-01-11 11:28:13   Ancient:#1946853 AB:#1829229   25/60 peers    502 MiB chain  0 bytes queue  RPC:  0 conn,    0 req/s, 1257 µs
: 2021-01-11 11:28:27  personal_sendTransaction is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.
: 2021-01-11 11:28:44  eth_sendTransaction is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.
: 2021-01-11 11:28:45  eth_signTransaction is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.
: 2021-01-11 11:28:47  Imported #11633047 0x5fda…33c5 (230 txs, 12.48 Mgas, 1585 ms, 59.49 KiB)
: 2021-01-11 11:28:56  eth_accounts is deprecated and will be removed in future versions: Account management is being phased out see #9997 for alternatives.
: 2021-01-11 11:29:04  Imported #11633049 0x6bb2…12bc (177 txs, 12.47 Mgas, 1584 ms, 37.15 KiB)
: 2021-01-11 11:29:18  Imported #11633050 0x9afc…8575 (77 txs, 12.50 Mgas, 1370 ms, 14.77 KiB)

**Comment by misaghamouie** [comment]
I have this problem too
In the synchronization process node
Synchronization speed of old blocks is very slow
I want to know how can I increase the sync speed?
Sync takes days at this speed

**Comment by roninkaizen** [comment]
i found a ultralight increase of speed with setting --scale-verifiers --num-verifiers=2/4/8/16
and it also helped to raise the min-peers value to 30,
if you like to try it out and report on Discord-OpenEthereum-support?

**Comment by mtb-pro** [comment]
Thanks @rakita 
Ancient process improved
