### ISSUE TITLE
Error serving connection: Error(BodyWrite, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })

### ISSUE THREAD

**Issue by misaghamouie** [openethereum/openethereum#225]
Syncing #11196866 0xe968…b379     0.80 blk/s  144.6 tx/s    9.9 Mgas/s      0+  355 Qed  #11197227   10/10 peers     23 MiB chain  330 MiB db   69 MiB queue    2 MiB sync  RPC:  0 conn,  178 req/s, 9758 µs
 Syncing #11196869 0x1eba…a7eb     0.60 blk/s   80.8 tx/s    7.5 Mgas/s      0+  355 Qed  #11197227   10/10 peers     23 MiB chain  330 MiB db   69 MiB queue    2 MiB sync  RPC:  0 conn,  159 req/s, 1823 µs
Syncing #11196872 0x0831…0b81     0.60 blk/s  109.0 tx/s    7.4 Mgas/s      0+  343 Qed  #11197227   10/10 peers     23 MiB chain  331 MiB db   67 MiB queue    2 MiB sync  RPC:  0 conn,  157 req/s, 9659 µs
**and receive  Error serving connection: Error(BodyWrite, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })**
how to can fix this???
@folsen @raucao @kavu @shanev

**Comment by roninkaizen** [comment]
description is too less detailled, 
could you also write more details about your environment, pls?

**Comment by misaghamouie** [comment]
You mean  my config؟

**Comment by roninkaizen** [comment]
yes, the config

**Comment by rakita** [comment]
Not enough information
