### ISSUE TITLE
Failing tests for 3.1.1

### ISSUE THREAD

**Issue by mdben1247** [openethereum/openethereum#242]
I am checking out `v3.1.1` and trying to run all the tests with:

`cargo test --all`

compilation fails for `wasm` and `parity-rpc`, because of missing files. Then trying with:

`cargo test --all --exclude wasm --exclude parity-rpc`

and one test is failing:
`test json_tests::runner::ethereum_json_tests ... FAILED`

**Comment by rakita** [comment]
you need to download git submodule:
`git submodules init`
`git submodules update`

**Comment by mdben1247** [comment]
Thanks. That works. I am now however, a bit lost on how to make pull requests for changes in the submodules. Concretely, I was upgrading ethereum-types on my fork and was done with the main git tree, but there are now plenty of changes needed in those testing submodules. Any ideas on a workflow for that?

**Comment by rakita** [comment]
`ethereum_jso_tests` should contaion only JSON files, and for wasm you can rebase on dev it is removed there.
