### ISSUE TITLE
ethereum-types upgrade guidance

### ISSUE THREAD

**Issue by mdben1247** [openethereum/openethereum#249]
Basing on `v3.1.1`, I upgraded `ethereum-types` to `0.9.2` (with a host of other stuff that was pulled along). When running tests (excluding `wasm` and `secret-store`) I get 4 failures for POA stuff that I can't figure out what could be wrong, everything else is OK though. But more troubling, when running this version live, some blocks (every 50 or so) would give InvalidStateRoot. I pretty much double checked everything. So, if anyone has any clues on where to look and tips for debugging this I'd appreciate it.

**Comment by rakita** [comment]
It is hard to tell devil is always in the detail. can you share what exactly failures are for POA it is maybe related. And you can make draft pull request for me to see changes, there are probably a lot of them. And can you move changes to be based on `dev` branch, this is the branch that we will use to create next release.

**Comment by mdben1247** [comment]
POA failures are
```
---- engines::authority_round::tests::rejects_future_block stdout ----
thread 'engines::authority_round::tests::rejects_future_block' panicked at 'assertion failed: engine.verify_block_external(&header).is_ok()', ethcore/src/engines/authority_round/mod.rs:2015:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- engines::authority_round::tests::proposer_switching stdout ----
thread 'engines::authority_round::tests::proposer_switching' panicked at 'assertion failed: engine.verify_block_external(&header).is_ok()', ethcore/src/engines/authority_round/mod.rs:1989:9

---- snapshot::tests::proof_of_authority::fixed_to_contract_only stdout ----
thread 'snapshot::tests::proof_of_authority::fixed_to_contract_only' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Snapshot(BadEpochProof(2)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', ethcore/src/snapshot/tests/proof_of_authority.rs:259:87

---- snapshot::tests::proof_of_authority::fixed_to_contract_to_contract stdout ----
thread 'snapshot::tests::proof_of_authority::fixed_to_contract_to_contract' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Snapshot(BadEpochProof(2)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', ethcore/src/snapshot/tests/proof_of_authority.rs:302:87

```
I'll make a PR. I am also going to rebase to dev. I wanted it on vanilla `v3.1.1` first, exactly because of the convenience to directly compare to it. Also, blocks that fail are order of thousands apart (not 50 as said above). these fail, for example: #11765799, #11766382, #11772110, others in between are fine.

**Comment by mdben1247** [comment]
I rebased on `dev`. Same 4 POA test fail, everything else OK. Same mainnet failures with `InvalidStateRoot` on some blocks. Should I make a pull request for this one and close the previous one that was `3.1.1` based?

**Comment by rakita** [comment]
Yes, open a new pull request. I will go over changes and see what is broken probably next week. Thank you for the great amount of work that you did!
