### ISSUE TITLE
personal_signTransaction often timeout when i have 500,000 keystore file in my OpenEthereum  node

### ISSUE THREAD

**Issue by past2017** [openethereum/openethereum#274]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version  v3.0.1
- **Operating system**:  Linux
- **Installation**: homebrew 
- **Fully synchronized**:   yes
- **Network**: ethereum 
- **Restarted**:   yes

personal_signTransaction often timeout when i have 500,000 keystore file in my OpenEthereum  node
my keystore file is in ssd disk and OpenEthereum   is installed in a cloud machine
so is there a way to improve this performance ?

**Comment by adria0** [comment]
@past2017, for questions please use https://discord.io/openethereum, issues are for bugs and feature requests.
