### ISSUE TITLE
Block sync stopped without any errors.

### ISSUE THREAD

**Issue by rlaace423** [openethereum/openethereum#277]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.1.1
- **Operating system**: Linux
- **Installation**: pre-built binary
- **Fully synchronized**: yes (warp=false, tracing="on", cache_size=4096)
- **Network**: ethereum
- **Restarted**: I'm trying to stop..

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Openethereum stopped sync without any errors in log about 4 hours before(2021-02-23T20:26:17). Process itself is still alive, but it doesn't sync new blocks since 11915524.
![image](https://user-images.githubusercontent.com/5516480/108934037-847b3500-768f-11eb-8996-edcdcdf48ff1.png)

As you can see in the above, It shows any errors. Now I'm trying to stop it, but It hangs now.
Also there's enough disk space **(total 1.2TiB, 51% used)**, ram usage **(total 1.2GiB, 7.34GiB used currently).**

When It stopped, other system indicators seem to be normal, See below.

![image](https://user-images.githubusercontent.com/5516480/108933786-1afb2680-768f-11eb-90e0-54748ee03dc8.png)
cpu usage

![image](https://user-images.githubusercontent.com/5516480/108933931-5564c380-768f-11eb-927c-12ee4a7f247c.png)
current disk usage

![image](https://user-images.githubusercontent.com/5516480/108933198-14b87a80-768e-11eb-9817-a8a3d62ddbf7.png)
Network Input(byte), Network Output(byte), Network Packet Input(count), Network Packet Output(count) in order.

![image](https://user-images.githubusercontent.com/5516480/108934370-2a2ea400-7690-11eb-8a0d-e1053ff0f5fb.png)
remaining RAM

How can I solve this? Is it okay that I kill openethereum process forcibly? Does it cause database break down?
Is there anyway to stop and start openethereum gracefully?

**Comment by Legogris** [comment]
I had this on 3.0.1 a handful of times - a process restart resolved it for me.

It's a bit troubling to say the least, though.

**Comment by ytrezq** [comment]
@rlaace423 just send `SIGINT` to the process for a gracefull shutdown.

**Comment by yorickdowne** [comment]
Well @ytrezq the point isn't (just) behavior on shutdown, the point is that OE stopped syncing mid-stream, without showing an error as to why, then refused to shut down. There's a 5-hour gap between "OE stopped syncing" and "OE was asked to shut down and did not"

**Comment by rakita** [comment]
This look a lot like: https://github.com/openethereum/parity-ethereum/issues/11758
I will backport  fix that replaces parking_lot mutex with a standard mutex

**Comment by islishude** [comment]
> I had this on 3.0.1 a handful of times - a process restart resolved it for me.
> 
> It's a bit troubling to say the least, though.

same issue on 2.5.13

**Comment by mdben1247** [comment]
> This look a lot like: [openethereum/parity-ethereum#11758](https://github.com/openethereum/parity-ethereum/issues/11758)
> I will backport fix that replaces parking_lot mutex with a standard mutex

Just want to note, that a `3.0.1` client with the above fix, replacing `parking_lot` with standard locks, has been been running smoothly for months now. I haven't noticed this in 3.1+ yet, however I haven't been running this version so extensively round the clock.

**Comment by roninkaizen** [comment]
agree with @mdben1247 
since 3.0.1 never saw it again-
and i run them 24/7/365-
try a higher version with altered `parking_lot`

**Comment by islishude** [comment]
> same issue on 2.5.13

update.

no such errors in recent days.

**Comment by rakita** [comment]
Fix is merged in dev, if this is repeated please reopen this issue.
