### ISSUE TITLE
EthKey and EthStore repos down?

### ISSUE THREAD

**Issue by raphadko** [openethereum/openethereum#278]
Both returning 404:

https://github.com/openethereum/openethereum/blob/main/accounts/ethkey
https://github.com/openethereum/openethereum/blob/main/accounts/ethstore

**Comment by rakita** [comment]
we have now a little bit nicer folder structure:
https://github.com/openethereum/openethereum/tree/main/crates/accounts

**Comment by raphadko** [comment]
Nice! Make sure you update the links on item 6 here: https://github.com/openethereum/openethereum
