### ISSUE TITLE
Add tests for snapshot validity checks

### ISSUE THREAD

**Issue by rphmeier** [openethereum/openethereum#2944]
- Canonical hashes
- too many blocks
- wrong best block hash, state root

**Comment by 5chdn** [comment]
This _tests_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant. If so, please comment below and add an assignee, or close otherwise.

**Comment by folsen** [comment]
@ngotchac Could you take a look at this and potentially add anything that's missing and still relevant? Otherwise please close the issue.

**Comment by ngotchac** [comment]
I don't think any tests have been added, so I guess these are still relevant.

**Comment by lazaridiscom** [comment]
possibly someone should add the skeletons of those tests in an branch, thus an external contributor can pick this easier up.

**Comment by adria0** [comment]
Closing issue due to its stale state.
