### ISSUE TITLE
Fast sync hanging at 5112/6743 for 2 days

### ISSUE THREAD

**Issue by cyrusadkisson** [openethereum/openethereum#296]
- v3.2.0-rc.1-stable-efb80e103
- Linux Ubuntu 20.04.1 
- built from source
- no
- ethereum
- yes
- non-ancient core i5 laptop with 8 GB of ram and a 500GB external USB 2.0 mechanical hard drive

I'm trying to fast sync the mainnet and failing. My first attempt hung at "Syncing snapshot 5350" for a few days so I killed the process and started over. Waited another couple of days and now the process is hung at 5112/6743. Has been for 48 hours.

25/25 peers... at one point I think I saw it try to do 26/50 peers. I hope I wasn't dreaming that. (It has scrolled away too far now.)

command: openethereum --chain ethereum --pruning fast --db-path /path/to/storage

**Comment by proprietary** [comment]
Yup, this is happening to me too. I built from source on the main branch. I increased the peers to 100. Still stalls. I restart the client, it syncs from 0/6772 to #/6772 where # is a random number, and then it stalls at that # for days.

I am also using a HDD, not a SSD. Maybe that is the problem.

**Comment by rakita** [comment]
Snapshot warping can be like that, server from who you are getting data can disconnect or your connection can break and leave you in that state. Duplicate from: https://github.com/openethereum/openethereum/issues/63
On another note, I think you will need SSD to be able to sync to highest block.

**Comment by cyrusadkisson** [comment]
Not sure why you'd close this. Regardless of whether openethereum can be made to recover from such a stuck state (which of course would be preferable), it should at least provide error information about what is happening and why. We still don't know if it's a peering issue or the mechanical USB drive that's causing the issues.

And why would an SSD help anyway? What does the program or OS care?
