### ISSUE TITLE
Stuck at  615/622: parity-rocksdb-sys(build)

### ISSUE THREAD

**Issue by Chris1992GR** [openethereum/openethereum#298]
Hello,

i have problem installing openethereum.

the build stucks at  parity-rocksdb-sys(build). It doestn continue.
At Task manager only the c++ compiler hast cpu load and the powershell and everything else doesnt.

file number  615/622

iam using power shell.
here is the output.
Thank you

PS C:\Users\Christian\openethereum> cargo build --release --features final
   Compiling parity-rocksdb-sys v0.5.6
warning: use of deprecated associated function `std::sync::atomic::AtomicBool::compare_and_swap`: Use `compare_exchange` or `compare_exchange_weak` instead
    --> crates\ethcore\src\engines\authority_round\mod.rs:1248:22
     |
1248 |                     .compare_and_swap(true, false, AtomicOrdering::SeqCst)
     |                      ^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `std::sync::atomic::AtomicBool::compare_and_swap`: Use `compare_exchange` or `compare_exchange_weak` instead
    --> crates\ethcore\src\engines\authority_round\mod.rs:1273:22
     |
1273 |                     .compare_and_swap(true, false, AtomicOrdering::SeqCst)
     |                      ^^^^^^^^^^^^^^^^

warning: use of deprecated associated function `std::sync::atomic::AtomicU64::compare_and_swap`: Use `compare_exchange` or `compare_exchange_weak` instead
  --> crates\ethcore\src\engines\instant_seal.rs:84:69
   |
84 |                 let prev_last_sealed_block = self.last_sealed_block.compare_and_swap(
   |                                                                     ^^^^^^^^^^^^^^^^

warning: use of deprecated associated function `std::sync::atomic::AtomicBool::compare_and_swap`: Use `compare_exchange` or `compare_exchange_weak` instead
   --> crates\ethcore\src\snapshot\service.rs:519:14
    |
519 |             .compare_and_swap(false, true, Ordering::SeqCst)
    |              ^^^^^^^^^^^^^^^^

warning: use of deprecated associated function `std::sync::atomic::AtomicBool::compare_and_swap`: Use `compare_exchange` or `compare_exchange_weak` instead
   --> crates\ethcore\src\verification\queue\mod.rs:184:14
    |
184 |             .compare_and_swap(false, true, AtomicOrdering::Relaxed)
    |              ^^^^^^^^^^^^^^^^

warning: use of deprecated associated function `std::sync::atomic::AtomicBool::compare_and_swap`: Use `compare_exchange` or `compare_exchange_weak` instead
   --> crates\ethcore\src\verification\queue\mod.rs:202:14
    |
202 |             .compare_and_swap(false, true, AtomicOrdering::Relaxed)
    |              ^^^^^^^^^^^^^^^^

warning: 6 warnings emitted

    Building [=======================> ] 615/622: parity-rocksdb-sys(build)

**Comment by rakita** [comment]
It seems that build is still in progress. wait it to finish
