### ISSUE TITLE
OpenEthereum v3.2.0 version still showing OpenEthereum v3.2.0-rc.1-stable

### ISSUE THREAD

**Issue by hhs19** [openethereum/openethereum#303]
- OpenEthereum version 3.2.0
- Operating system: Windows
- Installation: window binary zip from download page
- Fully synchronized: yes
- Network: ropsten
- Restarted: yes

I have download and run the latest Windows OpenEthereum version 3.2.0 but notice that the version still showing 3.2.0-rc.1-stable, are the Windows binary zip have the correct version of OpenEthereum?

Thank You

**Comment by rakita** [comment]
Hi, Can confirm it is correct code, i need to bump version.

**Comment by rakita** [comment]
version bumpen and new tag made
