### ISSUE TITLE
Implementing t8ntool for Consensus Tests

### ISSUE THREAD

**Issue by qbzzt** [openethereum/openethereum#340]
We have a huge repository of state tests in https://github.com/ethereum/tests/tree/develop/GeneralStateTests. Currently they are used primarily for geth, but we'd like to collaborate and add openethereum. The interface is running an executable, documented here: https://ethereum-tests.readthedocs.io/en/latest/t8ntool-ref.html . 

Anybody on your side would like to collaborate on this?

**Comment by rakita** [comment]
Hi, we already have integration with `ethereum/tests` that is part of our CI. git-submodule is in here: https://github.com/openethereum/openethereum/tree/main/crates/ethcore/res
and here is json configuration that tell us what folder from that repo are we going to run: https://github.com/openethereum/openethereum/blob/main/crates/ethcore/res/json_tests.json
It would be better if OE tests can be run as a separate executable that adheres with t8tool, but for now, I see this as low priority for us.
On other note, it seems that t8tool evm traces are made to favor geth https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3155.md but parity traces are mostly seen as standard, not sure what to think about that.

**Comment by qbzzt** [comment]
> Hi, we already have integration with `ethereum/tests` that is part of our CI. git-submodule is in here: https://github.com/openethereum/openethereum/tree/main/crates/ethcore/res
> and here is json configuration that tell us what folder from that repo are we going to run: https://github.com/openethereum/openethereum/blob/main/crates/ethcore/res/json_tests.json

Thank you. 

> It would be better if OE tests can be run as a separate executable that adheres with t8tool, but for now, I see this as low priority for us.

I agree. Compatibility at the `t8ntool` level would take a lot of work. I think it will be easier to create compatibility at the level of the `retesteth` command line interface. I'll probably work on that this weekend.

> On other note, it seems that t8tool evm traces are made to favor geth https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3155.md but parity traces are mostly seen as standard, not sure what to think about that.

I'm not involved in that, so you'd have to discuss it at https://ethereum-magicians.org/t/eip-3155-create-evm-trace-specification/5007. I'm probably going to write a translator simply because I'd want to be able to compare the vmtraces coming out of `geth` and `openethereum-evm`. If they diverge there's a problem.

Since neither of us wants to tackle the `t8ntool` problem, I think it's right to close this issue.

**Comment by qbzzt** [comment]
> It would be better if OE tests can be run as a separate executable that adheres with t8tool, but for now, I see this as low priority for us.

I decided to spend the time to do it. I now have a Node script that receives t8ntool input, uses that to create a state test file, runs the state test file with `openethereum-evm`, massages the output to make it look like t8ntool output, and sends it out. It can do most state tests.

What it still can't do, however, is handle tests that emit event logs. You don't expose `logsHash` and `logsBloom`, which I need to handle those tests. Can you please add these to the `--std-dump-json`, or make them available by other means?

    Thanks,
         Ori

**Comment by qbzzt** [comment]
@rakita, can you please help me? I'm trying to figure out where the logsHash calculation is in the code, but I don't know enough Rust.

**Comment by rakita** [comment]
@qbzzt I dont think that we have logs hash

**Comment by qbzzt** [comment]
I couldn't find it in the yellow paper either, so it might `geth` specific. @winsvega, does it appear in other clients such as besu? If not, can we replace it with the `logsBloom` that does appear in the yellow paper and is also a function of the logs?

**Comment by qbzzt** [comment]
BTW, @rakita , is there a reason the evm trace doesn't produce a memory dump? Is there a way to make it happen?

**Comment by rakita** [comment]
@qbzzt I think that this is not the best time to work on this, it would be best if you can delay this work for two months, things should probably become easier by then.

**Comment by qbzzt** [comment]
> @qbzzt I think that this is not the best time to work on this, it would be best if you can delay this work for two months, things should probably become easier by then.

Sure. Let's get back to this early July.
