### ISSUE TITLE
0x74742225422a46136dd36b1619b31e8ca7bc7b6e5597de6de85437fa87c98c3c

### ISSUE THREAD

**Issue by kacon18** [openethereum/openethereum#361]
Its been stuck for more than an hour.  I been charged ETH & did not get to the intended wallet.  Please complete the transaction or return ETH to 0x520BE45F52C0B044b2d777d06aDa63fBE08af160. 

Thank you.

**Comment by c0deright** [comment]
see #353

**Comment by dwjorgeb** [comment]
> or return ETH 

Sure, that's exactly how blockchains work

**Comment by cybersi** [comment]
https://ethplorer.io/tx/0x74742225422a46136dd36b1619b31e8ca7bc7b6e5597de6de85437fa87c98c3c
