### ISSUE TITLE
after 4 days geth node is not fully synced. I used Geth/v1.10.2-stable-97d11b01/linux-amd64/go1.16

### ISSUE THREAD

**Issue by lokesh-ratnam** [openethereum/openethereum#377]
My logs file as shown below - 

INFO [04-20|09:34:12.797] Imported new state entries               count=768  elapsed=3.885ms     processed=743402185 pending=36472  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:16.271] Imported new state entries               count=768  elapsed=5.366ms     processed=743402953 pending=36097  trieretry=2   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:19.003] Imported new state entries               count=768  elapsed=9.251ms     processed=743403721 pending=35393  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:21.709] Imported new state entries               count=768  elapsed=5.515ms     processed=743404489 pending=34969  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:22.328] Imported new block headers               count=1    elapsed=6.156ms     number=12276213 hash="27f081…d86974" age=1m53s
INFO [04-20|09:34:23.974] Imported new state entries               count=768  elapsed=6.921ms     processed=743405257 pending=34210  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:25.714] Imported new block headers               count=2    elapsed=5.631ms     number=12276215 hash="3cb1ee…0db19a"
INFO [04-20|09:34:27.345] Imported new state entries               count=768  elapsed=6.547ms     processed=743406025 pending=33732  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:29.258] Imported new block headers               count=1    elapsed=5.528ms     number=12276216 hash="4f92e4…bb5009"
INFO [04-20|09:34:32.409] Imported new state entries               count=768  elapsed=2.449ms     processed=743406793 pending=34026  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:34.667] Imported new state entries               count=768  elapsed=7.572ms     processed=743407561 pending=33148  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:37.627] Imported new state entries               count=768  elapsed=7.692ms     processed=743408329 pending=32238  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:40.604] Imported new state entries               count=768  elapsed=7.459ms     processed=743409097 pending=31354  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:45.681] Imported new state entries               count=768  elapsed=7.139ms     processed=743409865 pending=30668  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:50.610] Imported new state entries               count=768  elapsed=6.874ms     processed=743410633 pending=29967  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:53.074] Imported new state entries               count=384  elapsed=4.165ms     processed=743411017 pending=29566  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:56.575] Imported new state entries               count=768  elapsed=5.201ms     processed=743411785 pending=29262  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:34:59.348] Imported new state entries               count=1152 elapsed=10.743ms    processed=743412937 pending=27882  trieretry=0   coderetry=0 duplicate=293 unexpected=408
INFO [04-20|09:35:02.623] Imported new state entries               count=384  elapsed=3.476ms     processed=743413321 pending=27674  trieretry=0   coderetry=0 duplicate=293 unexpected=408

Please give any suggestions how to synced fast .

**Comment by yorickdowne** [comment]
You are in the wrong github, this is for OpenEthereum.

In a nutshell though: Check IOPS, they're likely low; and engage on the Geth Discord.

**Comment by lokesh-ratnam** [comment]
> You are in the wrong github, this is for OpenEthereum.
> 
> In a nutshell though: Check IOPS, they're likely low; and engage on the Geth Discord.
