### ISSUE TITLE
how much disk space will cost for an archive node

### ISSUE THREAD

**Issue by alexlee85** [openethereum/openethereum#382]
hi, guys

I'm prepareing for a archive node, I want to know how much disk space will cost for an archive node.

I know geth will cost almost 7T disk space, is openethereum the same?

**Comment by xiaoqge** [comment]
10 year

**Comment by taxmeifyoucan** [comment]
Yes, almost the same. And count with redundancy for growing state - around 3TB/year. 
Check https://etherscan.io/chartsync/chainarchive and https://ethereum.org/en/developers/docs/nodes-and-clients/

**Comment by alexlee85** [comment]
tks, @taxmeifyoucan
