### ISSUE TITLE
Unable to sync xDAI chain with 3.2.3/.4

### ISSUE THREAD

**Issue by KaiRo-at** [openethereum/openethereum#383]
- **OpenEthereum version (>=3.1.0)**: 3.2.3, 3.2.4
- **Operating system**: Linux
- **Installation**: docker container from official docker hub repo
- **Fully synchronized**: no + yes
- **Network**: xdai
- **Restarted**: yes

I recently tried to set up a (non-validator) node on the xdai network in addition to multiple nodes I already run on Ethereum mainnet, Ropsten, and Görli (so I'm an experienced OpenEthereum node maintainer), as I will need to run Dapps against xDAI as well in the future. As I saw that @varasev got the needed patches (re-)merged recently in #330, I was under the impression that a normal OpenEthereum installation should work for that.

When I tried to run that with the latest OpenEthereum release (3.2.4), I barely found any peers, sync started from 0 when 1 peer was found after I forced the [official bootnodes](https://github.com/poanetwork/poa-chain-spec/blob/dai/bootnodes.txt) as reserved peers (eventually a second peer was found, I never saw more than 3 active at all) but got stuck at block #9186424 (with the correct block hash, so no forked block) where the node thought it was done syncing but the block explorers showed me there are many newer blocks there. After having that run for >24h, I tried to step back to 3.2.3 but saw the same.
With then going back another one and trying 3.2.2 (or "v3.2.2-rc.1"), I suddenly did get a good snapshot sync and a whole lot of peers and got the node up and running correctly.

FWIW,  `--chain=xdai --nat=extip:x.x.x.x --ports-shift=1000` (in addition to the `--reserved-peers` as discussed above) is pretty much all I have as the configuration options there, next to some RPC access stuff and a DB base path, which should not be relevant.

When I switch the working node to 3.2.3 (or 3.2.4) again, it's again not syncing and not finding peers, when going to 3.2.2 again, it works fine once more.

So, it looks to me like something in the hot-fix patch for 3.2.3 did break xDAI nodes instead. As [according to their forum](https://forum.poa.network/t/update-openethereum-to-v3-2-2/5313), there's a plan to switch xDAI to Berlin some time soon, it would be great if an OpenEthereum version would be available that both has the fixes to make Berlin work correctly and is also able to sync the xDAI chain correctly.  ;-)

**Comment by varasev** [comment]
Hi @KaiRo-at,

> I forced the official bootnodes as reserved peers

We are going to update the list of bootnodes tomorrow.

> it looks to me like something in the hot-fix patch for 3.2.3 did break xDAI nodes instead

The reason is that OpenEthereum 3.2.3 and 3.2.4 don't support xDai. At the moment, only the following versions support: v3.0.x, v3.2.2-rc.1.

We are waiting for a new release based on the `main` branch where xDai was recently added to (from v3.2.2-rc.1): https://github.com/openethereum/openethereum/commits/main

OpenEthereum team reported that the new release will appear on the next week. Also, we plan to include a new spec file for Berlin hard fork to the upcoming release

**Comment by KaiRo-at** [comment]
> The reason is that OpenEthereum 3.2.3 and 3.2.4 don't support xDai. At the moment, only the following versions support: v3.0.x, v3.2.2-rc.1.

Sorry, I don't understand. From all I can see, the only differences between v3.2.2-rc1 and 3.2.4 should be those: https://github.com/openethereum/openethereum/compare/v3.2.2-rc.1...v3.2.4

The patch from the `main` branch that makes 3.2.2-rc.1 support xDAI should also be in 3.2.4, particularly. So you just confused me even more but did not clear anything up. But maybe I'm just too stupid to understand.

In any case, I'm looking forward to a release that "fixes all things" and to not needing to use a broken version there (apart from the oversight that makes it be "3.2.2-rc.1" instead of a proper "3.2.2", it contains Berlin support that doesn't actually work correctly in two significant cases).

**Comment by varasev** [comment]
> Sorry, I don't understand. From all I can see, the only differences between v3.2.2-rc1 and 3.2.4 should be those: [v3.2.2-rc.1...v3.2.4](https://github.com/openethereum/openethereum/compare/v3.2.2-rc.1...v3.2.4)

That's right. But you can compare commits in those two tags: https://github.com/openethereum/openethereum/commits/v3.2.2-rc.1 and https://github.com/openethereum/openethereum/commits/v3.2.4 - there is no ["Backport AuRa commits for xdai" commit](https://github.com/openethereum/openethereum/commit/85391f99ac9132c0202afbc619e10a594d2e5112) for `v3.2.4`, so `v3.2.4` doesn't contain POSDAO features.

> The patch from the main branch that makes 3.2.2-rc.1 support xDAI should also be in 3.2.4, particularly.

It seems that v3.2.4 is based on another tag, not on v3.2.2-rc.1, so we don't see some 3.2.2-rc.1 changes in v3.2.4 (including POSDAO).

**Comment by KaiRo-at** [comment]
Wow, thanks, so both unexpected release management by OE, and GitHub's compare feature being suboptimal, not to say "broken". OK, that clears things up. Let's hope the specific case gets cleared up soon with a release that has all the commits. ;-)

**Comment by jomuel** [comment]
@KaiRo-at v3.2.3 and v3.2.4 were unscheduled hotfix releases that really could not wait. v3.2.5 will be back to normal with all the commits. We pre-released it yesterday and plan to release next week.

**Comment by KaiRo-at** [comment]
Thanks for all the help and info, seems to all work nicely with 3.2.5 now! \o/
