### ISSUE TITLE
`Invalid RLP` error when trying to use EIP-2930 transaction

### ISSUE THREAD

**Issue by varasev** [openethereum/openethereum#388]
- **OpenEthereum version (>=3.1.0)**: 3.2.5-rc.1
- **Operating system**: MacOS, Linux
- **Fully synchronized**: yes
- **Network**: local aura test network with Berlin HF activated

I tried to check EIP-2930 transaction in a local test chain - sent it to OpenEthereum node using `eth_sendRawTransaction` request, but the node returned `Invalid RLP.` error. The transaction RLP is:

```
0xb8ae01f8ab6501843b9aca0083061a8094110000000000000000000000000000000000000180b844adc9772e000000000000000000000000b916e7e1f4bcb13549602ed042d36746fd0d96c900000000000000000000000000000000000000000000043c33c1937564800000c001a077eaa83304ace3301b46fd5008a7d220f4ba2425fa89e453f5635b3f449471f7a060b64fd54fd876135555f9f12285f2d14d220446f4ae559c2c468c9d28726c3d
```

Can you clarify, what's wrong with it?

**Comment by varasev** [comment]
The response is `{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid RLP.","data":"RlpExpectedToBeList"},"id":1}`

**Comment by jomuel** [comment]
The first byte opens up a string instead of a list. Once you change it from `b8` to `f8`, it looks like a valid transaction with empty access list though. So:

``
0xf8ae01f8ab650184090aca0083061a8094110000000000000000000000000000000000000180b844adc9772e000000000000000000000000b916e7e1f4bcb13549602ed042d36746fd0d96c900000000000000000000000000000000000000000000043c33c1937564800000c001a077eaa83304ace3301b46fd5008a7d220f4ba2425fa89e453f5635b3f449471f7a060b64fd54fd876135555f9f12285f2d14d220446f4ae559c2c468c9d28726c3d
``

**Comment by varasev** [comment]
> The first byte opens up a string instead of a list. Once you change it from `b8` to `f8`, it looks like a valid transaction with empty access list though. So:
> 
> `0xf8ae01f8ab650184090aca0083061a8094110000000000000000000000000000000000000180b844adc9772e000000000000000000000000b916e7e1f4bcb13549602ed042d36746fd0d96c900000000000000000000000000000000000000000000043c33c1937564800000c001a077eaa83304ace3301b46fd5008a7d220f4ba2425fa89e453f5635b3f449471f7a060b64fd54fd876135555f9f12285f2d14d220446f4ae559c2c468c9d28726c3d`

Are you sure your RLP is correct? Seems you changed `gasPrice` so Geth responds to your example as follows: 

![image](https://user-images.githubusercontent.com/33550681/116726892-8d201c80-a9ec-11eb-8618-3d00fa7d09a4.png)

**Comment by rakita** [comment]
Hi @varasev, for eip2930 you are currently doing `rlp(01 | rlp[...])` you will find that devs call it `wrapped tx` and this should be only found when you have rlp list and want to add typed tx as bytes array. For all of rest of the system including rpc we accept `01 | rlp[...] ` bcs wrapper in there does not have purpose.

There was a lot of confusion about this when we implemented it, and confusion seems still not cleared, just look at `Eth R&D` discord `json-rpc-api` chat for more info.
For example one good comment that I kinda agree with:
`IMO, the format you send over eth_sendRawTransaction should always be the pre-image of the transaction hash. So the extra RLP-encoding of the typed transaction over json-rpc sounds wrong to me.`

**Comment by varasev** [comment]
@rakita Without wrapping it works fine, thank you
