### ISSUE TITLE
v3.2.4 Unknown api: rpc

### ISSUE THREAD

**Issue by vlddm** [openethereum/openethereum#389]
Using `OpenEthereum/v3.2.4-stable-0996732-20210415/x86_64-linux-gnu/rustc1.51.0`
If openethereum started with `--ipc-apis=all` I got this error:

```
$ geth attach .local/share/openethereum/jsonrpc.ipc 
Fatal: Failed to start the JavaScript console: api modules: Method not found
```
Trying to start OE with `--ipc-apis=rpc`:
```
Unknown api: rpc
Error: 1
```

**Comment by jomuel** [comment]
This has been fixed in v3.2.5.

**Comment by sukri74** [comment]
Yes

**Comment by sukri74** [comment]
Yes
