### ISSUE TITLE
The node is syncing slowly

### ISSUE THREAD

**Issue by 1scrooge** [openethereum/openethereum#399]
- **OpenEthereum version**: 3.2.5
- **Operating system**: Linux
- **Installation**: Docker
- **Fully synchronized**: no 
- **Network**: ropsten 
- **Restarted**: yes

Hi.
Today our node is syncing slowly. I've updated up to 3.2.5,  but the same problem. Any ideas?

**Comment by iFA88** [comment]
Greetings!
I can confirm some issue with Ropsten.
I have two separate client with the latest OpenEthereum and the sync has stopped on `10210390` block.

**Comment by iFA88** [comment]
> I have the same. The node is stuck at 10210390

Sadly we need resync from 0.

**Comment by 1scrooge** [comment]
@iFA88 Do you know any public ropsten node?

**Comment by iFA88** [comment]
> @iFA88 Do you know any public ropsten node?
No one, sorry.

**Comment by 1scrooge** [comment]
@iFA88 Do you know where I cat download a snapshot DB?

**Comment by iFA88** [comment]
> @iFA88 Do you know where I cat download a snapshot DB?

Nope, just delete your chain folder and do a full resync.

Please close this issue. Thank you!
