### ISSUE TITLE
Cargo build error 

### ISSUE THREAD

**Issue by fwhappy** [openethereum/openethereum#442]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.2.5
- **Operating system**: MacOS
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: xDai
- **Restarted**: no

Failed to compile client.

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /Users/xh/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:55:20
    |
55  |             extras.insert(util::ident(&ext), |_| panic!("Only one #[extras] attribute can be declared."));
    |                    ^^^^^^ -----------------  ----------------------------------------------------------- supplied 2 arguments
    |                    |
    |                    expected 1 argument
    |
note: associated function defined here
   --> /Users/xh/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:848:12
    |
848 |     pub fn insert(&mut self, value: T) -> &mut T {
    |            ^^^^^^

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /Users/xh/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:89:23
    |
89  |                 error.insert(variant, |_| panic!("Only one #[error] variant can be declared."));
    |                       ^^^^^^ -------  -------------------------------------------------------- supplied 2 arguments
    |                       |
    |                       expected 1 argument
    |
note: associated function defined here
   --> /Users/xh/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:848:12
    |
848 |     pub fn insert(&mut self, value: T) -> &mut T {
    |            ^^^^^^

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /Users/xh/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:93:21
    |
93  |                 end.insert(variant, |_| panic!("Only one #[end] variant can be declared."));
    |                     ^^^^^^ -------  ------------------------------------------------------ supplied 2 arguments
    |                     |
    |                     expected 1 argument
    |
note: associated function defined here
   --> /Users/xh/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:848:12
    |
848 |     pub fn insert(&mut self, value: T) -> &mut T {
    |            ^^^^^^

   Compiling fixed-hash v0.6.1
     Running `rustc --crate-name fixed_hash --edition=2018 /Users/xh/.cargo/registry/src/github.com-1ecc6299db9ec823/fixed-hash-0.6.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto --cfg 'feature="byteorder"' --cfg 'feature="rand"' --cfg 'feature="rustc-hex"' --cfg 'feature="std"' -C metadata=40b0a9ef947904a8 -C extra-filename=-40b0a9ef947904a8 --out-dir /Users/xh/git/openethereum/target/release/deps -L dependency=/Users/xh/git/openethereum/target/release/deps --extern byteorder=/Users/xh/git/openethereum/target/release/deps/libbyteorder-91ba1c3502eac7fa.rmeta --extern rand=/Users/xh/git/openethereum/target/release/deps/librand-92a19990edea6c60.rmeta --extern rustc_hex=/Users/xh/git/openethereum/target/release/deps/librustc_hex-0476a5f1ceb3f05e.rmeta --extern static_assertions=/Users/xh/git/openethereum/target/release/deps/libstatic_assertions-6585aabaf1c6b452.rmeta --cap-lints allow`
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0061`.
error: could not compile `logos-derive`

What do I need to do?

**Comment by Asara** [comment]
Hey I was hitting the same issue when using rust 1.53.  Downgrading to 1.51 allows openethereum to build.

**Comment by Hongssd** [comment]
rust 1.51
warning: panic message is not a string literal
   --> crates/vm/evm/src/interpreter/mod.rs:835:33
    |
835 |                       _ => panic!(format!(
    |  _________________________________^
836 | |                         "Unexpected instruction {:?} in CALL branch.",
837 | |                         instruction
838 | |                     )),
    | |_____________________^
    |
    = note: `#[warn(non_fmt_panic)]` on by default
    = note: this is no longer accepted in Rust 2021
    = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by fwhappy** [comment]
> Hey I was hitting the same issue when using rust 1.53. Downgrading to 1.51 allows openethereum to build.

This worked for me.

I switched the cargo to version 1.5.0 and it built successfully.

Thanks a lot!

**Comment by roninkaizen** [comment]
agree with @fwhappy and @Asara 
`rustup override set 1.51.0` 
could be the solution

**Comment by sunce86** [comment]
Yes, some external libraries are not buildable with the 1.53.0 Rust version, workaround is to downgrade Rust version for now.

**Comment by roninkaizen** [comment]
@Hongssd 
something else is missing-
did you try `cargo clean` ?

**Comment by nolash** [comment]
> rustup override set 1.51.0
could be the solution

worked for me wtr https://github.com/openethereum/openethereum/issues/464 - thanks

**Comment by Voklen** [comment]
PR #463 does seem to fix the problem so I hope it's merged soon, but in the meantime you can still use the commits.
When your compiling it after you've ran:
```bash
git clone https://github.com/openethereum/openethereum --recursive
cd openethereum
```
you can get the patches from @717a56e1  by running
```bash
git remote add patch https://github.com/717a56e1/openethereum.git
git pull --no-edit patch eip-712-parser
```
and then after that building
```
cargo build --release --features final
```

**Comment by ymonye** [comment]
> PR #463 does seem to fix the problem so I hope it's merged soon, but in the meantime you can still use the commits.
> When your compiling it after you've ran:
> 
> ```shell
> git clone https://github.com/openethereum/openethereum --recursive
> cd openethereum
> ```
> 
> you can get the patches from @717a56e1 by running
> 
> ```shell
> git remote add patch https://github.com/717a56e1/openethereum.git
> git pull --no-edit patch eip-712-parser
> ```
> 
> and then after that building
> 
> ```
> cargo build --release --features final
> ```

Nice, I just had this problem and happened to come across this 6 minutes after posted. Thanks!

**Comment by dhcn** [comment]
I use a ugly hacking method， I remove the second argument。

**Comment by khhussnain** [comment]
> > rustup override set 1.51.0
> > could be the solution
> 
> worked for me wtr #464 - thanks

Yeah it worked. Rustup override to 1.51.0

**Comment by khhussnain** [comment]
#464
Yeah it worked. Rustup override to 1.51.0

**Comment by frmiqueias** [comment]
If you prefer to override the Rust version for just one particular project, you can override the version by creating a rust-toolchain file in the same directory as Cargo.toml:

`$echo "1.51.0" > rust-toolchain`

It works for me

[https://users.rust-lang.org/t/how-can-i-revert-to-older-version-of-rust/20497/6](https://users.rust-lang.org/t/how-can-i-revert-to-older-version-of-rust/20497/6)

**Comment by varasev** [comment]
Fixed in https://github.com/openethereum/openethereum/pull/463.

**Comment by Pyloris** [comment]
> I use a ugly hacking method， I remove the second argument manually。
downgrading rust didn't work for me so i did the same.
