### ISSUE TITLE
eth_gasPrice should be based on effective_gas_price

### ISSUE THREAD

**Issue by sunce86** [openethereum/openethereum#449]
Currently, eth_gasPrice calculation is based on the gas_price of legacy transactions and maxFeePerGas of 1559 transactions.

This should be changed so the eth_gasPrice  calculation is based on effective_gas_price, which is calculated as min(maxFeePerGas, baseFee+maxPriorityFeePerGas). Legacy transaction are promoted to 1559 style transactions by setting maxFeePerGas = gasPrice && maxPriorityFeePerGas = gasPrice

**Comment by sunce86** [comment]
PR merged. Closed.

**Comment by varasev** [comment]
Hi @sunce86, do these changes correspond to Geth behavior for eth_gasPrice? https://github.com/ethereum/pm/issues/328#issuecomment-853234014

**Comment by sunce86** [comment]
@varasev Yes. That comment is a bit outdated but this PR is actually about:

"eth_gasPrice after London will return the exact same number based on the total fees paid (tip + base)"
