### ISSUE TITLE
missing gasPrice field value from eth_getTransactionByHash for new EIP 1559 type = 2 transactions

### ISSUE THREAD

**Issue by mtbitcoin** [openethereum/openethereum#453]
When calling curl http://localhost:8545 -X POST --data "{\"jsonrpc\":\"2.0\",\"method\":\"eth_getTransactionByHash\",\"params\":[\"0x2b6e2683876baa10f2de87811b7f4cb18b9b68e0519f7d943f0348cf6d4c77d9\"],\"id\":1}"  -H "Content-Type: application/json" , the gasPrice field is missing. When comparing with Geth a proper gasPrice value is returned

{
    "jsonrpc": "2.0",
    "result": {
        "accessList": [],
        "blockHash": "0x310e11add898b3b617579832164daeb5c4eca8c76b902ca6b44686f04b7ade67",
        "blockNumber": "0xa05e00",
        "chainId": "0x3",
        "condition": null,
        "creates": null,
        "from": "0x822378bfb78bb5635d45cc1f64e47db21ec75ffd",
        "gas": "0x5208",
        "hash": "0x2b6e2683876baa10f2de87811b7f4cb18b9b68e0519f7d943f0348cf6d4c77d9",
        "input": "0x",
        "maxFeePerGas": "0x25a02aa9c",
        "maxPriorityFeePerGas": "0x25a02aa9c",
        "nonce": "0x0",
        "publicKey": "0xe72cffa12972763ce7363bc05eeb7f61688a780bb45728584f3fa37e2a53e87da29bf01c740ae0ad79d1081995bf6b814d36799f1145b61e9c6387cc53bba2c3",
        "r": "0x23b8a29e6e4ae9dbfa5db770c6d13c280ec6008ec2be3825ad881edbcb6ef8ce",
        "raw": "0x02f86c038085025a02aa9c85025a02aa9c825208948210357f377e901f18e45294e86a2a32215cc3c97b80c001a023b8a29e6e4ae9dbfa5db770c6d13c280ec6008ec2be3825ad881edbcb6ef8cea00c3d666377009573d404737f0fa23faebf74a469bc05b8aba16d46e45d9c7afe",
        "s": "0xc3d666377009573d404737f0fa23faebf74a469bc05b8aba16d46e45d9c7afe",
        "to": "0x8210357f377e901f18e45294e86a2a32215cc3c9",
        "transactionIndex": "0xa",
        "type": "0x2",
        "v": "0x1",
        "value": "0x7b"
    },
    "id": 1
}

**Comment by sunce86** [comment]
Hi, 
The response was intentionally changed this way.
Can you post the equivalent response from geth?

**Comment by mtbitcoin** [comment]
Sure, this is the equivalent geth response

{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0x310e11add898b3b617579832164daeb5c4eca8c76b902ca6b44686f04b7ade67",
        "blockNumber": "0xa05e00",
        "from": "0x822378bfb78bb5635d45cc1f64e47db21ec75ffd",
        "gas": "0x5208",
        "gasPrice": "0x25a02aa9c",
        "maxFeePerGas": "0x25a02aa9c",
        "maxPriorityFeePerGas": "0x25a02aa9c",
        "hash": "0x2b6e2683876baa10f2de87811b7f4cb18b9b68e0519f7d943f0348cf6d4c77d9",
        "input": "0x",
        "nonce": "0x0",
        "to": "0x8210357f377e901f18e45294e86a2a32215cc3c9",
        "transactionIndex": "0xa",
        "value": "0x7b",
        "type": "0x2",
        "accessList": [],
        "chainId": "0x3",
        "v": "0x1",
        "r": "0x23b8a29e6e4ae9dbfa5db770c6d13c280ec6008ec2be3825ad881edbcb6ef8ce",
        "s": "0xc3d666377009573d404737f0fa23faebf74a469bc05b8aba16d46e45d9c7afe"
    }
}

**Comment by mtbitcoin** [comment]
is this related to https://github.com/openethereum/openethereum/issues/445 where the effectiveGasPrice is also omitted from the txn receipt ?

**Comment by mtbitcoin** [comment]
so it appears for compatibility, this is how geth handles it https://github.com/ethereum/eth1.0-specs/pull/206

**Comment by sunce86** [comment]
https://github.com/ethereum/eth1.0-specs/blob/05d6bf480a4e3228cf42b86b044de6832c077b3a/json-rpc/spec.json#L1709

Here is a spec that says one of the gas_price or maxFeePerGas/maxPriorityFeePerGas should be provided for Transaction object, so geth is against the spec. Either they need to fix it or the spec needs to be updated.

**Comment by sunce86** [comment]
> is this related to #445 where the effectiveGasPrice is also omitted from the txn receipt ?

Actually, this is a different issue which is addressed and we have a PR for it:
https://github.com/openethereum/openethereum/pull/450
