### ISSUE TITLE
eth_estimateGas returns "Requires higher than upper limit of X" after London Ropsten Testnet Hard Fork

### ISSUE THREAD

**Issue by dhl** [openethereum/openethereum#459]
- **OpenEthereum version (>=3.1.0)**: 3.3.0-rc2
- **Operating system**: Linux
- **Installation**: installed from release archive
- **Fully synchronized**: yes
- **Network**: ropsten
- **Restarted**: yes

## Description
Upgraded OpenEthereum node from 3.2.4 to 3.3.0-rc2. After client is synced and processed past the Ropsten London hard fork block, all calls to `eth_estimateGas` have failed with error "Requires higher than upper limit of X".

## Expected
When making `eth_estimateGas` JSON-RPC call for ETH transfer transaction, the result returned should be  21000`.

## Actual
`eth_estimateGas` returns with an error message

```json
{"jsonrpc":"2.0", "error":{"code":-32015,"message":"Transaction execution error.","data":"Internal(\"Requires higher than upper limit of 207203170\")"},"id":42}
```

**Comment by sunce86** [comment]
Hi, can you post the original request (for the testing purposes)?

**Comment by sunce86** [comment]
PR merged. Closed.
