### ISSUE TITLE
GetNodeData from eth63 is missing

### ISSUE THREAD

**Issue by sunce86** [openethereum/openethereum#466]
GetNodeData function was removed in 3.1.0 version.

It should be reverted.

**Comment by varasev** [comment]
Thanks for creating the issue.

On xDai chain we use Nethermind and OpenEthereum clients at the same time.

Nethermind team just noticed that `GetNodeData` was [removed from OpenEthereum](https://github.com/openethereum/openethereum/pull/14), so state sync on xDai chain works only off Nethermind nodes.

We are asking to bring `GetNodeData` back to OpenEthereum so Nethermind nodes could sync with OpenEthereum nodes on xDai. Thank you

**Comment by jomuel** [comment]
Since it's another eth protocol task, I'll do this while I'm at it. Do you know if there was a problem with the GetNodeData implementation, or was it just removed due to not being used?

**Comment by varasev** [comment]
> Since it's another eth protocol task, I'll do this while I'm at it. Do you know if there was a problem with the GetNodeData implementation, or was it just removed due to not being used?

Personally, I don't know, but seems there were no any mentions about problems with GetNodeData
