### ISSUE TITLE
Stopped syncing at block 12833000 (London fork)

### ISSUE THREAD

**Issue by kepikoi** [openethereum/openethereum#487]
- **OpenEthereum version (>=3.1.0)**: 3.3.0-rc.3
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**:  yes
- **Network**: ethereum
- **Restarted**: yes

All my OE 3.3.0-rc.3 nodes stopped syncing at block 12833000. Based on this [comment](https://github.com/ethereum/pm/issues/245#issuecomment-832122309) I assume it is the London fork block.

**Comment by sunce86** [comment]
Hi, yes, please update to rc4 version.

**Comment by kepikoi** [comment]
Thank you! I've updated and my nodes continued syncing. Seems to me a somewhat tight schedule given that rc4 was released just yesterday
