### ISSUE TITLE
Ropsten stopped at Block 10679537

### ISSUE THREAD

**Issue by kepikoi** [openethereum/openethereum#489]
- **OpenEthereum version (>=3.1.0)**: 3.3.0-rc.4
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**:  yes
- **Network**: ropsten 
- **Restarted**: yes

OpenEthereum Ropsten nodes stopped at 10679537 (as currently visible on [Etherscan](https://ropsten.etherscan.io/)). Geth nodes have already surpassed 10680462 (e.g. Infura)

**Comment by sunce86** [comment]
There was a disagreement between the clients in a way how sender balance is validated against transaction. 

Other clients will provide fixes. Closing.
