### ISSUE TITLE
eth_feehistory method is failing with Invalid param Error

### ISSUE THREAD

**Issue by barathbitgo** [openethereum/openethereum#495]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**:  3.3.0-rc.4
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**:  yes
- **Network**: goerli
- **Restarted**: yes

`eth_feehistory` method seems to throwing unexpected error

Request used: 
```
curl --location --request POST 'http://localhost:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_feeHistory",
    "params": [1,"latest",[60]],
    "id": f283137b-3feb-41fb-84d6-34f99ecda124
}
```

Expected Behavior:

Either return the result for the `eth_feeHistory` method if the node supports 
```
{"result":{"reward":[["0x12a05f1f9"]],"oldestBlock":5227912,"baseFeePerGas":["0x7","0x7"],"gasUsedRatio":[0.03307349490548695]},"id":"1","jsonrpc":"2.0"}
```

or return error if node doesn't support

```
{"id":"1","jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"}}
```

Actual Behavior:
Invalid param error is being returned 
```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid type: integer `1`, expected a 0x-prefixed hex string with length between (0; 64]."},"id":1}
```

The same method seems to be working fine with geth nodes

**Comment by sunce86** [comment]
For OE, you need to provide:

"params": ["0x01","latest",[60]],

**Comment by barathbitgo** [comment]
Yeah, That's about it
