### ISSUE TITLE
Invalid params: invalid type: integer `4`, expected a 0x-prefixed hex string with length between (0; 64]

### ISSUE THREAD

**Issue by heipacker** [openethereum/openethereum#505]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 0.0.0
- **Operating system**: Windows / MacOS / Linux
- **Installation**: homebrew / one-line installer / built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum / ropsten / kovan / ...
- **Restarted**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

{"jsonrpc":"2.0","method":"eth_feeHistory","params":[4, "latest", [0, 50, 100]],"id":73}

{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params: invalid type: integer `4`, expected a 0x-prefixed hex string with length between (0; 64]."
    },
    "id": 73
}

expected result:

{
    "jsonrpc": "2.0",
    "id": 73,
    "result": {
        "oldestBlock": 12964946,
        "reward": [
            [
                "0x6fc23ac00",
                "0x6fc23ac00",
                "0xef786308e"
            ],
            [
                "0x1",
                "0x6c088e7b3",
                "0xcce416600"
            ],
            [
                "0x6a8b15e00",
                "0x7aef40a00",
                "0xf5de81400"
            ],
            [
                "0x0",
                "0x7735945b3",
                "0x311a060680"
            ]
        ],
        "baseFeePerGas": [
            "0x0",
            "0x0",
            "0x0",
            "0x0",
            "0x0"
        ],
        "gasUsedRatio": [
            0.9995404846318936,
            0.9995972029248177,
            0.9996174660036078,
            0.9997712
        ]
    }
}

**Comment by sunce86** [comment]
Copy of https://github.com/openethereum/openethereum/issues/495

Closed.
