### ISSUE TITLE
stuck before london hard fork 

### ISSUE THREAD

**Issue by nolash** [openethereum/openethereum#510]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.2.6
- **Operating system**: Windows / MacOS / Linux: archlinux
- **Installation**:  package (latest)
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

invoking:

``` 
/usr/bin/openethereum -d /home/openethereum/.local/share/openethereum --no-config
```

stuck at block 12,964,999

**Comment by GBBx** [comment]
hi @nolash I think you need to update to [3.3.0-rc.4](https://github.com/openethereum/openethereum/releases/tag/v3.3.0-rc.4)
