### ISSUE TITLE
OE pretends to support EIP1559 on xDAI chain.

### ISSUE THREAD

**Issue by fleupold** [openethereum/openethereum#515]
- **OpenEthereum version (>=3.1.0)**: 3.3.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: xDAI
- **Restarted**: yes

xDAI doesn't support EIP1559. Yet, OE 3.3. returns a valid default response for `eth_feeHistory`. This may lead clients to believe that EIP1559 is supported and therefore send such a transaction which will get rejected by the client.

Other clients (e.g. Nethermind, previous versions of OE) would return `Method Not Found` when `eth_feeHistory` is called on a non EIP1559 compatible network.

request:
```
{
  "jsonrpc": "2.0",
  "method": "eth_feeHistory",
  "params": [
    "0x1",
    "latest",
    [
      0.5
    ]
  ],
  "id": 10
}
```

response:
```
{
  "jsonrpc": "2.0",
  "result": {
    "baseFeePerGas": [
      "0x0",
      "0x0"
    ],
    "gasUsedRatio": [
      0.9513331764705882
    ],
    "oldestBlock": "0x10ee11a",
    "reward": [
      [
        "0x3b9aca00"
      ]
    ]
  },
  "id": 10
}
```

**Comment by varasev** [comment]
Now OE really supports EIP-1559 on xDai (starting from v3.3.0-rc.12).
