### ISSUE TITLE
Is OpenEthereum also vulnerable to the EVM bug fixed in Geth v1.10.8 and in Erigon 2021.08.04-alpha?

### ISSUE THREAD

**Issue by xanoni** [openethereum/openethereum#516]
Given almost 20% of nodes still use OpenEthereum, do we know if it is also vulnerable? 

Or is it just Erigon and Geth? (Are there more?)

**Comment by sunce86** [comment]
OE is not affected.

**Comment by xanoni** [comment]
Thank you! In Rust we Trust.
