### ISSUE TITLE
Shared queue of PIP requests between handlers

### ISSUE THREAD

**Issue by rphmeier** [openethereum/openethereum#5323]
Multiple benefits:
  - no racing between handlers on who gets ticked first
  - no duplicate logic

**Comment by adrianbrink** [comment]
@rphmeier What does pip refer to? I have searched through the parity codebase with ripgrep, but only ever find it in some doc string. :-)

**Comment by rphmeier** [comment]
https://github.com/paritytech/parity/wiki/The-Parity-Light-Protocol-(PIP)

Implemented in the `ethcore/light/src/net` directory

**Comment by adrianbrink** [comment]
Oh right, I kept reading this as a capital i instead of a lower case L. :-)

**Comment by rphmeier** [comment]
It is a capital `I`... the Parity lIght Protocol ;) 

(naming could be subject to change...)

**Comment by folsen** [comment]
@rphmeier would like to keep this issue around, but could you provide some more details so this is easier to just pick up and work on?

**Comment by adria0** [comment]
Closing the issue due to its stale state
