### ISSUE TITLE
 How to handle this error "WebSocket interface is active. Open WS connection to access RPC." ? 

### ISSUE THREAD

**Issue by fm-b** [openethereum/openethereum#535]
- **OpenEthereum version v3.3.0-rc.7-stable
- **Operating system**:/ Linux
- **Installation**: built from source
- **Fully synchronized**: no / yes
- **Network**: ethereum 

hello every one,
I have started an openethereum node on mainnet with following configs:

./openethereum --jsonrpc-hosts all --jsonrpc-apis all  --ws-origins="*" --ws-hosts=all --ws-interface=all --jsonrpc-interface=all ---ws-apis=all --metrics --no-warp

And while it was syncing I tried to check syncing status via following piece of code:

const provider = 'http://localhost:8546'; // enter your specific RPC host and port
const Web3 = require('web3');
const web3Provider = new Web3.providers.HttpProvider(provider);
const web3 = new Web3(web3Provider);

web3.eth.isSyncing().then((result) => {
    console.log("sync=  ",result);
  });

unfortunately, I encountered the error "WebSocket interface is active. Open WS connection to access RPC" after running it.
I think web3 can not work with websocket.

**Comment by kelleyloves** [comment]
Suck a dick and die subliminal asses
