### ISSUE TITLE
Latest Rust version compiles main branch went error

### ISSUE THREAD

**Issue by bitweedx64** [openethereum/openethereum#547]
For questions please use https://discord.io/openethereum, issues are for bugs and feature requests.

_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version (>=3.1.0)**: 3.3.0-rc.8
- **Operating system**: Linux ARM64
- **Installation**: built from source

When compile main branch with latest Rust version 1.55.0 on ARM Linux, one package occurs error: `logos-derive`, and it shows error like:
```
$ cargo +nightly check
   Compiling logos-derive v0.7.7
error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /home/birchmd/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:55:20
    |
55  |             extras.insert(util::ident(&ext), |_| panic!("Only one #[extras] attribute can be declared."));
    |                    ^^^^^^ -----------------  ----------------------------------------------------------- supplied 2 arguments
    |                    |
    |                    expected 1 argument
    |
note: associated function defined here

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /home/birchmd/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:89:23
    |
89  |                 error.insert(variant, |_| panic!("Only one #[error] variant can be declared."));
    |                       ^^^^^^ -------  -------------------------------------------------------- supplied 2 arguments
    |                       |
    |                       expected 1 argument
    |
note: associated function defined here

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /home/birchmd/.cargo/registry/src/github.com-1ecc6299db9ec823/logos-derive-0.7.7/src/lib.rs:93:21
    |
93  |                 end.insert(variant, |_| panic!("Only one #[end] variant can be declared."));
    |                     ^^^^^^ -------  ------------------------------------------------------ supplied 2 arguments
    |                     |
    |                     expected 1 argument
    |
note: associated function defined here

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0061`.
error: could not compile `logos-derive`

To learn more, run the command again with --verbose.
```

That's how far I could get.

**Comment by bitweedx64** [comment]
I'm not a Rust developer so I'm sorry for the poor information that I could get from the error. I simply just want to use Open Ethereum on my ARM Linux VPS, and there isn't a prebuilt one.

**Comment by 1garo** [comment]
Same thing happening here, the difference is that I'm running it in a x86_64 architecture and not a ARM

**Comment by kaiuri** [comment]
@bitweedx64 , while my [PR](https://github.com/openethereum/openethereum/issues/518#issuecomment-988907196) doesn't get merged, you can fix this issue by adding a `rust-toolchain.toml` file inside the repo containing the following code 

```toml
[toolchain]
    channel = "1.51.0"
```

**Comment by bitweedx64** [comment]
> @bitweedx64 , while my [PR](https://github.com/openethereum/openethereum/issues/518#issuecomment-988907196) doesn't get merged, you can fix this issue by adding a `rust-toolchain.toml` file inside the repo containing the following code
> 
> ```toml
> [toolchain]
>     channel = "1.51.0"
> ```

Sure, thank you!

**Comment by varasev** [comment]
Fixed in https://github.com/openethereum/openethereum/pull/463.
