### ISSUE TITLE
Official OE support past London (?)

### ISSUE THREAD

**Issue by KaamilW** [openethereum/openethereum#555]
Hey Team, @varasev 

Seeing that there are new client rc versions coming, I just wanted to confirm -> does your team officially took over the support of OE moving forward and we could expect that it will be maintained for the future Ethereum HF & have support for PoA AuRa?

There are several projects that we are working on and we need to choose a main RPC client to relay on for them.

Kindly looking for an advise from your side.

**Comment by varasev** [comment]
@KaamilW unfortunately, we don't plan to maintain OE since we don't have experienced Rust developers in our team.
