### ISSUE TITLE
add debug interface to rpc for supporting Remix IDE debugger.

### ISSUE THREAD

**Issue by 3esmit** [openethereum/openethereum#5727]

**Comment by rphmeier** [comment]
could you link to a specification of this interface? it's not on the main ethereum RPC wiki page.

**Comment by 3esmit** [comment]
I think the specification still loose due solidity constant changes. I tested it a lot this feature with "EtherCamp Ethereum Studio" that probably was using ethereumjs and memory blockchain.
In geth I can set a transaction id and debug from it.
I've found this might be useful: 
- https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug
- https://github.com/ethereum/go-ethereum/pull/14350
- https://github.com/ethereumjs/testrpc/issues/248

**Comment by folsen** [comment]
@3esmit Do you know if there's any up to date list for changes required to work with Remix?

**Comment by adria0** [comment]
Closing issue due to its stale state.
