### ISSUE TITLE
At what moment does selfdestruct actually removes the state from the disk?

### ISSUE THREAD

**Issue by varasev** [openethereum/openethereum#576]
We asked Dark Forest to clear their unnecessary state by selfdestruct. There is an assumption that the state is not removed from node's disk immediately, and it probably happens with some time interval (or with some conditions). Currently, we need to research and clarify this moment for OpenEthereum client.

**Comment by rimrakhimov** [comment]
I believe it depends on below factors:
- If the node is synchronized with _archive_ pruning method, state is never removed from the disk.
- If the node is synchronized with _fast_ pruning method, then the two following options impact the time state is actually removed from the disk: `--pruning-history` and `--pruning-memory`.
    ```
    --pruning-history=[NUM]
        Set a minimum number of recent states to keep in memory when pruning is active. (default: 64)

    --pruning-memory=[MB]
        The ideal amount of memory in megabytes to use to store recent states. As many states as possible will be kept
        within this limit, and at least --pruning-history states will always be kept. (default: 32)
    ```

   The node stores states for some latest epochs (epoch = block number; one state per epoch). When the total amount of space used by states exceeds `--pruning-memory` value, states for oldest epochs are starting to be removed from the disk, until the total amount of space will not again become less than `--pruning-memory` (or total number of epochs left will become equal to `--pruning-history`). 

    There are some details omitted regarding the fact that we store only differences between states. However, as we consider the SELFDESTRUCT operation, I believe that the whole data related to the contract can be removed from the disk at once.

    There is some minimum number of blocks to be sealed before the data will be actually removed (`--pruning-history`). If we want to reduce that period, we can set this option to be less. However, there is a minimum value equals to _8_, and less options will be increased to _8_ anyway. 

     Another argument that impacts the time contract data will be removed from the disk is amount of memory currently used to store state trees. The pruning only occurs if the total space used for keeping states becomes greater than `--pruning-memory` value, and is finished when space used becomes less than that value.

**Comment by rimrakhimov** [comment]
_There is an update after more thorough inspection and experimental setup._

`SELFDESTRUCT` does not clean up the storage used by the contract. The operation removes account data from the _StateTrie_ which includes _StorageRoot_. However the corresponding _StorageTrie_ is not traversed and removed from the database. Thus, all data the contract had stored in the database stays there forever. Furthermore, the pointer to the storage root to traverse it is lost.

If we clear concrete slot using the `SSTORE(.., 0)` opcode, the corresponding data is actually removed from the storage and the _StorageTrie_ is updated. Thus, the rules described in the previous comment applies in that case.
