### ISSUE TITLE
Allow warp syncing for light clients

### ISSUE THREAD

**Issue by rphmeier** [openethereum/openethereum#6010]
1. Generalize snapshot restoration targets via a trait. Don't require a full `BlockChain`/`StateDB`, but maybe   associated types.
2. Don't require getting state chunks (all we care about are secondary/corroboration chunks)
3. Background header sync in order to get ancient CHT roots. This should be toggleable via RPC: mobile apps might set this to only run when connected to wifi. Only downside is headers in the gap will be unavailable until that sync completes

**Comment by adria0** [comment]
Closing issue due to its stale state.
