### ISSUE TITLE
Convert RPC to use `Bytes`

### ISSUE THREAD

**Issue by Vurich** [openethereum/openethereum#6015]
The PR to convert most of the codebase to use `Bytes` is almost done, but we still have to convert to/from `Vec` every time we hit the RPC layer, which is an overhead. It's not slower than using `Vec` everywhere, since if `Bytes` is uniquely owned it can reuse the allocation when converting to `Vec` and if it wasn't uniquely owned it would have to be cloned speculatively somewhere in the stack if it was `Vec` anyway. However, it is an easy (not quick, necessarily, but easy) win to just reuse the shared buffer. Ideally we would have written the code to ubiquitously use slices, but we didn't so this is second-best. Refactoring to use slices would be a long and painful journey.

**Comment by seunlanlege** [comment]
is this being actively worked on?

**Comment by adria0** [comment]
Closing issue due to its stale state.
