### ISSUE TITLE
Make docker image build on alpine:edge instead of alpine:3.13.2

### ISSUE THREAD

**Issue by varasev** [openethereum/openethereum#614]
Some time ago `alpine` version was fixed to `3.13.2` because of `cmake` compiling errors: https://github.com/openethereum/openethereum/commit/a55799d52366574e6e62da71f26cfd0585ba487a. We need an ability to build OE docker image on `alpine:edge`.

**Comment by varasev** [comment]
For `alpine:3.13.2` it's important to set `edition = "2018"` in `crates/rpc-common/Cargo.toml` and `crates/rpc-servers/Cargo.toml`.

**Comment by rimrakhimov** [comment]
Fixed in #633
