### ISSUE TITLE
Instant finality mode

### ISSUE THREAD

**Issue by arkpar** [openethereum/openethereum#6351]
With this mode enabled Parity RPC would report head of the chain to be N blocks behind the actual head. Pending state would include last N blocks and all transactions from the last N blocks would be returned as "pending".
A more advanced version could be implemented on a per-dapp basis.

**Comment by dip239** [comment]
opened correspondend RFE at [web3.js](https://github.com/ethereum/web3.js/issues/1003)

**Comment by folsen** [comment]
@arkpar What's the motivation behind this, is there anyone else doing this?

**Comment by folsen** [comment]
@dip239 so a basic version of this feature would look like `parity --delayed` and it just pretends it's 5 blocks behind the tip?

**Comment by adria0** [comment]
Closing issue due to its stale state.
