### ISSUE TITLE
Unable to export database before ancient blocks download is completed.

### ISSUE THREAD

**Issue by 3esmit** [openethereum/openethereum#6933]
**Adding a TLDR here**: `parity export blocks` should export blocks up the point that they exist, and print out a warning that it is not complete if not all ancient blocks are downloaded.

----

I'm trying `parity export blocks`
and I'm end up with this
```
(...)
2017-10-29 17:53:14  #3810000
2017-10-29 17:53:16  #3820000
2017-10-29 17:53:18  #3830000
Error exporting incomplete chain
```

How my chain is incomplete? I have parity open for weeks... it should been synced 100%
Where I can check the download of my blockchain and how to ensure it stays complete?

I'm running:
 - **Parity version**: 1.8.2
 - **Operating system**: Linux
 - **And installed**: installer (.deb from releases)

**Comment by Office-Julia** [comment]
Hello.
Let me assist you in resolving this issue.

Perhaps problem is damaged database (due to memory problem or something).
Could you please run the following command:

>  parity db kill

Regards,
Julia.

**Comment by 3esmit** [comment]
> parity db kill

You know this hurts? I'm trying to export db because I don't want to download it again.

**Comment by 5chdn** [comment]
Are you fully synchronized? It seems you are not certain about it.

How does your configuration look like? Are you using warp sync or disabling ancient block download?

**Comment by 3esmit** [comment]
I'm using regular config about database, I just changed ports and node connection settings. 
It seems that I'm not fully syncronized, but parity says I am, thats because of warp sync. I would like to be able to see the download of blockchain history on background when warp synced.

**Comment by 5chdn** [comment]
You see that, the yellow block numbers in your logs are the ancient blocks.

**Comment by 3esmit** [comment]
Seems like after awhile I was able to export.
I guess this confusion would be clearified if a progress bar in Parity UI containing the ancient block be at footer

```
2017-11-02 13:59:54  #4440000
2017-11-02 14:00:02  #4450000
2017-11-02 14:00:09  #4460000
2017-11-02 14:00:14  #4470000
2017-11-02 14:00:18  Export completed.
```

**Comment by 5chdn** [comment]
Related #6956

**Comment by 5chdn** [comment]
Leaving this open, it should be handled by the client.

**Comment by 3esmit** [comment]
I agree, it should export up to the point it have it.

**Comment by qiluge** [comment]
while I use cmd ```parity export  blocks --from 5031823 --to 5088019 block.rlp```,  parity export error: ``` Configured for Ethereum using Ethash engine
Error exporting incomplete chain```, while I remove to argument, the output is ```Configured for Ethereum using Ethash engine
2019-02-25 06:45:08 UTC Export completed.```
But my block.rlp file is empty. Is this a bug?

**Comment by seunlanlege** [comment]
@qiluge your node doesn't have that block height

**Comment by rakita** [comment]
Closing issue due to its stale state.
