### ISSUE TITLE
Modifications for better cross-project use of HashDB/Patricia Trie

### ISSUE THREAD

**Issue by rphmeier** [openethereum/openethereum#7019]
cc @debris 

HashDB interface currently uses local primitive types, while with the `primitives` crate approach local types can be used. Also the assumption on keccak is not likely to remain strong.

A modification of the interface from

```rust
trait HashDB {
    fn insert(&mut self, value: Vec<u8>) -> H256; 

    ....
}
```

```rust
trait HashFunction {
    type Out: Debug + PartialEq + Eq + Clone + Copy + Hash + Send + Sync;

    fn hash(x: &[u8]) -> Self::Out;
}

trait HashDB<F: HashFunction> {
    fn insert(&mut self, value: Vec<u8>) -> F::Out;

    ....
}
```

would be a definite improvement and lead to the crate carrying around fewer dependencies.

-------

One problem is the special-casing of many known hashes like NULL_RLP, RLP_EMPTY, etc. in the patricia trie or in memory db. How can we handle the special cases correctly without re-hashing or doing extra work on each hash?

**Comment by rphmeier** [comment]
Trait aliases makes this even better, but a local `trait KeccakDB: HashDB<Keccak256> {}` with a blanket impl would be fine too.

**Comment by folsen** [comment]
@dvdplm is this related to what you're working on?

**Comment by rphmeier** [comment]
I think this is a part of it yeah. I forgot I filed this one!

**Comment by adria0** [comment]
Closing the issue due to its stale state
