### ISSUE TITLE
Expose finality information to BlockChain

### ISSUE THREAD

**Issue by rphmeier** [openethereum/openethereum#7358]
- Reorganization past finalized blocks should not be allowed
 - `parity_lastFinalized` RPC call
 - Maybe fire an event when a block is finalized

**Comment by andresilva** [comment]
Only the first bullet point is implemented right now, there's no way to get finality info through the RPC and no event is fired when a block is finalized. I think we should at least implement the RPC method before closing this.

**Comment by adria0** [comment]
Closing issue due to its stale state.
