### ISSUE TITLE
jsonrpc call trace_replayTransaction slows dramatically with bigger db

### ISSUE THREAD

**Issue by jo-tud** [openethereum/openethereum#7423]
I'm running:
**Which Parity version?**: v1.9.0-unstable
**Which operating system?**: Linux
**How installed?**: from source
**Are you fully synchronized?**: no
**Did you try to restart the node?**: yes

*I'm running parity with the parameters: --pruning archive --tracing on --mode active --fat-db on --scale-verifiers*

**RPC-Call (Tx in block 2396812) :** `curl --data '{"method":"trace_replayTransaction","params":["0x0a735d7da893a87fbcd7c9dfa49dfafa7b0c62ae69b1883c1bbd91e785f58ad9",["trace","vmTrace","stateDiff"]],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545 > /dev/null`

Actual: When executing the RPC-Call right after block 2396812 is synced it takes 15-20 seconds. Then as more and more of the chain is synced the call takes more and more time to finish. For example when it is synced to block 3.2M, the call takes 2.5min. When it is synced to block 4M it takes over 5min.

Expected: The RPC-Call has similar execution times, independent of the synced chain size.

**Comment by tzapu** [comment]
hello,

I tested for this and got the following results
chain synced to ~2.4 mil blocks
first run: 0:00:15
second run: 0:00:04
chain synced to ~4.8 mil blocks
first run: 0:25:15
second run: 0:22:17

mode offline, tracing on, archive,  16gb cache-size.
while it's running, 1 CPU core is 100% used.

cheers
alex

**Comment by folsen** [comment]
@tzapu Is this on a HDD or SSD?

**Comment by tzapu** [comment]
@folsen this was on an assortment of hosted or local ssd s
cheers

**Comment by sammy1991106** [comment]
Experience the same issue on Ropsten

**Comment by wenhuanglin** [comment]
@tzapu I dont have this issue with my node setting is `--tracing on`. Yet when i tried to replay a fail tx (out of gas), it takes more than 10 mins to get response and it slows the whole node.
