### ISSUE TITLE
Impossible to create snapshots with OverlayRecent pruning

### ISSUE THREAD

**Issue by 5chdn** [openethereum/openethereum#7436]
> - **Which Parity version?**: 1.8.5
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: no

As discussed on Riot.

> a fresh parity installation warps directly to #4455000 (400k blocks behind)
>
>     2018-01-02 09:59 +00:00: 2018-01-02 09:59:05 UTC Snapshot: 1614697 accounts 0 blocks 396046888 bytes
>     2018-01-02 09:59 +00:00: 2018-01-02 09:59:06 UTC Imported #4841004 4986…90f2 (169 txs, 7.96 Mgas, 1128.18 ms, 34.60 KiB)
>     2018-01-02 09:59 +00:00: 2018-01-02 09:59:07 UTC Periodic snapshot failed: block state pruned.Run with a longer `--pruning-history` or with `--no-periodic-snapshot`
> 
> with pruning history of 1000 the bootnode only had time to put 1614697 accounts in before failing
> according to etherscan there's 17.5 million accounts
> at this rate we won't be able to produce snapshots with OverlayRecent pruning
> we should look into enabling a different pruning algo that does not require keeping recent states in memory

**Comment by 5chdn** [comment]
related to but not certainly the same issue #6372

**Comment by slavicd** [comment]
What does it mean for the regular user, though? Should one use geth for now or can this be mitigated somehow with parity? (Waiting 40+ hours for sync is not a solution, I believe)

**Comment by folsen** [comment]
Closing in favor of all the ongoing work to improve snapshot creation/downloading/chunking.

**Comment by 5chdn** [comment]
I'm unsure. This issue is far from being resolved and it gets more urgent every day. Please close if you are _really_ sure this will be fixed soon by any other workaround.

**Comment by vorot93** [comment]
Warp sync works now.
