### ISSUE TITLE
Panic at 'nonce will return Some when given BlockId::Latest'

### ISSUE THREAD

**Issue by yorickdowne** [openethereum/openethereum#75]
OpenEthereum 3.1.0-rc1-stable-51817baec-20200925/x86_64-linux-gnu/rustc1.46.0

- **Installation**:  built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: Automatically on failure

OE panics, and on restart reports a corrupted DB. See attached log.
[openeth.log](https://github.com/openethereum/backport-3.1/files/5406907/openeth.log)

**Comment by adria0** [comment]
It seems an old bug https://github.com/openethereum/openethereum/issues/10075

**Comment by yorickdowne** [comment]
Do you want the DB?

**Comment by adria0** [comment]
@yorickdowne yes, please. Send me the data via private discord.

**Comment by rakita** [comment]
last week I put some various [sleeps ](https://github.com/openethereum/backport-3.1/tree/rakita/test/inconsistency) in-between cache/db commit in OE, and I got similar problem as you in `TransactionQueue::import` but for me it was missing state of best block. Ether way, I tweaked how verification of new blocks are done [here](https://github.com/openethereum/backport-3.1/pull/74), and with sleeps added, left it for few days to run. It seems that it helped. I am currently running it for testing.

**Comment by yorickdowne** [comment]
Building that now, @rakita . That sounds promising.

**Comment by yorickdowne** [comment]
Hello @rakita , congrats on 3.1 release! Your change is in `dev` I see but not `main` quite yet. I'm still syncing on it, a sync from scratch isn't fast. Since 3.1 release it looks like snapshot servers are now available, and it's trying to get a snapshot. Let's see how it does. I may recompile from `dev` to get the 3.1 release with your change for this testing.

**Comment by rakita** [comment]
Thanks @yorickdowne.  Yeah, change is in dev.

**Comment by yorickdowne** [comment]
I'll be checking in every so often here. So far so good, still progressing with sync on `dev`. I'm at 10,636k, I expect it'll take a week or more longer.

**Comment by rakita** [comment]
This is probably related with #69, for for that is found here: https://github.com/openethereum/openethereum/pull/149

**Comment by ryanobjc** [comment]
I also have this.

**Comment by ryanobjc** [comment]
That PR code didn't seem to recover my install.  I tried doing db reset <N> more but it just broke my db, and so now I just deleted my entire eth node and will have to redownload the entire blockchain again.

What version of openethereum should I use if I want it to just... work?

**Comment by rakita** [comment]
@ryanobjc This is probably related to #69 use this pull request to sync again [this pull request](https://github.com/openethereum/openethereum/pull/149)

**Comment by yorickdowne** [comment]
Resolved with current code
