### ISSUE TITLE
u8 overflow in Session.read_hello

### ISSUE THREAD

**Issue by yrashk** [openethereum/openethereum#7567]
> I'm running:
>
> - **Which Parity version?**: master
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: other
> - **Did you try to restart the node?**: yes

In connection to my investigation mentioned in https://github.com/paritytech/parity/issues/7566, I have found what seem to me to be a subtle bug in capabilities negotiation code.

Particularly, when updating offsets of capabilities ID's https://github.com/paritytech/parity/blob/master/util/network/src/session.rs#L537 there's a `+=` operation on a u8. The crux of the issue here is that if you `cargo build --release`, this operation will wrap on overflow, but it will panic in `debug`: https://play.rust-lang.org/?gist=0aad6f0feaeddde21400dec729773f94&version=stable -- you can see the difference by alternating`Mode` between `Debug` and `Release`.

To the best of my understanding, this issue is *not* theoretical as Whisper's implementation seems to add two protocols with the same high-number `packet_count` (128): https://github.com/paritytech/parity/blob/master/parity/whisper.rs#L90-L103. 

Adding 128 twice *will* create an overflow. This means that the resulting ID offsets will wrap. Is this an intended behaviour or not?

Even if this behaviour is intended, at least currently, if you use debug builds of Parity, with Whisper enabled, this will crash one of the clients because of the overflow.

Any clarification on this matter will be highly appreciated.

**Comment by debris** [comment]
thanks @yrashk for detailed description of the problem! @arkpar how should be solve this issue?

**Comment by arkpar** [comment]
According to the spec packet id is a single byte < 2**7. In case common capabilities exceed that the behaviour is unspecified however. I guess it would be simply check for total number of packets when processing `NetworkIoMessage::AddHandler` message and panic.
@rphmeier  would it be possible to reduce the number of packet type in the extension protocol?

**Comment by rphmeier** [comment]
Yes, I think it is only necessary for the main whisper protocol for compatibility with Geth nodes.

**Comment by yrashk** [comment]
Just for the convenience of future readers of this thread: https://github.com/ethereum/devp2p/blob/master/rlpx.md is the spec referred to by @arkpar

**Comment by yrashk** [comment]
On this note, I am still not sure where does the 128 packet types requirement come from. Any clues?

**Comment by arkpar** [comment]
@yrashk It's in the spec that you've referenced:
`packet-type: single byte < 2**7 // valid values are [1,4]`

**Comment by yrashk** [comment]
Any thoughts on how we can resolve this? I asked the specification author why does it use 128 types and the answer was "we need to decide upon some arbitrary number. 128 is as good as any other.". I am not sure that's a great rationale, but that's what we have so far.

**Comment by rphmeier** [comment]
Well the real reason is that we decided to reserve additional packet codes for whisper (actually so Geth can keep using its `MailServer` extensions). We should just register the `ParityExtensions` to whisper using fewer packet types since it only needs a couple.
