### ISSUE TITLE
Implement filesystem tree structure for keys subdirectory to prevent thousand of files in one directory

### ISSUE THREAD

**Issue by c0deright** [openethereum/openethereum#7691]
# Environment

> - **Which Parity version?**: v1.7.10-stable-3931713-20171211/x86_64-linux-gnu/rustc1.22.1
> - **Which operating system?**: Linux
> - **How installed?**: dpkg -i parity_1.7.10_amd64.deb

# Current situation

Running a parity node with ten thousand or possible hundreds of thousands private key files in `~/.local/share/io.parity.ethereum/keys/ethereum` might be a problem for some filesystems. Tools like `updatedb`, `ls` or `du` might cause problems on directories with that many files in it.

# Possible improvement

Break down the contents of the keys directory in a 2 directories deep structure of e.g. 16 directories each like `mkdir` would do with this cmd:

`mkdir -p {0..9}/{0..9} {0..9}/{a..f} {a..f}/{0..9} {a..f}/{a..f}`

Then find a way to balance new key files in these 256 directories (per random?). Allow externally generated key files to be dropped in any of the subdirectories (inotify on all 256 directories?).

**Comment by folsen** [comment]
Some additional things previously discussed around this issue:

* There would be a problem with usability if it was always folders, it is a very niche use-case to have thousands of keys handled by Parity, the average user would prefer to have one folder, so the feature would need to be opt-in.
* If one opts in after already having keys, keys need to be moved into the folder structure in a migration script.
* Similarly, how does it handle when opting-out, migrate everything back to one folder? Or should always find all keys in all folders and so the user themselves can choose their folder structure.

**Comment by c0deright** [comment]
Hi @folsen 

* Opt-In: That's fine. Only power-users will need this feature
* Moving key files by parity when enabling/disabling that feature I guess it not the best way. Nobody would assume parity doing this.

I would propose a flag that just enables searching in *all* subdirectories beneath `keys/ethereum` for private keys instead of only the `keys/ethereum` directory itself. Parity should not move key files around. Creating a directory structure and placing new key files should be left to the user running parity.

**Comment by folsen** [comment]
@c0deright putting the burden on the user to manage the keyfiles and folders doesn't seem great, but it would make implementation a lot easier if we just said that it's supposed to read files from all folders in the keys folder, not just keys in the root.

**Comment by adria0** [comment]
Closing issue due to its stale state.
