### ISSUE TITLE
Add "context data" flow through the engine pipeline

### ISSUE THREAD

**Issue by andresilva** [openethereum/openethereum#7840]
The idea is to be able to have a specific context defined for each different engine. The context is passed through the engine pipeline as a block is created, its header is populated from its parent, closed and sealed. This is useful for example to be able to do reward attribution based on information that will be added in the seal.

Ideally this would be done with an associated type but currently engines are mostly used as trait objects.

**Comment by rphmeier** [comment]
I think this is related to @0x7CFE's Client refactoring. The key observation is that basically only the client and block sealer use the verification pipeline in a way that would require context data to be threaded through, so we can split up the trait into two; one which provides a `VerificationPipeline` and one which provides other `Engine` data like `extra_info`, `seal_fields`, etc. When instantiating a client we can instead have it be generic over the `VerificationPipeline`.

**Comment by adria0** [comment]
Closing the issue due to its stale state
