### ISSUE TITLE
Get the light client to compile for wasm

### ISSUE THREAD

**Issue by tomaka** [openethereum/openethereum#7915]
cc @rphmeier 

In order to be able to run the light client inside of a browser extension.

Problematic libraries include `mio` (doesn't support emscripten), `ring` (uses raw assembly), `rocksdb` and `openssl` (both will be hard to compile).

**Comment by kirushik** [comment]
`openssl` will likely be replaced with `rustls` as a part of #7829, so it's eventually will be the `ring` issue again.

**Comment by tomaka** [comment]
A good first step for this issue is either #7954 or #7955.

**Comment by rphmeier** [comment]
I would break up the tasks for this like so:
  - [ ] Break out any explicit dependency on `ethcore-network` from `ethcore-light`, instead doing everything through traits
  - [ ] Break out any explicit dependency on `rocksdb` (this may already not exist as everything is done through the `KeyValueDb` trait.
  - [ ] Compile `ethcore-light` and `ethcore-rpc` for WASM.
  - [ ] Write a Rust wrapper which expects extern functions that can provide network and DB context somehow and also exports a function for making RPC calls.
  - [ ] Write JS code that uses libp2p and local storage to fulfill the requirements of the Rust wrapper and can use its RPC function to answer its queries

**Comment by tomaka** [comment]
Should the network code be hard-coded to libp2p/devp2p (eg. pass an instance of `libp2p::Transport`), or should it be more generic?

I'd go for the first option, because Parity may depend on some specific networking behaviours. If we go for the second option, every single corner case would need to be documented in the API.

**Comment by rphmeier** [comment]
Keeping it generic seems the best way to make it testable. Right now the light client network code is fairly network-independent and exposes a few hooks that can be called by devp2p or libp2p or an in-memory test network.

**Comment by tomaka** [comment]
> In general, how are you supposed to unit test libp2p-based code?

You can fairly easily create an implementation of [the `Transport` trait](https://github.com/libp2p/rust-libp2p/blob/3b859b683357abbb13bb9f48c97643363446beb1/libp2p-swarm/src/transport.rs#L73-L103) that reads/write to/from memory, or that calls a custom handler.

**Comment by tomaka** [comment]
> Take ethcore-io stuff out of ethcore to cut out the mio dependency.

This is really difficult, so instead I suggest adding an optional `mio` feature to `ethcore-io`.
Only `network-devp2p` would require that `mio` feature.

**Comment by tomaka** [comment]
Notes for myself for crypto libraries alternatives:
- https://github.com/dalek-cryptography
- https://github.com/RustCrypto

**Comment by adria0** [comment]
Closing issue due to its stale state.
