### ISSUE TITLE
Add parameter in chain spec for wasm-only network

### ISSUE THREAD

**Issue by bjornwgnr** [openethereum/openethereum#8179]

**Comment by Tbaut** [comment]
Isn't that the same issue ? https://github.com/paritytech/wiki/issues/29
I'll do that prob. tomorrow

**Comment by niklasad1** [comment]
@Tbaut I think this is not implemented yet and is on the ```wishlist```

**Comment by 5chdn** [comment]
We could have an `EvmActivationTransition` so custom chains could set this to `0x7fffffffffffff` to have Wasm only.

**Comment by 5chdn** [comment]
@HCastano what we currently have is a `wasmActivationTransition`, so we can enable Wasm VM in addition to the Ethereum VM. I'm not entirely sure what's the best way to get this implemented, but I would suggest introducing an `evmActivationTransition` that defaults to `0x0` means all chains have EVM enabled by default (this makes sense to some degree and guarantees backward compatibility with existing chains).

And the actual logic behind `evmActivationTransition` would be to control when (or if ever) there should be an EVM enabled. I'm unsure what's the best way to implement this. Hope that helps.

**Comment by adria0** [comment]
Closing issue due to its stale state.
