### ISSUE TITLE
refactor the way tasks are scheduled in event-loop

### ISSUE THREAD

**Issue by debris** [openethereum/openethereum#8186]
after #8185 

Current design requires us to define all tasks types in a single place in `ClientIoMessage`. It makes it difficult to modularize `ethcore` . Let's think how we could refactor that so tasks could be scheduled without the need of defining them in a single place.

cc @tomaka @0x7CFE

**Comment by tomaka** [comment]
Ideally the long-term plan would be to remove the current `ethcore_io` crate and use futures and streams.
If that happens, each individual message could have its own stream.

**Comment by 0x7CFE** [comment]
@debris Recently I was skimming through a [blog post describing Actix API](https://simplabs.com/blog/2018/06/11/actix.html). Maybe we may use something similar.

The key idea is that instead of huge enums messages and handlers may be defined as trait impls:
```rust
use actix::prelude::*;

// `PlusOne` message implementation

struct PlusOne;

impl Message for PlusOne {
    type Result = u32;
}

// `CounterActor` implementation

struct CounterActor {
    count: u32,
}

impl CounterActor {
    pub fn new() -> CounterActor {
        CounterActor { count: 0 }
    }
}

impl Actor for CounterActor {
    type Context = Context<Self>;
}

impl Handler<PlusOne> for CounterActor {
    type Result = u32;

    fn handle(&mut self, _msg: PlusOne, _ctx: &mut Context<Self>) -> u32 {
        self.count += 1;
        self.count
    }
}
```

That way code would be organized more naturally.

**Comment by adria0** [comment]
Closing the issue due to its stale state
