### ISSUE TITLE
Command line utility for recreating traces

### ISSUE THREAD

**Issue by debris** [openethereum/openethereum#8221]
It should be possible for users with fatdb to recreate tracesdb.

cc #8217

**Comment by tomusdrw** [comment]
Why fatdb? I think you can recreate tracesdb from any db, given that you have the state (so probably archive would be required) before the block.

**Comment by debris** [comment]
> Might deserve an RPC as well?

I would put this feature in database-fix utilities, so I believe that we do not need an rpc for that
