### ISSUE TITLE
Support snapshots (evm_snapshot/evm_revert)

### ISSUE THREAD

**Issue by LogvinovLeon** [openethereum/openethereum#8266]
When developing smart contracts it's usefull to have your tests independent on each other. That simplifies writing and debugging them. Currently frameworks like truffle allow you to do so.
When they run against clients supporting snapshots (`evm_snapshot/evm_revert`) they use that. When they run against Parity/Geth they just redeploy all the contracts before each test. That's inefficient. Setup takes a lot of time and could be reused.

This issue is a feature request to implement Ganache-like `evm_snapshot` and `evm_revert` functionality.

Side note: I know that Parity is not intended to use for automated and fast CI testing as Ganache, but Ganache uses `ethereumjs-vm` which is majorly outdated and I want to run my tests against a modern VM.

**Comment by folsen** [comment]
@maciejhirsz Is this something we would want to support in Parity directly or just through the evm lib and like adapt the vm to be usable directly with ganache and truffle?

**Comment by LogvinovLeon** [comment]
Any updates here? We've just managed to get it working in Geth and waiting for a PR to get merged into upstream.

**Comment by LogvinovLeon** [comment]
Is there any chance someone from the Parity team will look into that?
If no and if we find some eng cycles to look into that - will you be willing to review the PR and get it merged once it's ready? Also - do you have any suggestions for someone who will be working on that about where to start?

**Comment by maciejhirsz** [comment]
I don't think anyone is working on this, else there would be an assignee.

**Comment by folsen** [comment]
@LogvinovLeon We would definitely be willing to review PRs and merge as well as try to help out and mentor as much as we can. I think it's best to join the watercooler on riot to find some help and/or PM me there and I can see if I can set you up with someone that is willing to mentor.

**Comment by adria0** [comment]
Closing issue due to its stale state.
