### ISSUE TITLE
(Feature Request) Add whitelisting for unlocked accounts

### ISSUE THREAD

**Issue by rstormsf** [openethereum/openethereum#8361]
# Scenario:
If parity has unlocked account, provide an ability to whitelist a list of addresses to which this account can send transactions to.
For example:
`config.toml`
```yaml
[account]
unlock = ["0xb8...3"]
password = ["parity_password"]
whitelisted_accounts_to_send = ["0x0...4"]
```
so in that case if someone gains access to public RPC port, the attacker will still not be able to withdraw all the funds from unlocked account

# WHY
1. I have made an experiment by deploying parity node with testnet Sokol coins and leaving 8545 port open. Within 13 hours, the botnet was able to flood the node with transactions. First of all, it withdrew all the funds. Second, it flooded the node with pending tx, so as soon as the unlocked accounts received any funds, it will lose them the second it was received.
2. It will make a better security model for [parity-bridges](https://github.com/paritytech/parity-bridge), hence making @snd life much easier.

# Solution
An unlocked account can check if the `to` field is matching the array of addresses to send, then make a transaction, otherwise reject.

# Use cases
Some people might forget to close open RPC ports or they would have to create 2nd layer in order to provide status of the node. 
With whitelisting, it will be possible to leave public RPC port with unlocked account. People do make those mistakes by deploying nodes with open ports.
It's just a convenience for many other devs who don't have much experience in devops.

**Comment by adria0** [comment]
Closing issue due to its stale state.
