### ISSUE TITLE
Document breaking config changes in 3.1

### ISSUE THREAD

**Issue by Legogris** [openethereum/openethereum#84]
3.1 has several breaking config changes; `snapshot` parameters are changed, `rpc` api is not recognized, I'm sure there are others.

Release notes would ideally contain explicit lists of breaking changes for users upgrading.

**Comment by adria0** [comment]
@Legogris, agree, we need to improve this. Thank you for signaling us.

**Comment by rakita** [comment]
3.1 release was kinda special because bese code was v2.5.13, in future releases, this should be better.
