### ISSUE TITLE
Split test specs

### ISSUE THREAD

**Issue by andresilva** [openethereum/openethereum#8424]
https://github.com/paritytech/parity/pull/8419#discussion_r182053038

Currently we just put all test specs in the `res` folder regardless of where they're used. We should split https://github.com/paritytech/parity/blob/master/ethcore/src/spec/spec.rs#L809 and move each spec to the module that uses it. We should also annotate test specs with `#[cfg(test)]` so that the spec isn't included in the binary.

**Comment by adria0** [comment]
Closing the issue due to its stale state
