### ISSUE TITLE
Persistent time-based peer disabling

### ISSUE THREAD

**Issue by tomusdrw** [openethereum/openethereum#8428]
Currently we only "ban" peers in memory, when we detect they are on some different forks or different networks.

Every time the node is started though we again make a dozen of useless connections and requests, cause that info is not persisted.

I think it would make sense to have a file similar to `nodes.json` where we store peers that are temporarily banned (for some speciifc amount of time).

It would also help with dealing with warp-sync issues, currently you may end up with 25 peers that cannot provide you snapshot data that you are requesting (with `--warp-barrier`) - in such case we just idle and hope new peers will connect to use, or the old ones will get disconnected. The solution would be to temporarily ban current peers (say for 5 minutes), disconnect them and try to discover more.

CC @andresilva @ngotchac 

@rphmeier any thoughts?

**Comment by adria0** [comment]
Closing issue due to its stale state.
