### ISSUE TITLE
Call ``getTransaction`` json-rpc api in pending filter callback returns None

### ISSUE THREAD

**Issue by yihuang** [openethereum/openethereum#8482]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.0-beta-0a9d41e-20180320/x86_64-linux-gnu/rustc1.24.1
> - **Which operating system?**: Linux
> - **How installed?**: installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I'm using json-rpc api to process new transactions, my code is like this:

```
def on_new_transaction(w3, h):
    trans = w3.eth.getTransaction(h)
    assert trans != None, 'impossible'

filter  = w3.eth.filter('pending')
filter.watch(functools.partial(on_new_transaction, w3))
```

Expected behavior: ``getTransaction`` shouldn't return ``None``.
Actual behavior: it returns ``None`` very often.
What should I do?

**Comment by tomusdrw** [comment]
Are you running in `--geth` mode? What pool size do you have? Any CLI set for `--relay-set`?

**Comment by yihuang** [comment]
Full command of running parity:

``/usr/bin/parity --rpcport=8357 --port=30305 --jsonrpc-apis=all --cache-size=2048 --geth --mode=active --min-peers=50 --max-peers=100 --db-compaction=ssd``

**Comment by adria0** [comment]
Closing issue due to its stale state.
