### ISSUE TITLE
WS Error: Exceeded maximum buffer capacity

### ISSUE THREAD

**Issue by mdben1247** [openethereum/openethereum#85]
- **OpenEthereum version**: 3.1.0
- **Operating system**: Linux
- **Installation**: built from source
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

An error occours when sending requests with websockets and the response is large in size (such as querying some historic logs):

`WS Error <Io(Custom { kind: InvalidInput, error: "Exceeded maximum buffer capacity" })>`

I guess this is due to upgrade in jsonrpc-core to v15.0.0, which now has a default maximum payload of 5MB. Attached is a small patch that adds a new setting: ws-max-payload. Ideally this would be split to in/out max size, but this version does not support it yet, see paritytech/jsonrpc#594

[max_payload.zip](https://github.com/openethereum/openethereum/files/5517160/max_payload.zip)

**Comment by rakita** [comment]
done at https://github.com/openethereum/openethereum/pull/112
