### ISSUE TITLE
Make it possible to control logging in parity-clib

### ISSUE THREAD

**Issue by tomaka** [openethereum/openethereum#8574]
Right now the logs are always printed on stdout with no way of retrieving them or filtering them.

**Comment by tomaka** [comment]
This is complicated because of the `parity_devLogs` RPC query which requires returning the logs.

**Comment by tomaka** [comment]
Also there's a "conflict" with the CLI options that allow controlling the mode, color and file of the logging.

**Comment by seunlanlege** [comment]
this should be closed with #10007

**Comment by adria0** [comment]
Closing issue due to its stale state.
