### ISSUE TITLE
Make it possible to customize the database and network backends in parity-clib

### ISSUE THREAD

**Issue by tomaka** [openethereum/openethereum#8575]
So that you can use your own custom implementation.

Important especially for the database for Android/iOS/emscripten.

**Comment by tomaka** [comment]
Changed to "somedaymaybe" because we can run a light client in the browser or on Android without having to customize the database or networking layer (although that would be a plus).

**Comment by sorpaas** [comment]
This is actually do-able given we've done the rocksdb refactoring. We basically just need to copy and re-implement this mod (https://github.com/paritytech/parity/blob/master/parity/db/rocksdb/mod.rs), and then expose that to C.

**Comment by adria0** [comment]
Closing issue due to its stale state.
