### ISSUE TITLE
Test eth RPC interface for the light client.

### ISSUE THREAD

**Issue by dvdplm** [openethereum/openethereum#8693]
Currently there are no tests for [RPC calls against the light client](https://github.com/paritytech/parity/tree/master/rpc/src/v1/impls/light) and there is a significant amount of logic to manage requests. 
The [tests for the full client require a fair amount of setup](https://github.com/paritytech/parity/blob/master/rpc/src/v1/tests/eth.rs#L84) and the difference in style of implementation means that replicating that for the light client RPC calls could be a significant chunk of work.

Can/should some of this logic be moved from the rpc crate into `ethcore/light`? It is possible that using the existing testing helpers in `ethcore/light` will make it easier to achieve proper test coverage.

The background to this issue is a [panic-bug](https://github.com/paritytech/parity/issues/8678) that was caused by an off-by-one mistake in the [rpc crate](https://github.com/paritytech/parity/pull/8683/commits/4a27a10444ffbb9cb533b025e794feda9df2d7ab) when setting up requests for an `eth_getBlockByHash` RPC call: finding the bug was harder than expected and adding a test for it even more so (hence this ticket here).

**Comment by rphmeier** [comment]
We should be able to mock the `OnDemand` service completely for the light client RPCs. IMO that would work better than actually trying to set up a dummy network to request data from.

**Comment by adria0** [comment]
Closing issue due to its stale state.
