### ISSUE TITLE
Merge 3.1.0 to the main branch

### ISSUE THREAD

**Issue by artob** [openethereum/openethereum#87]
Right now the `main` branch is at bf5830f766bf89861b92824de08f92a00de79d44 and does not reflect the fact that you've released [3.1.0](https://github.com/openethereum/openethereum/releases/tag/v3.1.0).

This is pretty confusing. In particular, the [changelog](https://github.com/openethereum/openethereum/blob/main/CHANGELOG.md) gives the impression that 3.1RC1 is the latest release.

**Comment by rakita** [comment]
you can see branch `release/v3.1.0` for a particular release. Will change changelog.

**Comment by palkeo** [comment]
Could you clarify where the main branch is?
Meaning, the branch containing the latest unreleased commits as well, that will end up in a future release. And that would be on top of the latest release, unlike the current main or dev branch.

**Comment by rakita** [comment]
`main` branch updated
