### ISSUE TITLE
Add block and uncle reward in the JSON-RPC method trace_replayBlockTracations mode='stateDiff'

### ISSUE THREAD

**Issue by ankitchiplunkar** [openethereum/openethereum#8747]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.4-stable
> - **Which operating system?**: Linux 18.04
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
This is a feature request and not a bug issue
The JSON-RPC method trace_replayBlockTracations when run in mode stateDiff returns the differences in state after every transaction. Is it possible to also get the difference in the state due to the rewards during the block, meaning the difference in state due to the block and uncle reward?

**Comment by Tbaut** [comment]
@andresilva Is this issue at least partly solved by: https://github.com/paritytech/parity/pull/8490 ?

**Comment by andresilva** [comment]
I don't think so since that PR just extends whatever we already had for tracing rewards to tag the kind of reward. So if it wasn't showing up in `stateDiff` then that shouldn't have changed. I'm not very familiar with the tracing module so I would have to test this.

**Comment by dkrupiza** [comment]
We checked the most current code of #8490 and miner rewards for blocks as well as uncles are not reflected in the `stateDiff`. Having this data in the `stateDiff` would be great, as it would provide a complete picture of the state change (at the moment, only the `stateDiff` of transactions is presented).

**Comment by foxfromabyss** [comment]
If you replay a Block, the miner rewards are part of the block. Therefore they should also be the a part of the StateDiff of that block. But now the problem is, that the RPC call says replay transactions, but the miner reward do not constitute transactions per se. Nonetheless, they are an important part of the StateDiff for the block. Would it be correct to add a StateDiff to replay_block_transactions for this reward, even though there's no transaction, basically? And even so, should there be one StateDiff for both block and uncle miner reward, or should there be 2 separate ones?

**Comment by foxfromabyss** [comment]
The current implementation of trace_replayBlockTransactions depends on TraceResults. Without adding a transaction (which would need a concept of an account that gives the miner its rewards) we can not add the information about the miner block/uncle reward to the JSON. What would be a good way to solve this issue?

**Comment by andresilva** [comment]
There are traces available for rewards when you trace the block:

```
curl --data '{"method":"trace_block","params":["latest"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":[{"action":{"author":"0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2","rewardType":"block","value":"0x4563918244f40000"},"blockHash":"0x2a1f2b176481a6cb6f40b4e1897e777ef3c3a03fd3af8e641c16415d314aba08","blockNumber":15,"result":null,"subtraces":0,"traceAddress":[],"transactionHash":null,"transactionPosition":null,"type":"reward"}],"id":1}
```

You can check for an action of type `reward` and you can also test the `rewardType` (block author, uncle, etc.)

We have the notion of a `SYSTEM_ADDRESS` which could be used to create these virtual transactions for block rewards. This would also be useful for other kinds of system-level transactions that are part of consensus but needs to be done as part of a bigger refactoring.

**Comment by ankitchiplunkar** [comment]
@andresilva I discovered for the first time that `trace_block` returns miner/uncle rewards.

```
$ curl --data '{"method":"trace_block","params":["0x3"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0",
"result":[
{"action":{"author":"0x5088d623ba0fcf0131e0897a91734a4d83596aa0","rewardType":"block","value":"0x478eae0e571ba000"},"blockHash":"0x3d6122660cc824376f11ee842f83addc3525e2dd6756b9bcf0affa6aa88cf741","blockNumber":3,"result":null,"subtraces":0,"traceAddress":[],"transactionHash":null,"transactionPosition":null,"type":"reward"},
{"action":{"author":"0xc8ebccc5f5689fa8659d83713341e5ad19349448","rewardType":"uncle","value":"0x340aad21b3b70000"},"blockHash":"0x3d6122660cc824376f11ee842f83addc3525e2dd6756b9bcf0affa6aa88cf741","blockNumber":3,"result":null,"subtraces":0,"traceAddress":[],"transactionHash":null,"transactionPosition":null,"type":"reward"}
],
"id":1}
``` 
In that scenario, if the method `trace_replayTransactions` is not appropriate for returning block rewards, can you enable `stateDiff` during the `trace_block`? 

Example parameters:
1. `Quantity | Tag` - Integer of a block number, or the string 'earliest', 'latest' or 'pending'.
2. `Array` - Type of trace, one or more of: "trace", "stateDiff".

If yes, should I open another issue detailing the discussion?

**Comment by ankitchiplunkar** [comment]
any updates on this?

**Comment by adria0** [comment]
Closing issue due to its stale state.
