### ISSUE TITLE
Improvements to discovery implementation

### ISSUE THREAD

**Issue by jimpo** [openethereum/openethereum#8757]
> I'm running:
>
> - **Which Parity version?**: master
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ropsten
> - **Did you try to restart the node?**: yes

There are a number of issues with the current implementation of the Ethereum discovery protocol, mainly in terms of divergence from the Kademlia protocol. Here is a list of possible improvements.

- The XOR distance metric is implemented incorrectly (fixed by #8589).
- The k-buckets can grow beyond k=16 entries.
- Evictions from k-buckets are wrong because entries are not maintained in most-recently-seen order. When existing entries are pinged and they respond, the entry is not moved to the front of the bucket.
- Timeouts on FIND_NODE requests are not tracked or handled.
- The echo'ed hash in pong messages is not verified.
- Per the Kademlia protocol, when a FIND_NODE request is received, the sender should be added to the receiver's k-bucket. This does not happen.
- [Endpoint proof](https://github.com/ethereum/devp2p/blob/master/discv4.md#endpoint-proof) is not required before making FIND_NODE requests.
- The node lookup routine (`discover` method) does not guarantee that the k closest nodes to the target have been queried, as specified by Kademlia. It only guarantees the closest alpha=3 have been. 
- Ping timeout (300ms) seems quite short and there are no retries if a node times out.
- Nodes are selected for Ethereum peering from the routing table, which is biased towards XOR-closer nodes. Peers should instead by selected by a fresh lookup to a random target.
- Nodes in the routing table should be limited by subnet, as recommended in [Low Resource Eclipse Attacks on Ethereum's P2P Network](http://www.cs.bu.edu/~goldbe/projects/eclipseEth).

Some of the more significant architectural issues (like having too many nodes per k-bucket) can be solved by tracking nodes in more places. I propose that a node may be in the following locations a) a k-bucket b) a replacement cache for a k-bucket, as discussed in Section 4.2 of [the Kademlia paper](https://pdos.csail.mit.edu/~petar/papers/maymounkov-kademlia-lncs.pdf) c) a ping to the node in in-flight, waiting for response or timeout d) a queue to be pinged, to avoid flooding the network with pings e) none of the above, but we have received endpoint proof within the past 12 hours. The locations can be tracked in a HashMap of NodeId to location (as an enum), with the following transitions:

- Newly discovered nodes go to the ping queue or in-flight ping immediately.
- When an in-flight pinged node times out, it is dropped.
- When an in-flight pinged node responds with pong, it may go into a k-bucket. If the k-bucket is full, the node goes into the replacement cache (which is a FIFO queue). If the replacement cache is full, it is popped and the new node is pushed.
- When a k-bucket node times out a PING or FIND_NODE 5 times in a row, it is evicted and replaced with the back of the replacement cache.
- Periodically, all k-bucket entries are pinged at random. They remain in the k-bucket and the number of consecutive timeouts is recorded.

If GitHub issues is not the right place to track this, let me know.

**Comment by fjl** [comment]
I'm happy you're taking the initiative on those issues! I agree with all your points except one:

> Ping timeout (300ms) seems quite short and there are no retries if a node times out.

It's OK if discovery is slightly lossy in this regard. There are enough nodes around.

**Comment by adria0** [comment]
Closing the issue due to its stale state
