### ISSUE TITLE
Upgrade the ethereum-types dependency

### ISSUE THREAD

**Issue by artob** [openethereum/openethereum#88]
The new [3.1.0](https://github.com/openethereum/openethereum/releases/tag/v3.1.0) release is pulling in [ethereum-types](https://crates.io/crates/ethereum-types) [0.4.2](https://crates.io/crates/ethereum-types/0.4.2) (Feb 2019). That's a very old release, and complicates upgrading to 3.1.0 since code bases currently using Parity Ethereum 2.6, Parity Ethereum 2.7, or OpenEthereum 3.0 are going to be pulling in ethereum-types [0.6.0](https://crates.io/crates/ethereum-types/0.6.0), [0.8.0](https://crates.io/crates/ethereum-types/0.8.0), and [0.9.0](https://crates.io/crates/ethereum-types/0.9.0), respectively.

A further problem complicating what's necessary to figure out and solve the build errors due to the upgrade is that the source code for ethereum-types 0.4.2 isn't even tagged upstream in the [paritytech/parity-common](https://github.com/paritytech/parity-common) repository. Their version tags for ethereum-types begin with [0.5.3-beta.1](https://github.com/paritytech/parity-common/releases/tag/ethereum-types-v0.5.3-beta.1).

**Comment by adria0** [comment]
Agree @artob, we plan to update dependencies by 1Q2021, after BerlinHF

**Comment by rakita** [comment]
ethereum-types updated to 0.9.2 in `dev`
