### ISSUE TITLE
[Feature request] storage or caching for light nodes

### ISSUE THREAD

**Issue by andrewheadricke** [openethereum/openethereum#8815]
It would be great if Parity stored data when running in `light` mode.  I find myself querying the same blocks, contracts over and over, it would be great if Parity stored data it had received so that it didn't have to keep going to the network and asking again.

I know Geth has some caching in this regard, I would prefer it to be storage to disk, but caching would be better than nothing IMO.

**Comment by adria0** [comment]
Closing issue due to its stale state.
