### ISSUE TITLE
Error importing ancient block: Author is not a current proposer

### ISSUE THREAD

**Issue by phahulin** [openethereum/openethereum#8954]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: master
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: sokol
> - **Did you try to restart the node?**: yes

When using current master and trying to sync with an existing chain, I get a bunch of errors like this
```
Error importing ancient block: Engine error (Author is not a current proposer: Expected 0x2346…8d28, found 0xe8dd…7aca)
```
after that the sync seem to continue normally.
We use PoA-based network with validators via safeContract.

**Comment by 5chdn** [comment]
Uh, oh, did you have updates to the validator sets at some point?

**Comment by phahulin** [comment]
Yes, we have a list of validators changed within a contract + we had some forks when validator contract itself changed (using `multi`).

**Comment by phahulin** [comment]
I'm still seeing this in 1.11.8.
Is this error a blocker for update to 1.11.8 or can it be ignored?

**Comment by Tbaut** [comment]
@andresilva should know about this :)

**Comment by phahulin** [comment]
@andresilva please take a look, I'd really appreciate it.

**Comment by phahulin** [comment]
Seem to happen only during warp sync

**Comment by andresilva** [comment]
I haven't been able to reproduce this yet. Could you share the multi validator definition from your contract? (so that I can replicate similar validator set migrations).

**Comment by phahulin** [comment]
Now I also can't reproduce it reliably. It sometimes happen when warp-syncing 1.11 from 1.10 node

**Comment by phahulin** [comment]
@andresilva Sometimes I still get this error. But only during warp-sync.
Could you try to reproduce it? Please use our [spec.json(https://raw.githubusercontent.com/poanetwork/poa-chain-spec/core/spec.json) and [list of reserved peers](https://raw.githubusercontent.com/poanetwork/poa-chain-spec/core/bootnodes.txt)
```
$ parity --chain spec.json --reserved-peers bootnodes.txt
```

After warp sync completes (very quickly), wait till the background-verifier goes almost to the head of the chain (~1.5 hour) and you should get those error messages.

**Comment by andresilva** [comment]
I haven't been able to reproduce this yet. But after warp finished and it started importing I can easily replicate #9300.

**Comment by Tbaut** [comment]
Is that problem still actual? Happy to re-open if that's the case.

**Comment by froller** [comment]
Yes, it still present on Parity-Ethereum/v2.5.7-stable-6bd7db9-20190829/x86_64-linux-gnu/rustc1.36.0

**Comment by joshua-mir** [comment]
@froller could you describe the situation you see this in? (which network, sync mode, stage of sync)
