### ISSUE TITLE
Refactor: alleviate painful AsHashDB impls with macro (or magic)

### ISSUE THREAD

**Issue by dvdplm** [openethereum/openethereum#9022]
In the course of [Make HashDB generic](https://github.com/paritytech/parity/pull/8739) changes were made to the `HashDB` trait that made it impossible to keep the generic impls of `AsHashDB` we had before. To work around this concrete impls for `AsHashDB` were added in many places. Find a more elegant way to deal with the issue, e.g. by adding a `impl_as_hash_db!` macro.

See the [`NOTE`](https://github.com/paritytech/parity/pull/8739/files#diff-b7cc171f2158609f8381e6ce2db3e77eR77) in the code for more details.

**Comment by adria0** [comment]
Closing the issue due to its stale state
