### ISSUE TITLE
OpenEthereum 3.0 Broadcasts Dropped and Replaced Transactions Under Mined Blocks

### ISSUE THREAD

**Issue by ymonye** [openethereum/openethereum#91]
- **OpenEthereum version**: 3.0.1
- **Operating system**: Linux
- **Installation**: Built from source
- **Fully synchronized**: Yes (archive node)
- **Network**: Ethereum Mainnet
- **Restarted**: Yes

OpenEthereum appears to broadcast dropped and replaced transactions under mined blocks. For example, the below appears in Etherscan:

https://etherscan.io/tx/0x51449e424281045f7b49e36b8c6d10aa53c562106e3a854901b79514c6ec0cd6

However, my archive node broadcasts that transaction as appearing in block 11232270. This is after calling:

```
web3.eth.getBlock('latest').then(function(block){

//x = for loop across all transactions in that block

web3.eth.getTransactionFromBlock(block.number, x)
});
});

```

I then have to wait a few seconds before re-running the above web3 call to show correctly mined transaction hashes. The problem is running web3.eth.getBlock('latest') is unreliable under OpenEthereum if I'm too early, as the client may not have correctly processed transactions. I am better off running 'latest' - 1.

**Comment by adria0** [comment]
`3.0.1` is deprecated, please use version `3.1.0`. Closing the issue.
