### ISSUE TITLE
toml parser does not evaluate windows system variables

### ISSUE THREAD

**Issue by nicexe** [openethereum/openethereum#9110]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.10.9
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer
> - **Are you fully synchronized?**: N/A
> - **Which network are you connected to?**: N/A
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

### Description

It seems like the toml parser that parity uses does not evaluate windows system variables (like `%AppData%`).

I tried also escaping the percentage signs but no luck.
 
### Expected behavior

An entry like `chain = "%AppData%\\Parity\\Ethereum\\custom_genesis_spec.json"` in the config toml file should be evaluated to something like `c:\users\user\AppData\Roaming\Parity\Ethereum\custom_genesis_spec.json`

### Actual behavior

Paths in config toml files with windows system variables result in an error similar to this: "There was an error reading your config file at: %UserProfile%\AppData\Roaming\Parity\Ethereum\custom_genesis_spec.json"

### Steps to reproduce

1. Make a new file `C:\Users\nicexe\AppData\Roaming\Parity\Ethereum\custom_chain.toml`:
```toml
[parity]
chain = "%AppData%\\Parity\\Ethereum\\custom_genesis_spec.json"
```
2. Start parity with `"Program Files\Parity Technologies\Parity\parity.exe" --config "%UserProfile%\AppData\Roaming\Parity\Ethereum\custom_chain.toml"` on the command prompt

**Comment by nicexe** [comment]
The same problem exists on *nix systems. Confirmed on CentOS 7 and macOSX 10.13

(the env variables on such systems look more like `$THIS` though)

**Comment by debris** [comment]
parity config files do not evaluate system variables.

https://github.com/paritytech/parity-ethereum/blob/8dd4db5d85e34e9c66be5db1d7664e51f915a38b/util/dir/src/helpers.rs#L20-L32

The only supported variables are:

- `$HOME` - which is home directory
- `$BASE` - which is a parity root directory
- `$LOCAL` - which is a local path

We may consider adding system variables evaluation in future, but for now I believe we should just improve our documentation, cause it may be a bit confusing by not explaining that these variables are not system variables

https://wiki.parity.io/Configuring-Parity-Ethereum

**Comment by adria0** [comment]
Closing issue due to its stale state.
