### ISSUE TITLE
Remove engine to client circular reference

### ISSUE THREAD

**Issue by sorpaas** [openethereum/openethereum#9114]
In `ethcore`, the `Engine` trait is usually invoked by `Client`. However, in some cases, an `Engine` would also need to query additional state, and requires a reference back to `Client`. We have `Engine::register_client` and `Error::RequiresClient`. Because this is circular, it may be better if we can remove it.

Currently we only use this feature for Aura engine in two places:

* In `on_close_block`, where we need to calculate how many empty steps have passed.
* In `EpochManager::zoom_to` function, where we need to get the epoch transition for the parent block.

The first one can be easily fixed by using the new AncestryIterator, possibly combined with `set_metadata`.

The second one is a little bit more complicated -- we would need to add an extra field to `BlockDetails`, recording the current epoch transition directly, and then use the same method we allowed engine to fetch finalized info to fetch current epoch transition. The complication arises because this time we cannot avoid a DB migration. But it indeed has its benefits -- the `epoch_transition_for` function can now be always `O(1)`.

**Comment by adria0** [comment]
Closing the issue due to its stale state
