### ISSUE TITLE
Alternative scoring implementation

### ISSUE THREAD

**Issue by tomusdrw** [openethereum/openethereum#9118]
## Why
Currently our scoring implementation is using a simple mapping of:
```
score = gas price
```
and every transaction is considered independently.

However a chain of transactions from a single sender:
```
Tx1(sender=X, nonce=N, gas_price=10)
Tx2(sender=X, nonce=N+1, gas_price=1_000)
Tx3(sender=X, nonce=N+2, gas_price=1_000_000)
```
is blocked by the score of the first transaction (we will never include `Tx1` if there are other transactions with `gas_price > 10` that can be included).
Including though `Tx1` would (most likely) allow us to include `Tx2` and `Tx3` and get the high fee that is payed there.

## How

The idea is to implement an alternative (experimental) scoring (should be controlled via CLI flag) that will bump a score of `Tx1` to reflect that there are more transactions in the chain.

Possible algorithm:
```rust
let last_index = txs.len() - 1;
score[last_index] = gas_price[last_index];
for i in last_index..1 {
   score[i - 1] = gas_price[i - 1]   // base score is always equal to gas price
         + is_consecutive(i - 1)     // only apply to consecutive nonces
         * 21_000 / gas[i - 1]       // "heavy" transactions are harder to bump
         * score[i]                  // Use the score of next transaction
         / 1_000                     // But require it to be order of magnitude greater
}

fn is_consecutive(i) {
 if nonce[i] + 1 == nonce[i+1] { 1 } else { 0 }
}
```

## Examples
Couple of examples of how it behaves:
```
# Simple transaction, increasing gas price

{"gp":1,"gas":21000,"score":3}
{"gp":1000,"gas":21000,"score":2000}
{"gp":1000000,"gas":21000,"score":1000000}
-----------------------
{"gp":1,"gas":21000,"score":2}
{"gp":1000,"gas":21000,"score":1000}
-----------------------
{"gp":1,"gas":21000,"score":2.001}
{"gp":1000,"gas":21000,"score":1001}
{"gp":1000,"gas":21000,"score":1000}

# Large transaction is harder to bump

{"gp":1,"gas":1000000,"score":1.021}
{"gp":1000,"gas":21000,"score":1000}
-----------------------
{"gp":1,"gas":1000000,"score":1.042}
{"gp":1000,"gas":21000,"score":2000}
{"gp":1000000,"gas":1000000,"score":1000000}
-----------------------
{"gp":1,"gas":1000000,"score":22}
{"gp":1000000,"gas":21000,"score":1000000}
-----------------------
{"gp":1,"gas":21000,"score":1001}
{"gp":1000000,"gas":1000000,"score":1000000}

# Transactions with similar fee are only slightly affected.
{"gp":1,"gas":21000,"score":1.001001}
{"gp":1,"gas":21000,"score":1.001}
{"gp":1,"gas":21000,"score":1}
-----------------------
{"gp":1,"gas":21000,"score":1.001000021}
{"gp":1,"gas":1000000,"score":1.000021}
{"gp":1,"gas":5000000,"score":1}
-----------------------
```

Possible attack scenario to proposed scheme:
```
Tx1 {"gp":1,"gas":21000,"score":2625000001.001}
Tx2 {"gp":1,"gas":8000000,"score":2625000000001}
Tx3 {"gp":1e+18,"gas":21000,"score":1e+18}
```
Tx3 is used to bump the priority of `Tx1`, and `Tx2` is just transfering out all the remaining funds yelding `Tx3` invalid.
This could be addressed by only looking one transactions ahead (i.e. use `gasPrice[i]` instead of `score[i]`). 

The attack could also be possible if `Tx1` was clearing the account as well (i.e. calling a contract, with the entire balance). Preventing such scenario is way more difficult, but could be addressed by not bumping priority if we detect that the remaining balance of the account does not cover the cost of next transaction (we would assume that the account won't get topped up in the meantime nor will it get any refunds).
We could also disable prioritization if any transaction is transferring more than half of the entire account balance.

## Notes

Related discussions: https://ethereum-magicians.org/t/child-pays-the-parent-in-ethereum-help-build-this-eip/639

Implementing the scoring will affect propagation as well, but obviously receiving peer will be deciding on the priorities on their own, so may decide to reject the transaction anyway.

Also for the scoring bump to be effective all transactions need to get to the pool on regular terms (i.e. without the bump) - the priority is only affected after all of them are imported.

**Comment by tomusdrw** [comment]
@insipx yeah, we basically want local transactions to always have the highest priority.

**Comment by adria0** [comment]
Closing issue due to its stale state.
