### ISSUE TITLE
Excessive memory use during consistent jsonrpc queries

### ISSUE THREAD

**Issue by tzapu** [openethereum/openethereum#9344]
Hello,

As per the multiple issues and responses given (eg https://github.com/paritytech/parity-ethereum/issues/8974#issuecomment-407065513) it seems there is a correlation between available resources, json rpc threads and their saturation and dropping peer counts.

If you could please provide some recommended settings that would avoid our nodes running out of peers it would be much appreciated. 

For example, a node I run, on 1.11.8, on 8 cores, with the following params 
```
--mode=active
--base-path=/paritydb
--db-compaction=ssd
--pruning=fast
--no-ancient-blocks
--jsonrpc-interface=all
--jsonrpc-cors=all
--ws-interface=all
--tx-queue-gas=off
--tx-queue-mem-limit=0
--tx-queue-size=4294967295
--cache-size=6000
--min-peers=100
--max-peers=200
--scale-verifiers
--num-verifiers=2
--jsonrpc-server-threads=4
--jsonrpc-threads=4
--unsafe-expose
```

works fine for a bit then suddenly looses peers until restart. here is a weeks's worth of peer counts

<img width="775" alt="screenshot 2018-08-11 23 10 25" src="https://user-images.githubusercontent.com/2983312/44023159-6097f97e-9ef2-11e8-9e35-24dded5be2b6.png">

sorry for not using the template, it's a more generic question, but i can recreate if needed.

thanks for all your hard work

**Comment by Tbaut** [comment]
Thanks for re-posting.
From your config, your node is very open (see our [security best practices](https://wiki.parity.io/FAQ#what-are-the-security-best-practices)). It means that your node might be very busy receiving transactions or answering rpc calls from the whole world.

Could you try to  monitor the amount of connections and reduce the scope of the http rpc and ws servers to decrease its load?

**Comment by Tbaut** [comment]
>he http/ws rpc ports are not open to the outside world

Because of a firewall?

> it should be used by only a couple of microservices

Do you monitor the amount of incoming RPCs/transactions in the queue? It would be worth giving a try.

**Comment by tzapu** [comment]
Hi, the services are monitoring the pending transaction queue and the nodes are not used to submit tx s through them. 

Connections are made through websockets and there would be about 3 live websocket connections on at all times.

Is there any way in parity to monitor how hard it's being hit by our own rpc requests? 

Would an avalanche of requests cause the peer loss even if json rpc threads are limited at parity level? 

Is there anyway to reserve some threads to always be available and only be available to the inner workings of parity so they can't be affected by the rpc requests?

**Comment by Tbaut** [comment]
>Is there any way in parity to monitor how hard it's being hit by our own rpc requests?

You can see the amount of rpc/s through the default command line output.
You can also log the rpc requestions with `-l rpc`

>Would an avalanche of requests cause the peer loss 

yes
>even if json rpc threads are limited at parity level?

Probably not. How many core do you have on that machine with `--jsonrpc-threads=4` and `--jsonrpc-server-threads=4` ?

Any reason for these numbers?
```
--tx-queue-gas=off
--tx-queue-mem-limit=0
--tx-queue-size=4294967295
```

I'd leave the default one to try and increase the size of the queue etc if that's a bottleneck only.

**Comment by tzapu** [comment]
I am seeing 20-40req/s on average and bursts of ~150req/s
to validate if the requests are to blame, i could stop all of them and see peer stability. just in case, for this level of load, how many cores/threads do you think would be ok?

the machine has 8 cores
the tx-queue related settings are there just to make sure we cast as wide a net as possible to catch as many pending transactions as possible

thank you for the very through explanations. i will try to play with the settings along your recommendations and see what I come up with.

if you would prefer you can close this issue and i'll ask for a reopen after I have played with it some more (it takes time unfortunately to validate each setup :( )

thanks again

**Comment by tzapu** [comment]
hello, to updated the post, i have tried a lots of various configs and by far the most stable has been:
```
docker run -d --restart always --name parity --net host -v /nvmessd/parity-pending/:/root/.local/share/io.parity.ethereum/ parity/parity:stable --ports-shift=1000 --mode=active --db-compaction=ssd --pruning=fast --no-ancient-blocks --jsonrpc-interface=all --jsonrpc-cors=all --ws-interface=all --tx-queue-gas=off --tx-queue-mem-limit=4096 --tx-queue-size=4294967295 --cache-size=6000 --min-peers=20 --max-peers=50 --scale-verifiers --num-verifiers=2 --jsonrpc-threads=2 --no-periodic-snapshot --unsafe-expose --nat extip:xx.xxx.xx.xxx
```
where parity:stable = 2.0.6
on a 4 core, 30.5 gb ram, i3.xlarge aws instance

i tried a lot more performant machines, up to 16 cores, there were only slight improvements to the original configuration and issues. 

it runs perfectly until it runs out of memory. i have no idea why, but after 24-48 hours, it starts eting through ram. without swap it would get oom killled. with 16gb of swap, it continues to fill everything and keeps working but starts dropping off peers.

not sure where to take this further, i have not seen any issues related with excessive memory consumption, any ideas?

**Comment by adria0** [comment]
Closing issue due to its stale state.
