### ISSUE TITLE
Mine one block, force a fork 

### ISSUE THREAD

**Issue by dpc** [openethereum/openethereum#9434]
I'd like to write a testing framework for stuff that integrates (runs on top of)  ethereum node. To ensure correct handling of of corner cases I'd like to simulate things like eg. reorgs.

I was googling for regtest for ethereum and I've found things like: https://wiki.parity.io/Private-development-chain . It seems it covers what I need from a node itself, but I need to tightly control mining.

I need to be able to:

* mine exactly one block on demand
* force a fork - make the miner mine on top of an arbitrary block instead of a "longest one"

**Describe the solution you'd like**
I would like two command line arguments / rpcs:

* `stop-after-one-block`
* `force-height=12345`

that would accomplish the above.

**Describe alternatives you've considered**
I haven't considered much and I have no idea about ETH mining. I'm open for suggestions.

I tried to ask the same question in ethminer github, but they've told me that I should probably use cpuminer provided by the network client itself. https://github.com/ethereum-mining/ethminer/issues/1522

**Comment by joshua-mir** [comment]
This would actually be quite involved to implement, as it would need a new consensus engine/modification of an existing one, and would probably have to come after https://github.com/paritytech/parity-ethereum/issues/8259 is implemented.

**Comment by adria0** [comment]
Closing issue due to its stale state.
