### ISSUE TITLE
Light client crashes with memory corruption on 64-bit ARMv8

### ISSUE THREAD

**Issue by ni3gavhane** [openethereum/openethereum#9482]
- **Parity Ethereum version**: v2.1.0-unstable-72fd1fa-20180904/aarch64-linux-gnu/rustc1.28.0
- **Operating system**: Ubuntu 16.04.3 LTS
- **Installation**: built from source
- **Fully synchronized**: no - light mode
- **Network**: tobalaba
- **Restarted**: no
I tried to run the client in light mode with following command
./parity --chain=tobalaba --light

**Observations**:
The below log file grows rapidly to 3.6G.
~/.local/share/io.parity.ethereum/chains_light/Tobalaba/db/5b5adf025532f2b0/overlayrecent/db/000024.log
The memory foot print of the the parity process also grows to almost ~4G.

The client crashes with memory corruption.
![mem_crash](https://user-images.githubusercontent.com/43007217/45102863-1c7eb000-b11e-11e8-9c82-5f30d8b0860e.jpg)

**Comment by niklasad1** [comment]
Hey @ni3gavhane 

I can't verify this behavior on master (4e8e5bbb8)

## db (fully synced)
```bash
4.0K    Tobalaba/db/5b5adf025532f2b0/overlayrecent/db/trace_blooms
4.0K    Tobalaba/db/5b5adf025532f2b0/overlayrecent/db/blooms
16M     Tobalaba/db/5b5adf025532f2b0/overlayrecent/db
161M    Tobalaba/db/5b5adf025532f2b0/overlayrecent
161M    Tobalaba/db/5b5adf025532f2b0
161M    Tobalaba/db
161M    Tobalaba
32K     Tobalaba/network
161M
```

## Parity process 
Peaks for me at 8% of 15.4G -> ~1.2G (still a lot but still not near 4G)

Can run ```valgrind``` on parity and provide the output?

You can do that as follows:
```bash
# install valgrind
$ cargo build --features memory_profiling
$ valgrind --tool=massif --massif-out-file=valgrind_massif.log ./parity --chain=tobalaba --light
```

**Comment by ni3gavhane** [comment]
Please find the attached valgrind log. on another note are you trying to run this on x86 architecture?
I have another observations the unoptimized binary with debug symbols works as expected.
I have also attached my architecture details.
[valgrind_massif.log](https://github.com/paritytech/parity-ethereum/files/2358402/valgrind_massif.log)
![arch](https://user-images.githubusercontent.com/43007217/45179359-96935f80-b218-11e8-943c-a799f39b5635.png)
![cpu](https://user-images.githubusercontent.com/43007217/45179360-96935f80-b218-11e8-902c-ada25e1dea0a.png)

Thank you.

**Comment by ni3gavhane** [comment]
I can confirm if I move to recent master, the memory crash does not happen. But still the log file and memory foot print is incrementally growing.

**Comment by ni3gavhane** [comment]
Thanks for the reply. I built with the default setting (jemalloc).
- on ARM, the file keeps growing, right now after 8 hours its 1.3G. The .sst file is not getting created.  Please see the below.
![arm64](https://user-images.githubusercontent.com/43007217/45231584-b3896a80-b2cc-11e8-86d3-85adedc020e5.png)

- on x86-64, I am getting expected behaviour, see the below 
![x86-64](https://user-images.githubusercontent.com/43007217/45231636-e6336300-b2cc-11e8-972e-36d69bb43922.png)
db dir snapshot.

**Comment by ordian** [comment]
@ni3gavhane is your arm cpu 32-bit? Currently, we don't support that (https://github.com/paritytech/parity-common/issues/27), but PRs are welcome.

**Comment by ni3gavhane** [comment]
Thanks. No its not 32-bit cpu. It is 64bit.
