### ISSUE TITLE
openethereum sync to ethereum mainnet

### ISSUE THREAD

**Issue by HatimKH** [openethereum/openethereum#95]
- **OpenEthereum version (>=3.1.0)**: 3.1.0
- **Operating system**: docker container
- **Installation**: docker pull openethereum/openethereum:latest
- **Fully synchronized**: yes
- **Network**: ethereum 
- **Restarted**: no 

After getting fully synced, openethereum started running  normally during 2 days. then, it crashed  and generated the error below. It cannot be started again.

````
2020-11-11 01:55:25 UTC 27 -> GetNodeData: item 0/266 – slow state fetch for hash 0xb4d1c176085e94508ccb19316c7aaede28454033d056ba7cd8674d6fadcc55a7; took 477.705383ms, total 477.705383ms
````

**Comment by rakita** [comment]
Hi, this log is not from 3.1.0 version

**Comment by HatimKH** [comment]
@rakita 
I'm pulling latest docker version available 14 days ago in docker hub.
Sorry, I deleted the docker container and cannot provide more info.

**Comment by rakita** [comment]
@HatimKH np. Docker latest was updated recently to ` v3.1.0` . ` v3.1.0`  is more stable then ` v3.0.1`  because it is a backport from ` v2.5.13` , and `GetNodeData` was removed from 3.1.0
