### ISSUE TITLE
Move the `light::Provider` trait from the light client implementation 

### ISSUE THREAD

**Issue by niklasad1** [openethereum/openethereum#9512]
So in the case of the light client, some nodes have to provide data to the light clients such as block headers and similar. Currently, this implementation (including the trait) sits in the [light client implementation](https://github.com/paritytech/parity-ethereum/blob/master/ethcore/light/src/provider.rs) and it is typically provided by `full-nodes`.

Thus, it is better to decouple this from the light client by moving this to its own crate for example somewhere in [ethcore](https://github.com/paritytech/parity-ethereum/blob/master/ethcore) 

Also, in the future, if we want to decouple the `light client` (e.g. compile it down to WASM) from the `full-client` this will help too!

**Comment by adria0** [comment]
Closing the issue due to its stale state
