### ISSUE TITLE
eth_getBlockByNumber("pending", bool) should return the contents of the pending pool

### ISSUE THREAD

**Issue by tzapu** [openethereum/openethereum#9540]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 1.11.8
- **Operating system**: Linux 
- **Installation**: docker
- **Fully synchronized**yes
- **Network**: ethereum
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Actual**
Calling `eth_getBlockTransactionCountByNumber` with a block number of `pending` returns the count of the full pending pool as seen by the node, since it was fixed.
Calling `eth_getBlockByNumber` with a block number of `pending` returns nothing if there are no local submited transactions.
**Expected**
Calling `eth_getBlockByNumber` with a block number of `pending` should return all the transaction data or hashes from the pool to keep behaviour consistent with `eth_getBlockTransactionCountByNumber`.
Alternatively maybe a parameter could be added to `parity_pendingTransations` to return just the hashes, rather than always returning the full data.

Thank you very much for all your hard work.

**Comment by adria0** [comment]
Closing issue due to its stale state.
