### ISSUE TITLE
Import of an exported, local chain, is slower than a network sync

### ISSUE THREAD

**Issue by jmooo** [openethereum/openethereum#9626]
- **Parity Ethereum version**: 2.1.1
- **Operating system**: Ubuntu 18.10.1
- **Installation**: one-line installer
- **Fully synchronized**: no 
- **Network**: ethereum
- **Restarted**:  yes

Using the latest beta of Parity I'm trying to create a new archival node. I've exported the blockchain from my geth 1.8.15 archival node (pre-export: 1400gb, post-export: 54gb, I'm assuming because state-data is not exported...unfortunately). I'm using 2 SSDs inside GCP on a 16 core machine with 16gb ram. One SSD holds the exported blockchain, the other is where parity is importing to. Didn't want to possibly max-out the limits on one drive with both read & write.

At first parity imports about 2000 blocks/s, and steadily drops to 1000, 500, 50...now it does about 0.4 blk/s and 3 tx/s. I also have a parity node just doing a network sync I started at the same time and it is far ahead of my SSD import!

The commands I used:

    $ geth --cache 6000 --gcmode "archive" --syncmode "full" --datadir /mnt/disk1/ export /mnt/disk1/export.rlp
    $ parity --cache-size 6000 --pruning archive --tracing on --base-path /mnt/disk2 import /mnt/disk1/geth.export

Attached screencap of latest parity import progress:

![parity](https://user-images.githubusercontent.com/1500269/45911414-d2f1be80-bdc7-11e8-8b0a-e20a0880f619.png)

**Comment by adria0** [comment]
Closing issue due to its stale state.
