### ISSUE TITLE
Long RPC response time

### ISSUE THREAD

**Issue by KrzychDudek** [openethereum/openethereum#9699]
- **Parity Ethereum version**: v2.1.1-beta-cb09330-20180919
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**: yes

Parity runs in demon mode. 
The configuration

[parity]
mode = "active"
release_track = "stable"
mode_alarm = 60

[network]
min_peers = 25
max_peers = 50

[ui]
disable = true

[rpc]
interface = "all"
apis = ["eth", "parity", "traces", "parity_accounts","signer"]

[websockets]
interface = "all"
apis = ["eth", "parity_pubsub", "traces","signer"]

[ipc]
disable = true

[dapps]
disable = true

[footprint]
tracing = "on"
db_compaction = "ssd"
cache_size = 4096

[misc]
logging = "sync=info,tcp=info,client=debug,rpc=debug,rpc_client=info,signer=info,shutdown=debug,import=info,txqueue=info,discovery=info,fetch=info,pubsub=info,own_tx=info"
log_file = "/patch/to/log/pa.log"`

The problem that I face: after around 12h, an the RPC call (eg. eth_getBalance) responded after long time like 5 minutes.
`curl --data '{"method":"eth_getBalance","params":["(.....)"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:(...)

As the localhost call eliminates the network latency the call result should be immediately, as it is just after the parity start.

Thanks for help

**Comment by joshua-mir** [comment]
could you share some of the logs from around that time? 

Also, you may find that increasing `server_threads` or `processing_threads` in the `[rpc]` section of your config might help out (if and only if the issue is due to heavy load).

**Comment by KrzychDudek** [comment]
[parity.2018-10-04_02.log](https://github.com/paritytech/parity-ethereum/files/2445988/parity.2018-10-04_02.log)
This is a log for an hour when the problem starts.
As you can see on the beginning of log I check the balance in 6 minutes intervals.

I will give a try for the configuration:
server_threads = 5
processing_threads = 3

**Comment by KrzychDudek** [comment]
[parity.2018-10-04_02.log](https://github.com/paritytech/parity-ethereum/files/2445988/parity.2018-10-04_02.log)
This is a log for an hour when the problem starts.
As you can see on the beginning of log I check the balance in 6 minutes intervals.

I will give a try for the configuration:
server_threads = 5
processing_threads = 3

**Comment by KrzychDudek** [comment]
My today's finding:
```
netstat -an | egrep '30303.*'
tcp        0      0 0.0.0.0:30303           0.0.0.0:*               LISTEN     
tcp        0      0 10.0.1.4:51574          114.203.210.12:30303    ESTABLISHED
tcp        0  11744 10.0.1.4:52342          13.211.167.151:30303    ESTABLISHED
tcp        0      0 10.0.1.4:47584          80.211.76.253:30303     ESTABLISHED
tcp        0      0 10.0.1.4:59058          167.114.230.93:30303    ESTABLISHED
tcp        0      0 10.0.1.4:42700          35.224.60.254:30303     ESTABLISHED
tcp        0      0 10.0.1.4:45976          95.179.136.34:30303     ESTABLISHED
tcp        0      0 10.0.1.4:47368          35.192.105.45:30303     ESTABLISHED
tcp        0      0 10.0.1.4:37240          18.136.75.234:30303     ESTABLISHED
tcp        0   1360 10.0.1.4:40478          139.99.160.213:30303    ESTABLISHED
tcp        0      0 10.0.1.4:40494          139.99.51.203:30303     ESTABLISHED
tcp        0      0 10.0.1.4:34814          145.239.7.236:30303     ESTABLISHED
tcp        0      0 10.0.1.4:37036          65.52.144.36:30303      ESTABLISHED
tcp        0      0 10.0.1.4:55230          149.28.149.128:30303    ESTABLISHED
tcp        0      0 10.0.1.4:52462          178.62.210.105:30303    ESTABLISHED
tcp        0   6000 10.0.1.4:44114          77.223.66.87:30303      ESTABLISHED
tcp        0      0 10.0.1.4:37268          167.114.231.158:30303   ESTABLISHED
tcp        0      0 10.0.1.4:37058          193.70.55.37:30303      ESTABLISHED
tcp        0      0 10.0.1.4:43200          167.114.253.76:30303    ESTABLISHED
tcp        0      0 10.0.1.4:44138          209.58.171.69:30303     ESTABLISHED
tcp        0      0 10.0.1.4:52322          93.243.17.8:30303       ESTABLISHED
tcp        0  10672 10.0.1.4:55250          167.99.225.8:30303      ESTABLISHED
tcp        0      0 10.0.1.4:56468          167.114.231.164:30303   ESTABLISHED
tcp        0      0 10.0.1.4:36688          85.214.192.88:30303     ESTABLISHED
tcp        0      0 10.0.1.4:57736          94.130.180.104:30303    ESTABLISHED
tcp        0      0 10.0.1.4:50634          144.217.139.5:30303     ESTABLISHED
```

For the RPC port

```
netstat -an | egrep 'XXXX.*'
tcp        0      0 0.0.0.0:XXXX            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:XXXX            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:XXXX            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:XXXX            0.0.0.0:*               LISTEN     
tcp        1      0 0.0.0.0:XXXX            0.0.0.0:*               LISTEN     
tcp        0      0 --.--.--.--:XXXX           --.--.--.--:XXXX     ESTABLISHED
tcp      191      0 127.0.0.1:XXXX          127.0.0.1:XXXX         CLOSE_WAIT 
tcp        0      0 --.--.--.--:XXXX           --.--.--.--:XXXX     ESTABLISHED
tcp        0      0 127.0.0.1:XXXX         127.0.0.1:XXXX          FIN_WAIT2  
tcp        0      0 --.--.--.--:XXXX           --.--.--.--:XXXX     ESTABLISHED
tcp      191      0 127.0.0.1:XXXX          127.0.0.1:XXXX         CLOSE_WAIT 
tcp      351      0 --.--.--.--:XXXX           --.--.--.--:XXXX     CLOSE_WAIT 
```

and for the WebSocket:

```
netstat -an | egrep 'YYYY.*'
tcp        0      0 0.0.0.0:YYYY            0.0.0.0:*               LISTEN     
tcp        0      0 --.--.--.--:YYYY           --.--.--.--:YYYY     ESTABLISHED
tcp        0 --.--.--.--:YYYY           --.--.--.--:YYYY     ESTABLISHED
tcp        0      0 --.--.--.--:YYYY           --.--.--.--:YYYY     ESTABLISHED
tcp        0      0 --.--.--.--:YYYY           --.--.--.--:YYYY     ESTABLISHED
tcp        0      0 --.--.--.--:YYYY           --.--.--.--:YYYY     ESTABLISHED
tcp        0      0 --.--.--.--:YYYY           --.--.--.--:YYYY     ESTABLISHED
```

Is it possible that this issue is related to [#9556](https://github.com/paritytech/parity-ethereum/issues/9656)

**Comment by debris** [comment]
#9711 is unrelated

**Comment by adria0** [comment]
Closing issue due to its stale state.
