### ISSUE TITLE
randomStatetest561BC_Frontier...error: test failed, to rerun pass '--lib'

### ISSUE THREAD

**Issue by 5chdn** [openethereum/openethereum#9720]
- **Parity Ethereum version**: 2.1.2
- **Operating system**: Windows
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum
- **Restarted**: yes

`randomStatetest561BC_Frontier...error: test failed, to rerun pass '--lib'`

This test repeatedly fails but only on Windows. Any ideas?

**Comment by 5chdn** [comment]
https://gitlab.parity.io/parity/parity-ethereum/-/jobs/103464

**Comment by adria0** [comment]
Closing issue due to its stale state.
