### ISSUE TITLE
web3.eth.getGasPrice sometimes returns 0 for xDai chain

### ISSUE THREAD

**Issue by varasev** [openethereum/openethereum#9795]
- **Parity Ethereum version**: 1.11.8-stable, 2.0.8-stable
- **Operating system**: MacOS
- **Installation**: homebrew
- **Fully synchronized**: yes
- **Network**: xdai
- **Restarted**: yes

`web3.eth.getGasPrice` (web3 1.0 is used) sometimes returns `0` for `xDai` chain but sometimes it returns a correct value of `1 gwei`.

However, for `POA Sokol` and `POA Core` it works fine: https://github.com/status-im/status-react/pull/6388#issuecomment-431315340

Seems something's wrong with `eth_gasPrice` JSON RPC for xDai chain which uses [transactions with zero gas price](https://wiki.parity.io/Permissioning.html#gas-price) for its bridge part.

I tried to launch Parity in the following manner:

```bash
parity --no-warp --jsonrpc-port 8545 --jsonrpc-apis all --chain ./spec.json --reserved-peers ./bootnodes.txt
```

`spec.json` and `bootnodes.txt` should be taken from here: https://github.com/poanetwork/poa-chain-spec/tree/dai

The code to reproduce:

```javascript
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'));

async function main() {
  setInterval(async function() {
    const res = await web3.eth.getGasPrice();
    console.log(res); // prints `1000000000` or `0`
  }, 5000);
}

main();
```

**Comment by joshua-mir** [comment]
@varasev just to make sure no recent fixes address this issue, can you try to replicate with a recent version of parity? (stable or beta?)

**Comment by varasev** [comment]
@joshua-mir The same is observed with 2.0.8-stable.

**Comment by varasev** [comment]
I've updated the description ☝️ to reproduce the bug on a local node.

**Comment by joshua-mir** [comment]
Thanks!

I have a hunch this has something to do with how we calculate the gas price to use based on previous blocks, specifically, it is calculated as the median of the previous blocks. I just checked out the block explorer for xDai and it looks like most blocks are empty, which might be the issue here.

@tomusdrw are you the right person to ask about this?

**Comment by tomusdrw** [comment]
@joshua-mir correct, gas price estimate is based on transactions from last blocks. If there is none we fallback to some default value, but if there are some transactions we will use their gas price.

Perhpas we should add a minimal bound to `eth_gasPrice` in case `min-gas-price` in CLI is set, cause afair the issue keeps returning.
