### ISSUE TITLE
Feature Request: ipc file permissions (re)set on (re)start

### ISSUE THREAD

**Issue by stone212** [openethereum/openethereum#9796]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.7
- **Operating system**: Linux
- **Installation**: parity binary
- **Fully synchronized**: yes
- **Network**: other
- **Restarted**: yes

Anytime Parity re-starts the IPC file re-sets to its original file permissions.  It would be very helpful (for development and also for situations where Parity dies but re-starts due to systemd) for a config option that sets the IPC file permissions.  For example:

```
[ipc]
chmod = 775
```

or `ipc-chmod="775"`

**Comment by adria0** [comment]
Closing issue due to its stale state.

**Comment by stone212** [comment]
@adria0  It's not "stale."  It is unresolved.  That's a big difference.
