### ISSUE TITLE
[Private transactions] Get rid of BlockId::Latest usages in the code of private_tx module 

### ISSUE THREAD

**Issue by grbIzl** [openethereum/openethereum#9825]
Right now several methods in private tx module rely on BlockId::Latest for calling client's methods.
This should be rework to exact block hash in order to avoid issues. 
Most of the places with these usages marked with corresponding TODO like this one:
https://github.com/paritytech/parity-ethereum/blob/master/ethcore/private-tx/src/lib.rs#L209

**Comment by adria0** [comment]
Closing the issue due to its stale state
