### ISSUE TITLE
Thread 'IO Worker #2' panicked at 'db get failed

### ISSUE THREAD

**Issue by mat7ias** [openethereum/openethereum#9864]
- **Parity Ethereum version**: v2.3.0-unstable-3a6e04ba1-20181101/x86_64-linux-gnu/rustc1.30.0
- **Operating system**: Linux (using WSL)
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: kovan 
- **Restarted**: yes (works fine now)

I ran into this bug after running `./target/release/parity --no-warp --chain kovan`. It's syncing fine when I restart it but decided to open an issue since it prompted me to do so.

2018-11-05 17:32:13  Syncing #5062865 0xf5da…4a4d    53.21 blk/s  136.4 tx/s   38 Mgas/s      0+ 1880 Qed  #5064746    5/25 peers   838 KiB chain 65 MiB db 4 MiB queue 1 MiB sync  RPC:  0 conn,    0 req/s,    0 µs

====================

stack backtrace:
   0:     0x7faea3d5580c - <no info>
   1:     0x7faea3d54a82 - <no info>
   2:     0x7faea3d54af8 - <no info>
   3:     0x7faea3d53cae - <no info>
   4:     0x7faea25f74c7 - <no info>
   5:     0x7faea3db0bc3 - <no info>
   6:     0x7faea3db0729 - <no info>
   7:     0x7faea3db068d - <no info>
   8:     0x7faea32e2750 - <no info>
   9:     0x7faea32cce3d - <no info>
  10:     0x7faea2fabf96 - <no info>
  11:     0x7faea2f9b000 - <no info>
  12:     0x7faea2f8954a - <no info>
  13:     0x7faea2f74a39 - <no info>
  14:     0x7faea2f71183 - <no info>
  15:     0x7faea2fe9ad4 - <no info>
  16:     0x7faea30165db - <no info>
  17:     0x7faea2fc4b4b - <no info>
  18:     0x7faea2fc5476 - <no info>
  19:     0x7faea3ddd459 - <no info>
  20:     0x7faea2fcbf12 - <no info>
  21:     0x7faea3dcb2ea - <no info>
  22:     0x7faea3db13e5 - <no info>
  23:     0x7faea12176da - <no info>
  24:     0x7faea0d1188e - <no info>
  25:                0x0 - <no info>

Thread 'IO Worker #2' panicked at 'db get failed, key: [0, 99, 120, 110, 52, 128, 247, 60, 78, 12, 236, 50, 240, 47, 172, 146, 86, 58, 124, 68, 16, 188, 170, 187, 90, 227, 93, 24, 1, 192, 76, 244, 107], err: Custom { kind: Other, error: StringError("IO error: While pread offset 62743401 len 16268: /home/mattias/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/178055.sst: Bad address") }', ethcore/src/db.rs:235

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

2018-11-05 17:32:14  Finishing work, please wait...
Segmentation fault (core dumped)

**Comment by joshua-mir** [comment]
Duplicate of https://github.com/paritytech/parity-ethereum/issues/8096 but that issue is quite stale at this stage so it might be okay for conversation about the issue to be moved here.

This issue seems to be related to unreliable disk/file reading and is very hardware and environment specific. If this recurs on your machine, could you share details of your machine's specs?

**Comment by mat7ias** [comment]
I should have searched for an existing closed issue, didn't mean to make a duplicate. 
Yep sounds to be likely that was the cause, I was starting Chrome when as it occurred and had a few other programs running simultaneously.

**Comment by adria0** [comment]
Closing the issue due to its stale state
