### ISSUE TITLE
[Feature Request] support dropping individual non-reserved peers/ coordinate peers accross multiple nodes

### ISSUE THREAD

**Issue by dareniott** [openethereum/openethereum#9937]
- **Parity Ethereum version**: v2.2.1
- **Operating system**: Linux
- **Installation**: Docker
- **Fully synchronized**: yes
- **Network**: ethereum

While attempting to get and aggregate pending tx we are having problems with overall network visibility.  In order to gain better network penetration distributed nodes have helped along with increasing the peer count on those nodes, however we cannot *guarantee* that a number of our nodes are not simply talking to to the same peers and thereby reducing overall visibility in to the pending tx pool.  Parity already has method parity_netPeers to get all the peers a node is connected to.  It would be helpful if there was also a method to drop a specific peer from a node.  This would allow an outside coordination mechanism to look at the peers on any given node and coordinate them in aggregate so as to ensure the greatest level of network visibility.

**Comment by joshua-mir** [comment]
You can do something similar to what you want by manually reserving all peers and dropping non-reserved peers using the methods described [here](https://wiki.parity.io/JSONRPC-parity_set-module) (this likely will need some help from logic outside of the parity client, so this is still a valid feature request.)

**Comment by tomusdrw** [comment]
I think it would be nice to have more granular control then `dropNonReservedPeers` (i.e. dropping peers one by one). 
Note: dropped peers should be temporarily banned to prevent reconnecting right after drop.

**Comment by dareniott** [comment]
> You can do something similar to what you want by manually reserving all peers and dropping non-reserved peers using the methods described [here](https://wiki.parity.io/JSONRPC-parity_set-module) (this likely will need some help from logic outside of the parity client, so this is still a valid feature request.)

Yes I am currently using the parity_addReservedPeer method to keep our network of 10+ nodes connected to each other.  However running each of the 10+ nodes with 500 peers means there is likely some overlap in the connected peers.  If I could ensure that they all had unique peers I could ensure almost 50% visibility of all ETH nodes.

Reserved peers however does not allow me to discover new peers, it would be simplest to let parity discover new peers and drop/ban peers according to the criteria already in place, I simply want to help that a little by specifying that a specific node has a peer that is already present on another node so drop it.  Reserved peers also lets me specify that node1 should always connect to peerX, but does not allow me to tell node2 that it should not connect to peerX.  I could thereby create a unique network of reserved peers but still cannot control the peers that are picked up randomly.

**Comment by adria0** [comment]
Closing issue due to its stale state.
