### ISSUE TITLE
No recovery after bad snapshot restoration

### ISSUE THREAD

**Issue by phahulin** [openethereum/openethereum#9942]
- **Parity Ethereum version**: 2.2.1
- **Operating system**: Ubuntu 16.04
- **Installation**: binary
- **Fully synchronized**: no
- **Network**: sokol
- **Restarted**: yes

When trying to warp-sync Sokol network, the following error happens on some nodes:
```
Encountered error during snapshot restoration: RlpExpectedToBeList
```
Then syncing stops. This doesn't happen when using `--no-warp`.

**Comment by adria0** [comment]
Closing issue due to its stale state.
