### ISSUE TITLE
[feature request] pruning by blocknumber 

### ISSUE THREAD

**Issue by vietthang207** [openethereum/openethereum#9962]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.1.6
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**:  yes
- **Network**: ethereum
- **Restarted**: yes

I have 2 question:
1. As of my understanding, this 2 variables define how many states I'm gonna store. pruning_history is quite straight forward, you store 512 states in hard disk, but I don't know what pruning_memory does, I guess that the amout of RAM take to store state. Is my understanding correct?
2. Let say I change pruning_history from 512 to 1024, do I need to delete the db and resync the node in order for it to take effect?

**Comment by joshua-mir** [comment]
No, pruning doesn't require a resync, your node should use whatever pruning settings you set and.. prune... any excess (or wait until it refills with future state). pruning_memory determines how much memory is used to store the state trie history IF pruning_history does not surpass that amount already (so pruning_memory is "minimum memory" and pruning_history is "minimum history").

**Comment by vietthang207** [comment]
@joshua-mir So I think this perfectly fit my use case of partial archive node, I just need a new variable like pruning_history_barrier, and the node will keep every state after this barrier, instead of a fixed pruning_history config.
