### ISSUE TITLE
Generate docs from code

### ISSUE THREAD

**Issue by 5chdn** [openethereum/openethereum#9974]
Similar to the JSON-RPC docs that are automatically generated in the CI, we want:

- chainspec parameters automatically documented
- config file parameters automatically documented

Whenever there is a change to code, ideally we have scripts that extract the docs from the code and push it to the wiki/config generator.

- https://github.com/paritytech/parity-config-generator
- https://github.com/paritytech/parity-ethereum/blob/master/scripts/gitlab/publish-docs.sh

**Comment by 5chdn** [comment]
Follow-up to #8835

**Comment by joshua-mir** [comment]
https://github.com/paritytech/parity-ethereum/pull/10067 working on the config file side of this

**Comment by adria0** [comment]
Closing issue due to its stale state.
