### ISSUE TITLE
panic on proof validation 

### ISSUE THREAD

**Issue by ngotiendatdinosys** [openethereum/openethereum#9978]
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: Parity-Ethereum/v2.2.1-beta-5c56fc5-20181114/x86_64-macos/rustc1.30.1
- **Operating system**: MacOS
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: private
- **Restarted**: no

<img width="639" alt="screen shot 2018-11-28 at 10 10 51 am" src="https://user-images.githubusercontent.com/26533319/49126438-261b4c80-f2f6-11e8-9108-f53fb9736df9.png">

**Comment by 5chdn** [comment]
Can you share your chain specification?

**Comment by adria0** [comment]
Closing the issue due to its stale state
