### ISSUE TITLE
Authority node not sealing blocks when started as daemon

### ISSUE THREAD

**Issue by tymat** [openethereum/openethereum#9985]
- **Parity Ethereum version**: `2.2.1-beta-5c56fc5-20181114`
- **Operating system**: `Linux`
- **Installation**: one line installer
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

**OS Information**
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

Parity Kovan Authority does not seal blocks when started as a daemon using the following:

```
parity --chain=kovan --force-sealing --engine-signer="[authority_address]" --password=/home/path/to/password.txt --auto-update=all --min-gas-
price 1000000000 --gas-floor-target 8000000 --no-ws --no-ipc --jsonrpc-apis web3,eth,net,parity,traces,rpc,personal --jsonrpc-hosts="all" daemon /home/ethereum/kovan.pid
```

The exact same command without the `daemon` command shows that it will seal/mine properly

```
parity --chain=kovan --force-sealing --engine-signer="[authority_address]" --password=/home/path/to/password.txt --auto-update=all --min-gas-
price 1000000000 --gas-floor-target 8000000 --no-ws --no-ipc --jsonrpc-apis web3,eth,net,parity,traces,rpc,personal --jsonrpc-hosts="all" 
```

**Comment by Tbaut** [comment]
Thanks for the issue, @ddorgan will probably be able to help you there :)

**Comment by adria0** [comment]
Closing issue due to its stale state.
