### ISSUE TITLE
Unify Parity Ethereum and Substrate types

### ISSUE THREAD

**Issue by sorpaas** [openethereum/openethereum#9994]
Currently Parity Ethereum and Substrate uses different base types, which makes sharing code difficult.

#### Primitive Types

Both Parity Ethereum and Substrate uses `uint` and `fixed_hash` crate. However, type definitions are by macros, so for crates using `ethereum-types`, it's incompatible with crates using `substrate-primitves`. To unify this, we:

* Create another crate `primitive-types` that declare only what's in common of `ethereum-types` and `substrate-primitives`. Those types are `H160`, `H256`, `H512` and `U256`.
* After that, publish versions of `ethereum-types` and `substrate-primitves`.
* For RLP and parity-codec serialization, create feature flags on `primitive-types` crate.

#### Trie

We have two versions at this moment, one is https://github.com/paritytech/trie and another is `patricia_trie` in https://github.com/paritytech/parity-common. Those are interchangeable but type definitions are not compatible. To unify this, we:

* Remove `patricia_trie` in https://github.com/paritytech/parity-common
* Switch to https://github.com/paritytech/trie in Parity Ethereum.

#### RLP and parity-codec

There's only some small issues for this category:

* Remove `ethereum-types` feature flag on `rlp`, and define serialization in `ethereum-types` directly (with a `rlp` feature flag).
* Move `rlp_derive` to `parity-common` repo and publish it.

**Comment by dvdplm** [comment]
Primitive types: One questions is what to do about types that are "close in spirit" but not used in more than one project. E.g. what about `U512`? I think that is present in `ethereum-types` (if not, let's pretend it is for arguments sake) but not used in `substrate`. Would it still be in `primitive-types`? I'd say "yes", but it does bring the downside for `substrate` having to "pay for" types it doesn't use.

Tries
I take it you'll move https://github.com/paritytech/trie to `parity-common/trie`? This means we don't need `triehash` anymore (or is it useful still?).
And how about `codec`, is that moving as well to `parity-common/codec`, or, as it's only used in substrate should it stay its own thing? I'd argue that if `rlp` is in `parity-common` so should `codec`.

**Comment by sorpaas** [comment]
@dvdplm For this, I'd want to use the solutions that make it most easy for everyone to agree on things. That is, focus on unifying behaviors / types, and keep unnecessary changes at a minimal.

* So at this moment we probably just keep `U512` in `ethereum-types`, just because Substrate doesn't use this type.
* I think we may just temporarily keep `paritytech/trie` and `paritytech/parity-codec` at its current place, just because moving is an extra thing to be taken care of, which we can do outside of unification.
* Both `parity-codec` and `parity-codec-derive` are on crates.io, so we won't have issues getting it as an optional dependency for primitive types in parity-common.
* For `triehash`, I think we can unify it with `trie-root` in `paritytech/trie`.

**Comment by sorpaas** [comment]
> So both the new primitive-types crate and ethereum-types would need a dependency on uint (to construct the types). This is unfortunate and feels a little hackish to me. :/

We need `uint` / `fixed-hash` there anyway. `ethereum-types` has a lot more than just `U512` (like `H2048` for `Bloom`). I refactored how `serde` / `codec` / `rlp` are implemented so we won't duplicate any code.

> There's a risk that it never happens when all is said and done.

Let's do things step by step. :)

**Comment by adria0** [comment]
Closing issue due to its stale state.
